"""Exact geometric optics: rational media, piecewise-linear rays, and an
optical path length that is compared **exactly** and never approximated.

The obstacle, and how it is removed
-----------------------------------
An optical path length is a sum of terms ``n * sqrt(dx^2 + dy^2)``.  With
rational ``n`` and rational coordinates each term is a rational multiple of the
square root of a rational, so an optical path length lives in the field
``Q(sqrt p_1, ..., sqrt p_r)`` for finitely many primes.  Every such number has
an exact canonical form

    sum_i  a_i * sqrt(m_i)        a_i in Q,  m_i distinct squarefree positive ints

and that form is the ``Surd`` class below.  Two facts make comparison exact and
*total*:

* **Zero is decidable syntactically.**  Square roots of distinct squarefree
  positive integers are linearly independent over ``Q`` (Besicovitch 1940).  So
  a canonical ``Surd`` is zero iff every coefficient is zero -- a finite check
  on ``Fraction``s, no arithmetic on irrationals at all.
* **Nonzero is decidable by rational bracketing.**  If some coefficient is
  nonzero the value is a nonzero real, and enclosing each ``sqrt(m)`` in a
  rational interval of width ``2^-k`` (obtained from an *integer* square root of
  ``m * 4^k``) gives a rational interval around the sum that shrinks to nothing.
  Refine ``k`` until the interval excludes 0.  It always does, because we have
  already established the value is not 0.

So ``Surd.sign()`` is exact, total, deterministic, and never constructs a float.
The two-term case is decided by the primitive the brief names -- compare
``a*sqrt(x)`` against ``b*sqrt(y)`` by comparing ``a^2 x`` against ``b^2 y``,
signs handled first -- and that primitive is exported as
``compare_scaled_sqrt`` and tested directly.

What is here
------------
``Surd``               exact sums of rational multiples of square roots
``Vec``                a point with exact rational coordinates
``Medium``             a named region with an exact rational refractive index
``Ray``                a piecewise-linear path plus the medium of each segment
``optical_path_length``exact OPL of a ``Ray``, as a ``Surd``
``InterfaceStack``     the discrete path family: parallel interfaces, a rational
                       lattice of crossing points on each, and the OPL of any
                       choice of crossings
``MirrorArc``          a discrete family of reflection points on a circle,
                       generated by the rational chart (CRYSTAL.md Sec.4)
``snell_residual``     ``n1 sin t1 - n2 sin t2`` as an exact ``Surd``
``reflection_residual``the law of reflection as an exact ``Surd``
``critical_points``    stationary points of a discrete family, by exact sign
                       changes of the first difference -- *not* an optimizer

Nothing in this module knows Snell's law.  ``snell_residual`` is a
*measurement* applied to a route after it is found; no search function calls it,
and ``tests/test_physics.py`` asserts that by walking this file's AST.
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

from ..kernel import term as T
from .dimension import LENGTH, Quantity, exact

__all__ = [
    "OpticsError",
    "integer_sqrt", "is_perfect_square", "squarefree_part",
    "compare_scaled_sqrt",
    "Surd",
    "Vec",
    "Medium",
    "Ray",
    "optical_path_length",
    "InterfaceStack",
    "MirrorArc",
    "snell_residual", "snell_invariant", "sine_to_normal",
    "reflection_residual", "circle_tangent",
    "critical_points", "Critical",
    "reset_caches",
    "COUNTERS",
]

COUNTERS = T.Counters()


class OpticsError(Exception):
    pass


# --------------------------------------------------------------------------
# exact integer square root and squarefree decomposition
# --------------------------------------------------------------------------

def reset_caches() -> None:
    """Drop every memo table in this module.

    The memo tables are pure optimisations -- they change how many counter
    bumps a computation costs and nothing about its answer.  Demos call this
    first so their counter dumps are reproducible from a cold cache rather than
    depending on what ran earlier in the same process.
    """
    _SQUAREFREE.clear()
    _BRACKET.clear()
    _SIGN.clear()


def integer_sqrt(n: int) -> int:
    """``floor(sqrt(n))`` by Newton's method on integers.  Exact, no ``math``."""
    if isinstance(n, bool) or not isinstance(n, int):
        raise OpticsError("integer_sqrt needs an int, got %r" % (n,))
    if n < 0:
        raise OpticsError("integer_sqrt of a negative integer")
    if n < 2:
        return n
    COUNTERS.bump("surd.isqrt")
    x = 1 << ((n.bit_length() + 1) // 2)
    while True:
        y = (x + n // x) // 2
        if y >= x:
            return x
        x = y


def is_perfect_square(n: int) -> bool:
    if n < 0:
        return False
    r = integer_sqrt(n)
    return r * r == n


_SQUAREFREE: Dict[int, Tuple[int, int]] = {}


def squarefree_part(n: int) -> Tuple[int, int]:
    """``n = s^2 * f`` with ``f`` squarefree; returns ``(s, f)``.  ``n >= 0``."""
    if n < 0:
        raise OpticsError("squarefree_part of a negative integer")
    if n == 0:
        return (0, 1)
    got = _SQUAREFREE.get(n)
    if got is not None:
        return got
    COUNTERS.bump("surd.factor")
    s, m = 1, n
    d = 2
    while d * d <= m:
        if m % d == 0:
            e = 0
            while m % d == 0:
                m = m // d
                e += 1
            s *= d ** (e // 2)
        d += 1 if d == 2 else 2
    f = n // (s * s)
    _SQUAREFREE[n] = (s, f)
    return (s, f)


def _sqrt_of_fraction(q: Fraction) -> Tuple[Fraction, int]:
    """``sqrt(q) = c * sqrt(m)`` with ``c`` rational and ``m`` squarefree int.

    ``sqrt(p/d) = sqrt(p*d)/d``, then pull the square part out of ``p*d``.
    """
    if q < 0:
        raise OpticsError("sqrt of a negative rational is not a real length")
    if q == 0:
        return (Fraction(0), 1)
    p, d = q.numerator, q.denominator
    s, f = squarefree_part(p * d)
    return (Fraction(s, d), f)


# --------------------------------------------------------------------------
# the primitive the brief names: a*sqrt(x)  vs  b*sqrt(y), exactly
# --------------------------------------------------------------------------

def compare_scaled_sqrt(a, x, b, y) -> int:
    """Compare ``a*sqrt(x)`` with ``b*sqrt(y)``; ``-1``, ``0`` or ``1``.

    ``a, b`` exact rationals of any sign; ``x, y`` exact nonnegative rationals.
    Signs are resolved first, then the magnitudes by comparing ``a^2 x`` with
    ``b^2 y`` -- squaring is monotone on nonnegatives, so this is exact and no
    square root is ever evaluated.
    """
    a, b = exact(a), exact(b)
    x, y = exact(x), exact(y)
    if x < 0 or y < 0:
        raise OpticsError("compare_scaled_sqrt needs nonnegative radicands")
    COUNTERS.bump("surd.compare_scaled")
    sa = 0 if (a == 0 or x == 0) else (1 if a > 0 else -1)
    sb = 0 if (b == 0 or y == 0) else (1 if b > 0 else -1)
    if sa != sb:
        return 1 if sa > sb else -1
    if sa == 0:
        return 0
    lhs = a * a * x
    rhs = b * b * y
    if lhs == rhs:
        return 0
    bigger = 1 if lhs > rhs else -1
    return bigger if sa > 0 else -bigger


# --------------------------------------------------------------------------
# Surd: exact sums of rational multiples of square roots
# --------------------------------------------------------------------------

_BRACKET: Dict[Tuple[int, int], Tuple[Fraction, Fraction]] = {}
_SIGN: Dict[Tuple[Tuple[int, Fraction], ...], int] = {}

MAX_BRACKET_BITS = 8192


def _bracket(m: int, k: int) -> Tuple[Fraction, Fraction]:
    """Rationals ``lo <= sqrt(m) <= hi`` with ``hi - lo <= 2^-k``."""
    if m == 1:
        return (Fraction(1), Fraction(1))
    key = (m, k)
    got = _BRACKET.get(key)
    if got is not None:
        return got
    scale = 1 << k
    s = integer_sqrt(m * scale * scale)
    out = (Fraction(s, scale), Fraction(s + 1, scale))
    _BRACKET[key] = out
    return out


@dataclass(frozen=True)
class Surd:
    """``sum_i a_i sqrt(m_i)``: coefficients exact, radicands squarefree ints.

    Canonical by construction -- radicands are distinct, sorted ascending, and
    zero coefficients are dropped -- so ``Surd`` equality *is* mathematical
    equality (Besicovitch), and ``terms == ()`` is exactly the number zero.
    """

    terms: Tuple[Tuple[int, Fraction], ...]

    # -- constructors ----------------------------------------------------
    @staticmethod
    def zero() -> "Surd":
        return Surd(())

    @staticmethod
    def rational(q) -> "Surd":
        q = exact(q)
        return Surd(() if q == 0 else ((1, q),))

    @staticmethod
    def scaled_sqrt(c, q) -> "Surd":
        """``c * sqrt(q)`` for exact rational ``c`` and nonnegative rational ``q``."""
        c = exact(c)
        q = exact(q)
        if c == 0 or q == 0:
            return Surd(())
        f, m = _sqrt_of_fraction(q)
        return Surd(((m, c * f),))

    @staticmethod
    def sqrt(q) -> "Surd":
        return Surd.scaled_sqrt(1, q)

    @staticmethod
    def _canon(d: Dict[int, Fraction]) -> "Surd":
        return Surd(tuple(sorted((m, c) for m, c in d.items() if c != 0)))

    # -- arithmetic ------------------------------------------------------
    @staticmethod
    def _coerce(x) -> "Surd":
        """Accept an exact rational where a ``Surd`` is expected, and nothing else.

        This is what lets ``execute.extract.scalarize`` -- which computes
        ``sum(w * c for ...)`` over a cost vector with integer weights, starting
        from the integer ``0`` -- run over an optical cost vector unmodified.
        A float still raises, through ``dimension.exact``.
        """
        if isinstance(x, Surd):
            return x
        return Surd.rational(x)

    def __add__(self, other) -> "Surd":
        other = Surd._coerce(other)
        COUNTERS.bump("surd.add")
        d: Dict[int, Fraction] = dict(self.terms)
        for m, c in other.terms:
            d[m] = d.get(m, Fraction(0)) + c
        return Surd._canon(d)

    def __neg__(self) -> "Surd":
        return Surd(tuple((m, -c) for m, c in self.terms))

    def __radd__(self, other) -> "Surd":
        return Surd._coerce(other) + self

    def __sub__(self, other) -> "Surd":
        return self + (-Surd._coerce(other))

    def __rsub__(self, other) -> "Surd":
        return Surd._coerce(other) + (-self)

    def scale(self, k) -> "Surd":
        """Multiply by an exact rational."""
        k = exact(k)
        if k == 0:
            return Surd(())
        COUNTERS.bump("surd.scale")
        return Surd(tuple((m, c * k) for m, c in self.terms))

    def __rmul__(self, other) -> "Surd":
        return self.scale(other)

    def __mul__(self, other) -> "Surd":
        if not isinstance(other, Surd):
            return self.scale(other)
        COUNTERS.bump("surd.mul")
        d: Dict[int, Fraction] = {}
        for m1, c1 in self.terms:
            for m2, c2 in other.terms:
                s, f = squarefree_part(m1 * m2)
                d[f] = d.get(f, Fraction(0)) + c1 * c2 * s
        return Surd._canon(d)

    # -- exact decision --------------------------------------------------
    def as_fraction(self) -> Optional[Fraction]:
        """The exact rational value, or ``None`` if the number is irrational."""
        if not self.terms:
            return Fraction(0)
        if len(self.terms) == 1 and self.terms[0][0] == 1:
            return self.terms[0][1]
        return None

    def is_zero(self) -> bool:
        """Exact, and *syntactic*: distinct square roots are independent over Q."""
        return not self.terms

    def sign(self) -> int:
        """``-1``, ``0`` or ``1``.  Exact and total; never approximate."""
        if not self.terms:
            return 0
        got = _SIGN.get(self.terms)
        if got is not None:
            COUNTERS.bump("surd.sign_hit")
            return got
        COUNTERS.bump("surd.sign")
        if len(self.terms) == 1:
            m, c = self.terms[0]
            out = 1 if c > 0 else -1
        elif len(self.terms) == 2:
            (m1, c1), (m2, c2) = self.terms
            # sign(c1 sqrt m1 + c2 sqrt m2) = compare(c1 sqrt m1, -c2 sqrt m2)
            out = compare_scaled_sqrt(c1, m1, -c2, m2)
        else:
            out = self._sign_by_bracket()
        _SIGN[self.terms] = out
        return out

    def _sign_by_bracket(self) -> int:
        k = 16
        while k <= MAX_BRACKET_BITS:
            COUNTERS.bump("surd.refine")
            lo = Fraction(0)
            hi = Fraction(0)
            for m, c in self.terms:
                bl, bh = _bracket(m, k)
                if c > 0:
                    lo += c * bl
                    hi += c * bh
                else:
                    lo += c * bh
                    hi += c * bl
            if lo > 0:
                return 1
            if hi < 0:
                return -1
            k *= 2
        raise OpticsError(                                # pragma: no cover
            "sign undecided at 2^-%d; a nonzero canonical Surd must resolve, so "
            "this is a bug, not a bound" % MAX_BRACKET_BITS)

    def compare(self, other) -> int:
        COUNTERS.bump("surd.compare")
        return (self - Surd._coerce(other)).sign()

    # -- ordering (this is what makes L3's Pareto machinery apply verbatim) --
    def __eq__(self, other) -> bool:
        if not isinstance(other, Surd):
            return NotImplemented
        return self.terms == other.terms

    def __hash__(self) -> int:
        return hash(self.terms)

    def __lt__(self, other) -> bool:
        return self.compare(other) < 0

    def __le__(self, other) -> bool:
        return self.compare(other) <= 0

    def __gt__(self, other) -> bool:
        return self.compare(other) > 0

    def __ge__(self, other) -> bool:
        return self.compare(other) >= 0

    # -- views ------------------------------------------------------------
    def bracket(self, k: int = 32) -> Tuple[Fraction, Fraction]:
        """An exact rational enclosure, for printing.  No float is produced."""
        lo = Fraction(0)
        hi = Fraction(0)
        for m, c in self.terms:
            bl, bh = _bracket(m, k)
            if c > 0:
                lo += c * bl
                hi += c * bh
            else:
                lo += c * bh
                hi += c * bl
        return (lo, hi)

    def render(self) -> str:
        if not self.terms:
            return "0"
        parts = []
        for m, c in self.terms:
            cs = str(c.numerator) if c.denominator == 1 else "%d:%d" % (c.numerator,
                                                                       c.denominator)
            parts.append(cs if m == 1 else "%s*sqrt(%d)" % (cs, m))
        return " + ".join(parts).replace("+ -", "- ")

    def render_approx(self, digits: int = 6) -> str:
        """A decimal *string* built from exact integer arithmetic, for reading.

        No float is constructed: the digits come from an integer division of the
        exact rational bracket's midpoint numerator.  It is a rendering, and no
        decision anywhere in this package is made from it.
        """
        lo, hi = self.bracket(64)
        mid2 = lo + hi
        scale = 10 ** digits
        n = (mid2.numerator * scale) // (mid2.denominator * 2)
        sign = "-" if n < 0 else ""
        n = abs(n)
        whole, frac = n // scale, n % scale
        return "%s%d.%0*d" % (sign, whole, digits, frac)

    def __repr__(self) -> str:                       # pragma: no cover - view
        return "Surd(%s)" % self.render()


# --------------------------------------------------------------------------
# geometry
# --------------------------------------------------------------------------

@dataclass(frozen=True)
class Vec:
    """A point with exact rational coordinates."""

    x: Fraction
    y: Fraction

    @staticmethod
    def of(x, y) -> "Vec":
        return Vec(exact(x), exact(y))

    def minus(self, other: "Vec") -> "Vec":
        return Vec(self.x - other.x, self.y - other.y)

    def norm2(self) -> Fraction:
        """The exact squared length.  The unsquared length is generally a Surd."""
        return self.x * self.x + self.y * self.y

    def norm(self) -> Surd:
        return Surd.sqrt(self.norm2())

    def width(self) -> int:
        """Exact-arithmetic width: bits in the numerators and denominators."""
        out = 0
        for v in (self.x, self.y):
            out += abs(v.numerator).bit_length() + v.denominator.bit_length()
        return out

    def render(self) -> str:
        def f(v: Fraction) -> str:
            return str(v.numerator) if v.denominator == 1 else "%d:%d" % (
                v.numerator, v.denominator)
        return "(%s, %s)" % (f(self.x), f(self.y))


@dataclass(frozen=True)
class Medium:
    """A named optical medium with an exact rational refractive index ``n > 0``.

    ``n`` is rational on purpose.  Every index used in this package is a ratio
    of small integers, so every optical path length stays inside
    ``Q(sqrt ...)`` and every comparison stays exact.  A "physical" index like
    1.5168 is a decimal, i.e. a rational, and is representable here as
    ``Fraction(1897, 1250)`` with no loss whatsoever.
    """

    name: str
    index: Fraction

    @staticmethod
    def of(name: str, index) -> "Medium":
        n = exact(index)
        if n <= 0:
            raise OpticsError("a refractive index must be positive: %s" % n)
        return Medium(name, n)

    def render(self) -> str:
        n = self.index
        return "%s(n=%s)" % (self.name, str(n.numerator) if n.denominator == 1
                             else "%d:%d" % (n.numerator, n.denominator))


@dataclass(frozen=True)
class Ray:
    """A piecewise-linear path: ``k+1`` points and the medium of each of ``k``
    segments.  Nothing here asserts the path is physical; that is what the
    optimizer and the stationarity analysis are for."""

    points: Tuple[Vec, ...]
    media: Tuple[Medium, ...]

    def __post_init__(self) -> None:
        if len(self.points) < 2:
            raise OpticsError("a ray needs at least two points")
        if len(self.media) != len(self.points) - 1:
            raise OpticsError("each segment needs exactly one medium")

    def segments(self) -> Iterable[Tuple[Medium, Vec, Vec]]:
        for i, m in enumerate(self.media):
            yield (m, self.points[i], self.points[i + 1])

    def width(self) -> int:
        return sum(p.width() for p in self.points)

    def render(self) -> str:
        return " -> ".join(p.render() for p in self.points)


def optical_path_length(ray: Ray) -> Surd:
    """``sum_segments n * |p_{i+1} - p_i|``, exact, as a ``Surd``."""
    total = Surd.zero()
    for medium, p, q in ray.segments():
        COUNTERS.bump("optics.segment")
        total = total + Surd.scaled_sqrt(medium.index, q.minus(p).norm2())
    COUNTERS.bump("optics.opl")
    return total


def optical_time(ray: Ray, c: Quantity) -> Tuple[Surd, D.Dimension]:
    """OPL divided by the speed of light: the *time* Fermat's principle is about.

    Returned as ``(surd, dimension)`` because a ``Quantity`` holds a rational
    magnitude and an OPL is generally irrational.  The dimension is computed by
    ``dimension.py``, so ``optical_time`` of a path measured in metres against a
    ``c`` in metres per second has dimension ``T`` and could not have any other.
    """
    if c.value <= 0:
        raise OpticsError("the speed of light must be a positive magnitude")
    reciprocal = Fraction(c.value.denominator, c.value.numerator)
    return (optical_path_length(ray).scale(reciprocal), LENGTH.over(c.dim))


# --------------------------------------------------------------------------
# the discrete path family: parallel interfaces with a rational lattice
# --------------------------------------------------------------------------

def lattice(lo, hi, step) -> Tuple[Fraction, ...]:
    """``[lo, lo+step, ..., hi]`` in exact rationals.  Deterministic, finite."""
    lo, hi, step = exact(lo), exact(hi), exact(step)
    if step <= 0:
        raise OpticsError("lattice step must be positive")
    out: List[Fraction] = []
    k = 0
    v = lo
    while v <= hi:
        out.append(v)
        k += 1
        v = lo + step * k
    return tuple(out)


@dataclass(frozen=True)
class InterfaceStack:
    """The discrete path family the runtime optimizes over.

    ``media[0]`` is above ``interfaces[0]``, ``media[i]`` lies between
    ``interfaces[i-1]`` and ``interfaces[i]``, and ``media[-1]`` is below the
    last interface.  A *path* in the family is one lattice crossing point per
    interface; ``source`` sits in the first medium and ``target`` in the last.

    Reachability discipline (CRYSTAL.md Sec.4), stated because it must be:

    * **generated locus** -- rays whose crossings lie on the declared rational
      lattices, and nothing else;
    * **omitted locus** -- every crossing at an irrational abscissa, and every
      rational abscissa off the lattice.  The true Fermat crossing is generally
      in the omitted locus, which is exactly why ``snell_bracket`` exists and
      why no claim here is "the runtime found the physical ray";
    * **completion** -- the continuum family; the group law that extends is
      "OPL is a continuous convex function of the crossing abscissae" (for a
      single interface), and the operation that does *not* extend is
      "enumerate the family".
    """

    source: Vec
    target: Vec
    media: Tuple[Medium, ...]
    boundaries: Tuple[Fraction, ...]
    lattices: Tuple[Tuple[Fraction, ...], ...]

    def __post_init__(self) -> None:
        if len(self.media) != len(self.boundaries) + 1:
            raise OpticsError("k interfaces need k+1 media")
        if len(self.lattices) != len(self.boundaries):
            raise OpticsError("each interface needs one lattice")
        for i in range(1, len(self.boundaries)):
            if not self.boundaries[i] < self.boundaries[i - 1]:
                raise OpticsError("boundaries must descend in y")
        if not self.source.y > self.boundaries[0]:
            raise OpticsError("the source must lie in the first medium")
        if not self.target.y < self.boundaries[-1]:
            raise OpticsError("the target must lie in the last medium")

    @property
    def depth(self) -> int:
        return len(self.boundaries)

    def crossing(self, i: int, x: Fraction) -> Vec:
        return Vec(x, self.boundaries[i])

    def ray(self, xs: Sequence[Fraction]) -> Ray:
        """The ray crossing interface ``i`` at abscissa ``xs[i]``."""
        if len(xs) != self.depth:
            raise OpticsError("need one crossing per interface")
        pts = [self.source] + [self.crossing(i, exact(x)) for i, x in enumerate(xs)]
        pts.append(self.target)
        return Ray(tuple(pts), self.media)

    def opl(self, xs: Sequence[Fraction]) -> Surd:
        return optical_path_length(self.ray(xs))

    def paths(self) -> Iterable[Tuple[Fraction, ...]]:
        """Every member of the family, in a deterministic order."""
        combos: List[Tuple[Fraction, ...]] = [()]
        for lat in self.lattices:
            combos = [c + (x,) for c in combos for x in lat]
        for c in combos:
            yield c

    def size(self) -> int:
        n = 1
        for lat in self.lattices:
            n *= len(lat)
        return n


# --------------------------------------------------------------------------
# Snell, as a measurement of a route -- never as an input to finding one
# --------------------------------------------------------------------------

def sine_to_normal(dx: Fraction, dy: Fraction) -> Surd:
    """``sin`` of the angle between the segment ``(dx, dy)`` and the interface
    normal, signed by ``dx``.  Exact: ``dx / sqrt(dx^2+dy^2) = dx sqrt(m) / m``.

    The interface normal is the ``y`` axis throughout this module.
    """
    dx, dy = exact(dx), exact(dy)
    m = dx * dx + dy * dy
    if m == 0:
        raise OpticsError("a degenerate segment has no angle")
    COUNTERS.bump("optics.sine")
    return Surd.scaled_sqrt(Fraction(dx, m), m)


def snell_residual(stack: InterfaceStack, xs: Sequence[Fraction],
                   interface: int = 0) -> Surd:
    """``n_i sin(theta_i) - n_{i+1} sin(theta_{i+1})`` at one interface, exactly.

    This is a *measurement applied to a route already found*.  It is the exact
    derivative of the OPL with respect to that crossing abscissa, so it is zero
    exactly when the route is stationary in that coordinate -- but nothing in
    the routing machinery consults it, by design and by test.
    """
    ray = stack.ray(xs)
    p_in = ray.points[interface]
    p_mid = ray.points[interface + 1]
    p_out = ray.points[interface + 2]
    a = p_mid.minus(p_in)
    b = p_out.minus(p_mid)
    s1 = sine_to_normal(a.x, a.y).scale(stack.media[interface].index)
    s2 = sine_to_normal(b.x, b.y).scale(stack.media[interface + 1].index)
    COUNTERS.bump("optics.snell_residual")
    return s1 - s2


def reflection_residual(source: Vec, point: Vec, target: Vec,
                        tangent: Vec) -> Surd:
    """The law of reflection at ``point``, as an exact ``Surd`` that is zero
    exactly when the law holds.

    The law says the incident and reflected unit directions have equal
    tangential components:  ``(u.t)/|u| = (v.t)/|v|``, for ``u = P - A`` and
    ``v = B - P``.  Clearing denominators gives

        (u.t) * |v|  -  (v.t) * |u|   =   (u.t) sqrt(v.v) - (v.t) sqrt(u.u)

    which is a two-term ``Surd`` -- so its sign is decided by exactly the
    primitive the brief names, ``a sqrt(x)`` vs ``b sqrt(y)`` via ``a^2 x`` vs
    ``b^2 y``.  No angle, no arcsine, no square root evaluated.

    Like ``snell_residual`` this is a *measurement of a route*, never an input
    to finding one.
    """
    u = point.minus(source)
    v = target.minus(point)
    ut = u.x * tangent.x + u.y * tangent.y
    vt = v.x * tangent.x + v.y * tangent.y
    COUNTERS.bump("optics.reflection_residual")
    return Surd.scaled_sqrt(ut, v.norm2()) - Surd.scaled_sqrt(vt, u.norm2())


def circle_tangent(point: Vec) -> Vec:
    """The tangent to ``x^2+y^2=R^2`` at ``point``: exact, no normalisation."""
    return Vec(-point.y, point.x)


def snell_invariant(stack: InterfaceStack, xs: Sequence[Fraction]) -> Tuple[Surd, ...]:
    """``n sin(theta)`` in every medium along the route.  Snell's law says these
    are all equal; here they are simply *reported*, exactly."""
    ray = stack.ray(xs)
    out: List[Surd] = []
    for i, medium in enumerate(stack.media):
        d = ray.points[i + 1].minus(ray.points[i])
        out.append(sine_to_normal(d.x, d.y).scale(medium.index))
    return tuple(out)


# --------------------------------------------------------------------------
# stationarity -- a second algorithm, deliberately not the optimizer
# --------------------------------------------------------------------------

@dataclass(frozen=True)
class Critical:
    """A stationary point of a discrete family, with its exact classification."""

    index: int
    kind: str                       # "minimum" | "maximum" | "inflection" | "flat"
    value: Surd

    def render(self) -> str:
        return "i=%-4d %-11s opl=%s" % (self.index, self.kind, self.value.render())


def critical_points(values: Sequence[Surd], cyclic: bool = False) -> Tuple[Critical, ...]:
    """Stationary points of a discrete family, by exact sign changes.

    ``d_i = values[i+1] - values[i]``.  A point ``i`` is a discrete critical
    point when ``sign(d_{i-1})`` and ``sign(d_i)`` are not both ``+`` or both
    ``-``; it is a minimum on ``(-, +)``, a maximum on ``(+, -)``, and flat or
    an inflection otherwise.  Every comparison is an exact ``Surd`` sign.

    **This is not the extraction machinery and cannot be made into it.**  It
    enumerates the whole family and inspects local differences; it is an
    ``O(n)`` scan, not a shortest-path search, and it has no analogue at all
    once the family is a graph rather than a line.  That is the honest content
    of the stationary-vs-minimal disanalogy: minimization is a search, and
    stationarity is not.
    """
    n = len(values)
    if n < 3:
        return ()
    diffs: List[int] = []
    span = n if cyclic else n - 1
    for i in range(span):
        j = (i + 1) % n
        diffs.append((values[j] - values[i]).sign())
    out: List[Critical] = []
    rng = range(n) if cyclic else range(1, n - 1)
    for i in rng:
        prev = diffs[(i - 1) % len(diffs)]
        nxt = diffs[i % len(diffs)]
        if prev < 0 and nxt > 0:
            kind = "minimum"
        elif prev > 0 and nxt < 0:
            kind = "maximum"
        elif prev == 0 and nxt == 0:
            kind = "flat"
        elif prev == 0 or nxt == 0:
            kind = "flat"
        else:
            continue                     # strictly monotone through i
        out.append(Critical(index=i, kind=kind, value=values[i]))
    COUNTERS.bump("optics.critical_scan")
    return tuple(out)


# --------------------------------------------------------------------------
# a reflecting arc, generated by the rational chart
# --------------------------------------------------------------------------

@dataclass(frozen=True)
class MirrorArc:
    """Reflection points on the circle ``x^2 + y^2 = R^2``, generated exactly.

    The generated locus is the image of the rational chart

        t  |->  ( R(1-t^2)/(1+t^2),  R(2t)/(1+t^2) )

    over a finite rational lattice of ``t``, **plus** the chart's omitted point
    ``(-R, 0)``, which no finite ``t`` reaches.  That is
    ``notes/RATIONAL_CIRCLE_ATLAS.md``'s exact-finite-address / dense /
    measure-zero situation, restated for a mirror: the group law (rotation by a
    rational point) extends to the whole circle; the enumeration successor does
    not, and the *irrational* reflection points are the omitted locus.

    Points are ordered by increasing ``t`` with the omitted point first, which
    is the cyclic order around the circle, so ``critical_points(..., cyclic=True)``
    is meaningful on the resulting value list.
    """

    radius: Fraction
    ts: Tuple[Fraction, ...]

    @staticmethod
    def of(radius, ts: Sequence) -> "MirrorArc":
        r = exact(radius)
        if r <= 0:
            raise OpticsError("a mirror radius must be positive")
        return MirrorArc(r, tuple(exact(t) for t in ts))

    def points(self) -> Tuple[Vec, ...]:
        out = [Vec(-self.radius, Fraction(0))]        # the chart's omitted point
        for t in self.ts:
            den = 1 + t * t
            out.append(Vec(self.radius * Fraction(1 - t * t, den),
                           self.radius * Fraction(2 * t, den)))
        return tuple(out)

    def on_circle(self, p: Vec) -> bool:
        return p.norm2() == self.radius * self.radius

    def omitted_locus(self) -> str:
        return ("every irrational point of the circle, plus every rational point "
                "whose chart parameter is off the declared lattice; the chart's "
                "own omitted point (-R, 0) is supplied explicitly as the second "
                "chart")
