{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- अनन्त-केन्द्र — the center of the endless braid.
--
-- THE GARBHA'S SEED, ACTED ON.  With the ledger closed, the next
-- level is the symmetry OF the closed action, and its first citizen
-- is exhibited here: the INFINITE FULL TWIST — the half-wave applied
-- to every strand at once, by corecursion — is
--
--   §2  CENTRAL: it commutes with every crossing at every position
--       (the half-wave exchanges with the quarter turn pointwise by
--       one pair-split refl, and the stream paths close with
--       definitional leaves);
--
--   §3  OF ORDER TWO: its square is the identity, by a corecursive
--       path riding double-negation down the rope;
--
--   §4  PURE RESIDUE: it is an assembled fibrewise family — no base
--       motion — so the center of the infinite braid action lives
--       exactly where PurnaModa found the three-strand center: in
--       the descendable, vertical, per-strand stratum.
--
-- The tower's law scales to its limit: at three strands the full
-- twist was the global half-wave, central by refl; at infinity the
-- same object, now an infinite corecursive symmetry, is central by
-- stream paths.  What commutes with all coherence is what every
-- strand carries alone — the center is the descendable part, at
-- every scale including the endless one.
--
-- SYĀT — THE CLAIM, EXACTLY.  Centrality against the generators,
-- order two, and verticality; that the center is generated by this
-- twist (no other central elements beyond its powers) is the
-- standing construction.
------------------------------------------------------------------------

module AnantaKendra_TheInfiniteFullTwistIsCentralForTheWholeActionOfOrderTwoAndPureResidue where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat using (ℕ ; zero ; suc)
open import Cubical.Data.Bool using (Bool ; notnot)
open import Cubical.Data.Sigma using (_,_ ; fst ; snd)

open import Parasparasraya_TheMutualDependenceObjectionChecksWhenTheLeaningIsProductive
  using (Dhārā)
open import VeniBandha_TheSuppliedCoherenceIsTheQuarterTurnTheTwistedSwapBraidsByReflAndTheGeneratorHasExactOrderEight
  using (Sūtra)
open import CaturamsaBhramana_TheQuarterWaveLivesOnlyOnTheInterdependentPairAndEachSenseCarriesExactlyItsSquare
  using (caturaṃśa ; ardha)
open import AnantaVeni_TheInfiniteBraidActsOnTheInterdependentStreamAndEveryRelationOfEveryBraidGroupHoldsAtOnce
  using (Rajju ; saṃyoga ; veṇī∞)

open Dhārā

------------------------------------------------------------------------
-- १ · The infinite full twist, and the pointwise exchange.
------------------------------------------------------------------------

ardha∞ : Rajju → Rajju
śiras (ardha∞ s) = ardha (śiras s)
śeṣam (ardha∞ s) = ardha∞ (śeṣam s)

-- The half-wave and the quarter turn exchange, by one pair-split.
ardha-catur : (x : Sūtra) → ardha (caturaṃśa x) ≡ caturaṃśa (ardha x)
ardha-catur (a , b) = refl

-- The half-wave is an involution, pointwise.
ardha-dvi : (x : Sūtra) → ardha (ardha x) ≡ x
ardha-dvi (a , b) i = notnot a i , notnot b i

------------------------------------------------------------------------
-- २ · Centrality: the infinite twist commutes with every crossing.
------------------------------------------------------------------------

kendra∞ : (i : ℕ) (s : Rajju)
        → ardha∞ (veṇī∞ i s) ≡ veṇī∞ i (ardha∞ s)
śiras (kendra∞ zero s j) = ardha-catur (śiras (śeṣam s)) j
śiras (śeṣam (kendra∞ zero s j)) = ardha (śiras s)
śeṣam (śeṣam (kendra∞ zero s j)) = ardha∞ (śeṣam (śeṣam s))
śiras (kendra∞ (suc i) s j) = ardha (śiras s)
śeṣam (kendra∞ (suc i) s j) = kendra∞ i (śeṣam s) j

------------------------------------------------------------------------
-- ३ · Order two, down the whole rope.
------------------------------------------------------------------------

dvi-kendra : (s : Rajju) → ardha∞ (ardha∞ s) ≡ s
śiras (dvi-kendra s j) = ardha-dvi (śiras s) j
śeṣam (dvi-kendra s j) = dvi-kendra (śeṣam s) j

------------------------------------------------------------------------
-- ४ · Pure residue: the twist is an assembled fibrewise family — its
-- action never moves the base, only every fibre at once, which is
-- visible in its very definition: śiras acts, śeṣam recurses, no
-- strand changes address.  The center of the endless braid lives in
-- the vertical stratum, at infinity as at three.
------------------------------------------------------------------------
