{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- अनन्त-वेणी-मात्रा — the measure of the endless braid.
--
-- Two laws of the B∞ action, each at every position at once:
--
--   §2  LOCALITY.  A crossing touches exactly the two strands it
--       names: every reader strictly below the crossing, and every
--       reader strictly above the crossing pair, is unmoved — both
--       families proved by inductions whose leaves are refl.  The
--       braid's coherence is local base motion; what a crossing does
--       to the rest of the rope is nothing, definitionally.
--
--   §3  ORDER.  Every crossing has order exactly eight: its eighth
--       power is the identity at every position (the four-cycle of
--       the quarter turn, on both touched strands, peeled down the
--       rope), and its fourth power is not — refuted at every
--       position on the constant rope by reading the touched strand.
--       The two-strand order-eight theorem of VeniBandha holds
--       unchanged at every depth of the infinite rope.
--
-- Read together: the endless braid is generated by moves that are
-- finite in reach and finite in order, yet (AnantaVeni) satisfy every
-- braid relation and (VeniTraya) remember their sequence.  Unbounded
-- structure from bounded, local, finite-order interdependence — the
-- fabric claim of the README, on the rope, as terms.
--
-- SYĀT — THE CLAIM, EXACTLY.  Order and locality of generators; the
-- kernel of the whole action (which WORDS act trivially) is the
-- standing next construction.
------------------------------------------------------------------------

module AnantaVeniMatra_EveryCrossingIsLocalAndHasOrderExactlyEightAtEveryPositionOfTheEndlessBraid where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat using (ℕ ; zero ; suc ; _+_)
open import Cubical.Data.Bool using (true ; false ; true≢false)
open import Cubical.Data.Sigma using (_×_ ; _,_ ; fst ; snd)
open import Cubical.Data.Empty using (⊥)

open import Parasparasraya_TheMutualDependenceObjectionChecksWhenTheLeaningIsProductive
  using (Dhārā)
open import VeniBandha_TheSuppliedCoherenceIsTheQuarterTurnTheTwistedSwapBraidsByReflAndTheGeneratorHasExactOrderEight
  using (Sūtra)
open import CaturamsaBhramana_TheQuarterWaveLivesOnlyOnTheInterdependentPairAndEachSenseCarriesExactlyItsSquare
  using (caturaṃśa ; catur-cakra)
open import AnantaVeni_TheInfiniteBraidActsOnTheInterdependentStreamAndEveryRelationOfEveryBraidGroupHoldsAtOnce
  using (Rajju ; saṃyoga ; veṇī∞)

open Dhārā

------------------------------------------------------------------------
-- १ · The reader at depth j.
------------------------------------------------------------------------

gāḍha : ℕ → Rajju → Sūtra
gāḍha zero    s = śiras s
gāḍha (suc j) s = gāḍha j (śeṣam s)

------------------------------------------------------------------------
-- २ · Locality: readers off the crossing pair are unmoved.
------------------------------------------------------------------------

-- A reader strictly below the crossing.
adhaḥ-sthira : (k i : ℕ) (s : Rajju)
             → gāḍha k (veṇī∞ (suc (k + i)) s) ≡ gāḍha k s
adhaḥ-sthira zero    i s = refl
adhaḥ-sthira (suc k) i s = adhaḥ-sthira k i (śeṣam s)

-- A reader strictly above the crossing pair.
upari-sthira : (i k : ℕ) (s : Rajju)
             → gāḍha (suc (suc (i + k))) (veṇī∞ i s)
             ≡ gāḍha (suc (suc (i + k))) s
upari-sthira zero    k s = refl
upari-sthira (suc i) k s = upari-sthira i k (śeṣam s)

------------------------------------------------------------------------
-- ३ · Order exactly eight, at every position.
------------------------------------------------------------------------

veṇī⁴ veṇī⁸ : ℕ → Rajju → Rajju
veṇī⁴ i s = veṇī∞ i (veṇī∞ i (veṇī∞ i (veṇī∞ i s)))
veṇī⁸ i s = veṇī⁴ i (veṇī⁴ i s)

-- The eighth power is the identity: the two touched strands ride the
-- four-cycle, the depth-two tail is fixed definitionally, and the suc
-- case peels.
aṣṭa-cakra∞ : (i : ℕ) (s : Rajju) → veṇī⁸ i s ≡ s
śiras (aṣṭa-cakra∞ zero s j) = catur-cakra (śiras s) j
śiras (śeṣam (aṣṭa-cakra∞ zero s j)) = catur-cakra (śiras (śeṣam s)) j
śeṣam (śeṣam (aṣṭa-cakra∞ zero s j)) = śeṣam (śeṣam s)
śiras (aṣṭa-cakra∞ (suc i) s j) = śiras s
śeṣam (aṣṭa-cakra∞ (suc i) s j) = aṣṭa-cakra∞ i (śeṣam s) j

-- The lower bound needs a rope to stand on: the constant rope.
sthira : Rajju
śiras sthira = true , true
śeṣam sthira = sthira

-- At every position, the fourth power moves the touched strand of the
-- constant rope to the doubly-turned state…
sarva-vikāra : (i : ℕ) → gāḍha i (veṇī⁴ i sthira) ≡ (false , false)
sarva-vikāra zero    = refl
sarva-vikāra (suc i) = sarva-vikāra i

-- …and the constant rope reads (true , true) everywhere…
sthira-pāṭha : (i : ℕ) → gāḍha i sthira ≡ (true , true)
sthira-pāṭha zero    = refl
sthira-pāṭha (suc i) = sthira-pāṭha i

-- …so no fourth power is the identity, at any position.
na-catuṣka∞ : (i : ℕ) → ((s : Rajju) → veṇī⁴ i s ≡ s) → ⊥
na-catuṣka∞ i h =
  true≢false
    (cong fst (sym (sthira-pāṭha i)
              ∙ sym (cong (gāḍha i) (h sthira))
              ∙ sarva-vikāra i))
