{-# OPTIONS --cubical --safe #-}

-- A smallest exact holonomy/refinement organ.
--
-- This is finite lattice-gauge kinematics, not full loop quantum gravity:
-- there is no SU(2) representation theory, spin-network Hilbert space,
-- flux operator, geometric operator, constraint, or spin-foam amplitude here.
-- What is checked is the common kinematic seam.  Subdividing one oriented
-- edge into two introduces an internal gauge coordinate; quotienting that
-- coordinate is equivalent (as a Cubical path-level object) to the original
-- coarse holonomy.  Endpoint gauge transformations remain visible, while a
-- conjugation-invariant closed-loop observation descends through them.

module RelationalHolonomyRefinement where

open import Cubical.Foundations.Prelude
open import Cubical.Foundations.Equiv using (_≃_)
open import Cubical.Foundations.Structure using (⟨_⟩)
open import Cubical.Foundations.Isomorphism using (Iso ; isoToEquiv)
open import Cubical.Foundations.Univalence using (ua ; uaβ)
open import Cubical.Data.Sigma using (Σ≡Prop)
open import Cubical.Data.Prod using (_×_ ; _,_)
open import Cubical.HITs.SetQuotients as SQ using (_/_ ; [_] ; eq/ ; squash/)
open import Cubical.Algebra.Group.Base using (Group ; GroupStr)
open import Cubical.Algebra.Group.Properties using (module GroupTheory)

module _ {ℓ : Level} (G : Group ℓ) where

  private
    module G = GroupStr (snd G)
    module GT = GroupTheory G

  -- One oriented coarse edge and its two-edge subdivision.
  Coarse : Type ℓ
  Coarse = ⟨ G ⟩

  Refined : Type ℓ
  Refined = ⟨ G ⟩ × ⟨ G ⟩

  -- Path order: (a , b) traverses a first and b second.
  holonomy : Refined → Coarse
  holonomy (a , b) = b G.· a

  subdivide : Coarse → Refined
  subdivide g = G.1g , g

  holonomy-subdivide : (g : Coarse) → holonomy (subdivide g) ≡ g
  holonomy-subdivide g = G.·IdR g

  -- Gauge at the new internal vertex.  It changes the two edge labels but
  -- cannot change their composite transport.
  internalGauge : ⟨ G ⟩ → Refined → Refined
  internalGauge h (a , b) = (h G.· a) , (b G.· G.inv h)

  holonomy-internalGauge : (h : ⟨ G ⟩) (x : Refined)
    → holonomy (internalGauge h x) ≡ holonomy x
  holonomy-internalGauge h (a , b) =
      G.·Assoc (b G.· G.inv h) h a
    ∙ cong (G._· a) (sym (G.·Assoc b (G.inv h) h))
    ∙ cong (λ z → (b G.· z) G.· a) (G.·InvL h)
    ∙ cong (G._· a) (G.·IdR b)

  InternalRel : Refined → Refined → Type ℓ
  InternalRel x y = Σ[ h ∈ ⟨ G ⟩ ] (internalGauge h x ≡ y)

  RefinedModuloInternalGauge : Type ℓ
  RefinedModuloInternalGauge = Refined / InternalRel

  refinedClass : Refined → RefinedModuloInternalGauge
  refinedClass = [_]

  quotientHolonomy : RefinedModuloInternalGauge → Coarse
  quotientHolonomy = SQ.rec G.is-set holonomy
    (λ x y r → sym (holonomy-internalGauge (fst r) x)
               ∙ cong holonomy (snd r))

  coarseClass : Coarse → RefinedModuloInternalGauge
  coarseClass g = refinedClass (subdivide g)

  quotientHolonomy-coarseClass : (g : Coarse)
    → quotientHolonomy (coarseClass g) ≡ g
  quotientHolonomy-coarseClass = holonomy-subdivide

  -- Every refined connection is path-equal in the quotient to the canonical
  -- subdivision of its composite.  The path is generated by the internal
  -- gauge h = a⁻¹, so the extra subdivision coordinate is exactly gauge.
  canonicalize : (x : Refined)
    → refinedClass x ≡ coarseClass (holonomy x)
  canonicalize (a , b) = eq/ _ _ (G.inv a , pairPath)
    where
    firstPath : G.inv a G.· a ≡ G.1g
    firstPath = G.·InvL a

    secondPath : b G.· G.inv (G.inv a) ≡ b G.· a
    secondPath = cong (b G.·_) (GT.invInv a)

    pairPath : internalGauge (G.inv a) (a , b)
             ≡ subdivide (holonomy (a , b))
    pairPath i = firstPath i , secondPath i

  coarseClass-quotientHolonomy : (q : RefinedModuloInternalGauge)
    → coarseClass (quotientHolonomy q) ≡ q
  coarseClass-quotientHolonomy =
    SQ.elimProp (λ _ → squash/ _ _) (λ x → sym (canonicalize x))

  -- Cylindrical consistency as an actual equivalence, not a cardinality
  -- comparison: coarse holonomy and refined connections modulo the new
  -- internal gauge degree are mutually inverse.
  cylindricalIso : Iso RefinedModuloInternalGauge Coarse
  Iso.fun cylindricalIso = quotientHolonomy
  Iso.inv cylindricalIso = coarseClass
  Iso.rightInv cylindricalIso = quotientHolonomy-coarseClass
  Iso.leftInv cylindricalIso = coarseClass-quotientHolonomy

  cylindricalEquiv : RefinedModuloInternalGauge ≃ Coarse
  cylindricalEquiv = isoToEquiv cylindricalIso

  -- Univalence internalizes cylindrical consistency as identity of state
  -- spaces.  Transport is executable: a refined gauge class crosses the
  -- path to exactly its composite coarse holonomy.
  cylindricalPath : RefinedModuloInternalGauge ≡ Coarse
  cylindricalPath = ua cylindricalEquiv

  cylindricalTransport : (x : Refined)
    → subst (λ X → X) cylindricalPath (refinedClass x) ≡ holonomy x
  cylindricalTransport x = uaβ cylindricalEquiv (refinedClass x)

  -- Gauge at the two retained endpoints.  Refinement commutes with it after
  -- choosing the canonical subdivision, and coarse holonomy transforms by
  -- the usual endpoint law t · g · s⁻¹.
  endpointGauge : (⟨ G ⟩ × ⟨ G ⟩) → Coarse → Coarse
  endpointGauge (s , t) g = (t G.· g) G.· G.inv s

  refinedEndpointGauge : (⟨ G ⟩ × ⟨ G ⟩) → Refined → Refined
  refinedEndpointGauge (s , t) (a , b) =
    (a G.· G.inv s) , (t G.· b)

  holonomy-endpointGauge : (u : ⟨ G ⟩ × ⟨ G ⟩) (x : Refined)
    → holonomy (refinedEndpointGauge u x)
      ≡ endpointGauge u (holonomy x)
  holonomy-endpointGauge (s , t) (a , b) = first ∙ second
    where
    first : (t G.· b) G.· (a G.· G.inv s)
          ≡ ((t G.· b) G.· a) G.· G.inv s
    first = G.·Assoc (t G.· b) a (G.inv s)

    second : ((t G.· b) G.· a) G.· G.inv s
           ≡ (t G.· (b G.· a)) G.· G.inv s
    second = cong (λ z → z G.· G.inv s) (sym (G.·Assoc t b a))

  -- For a closed loop the source and target gauges coincide, hence holonomy
  -- changes by conjugation.  A class function is the abstract trace-like
  -- observable; no matrix representation or Wilson operator is postulated.
  ConjugationInvariant : {ℓo : Level} {O : Type ℓo}
    → (⟨ G ⟩ → O) → Type (ℓ-max ℓ ℓo)
  ConjugationInvariant f =
    (h g : ⟨ G ⟩) → f ((h G.· g) G.· G.inv h) ≡ f g

  closedLoopGaugeInvariant : {ℓo : Level} {O : Type ℓo}
    (f : ⟨ G ⟩ → O) → ConjugationInvariant f
    → (h g : ⟨ G ⟩) → f (endpointGauge (h , h) g) ≡ f g
  closedLoopGaugeInvariant f invariant h g = invariant h g
