{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- ArchivistLane -- a build aggregate: one module importing the modules
-- below, so that a single command rechecks all of them together.
------------------------------------------------------------------------

module ArchivistLane where

import AbhihitanvayaAnvitabhidhana_TheTypeOfTheSemanticsAlreadyTakesASideAndSoundnessIsFreeOnOneOfThem
import CertifiedRewritesFormASemicategoryAndOnlyTheCostComponentNeedsAnHLevel
import CurvatureIsNonVacuousBecauseHereIsOnePointOffTheImage
import DistrustIsExactlyNotCapableSoTheOnlyIsAnEquivalenceAndNotOneInclusion
import ExhaustionNotLengthIsWhatCoverageNeedsAndSafetyNeverNeededAnyFuelAtAll
import FullAbstractionIsAConditionOnTheContextFamilyAndCurvatureIsWitnessedInIt
import HolonomyIsInvisibleExactlyToAnInvariantConsumerAndExactlyIsNowEarned
import NRectanglesCannotCoverSucNFoolingCellsEvenWhenTheCoveringIsOnlyAProperty
import ProvenanceIsCarriedAndNeverConsumedSoFreeWasDoingDoubleDuty
import RnaDhana_TheStrongerFormIsUpstreamOfTheFlipAndOnlyItsImageWasPublished
import TheAdjunctionAndTheUnitCounitPackageAreInterderivableAndTheyNeedDifferentAxioms
import TheAdmissibleOrdersArePreciselyThePrincipalUpSetSoStrengthIsNotAFunctionOfTheEdgeCount
import TheCanonicalFuelIsTheArchivesOwnLengthAndOverFuellingIsInert
import TheCardinalFormOfTheFoolingBoundNeedsAnInjectionOfFinIntoFinAndDoesNotFollowByInstantiation
import TheCardinalityHalfOfOptimalIsExactlyAMereEquivalenceAndItSaysNothingAboutTheSchemeItself
import TheConverseContainmentReducesToPermTransitivityAndTheOtherThreeCasesAreFree
import TheEmptyListWasNeverCheckedAndItRefutesExactlyWhenTheDecoderSpaceIsEmpty
import TheExchangeLemmaIsTheWholeOfPermTransitivitySoTheConverseContainmentIsNowATheorem
import TheFamiliesAgreeOffTheBoundarySoDifferOnlyIsNowBothDirections
import TheFourVerdictsAreNotAPartitionAndUndecidedIsExclusiveOnlyWithForms
import TheImpossibilityNeedsNeitherHPropNorEveryRepresentative
import TheLeastRefutingListIsNotUniqueSoTheMeasureIsANumberAndNotACanonicalWitness
import TheOpenPigeonholeReducesToFinAndTheTargetBeingAPropIsWhatMakesTheMereEquivalencesUsable
import TheSeamIsVisibleTheMomentSomebodyIsPerfectSoExactlyWhenIsNowBothDirections
import TheTextPredicateIsUniqueSoExistsCarriesNoChoice
import TheTransportOverheadIsProvablyRedundantAndItsMechanismIsALibraryLemmaNotAMeasurement
import TheTwoDirectionsUpgradeToAnEquivalenceBecauseBothSidesArePropositions
import TheTwoPigeonholesAreInterderivableSoNothingAboutFiniteSetsIsLeftInTheOpenItem
import TheTwoSidedCutExistsOverANonEmptyResidualIndex
import TheTwoSidedCutNeedsNoInfinityBecauseTheEmptyMeetIsZero
import TheTwoSidedProfileCutNeedsTheBurdensAsAProfile
import TheUsualReasonsMadeExplicitTheInductivePermutationRelationEmbedsInAdjacentTranspositions
import TotalityNotSizeIsWhatTurnsAScopedFactorizationGlobal
import VacuityIsExactlyEmptinessAndTheEquivalenceCostsAUniverseLift
import CountingIsWhatDecidableEqualityBuysAndPermutationPreservesEveryMultiplicity
import Durnaya_TheProhibitionHasContentOnlyOffThePropositionalWorld
import Pythagoras_RatioIsTheInvariantAndLengthIsThePresentation
import Abhava_MamaAdarsanamNaTasyaAbhavah
import Nirjara_SheddingAPrimitiveCostsLaghava
