{-# OPTIONS --cubical-compatible --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- The elder's store, emitted on the act side so the compiled mouth can
-- speak about it.  Generated from machine/library.terms by
-- machine/AgamaLekhaka_...awk — the same 102 pairs the --cubical body
-- judged; one generator, two habitats, and the body's censuses are the
-- knowledge-portion's warrant for whatever the binary reports.
------------------------------------------------------------------------

module AgamaKanda_TheEldersStoreOnTheActSide where

open import Agda.Builtin.Nat using (Nat ; zero ; suc)
open import Agda.Builtin.List using (List ; [] ; _∷_)
open import Agda.Builtin.Sigma using (_,_)
open import KarmaKanda_TheActPortionOfTheBodyPathFreeAndCompiled

-- regenerated 2026-08-24: 108 unique pairs (gcd crossed; 5 fresh-constant lines stay with the elder)
आगमः : List Eq'
आगमः = ( (ze ⊕ (var 0)) , (var 0) )
      ∷ ( (mx (var 0) (var 0)) , (var 0) )
      ∷ ( (ze ⊗ (var 0)) , ze )
      ∷ ( ((var 0) ⊖ (var 0)) , ze )
      ∷ ( ((su ze) ⊗ (var 0)) , (var 0) )
      ∷ ( ((var 0) ⊖ (su (var 0))) , ze )
      ∷ ( (lq (su (var 0)) (var 0)) , ze )
      ∷ ( (lq (var 0) (var 0)) , (su ze) )
      ∷ ( ((su ze) ⊕ (var 0)) , (su (var 0)) )
      ∷ ( (mx (var 0) (su (var 0))) , (su (var 0)) )
      ∷ ( (mx (su (var 0)) (var 0)) , (su (var 0)) )
      ∷ ( ((su (var 0)) ⊖ (var 0)) , (su ze) )
      ∷ ( (lq (var 0) (su (var 0))) , (su ze) )
      ∷ ( (su ((var 0) ⊕ (var 1))) , ((su (var 0)) ⊕ (var 1)) )
      ∷ ( ((var 1) ⊕ (var 0)) , ((var 0) ⊕ (var 1)) )
      ∷ ( ((var 0) ⊖ (lq (var 0) ze)) , (var 0) )
      ∷ ( ((var 0) ⊗ (lq (var 0) ze)) , ze )
      ∷ ( ((lq (var 0) ze) ⊗ (var 0)) , ze )
      ∷ ( ((var 0) ⊖ (su (su (var 0)))) , ze )
      ∷ ( (lq (su (su (var 0))) (var 0)) , ze )
      ∷ ( (lq (var 0) (su (su (var 0)))) , (su ze) )
      ∷ ( ((su (su ze)) ⊗ (var 0)) , ((var 0) ⊕ (var 0)) )
      ∷ ( ((lq (var 0) ze) ⊖ (var 0)) , (lq (var 0) ze) )
      ∷ ( (lq (var 0) (lq (var 0) ze)) , (lq (var 0) ze) )
      ∷ ( (lq ((var 0) ⊕ (var 0)) ze) , (lq (var 0) ze) )
      ∷ ( (lq ((var 0) ⊕ (var 1)) (var 1)) , (lq (var 0) ze) )
      ∷ ( (mx (var 0) (su (su (var 0)))) , (su (su (var 0))) )
      ∷ ( (mx (su (su (var 0))) (var 0)) , (su (su (var 0))) )
      ∷ ( ((su (su (var 0))) ⊖ (var 0)) , (su (su ze)) )
      ∷ ( (lq (lq (var 0) ze) (var 0)) , (lq (su ze) (var 0)) )
      ∷ ( (lq (lq (var 0) ze) ze) , (lq (su ze) (var 0)) )
      ∷ ( (gc (var 0) (lq (var 0) ze)) , (mx (var 0) (su ze)) )
      ∷ ( (gc (lq (var 0) ze) (var 0)) , (mx (var 0) (su ze)) )
      ∷ ( (mx (var 0) (lq (var 0) ze)) , (mx (var 0) (su ze)) )
      ∷ ( (mx (lq (var 0) ze) (var 0)) , (mx (var 0) (su ze)) )
      ∷ ( (su ((var 0) ⊖ (su ze))) , (mx (var 0) (su ze)) )
      ∷ ( ((var 1) ⊕ ((var 0) ⊕ (var 0))) , ((var 0) ⊕ ((var 0) ⊕ (var 1))) )
      ∷ ( (su ze) , (lq (var 0) ((var 0) ⊕ (var 1))) )
      ∷ ( ((var 0) ⊕ ((var 1) ⊕ (var 2))) , (((var 0) ⊕ (var 1)) ⊕ (var 2)) )
      ∷ ( (lq (var 0) (var 2)) , (lq ((var 0) ⊕ (var 1)) ((var 2) ⊕ (var 1))) )
      ∷ ( ((var 1) ⊕ ((var 0) ⊗ (var 1))) , ((su (var 0)) ⊗ (var 1)) )
      ∷ ( (mx ((var 0) ⊕ (var 1)) (var 0)) , ((var 0) ⊕ (var 1)) )
      ∷ ( (mx (var 0) (lq (su ze) (var 0))) , (var 0) )
      ∷ ( ((var 0) ⊖ (su ((var 0) ⊕ (var 1)))) , ze )
      ∷ ( ((var 0) ⊖ (su (su (su (var 0))))) , ze )
      ∷ ( ((lq (var 0) ze) ⊖ (su (var 0))) , ze )
      ∷ ( (lq (mx (var 0) (su (var 1))) ze) , ze )
      ∷ ( (lq (mx (su (var 0)) (var 1)) ze) , ze )
      ∷ ( (lq (su ((var 0) ⊕ (var 1))) (var 0)) , ze )
      ∷ ( (lq (su ((var 0) ⊕ (var 1))) (var 1)) , ze )
      ∷ ( (lq (su (su (su (var 0)))) (var 0)) , ze )
      ∷ ( (mx (lq (var 0) ze) (su (var 0))) , (su (var 0)) )
      ∷ ( (mx (su (var 0)) (lq (var 0) ze)) , (su (var 0)) )
      ∷ ( (mx (su (var 0)) (lq (var 1) ze)) , (su (var 0)) )
      ∷ ( (lq (var 0) (su ((var 0) ⊕ (var 1)))) , (su ze) )
      ∷ ( (lq (var 0) (su (su (su (var 0))))) , (su ze) )
      ∷ ( (lq (lq (var 0) ze) (su (var 0))) , (su ze) )
      ∷ ( (lq (lq (var 0) ze) (su (var 1))) , (su ze) )
      ∷ ( (lq (lq (su ze) (var 0)) (var 0)) , (su ze) )
      ∷ ( ((var 0) ⊗ (mx (var 0) (su ze))) , ((var 0) ⊗ (var 0)) )
      ∷ ( ((mx (var 0) (su ze)) ⊗ (var 0)) , ((var 0) ⊗ (var 0)) )
      ∷ ( (lq (lq (su ze) (var 0)) ze) , (lq (var 0) ze) )
      ∷ ( ((var 0) ⊖ (lq (su ze) (var 0))) , ((var 0) ⊖ (su ze)) )
      ∷ ( (lq ((var 0) ⊕ ((var 0) ⊗ (var 0))) ze) , (lq (var 0) ze) )
      ∷ ( (lq ((var 0) ⊕ ((var 0) ⊗ (var 1))) ze) , (lq (var 0) ze) )
      ∷ ( (lq ((var 0) ⊖ (su ze)) (var 1)) , (lq (var 0) (su (var 1))) )
      ∷ ( (lq (var 0) (lq (su ze) (var 0))) , (lq (var 0) (su ze)) )
      ∷ ( (lq ((var 0) ⊕ (var 1)) (su (var 1))) , (lq (var 0) (su ze)) )
      ∷ ( (lq ((var 0) ⊖ (su ze)) ze) , (lq (var 0) (su ze)) )
      ∷ ( (lq (su ze) ((var 0) ⊗ (var 0))) , (lq (su ze) (var 0)) )
      ∷ ( (lq (su ze) ((var 0) ⊕ (var 0))) , (lq (su ze) (var 0)) )
      ∷ ( (mx (var 0) (su ((var 0) ⊕ (var 1)))) , (su ((var 0) ⊕ (var 1))) )
      ∷ ( (mx (su ((var 0) ⊕ (var 1))) (var 0)) , (su ((var 0) ⊕ (var 1))) )
      ∷ ( (mx (var 0) (su (su (su (var 0))))) , (su (su (su (var 0)))) )
      ∷ ( (mx (su (su (su (var 0)))) (var 0)) , (su (su (su (var 0)))) )
      ∷ ( ((su (su (su (var 0)))) ⊖ (var 0)) , (su (su (su ze))) )
      ∷ ( (mx ((var 0) ⊕ (var 0)) (su ze)) , ((var 0) ⊕ (mx (var 0) (su ze))) )
      ∷ ( (mx ((var 0) ⊕ (var 1)) (su (var 0))) , ((var 0) ⊕ (mx (var 1) (su ze))) )
      ∷ ( ((var 0) ⊕ ze) , (var 0) )
      ∷ ( ((var 0) ⊗ ze) , ze )
      ∷ ( (((var 0) ⊗ (var 1)) ⊕ ((var 0) ⊗ ze)) , ((var 0) ⊗ ((var 1) ⊕ ze)) )
      ∷ ( (mx (ze ⊕ ze) ((var 0) ⊕ ze)) , ((mx ze (var 0)) ⊕ ze) )
      ∷ ( (((var 0) ⊕ (var 0)) ⊗ (var 1)) , ((var 0) ⊗ ((var 1) ⊕ (var 1))) )
      ∷ ( (mx ze (var 0)) , (var 0) )
      ∷ ( (ze ⊖ (var 0)) , ze )
      ∷ ( ((var 0) ⊗ (lq ze ze)) , (var 0) )
      ∷ ( (mx (var 0) ((var 1) ⊗ ze)) , (var 0) )
      ∷ ( (mx (ze ⊕ (var 0)) (var 0)) , (var 0) )
      ∷ ( ((var 0) ⊗ (ze ⊕ ze)) , ze )
      ∷ ( (((var 0) ⊗ (var 1)) ⊗ ze) , ze )
      ∷ ( (mx ze ((var 0) ⊗ ze)) , ze )
      ∷ ( (lq ((var 0) ⊗ ze) (var 1)) , (su ze) )
      ∷ ( (lq ((var 0) ⊗ ze) ze) , (su ze) )
      ∷ ( (((var 0) ⊗ ze) ⊗ ((var 0) ⊗ ze)) , ze )
      ∷ ( (((var 0) ⊗ ze) ⊕ (((var 0) ⊗ ze) ⊗ (su ((var 0) ⊗ ze)))) , ze )
      ∷ ( ((((var 0) ⊗ ze) ⊗ ((var 0) ⊗ ze)) ⊗ (((var 0) ⊗ ze) ⊗ ((var 0) ⊗ ze))) , ze )
      ∷ ( ((ze ⊖ (var 0)) ⊗ ze) , ze )
      ∷ ( (ze ⊖ ((var 0) ⊗ ze)) , ze )
      ∷ ( (mx (var 6) ze) , (var 6) )
      ∷ ( (lq (su (var 1)) ze) , ze )
      ∷ ( (lq ze (var 1)) , (su ze) )
      ∷ ( ((var 0) ⊗ (su ze)) , (var 0) )
      ∷ ( (gc (su ze) ze) , (su ze) )
      ∷ ( (gc ze (su ze)) , (su ze) )
      ∷ ( (gc (su (var 1)) ze) , (su (var 1)) )
      ∷ ( (gc ze (su (var 1))) , (su (var 1)) )
      ∷ ( (lq (su ze) (su (var 1))) , (su ze) )
      ∷ ( (mx (su (var 6)) (su ze)) , (su (var 6)) )
      ∷ []
