{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}

module Kernel.IntrinsicProductiveInstall where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Bool using (Bool ; false ; true ; true≢false)
open import Cubical.Data.List using ([] ; _∷_)

open import Kernel.RewriteCertificate using
  (Tm ; var ; zero ; suc ; add)
import Kernel.IntrinsicRewrite as IR
open import FiniteIndraWeave using
  (TotalView ; LocalAction ; reweave ; Tear ; tear)
open import ProductiveIndraNet
open import ProductiveTear using
  (EarliestTear ; now-tear ; PrefixAudit ; prefix-torn)

locus : Bool → IR.Locus
locus false = IR.root
locus true = IR.under-right var IR.root

oldTerm newTerm : Bool → Tm
oldTerm root = IR.plug (locus root) (suc var)
newTerm root = IR.plug (locus root) (add var (suc zero))

-- The finite local operation recognizes exactly the two rooted source terms
-- generated by the intrinsic installation. Other terms remain untouched.
installAction : LocalAction Bool Tm
installAction false term = term
installAction true (suc var) = add var (suc zero)
installAction true (add var (suc var)) = add var (add var (suc zero))
installAction true term = term

oldView : TotalView Bool Tm
oldView observer target = oldTerm target

installedView : TotalView Bool Tm
installedView = reweave installAction oldView

installed-root : (target : Bool)
  → installAction true (oldTerm target) ≡ newTerm target
installed-root false = refl
installed-root true = refl

-- Each changed jewel is the source index of the actual intrinsic rooted run;
-- the run itself is formed by the one shared Delta installation.
installedRun : (target : Bool) → IR.Run (newTerm target)
installedRun target =
  IR.view (IR.install IR.add-one-delta IR.add-one-tail) (locus target)

installedRun-result : (target : Bool)
  → IR.result (installedRun target) ≡ oldTerm target
installedRun-result false = refl
installedRun-result true = refl

oldNet : Net Bool Tm
Net.view oldNet = oldView
Net.next oldNet = oldNet

installedNet : Net Bool Tm
installedNet = propagate installAction oldNet

-- Installation changes every future finite observation to the same rooted
-- installed view; this is computation of the guarded propagation.
installed-three : observe 3 installedNet ≡
  installedView ∷ installedView ∷ installedView ∷ []
installed-three = refl

tag : Tm → Bool
tag (suc _) = true
tag _ = false

root-tear : Tear false installedView
root-tear = tear true false
  (λ same → true≢false (cong tag same))

-- The stream tears at its first observation. The witness compares the root
-- observer with the installed observer at the root target.
installed-earliest : EarliestTear false installedNet
  (false ∷ true ∷ []) (false ∷ true ∷ []) 3
installed-earliest = now-tear root-tear

installed-audit : PrefixAudit false installedNet
  (false ∷ true ∷ []) (false ∷ true ∷ []) 3
installed-audit = prefix-torn installed-earliest
