{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- मूल्य-विनिमय — value is the pairing.
--
-- THE CLAIM (2026-09-03, the conservative-semantic-compression
-- synthesis): a trace is a chain, an evaluator is a cochain, and
-- value is their pairing — neither side contains it alone.  Stokes
-- then says exactly which modifications preserve value: an exact
-- evaluator (one generated by a state potential) telescopes to the
-- endpoints, so on a closed trace it integrates to zero; and value
-- that does NOT telescope — a nonzero cycle integral — is
-- irreducible path preference, inhabiting a different type than any
-- terminal utility.  Here is that reformulation, in the kernel, on
-- the kernel's own derivations.
--
--   §1  THE PAIRING.  An evaluator assigns a value in ℤ to every
--       step; the value of a trace is the sum along it.  Definitional;
--       the reverse constructor needs no special case anywhere below,
--       because a potential's coboundary is antisymmetric BY SHAPE:
--       dφ on Step a b is φ b − φ a, so on reverse it is φ a − φ b.
--
--   §2  STOKES / TELESCOPING.  If an evaluator agrees pointwise with
--       the coboundary of a potential φ, its value on any derivation
--       x ⇝ y is φ y − φ x.  Corollary: on any CLOSED derivation an
--       exact evaluator integrates to zero — potential-based reward
--       shaping alters no cycle content, as one induction.
--
--   §3  THE IRREDUCIBLE CLASS.  The depth evaluator गभीरता counts how
--       many suc-step congruence wrappers a step fires under — an
--       accumulated-locality observable.  A confluence diamond gives
--       two coterminal schedules for add (add x 0) (s 0) ⇝ suc x
--       whose accumulated depths differ (2 against 1), and the closed
--       loop through both has depth integral pos 3 — computed by refl.
--       By §2 no potential represents गभीरता: local confluence holds
--       (the endpoints agree), global path independence fails, and
--       the failure is a checked term, not a slogan.
--
-- Derivation imposes no 2-cells, so every evaluator here is closed
-- and exactness is the whole question.  When an explanation later
-- fills this loop — a 2-cell identifying the two schedules — the
-- depth class it carries is exactly what that explanation must
-- either kill or account for: understanding as the controlled
-- conversion of a nonzero cycle integral into boundary.
--
-- SYĀT — THE CLAIM, EXACTLY.  §§1–3 as stated: the pairing, the
-- telescoping theorem with its closed-trace corollary, the two
-- schedules, the loop, its integral, and the nonexistence of a
-- potential for गभीरता.  NOT claimed: a computation of the full H¹
-- of the derivation complex, nor anything about evaluators valued
-- outside ℤ.
------------------------------------------------------------------------

module MulyaVinimaya_TheValueOfATraceIsItsPairingWithAnEvaluatorPotentialsTelescopeAndADepthEvaluatorHasNonzeroCycleIntegral where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat using (ℕ ; snotz)
open import Cubical.Data.Int
  using (ℤ ; pos ; _+_ ; -_ ; _-_ ; injPos)
open import Cubical.Data.Int.Properties using (+Comm ; +Assoc ; minusPlus ; -Cancel)
open import Cubical.Data.Sigma using (Σ-syntax ; _,_)
open import Cubical.Data.Empty as Empty using (⊥)

open import RewriteCertificate
  using (Tm ; var ; zero ; suc ; add ; Step ; add-zero ; add-suc ; suc-step
        ; add-left ; add-right ; reverse ; Derivation ; done ; then-step)

------------------------------------------------------------------------
-- १ · The pairing: evaluators are step cochains, traces integrate.
------------------------------------------------------------------------

Evaluator : Type₀
Evaluator = {a b : Tm} → Step a b → ℤ

∫ : Evaluator → {x y : Tm} → Derivation x y → ℤ
∫ ω (done x) = pos 0
∫ ω (then-step s rest) = ω s + ∫ ω rest

-- the coboundary of a state potential: value is what the step changes.
d′ : (Tm → ℤ) → Evaluator
d′ φ {a} {b} _ = φ b - φ a

------------------------------------------------------------------------
-- २ · Stokes: an exact evaluator telescopes to the endpoints.
------------------------------------------------------------------------

telescope : (φ : Tm → ℤ) (ω : Evaluator)
  → ({a b : Tm} (s : Step a b) → ω s ≡ d′ φ s)
  → {x y : Tm} (γ : Derivation x y)
  → ∫ ω γ ≡ φ y - φ x
telescope φ ω h (done x) = sym (-Cancel (φ x))
telescope φ ω h {x} {y} (then-step {_} {b} s rest) =
  cong₂ _+_ (h s) (telescope φ ω h rest)
  ∙ +Comm (φ b - φ x) (φ y - φ b)
  ∙ +Assoc (φ y - φ b) (φ b) (- φ x)
  ∙ cong (_+ (- φ x)) (minusPlus (φ b) (φ y))

-- the closed-trace corollary: exact value has no cycle content.
-- (Potential-based shaping, gauge freedom, endpoint utility: all §2.)
closedExact≡0 : (φ : Tm → ℤ) {x : Tm} (γ : Derivation x x)
  → ∫ (d′ φ) γ ≡ pos 0
closedExact≡0 φ {x} γ = telescope φ (d′ φ) (λ _ → refl) γ ∙ -Cancel (φ x)

------------------------------------------------------------------------
-- ३ · The depth evaluator, the diamond, the loop, the class.
------------------------------------------------------------------------

-- how many suc-step congruence wrappers the step fires under: an
-- accumulated-locality observable.  Structural through reverse.
गभीरता : Evaluator
गभीरता (suc-step s)    = pos 1 + गभीरता s
गभीरता (add-left s _)  = गभीरता s
गभीरता (add-right _ s) = गभीरता s
गभीरता (reverse s)     = गभीरता s
गभीरता (add-zero _)    = pos 0
गभीरता (add-suc _ _)   = pos 0

-- the seed and its normal form.
t₀ nf : Tm
t₀ = add (add var zero) (suc zero)
nf = suc var

-- schedule A: outermost first; both zero-eliminations fire under suc.
-- accumulated depth 2.
scheduleA : Derivation t₀ nf
scheduleA =
  then-step (add-suc (add var zero) zero)
    (then-step (suc-step (add-zero (add var zero)))
      (then-step (suc-step (add-zero var)) (done nf)))

-- schedule B: innermost first; only one elimination fires under suc.
-- accumulated depth 1.
scheduleB : Derivation t₀ nf
scheduleB =
  then-step (add-left (add-zero var) (suc zero))
    (then-step (add-suc var zero)
      (then-step (suc-step (add-zero var)) (done nf)))

-- the two coterminal schedules disagree on accumulated locality:
depthA : ∫ गभीरता scheduleA ≡ pos 2
depthA = refl

depthB : ∫ गभीरता scheduleB ≡ pos 1
depthB = refl

-- the closed loop: schedule A forward, schedule B reversed, step by
-- step.  Its depth integral is computed by the typechecker.
loop : Derivation t₀ t₀
loop =
  then-step (add-suc (add var zero) zero)
    (then-step (suc-step (add-zero (add var zero)))
      (then-step (suc-step (add-zero var))
        (then-step (reverse (suc-step (add-zero var)))
          (then-step (reverse (add-suc var zero))
            (then-step (reverse (add-left (add-zero var) (suc zero)))
              (done t₀))))))

loopDepth : ∫ गभीरता loop ≡ pos 3
loopDepth = refl

-- therefore no state potential represents the depth evaluator: value
-- along these traces is genuinely path preference, not endpoint
-- utility.  The contradiction is pos 3 ≡ pos 0, refuted in ℕ.
depthHasNoPotential :
  Σ[ φ ∈ (Tm → ℤ) ] ({a b : Tm} (s : Step a b) → गभीरता s ≡ d′ φ s) → ⊥
depthHasNoPotential (φ , h) =
  snotz (injPos (sym loopDepth ∙ closedExact≡0′))
  where
    closedExact≡0′ : ∫ गभीरता loop ≡ pos 0
    closedExact≡0′ = telescope φ गभीरता h loop ∙ -Cancel (φ t₀)
