{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- विवरण — the elucidation.
--
-- The atom is initial (AdiBija): every receiver is read by exactly one
-- fold.  This module USES that — it is the decomposer, not another
-- theorem about it.  Give it any object built on the atom (any
-- derivation) and it returns that object's COMPLETE reading across a
-- declared family of lenses, computed, with each component certified
-- to be THE unique reading its lens admits — nothing chosen, nothing
-- missed.
--
--   §1  THE DECOMPOSITION.  `Vivarana d` bundles, for one derivation d:
--       its length (steps taken), its depth integral (accumulated
--       locality, a ℤ evaluator's fold), and its meaning (the endpoint
--       equality it certifies, in every environment).  Three lenses,
--       one object, read at once.  Add a lens = add a field; the atom
--       does the reading.
--
--   §2  IT IS COMPLETE, NOT PARTIAL.  Each field is exhibited as a fold
--       of AdiBija, so by fold-unique it is the ONLY reading compatible
--       with that lens's step-actions.  `elucidation-is-canonical`
--       states this for the meaning lens: the decomposition's semantic
--       component equals the corpus's own derivation-sound, forced.
--       "Seeing all paths" is therefore exact: these ARE the readings.
--
--   §3  IT COMPUTES ON ARBITRARY OBJECTS.  Run on the kernel's two
--       coterminal histories — direct (2 steps) and detour (4 steps,
--       carrying a reverse) — the elucidator SEPARATES them where they
--       differ (length 2 vs 4) and IDENTIFIES them where they agree
--       (same endpoints), both by refl.  The compressor and the
--       distinguisher are one instrument seen from two lenses: meaning
--       compresses the pair to one, length keeps them two, and the
--       elucidation carries both facts without collapse.
--
-- SYĀT — THE CLAIM, EXACTLY.  The record, its three lenses as folds,
-- canonicity of the meaning component, and the computed profiles of the
-- two named objects.  NOT claimed: that three lenses exhaust every
-- possible reading — the family is open by construction (add a
-- receiver), and completeness is per-lens (each is unique), not a
-- claim that no further lens exists.
------------------------------------------------------------------------

module Vivarana_TheElucidatorDecomposesAnyObjectOnTheAtomIntoItsCompleteReadingAndEachComponentIsTheUniqueFold where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat using (ℕ ; zero ; suc ; znots ; injSuc ; isSetℕ)
open import Cubical.Data.Int using (ℤ ; pos)
open import Cubical.Relation.Nullary using (¬_)

open import RewriteCertificate
  using (Tm ; Derivation ; Env ; eval ; derivation-sound)
open import GenerativeKernel using (seed ; target₀ ; direct-history ; detour-history)
open import MulyaVinimaya_TheValueOfATraceIsItsPairingWithAnEvaluatorPotentialsTelescopeAndADepthEvaluatorHasNonzeroCycleIntegral
  using (गभीरता)
open import AdiBija_TheKernelIsInitialEveryReadingIsItsUniqueFoldSoAllPathsThroughASystemAreEnumeratedByOneRecursor
  using (fold ; fold-unique ; soundR ; lenF ; ∫F)

------------------------------------------------------------------------
-- १ · The decomposition of one object, across the lens family.
------------------------------------------------------------------------

record Vivarana {a b : Tm} (d : Derivation a b) : Type where
  field
    steps   : ℕ                        -- the length lens
    charge  : ℤ                        -- the depth-integral lens
    meaning : (ρ : Env) → eval a ρ ≡ eval b ρ   -- the semantic lens

open Vivarana

-- THE ELUCIDATOR.  One object in, its full reading out — each field a
-- fold of the atom, so the whole record is generated by the recursor,
-- not assembled by hand.
elucidate : {a b : Tm} (d : Derivation a b) → Vivarana d
steps   (elucidate d) = lenF d
charge  (elucidate d) = ∫F गभीरता d
meaning (elucidate d) = fold soundR d

------------------------------------------------------------------------
-- २ · The reading is canonical: the semantic component is forced to be
--     the corpus's own soundness, by initiality.
------------------------------------------------------------------------

elucidation-is-canonical : {a b : Tm} (d : Derivation a b)
  → meaning (elucidate d) ≡ derivation-sound d
elucidation-is-canonical d =
  sym (fold-unique soundR derivation-sound refl (λ s e → refl) d)

------------------------------------------------------------------------
-- ३ · It computes on arbitrary objects: two coterminal histories,
--     decomposed, separated where they differ and identified where
--     they agree — every entry by refl.
------------------------------------------------------------------------

directProfile : steps (elucidate direct-history) ≡ suc (suc zero)
directProfile = refl

detourProfile : steps (elucidate detour-history) ≡ suc (suc (suc (suc zero)))
detourProfile = refl

-- the length lens keeps them apart…
lengths-differ : ¬ (steps (elucidate direct-history)
                  ≡ steps (elucidate detour-history))
lengths-differ p = znots (injSuc (injSuc p))

-- …while the meaning lens reads both as the same endpoint equality:
-- the two decompositions agree exactly on their semantic component,
-- because meaning lands in a set and the endpoints coincide.
meanings-agree : (ρ : Env)
  → meaning (elucidate direct-history) ρ ≡ meaning (elucidate detour-history) ρ
meanings-agree ρ = isSetℕ _ _ _ _
