{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- ‡µ‡‡Ø‡Ø-‡‡‡ ‚î the round trip is pure cost and trivial meaning.
--
-- The entrypoint note VYAYA_SESA (repo root) argues that complexity is
-- the failure of cost to be a localizing invariant: the groupoid
-- completion L : Derivation ‚í image(ua) sends meaning (eval) down
-- cleanly but cannot carry cost (Laghava).  This module makes the
-- EXACTNESS CRUX of that sequence a checked term, on the kernel's own
-- derivations.
--
-- The kernel of L is generated by the ROUND TRIPS d ‚äï revD d ‚î the
-- loops L collapses to the identity.  The claim of the sequence is that
-- on this kernel, MEANING VANISHES while COST DOES NOT.  Both halves,
-- proved:
--
--   ¬ß1  COST ON THE ROUND TRIP IS 2¬len d ‚î it grows with d, without
--       bound as d grows.  (len-++ then len-revD.)
--   ¬ß2  MEANING ON THE ROUND TRIP IS THE TRIVIAL PATH ‚î for every œ,
--       derivation-sound (d ‚äï revD d) œ ‚â° refl, because it is a loop
--       and meaning lands in a set.
--   ¬ß3  THEREFORE revD IS A DAGGER, NOT AN INVERSE: whenever len d > 0,
--       d ‚äï revD d ‚â done.  Reversal flips direction; it does not
--       cancel.  This is the exact crack ‚î a group inverse would give
--       length 0, and cost forbids it (Laghava, one category down).
--
-- Read as the localization sequence: the round-trip family lands in
-- ker L (meaning trivial, ¬ß2, so L collapses it), yet carries unbounded
-- cost (¬ß1).  A single invariant that is constant where another is
-- unbounded cannot factor through the first: COST DOES NOT DESCEND
-- ALONG L.  That is "cost is the non-localizing residual" as a term,
-- and ¬ß3 names why the completion must add exactly what cost cannot
-- survive.
--
------------------------------------------------------------------------

module VyayaSesa_TheRoundTripIsPureCostAndTrivialMeaningSoCostIsSupportedOnTheKernelOfTheGroupoidCompletion where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat using (‚Ñï ; zero ; suc ; _+_ ; isSet‚Ñï ; snotz)
open import Cubical.Data.Empty as Empty using (‚ä•)

open import RewriteCertificate
  using (Tm ; Derivation ; done ; Env ; eval ; derivation-sound)
open import EveryDerivationIsInvertible using (len ; _++_ ; revD ; len-++ ; len-revD)
open import GenerativeKernel using (direct-history)

------------------------------------------------------------------------
-- ‡ß ¬ Cost on the round trip is 2¬len d.
------------------------------------------------------------------------

roundTripCost : {a b : Tm} (d : Derivation a b)
  ‚Üí len (d ++ revD d) ‚â° len d + len d
roundTripCost d = len-++ d (revD d) ‚àô cong (len d +_) (len-revD d)

------------------------------------------------------------------------
-- ‡® ¬ Meaning on the round trip is the trivial path.
--     A round trip is a loop a ‚ a; its meaning is a path
--     eval a œ ‚â° eval a œ, and ‚ï is a set, so it is refl.
------------------------------------------------------------------------

roundTripMeaningTrivial : {a b : Tm} (d : Derivation a b) (œÅ : Env)
  ‚Üí derivation-sound (d ++ revD d) œÅ ‚â° refl
roundTripMeaningTrivial {a} d œÅ =
  isSet‚Ñï (eval a œÅ) (eval a œÅ) (derivation-sound (d ++ revD d) œÅ) refl

------------------------------------------------------------------------
-- ‡© ¬ revD is a dagger, not an inverse: a nonempty round trip is not
--     the identity derivation.  A group inverse would force length 0.
------------------------------------------------------------------------

daggerNotInverse : {a b : Tm} (d : Derivation a b)
  ‚Üí (len d + len d ‚â° zero ‚Üí ‚ä•)      -- d is nonempty (its doubled cost is not 0)
  ‚Üí (d ++ revD d ‚â° done a ‚Üí ‚ä•)
daggerNotInverse d nz eq =
  nz (sym (roundTripCost d) ‚àô cong len eq)
  -- len done a = zero definitionally; cong len eq : len (d ++ revD d) ‚â° len (done a) = 0

------------------------------------------------------------------------
-- The concrete witness on the kernel's own object: direct-history has
-- len 2, so its round trip has cost 4, trivial meaning, and is not the
-- identity ‚î one point of ker L that L collapses yet cost separates.
------------------------------------------------------------------------

witnessCost : len (direct-history ++ revD direct-history) ‚â° 4
witnessCost = roundTripCost direct-history

witnessMeaningTrivial : (œÅ : Env)
  ‚Üí derivation-sound (direct-history ++ revD direct-history) œÅ ‚â° refl
witnessMeaningTrivial = roundTripMeaningTrivial direct-history

witnessNotIdentity : (direct-history ++ revD direct-history ‚â° done _) ‚Üí ‚ä•
witnessNotIdentity = daggerNotInverse direct-history (Œª p ‚Üí snotz p)
