{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- व्यय-शेष — the round trip is pure cost and trivial meaning.
--
-- The entrypoint note VYAYA_SESA (repo root) argues that complexity is
-- the failure of cost to be a localizing invariant: the groupoid
-- completion L : Derivation → image(ua) sends meaning (eval) down
-- cleanly but cannot carry cost (Laghava).  This module makes the
-- EXACTNESS CRUX of that sequence a checked term, on the kernel's own
-- derivations.
--
-- The kernel of L is generated by the ROUND TRIPS d ⊕ revD d — the
-- loops L collapses to the identity.  The claim of the sequence is that
-- on this kernel, MEANING VANISHES while COST DOES NOT.  Both halves,
-- proved:
--
--   §1  COST ON THE ROUND TRIP IS 2·len d — it grows with d, without
--       bound as d grows.  (len-++ then len-revD.)
--   §2  MEANING ON THE ROUND TRIP IS THE TRIVIAL PATH — for every ρ,
--       derivation-sound (d ⊕ revD d) ρ ≡ refl, because it is a loop
--       and meaning lands in a set.
--   §3  THEREFORE revD IS A DAGGER, NOT AN INVERSE: whenever len d > 0,
--       d ⊕ revD d ≢ done.  Reversal flips direction; it does not
--       cancel.  This is the exact crack — a group inverse would give
--       length 0, and cost forbids it (Laghava, one category down).
--
-- Read as the localization sequence: the round-trip family lands in
-- ker L (meaning trivial, §2, so L collapses it), yet carries unbounded
-- cost (§1).  A single invariant that is constant where another is
-- unbounded cannot factor through the first: COST DOES NOT DESCEND
-- ALONG L.  That is "cost is the non-localizing residual" as a term,
-- and §3 names why the completion must add exactly what cost cannot
-- survive.
--
------------------------------------------------------------------------

module VyayaSesa_TheRoundTripIsPureCostAndTrivialMeaningSoCostIsSupportedOnTheKernelOfTheGroupoidCompletion where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat using (ℕ ; zero ; suc ; _+_ ; isSetℕ ; snotz)
open import Cubical.Data.Empty as Empty using (⊥)

open import RewriteCertificate
  using (Tm ; Derivation ; done ; Env ; eval ; derivation-sound)
open import EveryDerivationIsInvertible using (len ; _++_ ; revD ; len-++ ; len-revD)
open import GenerativeKernel using (direct-history)

------------------------------------------------------------------------
-- १ · Cost on the round trip is 2·len d.
------------------------------------------------------------------------

roundTripCost : {a b : Tm} (d : Derivation a b)
  → len (d ++ revD d) ≡ len d + len d
roundTripCost d = len-++ d (revD d) ∙ cong (len d +_) (len-revD d)

------------------------------------------------------------------------
-- २ · Meaning on the round trip is the trivial path.
--     A round trip is a loop a ⇝ a; its meaning is a path
--     eval a ρ ≡ eval a ρ, and ℕ is a set, so it is refl.
------------------------------------------------------------------------

roundTripMeaningTrivial : {a b : Tm} (d : Derivation a b) (ρ : Env)
  → derivation-sound (d ++ revD d) ρ ≡ refl
roundTripMeaningTrivial {a} d ρ =
  isSetℕ (eval a ρ) (eval a ρ) (derivation-sound (d ++ revD d) ρ) refl

------------------------------------------------------------------------
-- ३ · revD is a dagger, not an inverse: a nonempty round trip is not
--     the identity derivation.  A group inverse would force length 0.
------------------------------------------------------------------------

daggerNotInverse : {a b : Tm} (d : Derivation a b)
  → (len d + len d ≡ zero → ⊥)      -- d is nonempty (its doubled cost is not 0)
  → (d ++ revD d ≡ done a → ⊥)
daggerNotInverse d nz eq =
  nz (sym (roundTripCost d) ∙ cong len eq)
  -- len done a = zero definitionally; cong len eq : len (d ++ revD d) ≡ len (done a) = 0

------------------------------------------------------------------------
-- The concrete witness on the kernel's own object: direct-history has
-- len 2, so its round trip has cost 4, trivial meaning, and is not the
-- identity — one point of ker L that L collapses yet cost separates.
------------------------------------------------------------------------

witnessCost : len (direct-history ++ revD direct-history) ≡ 4
witnessCost = roundTripCost direct-history

witnessMeaningTrivial : (ρ : Env)
  → derivation-sound (direct-history ++ revD direct-history) ρ ≡ refl
witnessMeaningTrivial = roundTripMeaningTrivial direct-history

witnessNotIdentity : (direct-history ++ revD direct-history ≡ done _) → ⊥
witnessNotIdentity = daggerNotInverse direct-history (λ p → snotz p)
