{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- CorpusNames — the finite enumeration of declaration Names, and NOTHING
-- ELSE.  ZERO SEMANTIC SIGNIFICANCE: not a hierarchy, graph, taxonomy,
-- or root set; names survive only as provenance/navigation handles.
--
-- The list is EVERY public top-level declaration of EVERY `--safe`
-- module in the corpus — i.e. all of it except the must_fail lane, which
-- carries no `--safe` pragma (a vicious circle a --safe module cannot
-- contain) and is therefore excluded mechanically, not by taste.
--
-- It is machine-generated by `./generate-corpus-index` into
-- `CorpusGeneratedIndex.agda`, which imports each module (so `quote`
-- has the names in scope) and lists them.  Reflection cannot enumerate
-- the global environment, so this bootstrap is unavoidable; it is
-- deliberately quarantined here, and no semantic construction depends on
-- file/module/import organisation.  Regenerate after adding modules:
--
--     ./generate-corpus-index
------------------------------------------------------------------------

module CorpusNames where

open import CorpusGeneratedIndex using (corpusNames) public
