{-# OPTIONS --cubical --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- CakravalaWitness — EMITTED BY THE REACTOR, CHECKED BY THE KERNEL.
--
-- Generated by `runghc -imachine machine/NalandaEmit.hs 61`.
-- Do not hand-edit; regenerate.  The point of the file is that the
-- reactor's answer is a checked term and not a number to be trusted.
--
-- BHĀSKARA II, Bījagaṇita (1150), the cakravāla, on
--
--     x² − 61 y² = 1
--
-- reached in 15 turns of the wheel from the seed
-- (⌊√61⌋, 1, ⌊√61⌋² − 61).  Each turn's m is
-- the one Bhāskara's choice rule selects — among the m with k | (a + bm),
-- the one minimising |m² − D| — and that congruence is solved by
-- ĀRYABHAṬA's kuṭṭaka (Āryabhaṭīya, Gaṇitapāda 32–33, 499).
--
-- STATED OVER ℕ, SUBTRACTION-FREE, and that is forced rather than
-- stylistic.  Cubical's ℤ multiplication is unary — `pos (suc n) · m =
-- m + pos n · m` — so a `refl` on nine-digit ℤ literals asks for ~10¹⁸
-- unfoldings and never returns.  Cubical's ℕ is `Agda.Builtin.Nat`, whose
-- `_+_` and `_·_` are GMP-backed, so the same statement over ℕ is instant.
-- Clearing the subtraction is exactly what `BhavanaSemiring.agda` does for
-- bhāvanā, for the same reason.
--
-- THE TRACE BELOW IS THE GENERATOR'S WORD, NOT THE KERNEL'S.  It is here
-- so the derivation is inspectable; only the theorems are checked.
--
--   turn 0   7                   1                   k = -12
--   turn 1   8                   1                   k = 3
--   turn 2   39                  5                   k = -4
--   turn 3   164                 21                  k = -5
--   turn 4   453                 58                  k = 5
--   turn 5   1523                195                 k = 4
--   turn 6   5639                722                 k = -3
--   turn 7   29718               3805                k = -1
--   turn 8   440131              56353               k = 12
--   turn 9   469849              60158               k = -3
--   turn 10  2319527             296985              k = 4
--   turn 11  9747957             1248098             k = 5
--   turn 12  26924344            3447309             k = -5
--   turn 13  90520989            11590025            k = -4
--   turn 14  335159612           42912791            k = 3
--   turn 15  1766319049          226153980           k = 1
------------------------------------------------------------------------

module CakravalaWitness where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat using (ℕ ; _+_ ; _·_)
open import Cubical.Data.Sigma using (_×_ ; _,_)
open import BhavanaSemiring using (cx ; cy ; bhavanaℕ)
open import CakravalaNat using (ca ; cb ; cakravalaℕ)

D : ℕ
D = 61

------------------------------------------------------------------------
-- EVERY TURN OF THE WHEEL, CERTIFIED BY THE GENERAL THEOREM.
--
-- Each line below instantiates `CakravalaNat.cakravalaℕ` — proved for ALL
-- naturals as a commutative-semiring identity — at that turn's own
-- (a, b, m).  Note what this is NOT: it is not `refl`.  A `refl` per turn
-- would show only that this generator's arithmetic agrees with the
-- kernel's, and would not tie the run to Brahmagupta's law at all.  These
-- are the law firing, once per turn.
--
-- The m on each line is the one BHĀSKARA'S CHOICE RULE selects: among the
-- m with k | (a + bm), the one minimising |m² − D|.  The congruence is
-- solved by ĀRYABHAṬA's kuṭṭaka (Āryabhaṭīya, Gaṇitapāda 32–33, 499).
------------------------------------------------------------------------

-- turn 0:  a = 7,  b = 1,  m = 5
turn0 : ca D 7 1 5 · ca D 7 1 5
     + (D · (7 · 7) + D · (1 · 1 · (5 · 5)))
     ≡ 7 · 7 · (5 · 5)
     + (D · D · (1 · 1) + D · (cb 7 1 5 · cb 7 1 5))
turn0 = cakravalaℕ D 7 1 5

-- turn 1:  a = 8,  b = 1,  m = 7
turn1 : ca D 8 1 7 · ca D 8 1 7
     + (D · (8 · 8) + D · (1 · 1 · (7 · 7)))
     ≡ 8 · 8 · (7 · 7)
     + (D · D · (1 · 1) + D · (cb 8 1 7 · cb 8 1 7))
turn1 = cakravalaℕ D 8 1 7

-- turn 2:  a = 39,  b = 5,  m = 9
turn2 : ca D 39 5 9 · ca D 39 5 9
     + (D · (39 · 39) + D · (5 · 5 · (9 · 9)))
     ≡ 39 · 39 · (9 · 9)
     + (D · D · (5 · 5) + D · (cb 39 5 9 · cb 39 5 9))
turn2 = cakravalaℕ D 39 5 9

-- turn 3:  a = 164,  b = 21,  m = 6
turn3 : ca D 164 21 6 · ca D 164 21 6
     + (D · (164 · 164) + D · (21 · 21 · (6 · 6)))
     ≡ 164 · 164 · (6 · 6)
     + (D · D · (21 · 21) + D · (cb 164 21 6 · cb 164 21 6))
turn3 = cakravalaℕ D 164 21 6

-- turn 4:  a = 453,  b = 58,  m = 9
turn4 : ca D 453 58 9 · ca D 453 58 9
     + (D · (453 · 453) + D · (58 · 58 · (9 · 9)))
     ≡ 453 · 453 · (9 · 9)
     + (D · D · (58 · 58) + D · (cb 453 58 9 · cb 453 58 9))
turn4 = cakravalaℕ D 453 58 9

-- turn 5:  a = 1523,  b = 195,  m = 7
turn5 : ca D 1523 195 7 · ca D 1523 195 7
     + (D · (1523 · 1523) + D · (195 · 195 · (7 · 7)))
     ≡ 1523 · 1523 · (7 · 7)
     + (D · D · (195 · 195) + D · (cb 1523 195 7 · cb 1523 195 7))
turn5 = cakravalaℕ D 1523 195 7

-- turn 6:  a = 5639,  b = 722,  m = 8
turn6 : ca D 5639 722 8 · ca D 5639 722 8
     + (D · (5639 · 5639) + D · (722 · 722 · (8 · 8)))
     ≡ 5639 · 5639 · (8 · 8)
     + (D · D · (722 · 722) + D · (cb 5639 722 8 · cb 5639 722 8))
turn6 = cakravalaℕ D 5639 722 8

-- turn 7:  a = 29718,  b = 3805,  m = 7
turn7 : ca D 29718 3805 7 · ca D 29718 3805 7
     + (D · (29718 · 29718) + D · (3805 · 3805 · (7 · 7)))
     ≡ 29718 · 29718 · (7 · 7)
     + (D · D · (3805 · 3805) + D · (cb 29718 3805 7 · cb 29718 3805 7))
turn7 = cakravalaℕ D 29718 3805 7

-- turn 8:  a = 440131,  b = 56353,  m = 5
turn8 : ca D 440131 56353 5 · ca D 440131 56353 5
     + (D · (440131 · 440131) + D · (56353 · 56353 · (5 · 5)))
     ≡ 440131 · 440131 · (5 · 5)
     + (D · D · (56353 · 56353) + D · (cb 440131 56353 5 · cb 440131 56353 5))
turn8 = cakravalaℕ D 440131 56353 5

-- turn 9:  a = 469849,  b = 60158,  m = 7
turn9 : ca D 469849 60158 7 · ca D 469849 60158 7
     + (D · (469849 · 469849) + D · (60158 · 60158 · (7 · 7)))
     ≡ 469849 · 469849 · (7 · 7)
     + (D · D · (60158 · 60158) + D · (cb 469849 60158 7 · cb 469849 60158 7))
turn9 = cakravalaℕ D 469849 60158 7

-- turn 10:  a = 2319527,  b = 296985,  m = 9
turn10 : ca D 2319527 296985 9 · ca D 2319527 296985 9
     + (D · (2319527 · 2319527) + D · (296985 · 296985 · (9 · 9)))
     ≡ 2319527 · 2319527 · (9 · 9)
     + (D · D · (296985 · 296985) + D · (cb 2319527 296985 9 · cb 2319527 296985 9))
turn10 = cakravalaℕ D 2319527 296985 9

-- turn 11:  a = 9747957,  b = 1248098,  m = 6
turn11 : ca D 9747957 1248098 6 · ca D 9747957 1248098 6
     + (D · (9747957 · 9747957) + D · (1248098 · 1248098 · (6 · 6)))
     ≡ 9747957 · 9747957 · (6 · 6)
     + (D · D · (1248098 · 1248098) + D · (cb 9747957 1248098 6 · cb 9747957 1248098 6))
turn11 = cakravalaℕ D 9747957 1248098 6

-- turn 12:  a = 26924344,  b = 3447309,  m = 9
turn12 : ca D 26924344 3447309 9 · ca D 26924344 3447309 9
     + (D · (26924344 · 26924344) + D · (3447309 · 3447309 · (9 · 9)))
     ≡ 26924344 · 26924344 · (9 · 9)
     + (D · D · (3447309 · 3447309) + D · (cb 26924344 3447309 9 · cb 26924344 3447309 9))
turn12 = cakravalaℕ D 26924344 3447309 9

-- turn 13:  a = 90520989,  b = 11590025,  m = 7
turn13 : ca D 90520989 11590025 7 · ca D 90520989 11590025 7
     + (D · (90520989 · 90520989) + D · (11590025 · 11590025 · (7 · 7)))
     ≡ 90520989 · 90520989 · (7 · 7)
     + (D · D · (11590025 · 11590025) + D · (cb 90520989 11590025 7 · cb 90520989 11590025 7))
turn13 = cakravalaℕ D 90520989 11590025 7

-- turn 14:  a = 335159612,  b = 42912791,  m = 8
turn14 : ca D 335159612 42912791 8 · ca D 335159612 42912791 8
     + (D · (335159612 · 335159612) + D · (42912791 · 42912791 · (8 · 8)))
     ≡ 335159612 · 335159612 · (8 · 8)
     + (D · D · (42912791 · 42912791) + D · (cb 335159612 42912791 8 · cb 335159612 42912791 8))
turn14 = cakravalaℕ D 335159612 42912791 8

------------------------------------------------------------------------
-- THE BOOKKEEPING: the three divisions came out exact.
--
-- The identity above is the step's CONTENT; these are the step's
-- ACCOUNTS.  Bhāskara's choice rule earns its keep exactly here — it
-- picks the one m for which all three of these divisions are exact, and
-- `CakravalaDescent.oneCongruenceCoprime` proves that asking for the
-- middle one alone suffices, given the pulverizer's coefficients.
--
-- Two of the three are subtraction-free as they stand: a·m + D·b and
-- a + b·m are sums of naturals.  Only m² − D can go negative, and
-- |m² − D| = |k|·|k'| holds either way, so each line below is emitted in
-- whichever orientation is true at that turn.  The SIGNS of k and k' are
-- not recovered here — they are in the trace comments above, and they are
-- the generator's word, not the kernel's.
------------------------------------------------------------------------

-- turn 0 bookkeeping:  |k| = 12,  a' = 8,  b' = 1,  |k'| = 3
divA0 : 7 · 5 + D · 1 ≡ 12 · 8
divA0 = refl
divB0 : 7 + 1 · 5 ≡ 12 · 1
divB0 = refl
divK0 : 5 · 5 + 12 · 3 ≡ D
divK0 = refl

-- turn 1 bookkeeping:  |k| = 3,  a' = 39,  b' = 5,  |k'| = 4
divA1 : 8 · 7 + D · 1 ≡ 3 · 39
divA1 = refl
divB1 : 8 + 1 · 7 ≡ 3 · 5
divB1 = refl
divK1 : 7 · 7 + 3 · 4 ≡ D
divK1 = refl

-- turn 2 bookkeeping:  |k| = 4,  a' = 164,  b' = 21,  |k'| = 5
divA2 : 39 · 9 + D · 5 ≡ 4 · 164
divA2 = refl
divB2 : 39 + 5 · 9 ≡ 4 · 21
divB2 = refl
divK2 : 9 · 9 ≡ D + 4 · 5
divK2 = refl

-- turn 3 bookkeeping:  |k| = 5,  a' = 453,  b' = 58,  |k'| = 5
divA3 : 164 · 6 + D · 21 ≡ 5 · 453
divA3 = refl
divB3 : 164 + 21 · 6 ≡ 5 · 58
divB3 = refl
divK3 : 6 · 6 + 5 · 5 ≡ D
divK3 = refl

-- turn 4 bookkeeping:  |k| = 5,  a' = 1523,  b' = 195,  |k'| = 4
divA4 : 453 · 9 + D · 58 ≡ 5 · 1523
divA4 = refl
divB4 : 453 + 58 · 9 ≡ 5 · 195
divB4 = refl
divK4 : 9 · 9 ≡ D + 5 · 4
divK4 = refl

-- turn 5 bookkeeping:  |k| = 4,  a' = 5639,  b' = 722,  |k'| = 3
divA5 : 1523 · 7 + D · 195 ≡ 4 · 5639
divA5 = refl
divB5 : 1523 + 195 · 7 ≡ 4 · 722
divB5 = refl
divK5 : 7 · 7 + 4 · 3 ≡ D
divK5 = refl

-- turn 6 bookkeeping:  |k| = 3,  a' = 29718,  b' = 3805,  |k'| = 1
divA6 : 5639 · 8 + D · 722 ≡ 3 · 29718
divA6 = refl
divB6 : 5639 + 722 · 8 ≡ 3 · 3805
divB6 = refl
divK6 : 8 · 8 ≡ D + 3 · 1
divK6 = refl

-- turn 7 bookkeeping:  |k| = 1,  a' = 440131,  b' = 56353,  |k'| = 12
divA7 : 29718 · 7 + D · 3805 ≡ 1 · 440131
divA7 = refl
divB7 : 29718 + 3805 · 7 ≡ 1 · 56353
divB7 = refl
divK7 : 7 · 7 + 1 · 12 ≡ D
divK7 = refl

-- turn 8 bookkeeping:  |k| = 12,  a' = 469849,  b' = 60158,  |k'| = 3
divA8 : 440131 · 5 + D · 56353 ≡ 12 · 469849
divA8 = refl
divB8 : 440131 + 56353 · 5 ≡ 12 · 60158
divB8 = refl
divK8 : 5 · 5 + 12 · 3 ≡ D
divK8 = refl

-- turn 9 bookkeeping:  |k| = 3,  a' = 2319527,  b' = 296985,  |k'| = 4
divA9 : 469849 · 7 + D · 60158 ≡ 3 · 2319527
divA9 = refl
divB9 : 469849 + 60158 · 7 ≡ 3 · 296985
divB9 = refl
divK9 : 7 · 7 + 3 · 4 ≡ D
divK9 = refl

-- turn 10 bookkeeping:  |k| = 4,  a' = 9747957,  b' = 1248098,  |k'| = 5
divA10 : 2319527 · 9 + D · 296985 ≡ 4 · 9747957
divA10 = refl
divB10 : 2319527 + 296985 · 9 ≡ 4 · 1248098
divB10 = refl
divK10 : 9 · 9 ≡ D + 4 · 5
divK10 = refl

-- turn 11 bookkeeping:  |k| = 5,  a' = 26924344,  b' = 3447309,  |k'| = 5
divA11 : 9747957 · 6 + D · 1248098 ≡ 5 · 26924344
divA11 = refl
divB11 : 9747957 + 1248098 · 6 ≡ 5 · 3447309
divB11 = refl
divK11 : 6 · 6 + 5 · 5 ≡ D
divK11 = refl

-- turn 12 bookkeeping:  |k| = 5,  a' = 90520989,  b' = 11590025,  |k'| = 4
divA12 : 26924344 · 9 + D · 3447309 ≡ 5 · 90520989
divA12 = refl
divB12 : 26924344 + 3447309 · 9 ≡ 5 · 11590025
divB12 = refl
divK12 : 9 · 9 ≡ D + 5 · 4
divK12 = refl

-- turn 13 bookkeeping:  |k| = 4,  a' = 335159612,  b' = 42912791,  |k'| = 3
divA13 : 90520989 · 7 + D · 11590025 ≡ 4 · 335159612
divA13 = refl
divB13 : 90520989 + 11590025 · 7 ≡ 4 · 42912791
divB13 = refl
divK13 : 7 · 7 + 4 · 3 ≡ D
divK13 = refl

-- turn 14 bookkeeping:  |k| = 3,  a' = 1766319049,  b' = 226153980,  |k'| = 1
divA14 : 335159612 · 8 + D · 42912791 ≡ 3 · 1766319049
divA14 = refl
divB14 : 335159612 + 42912791 · 8 ≡ 3 · 226153980
divB14 = refl
divK14 : 8 · 8 ≡ D + 3 · 1
divK14 = refl


------------------------------------------------------------------------
-- THE FUNDAMENTAL SOLUTION.  `refl`: the kernel recomputes both sides.
------------------------------------------------------------------------

a b : ℕ
a = 1766319049
b = 226153980

fundamental : a · a ≡ D · (b · b) + 1
fundamental = refl

------------------------------------------------------------------------
-- BHĀVANĀ (Brahmagupta, Brāhmasphuṭasiddhānta 18, 628) GENERATES ONWARD.
--
-- The next solution is not searched for.  It is Brahmagupta's composition
-- of the solution with itself — tulya-bhāvanā — and `cx`/`cy` below are
-- his own two coordinates, taken from `BhavanaSemiring` rather than
-- rewritten here.
------------------------------------------------------------------------

a² b² : ℕ
a² = 6239765965720528801
b² = 798920165762330040

-- the composite really is Brahmagupta's composite, not a number this
-- generator chose: cx and cy at (a, b, a, b) evaluate to it
compositeIsBhavana : (cx D a b a b ≡ a²) × (cy a b a b ≡ b²)
compositeIsBhavana = refl , refl

-- and it solves the same equation
composed : a² · a² ≡ D · (b² · b²) + 1
composed = refl

------------------------------------------------------------------------
-- THE GENERAL THEOREM, FIRED AT THESE NUMBERS.
--
-- `bhavanaℕ` is proved in `BhavanaSemiring.agda` for ALL naturals, as a
-- commutative-semiring identity.  Instantiating it here is what makes the
-- two `refl`s above an instance of Brahmagupta's law rather than an
-- arithmetic coincidence that happens to hold at one pair of numbers.
------------------------------------------------------------------------

law : cx D a b a b · cx D a b a b
        + (D · (a · a · (b · b)) + D · (a · a · (b · b)))
    ≡ a · a · (a · a)
        + (D · D · (b · b · (b · b))
           + D · (cy a b a b · cy a b a b))
law = bhavanaℕ D a b a b
