{-# OPTIONS --cubical --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- CakravalaWitness — EMITTED BY THE REACTOR, CHECKED BY THE KERNEL.
--
-- Generated by `runghc -imachine machine/NalandaEmit.hs 61`.
-- Do not hand-edit; regenerate.  The point of the file is that the
-- reactor's answer is a checked term and not a number to be trusted.
--
-- BHĀSKARA II, Bījagaṇita (1150), the cakravāla, on
--
--     x² − 61 y² = 1
--
-- reached in 15 turns of the wheel from the seed
-- (⌊√61⌋, 1, ⌊√61⌋² − 61).  Each turn's m is
-- the one Bhāskara's choice rule selects — among the m with k | (a + bm),
-- the one minimising |m² − D| — and that congruence is solved by
-- ĀRYABHAṬA's kuṭṭaka (Āryabhaṭīya, Gaṇitapāda 32–33, 499).
--
-- STATED OVER ℕ, SUBTRACTION-FREE, and that is forced rather than
-- stylistic.  Cubical's ℤ multiplication is unary — `pos (suc n) · m =
-- m + pos n · m` — so a `refl` on nine-digit ℤ literals asks for ~10¹⁸
-- unfoldings and never returns.  Cubical's ℕ is `Agda.Builtin.Nat`, whose
-- `_+_` and `_·_` are GMP-backed, so the same statement over ℕ is instant.
-- Clearing the subtraction is exactly what `BhavanaSemiring.agda` does for
-- bhāvanā, for the same reason.
--
-- THE TRACE BELOW IS THE GENERATOR'S WORD, NOT THE KERNEL'S.  It is here
-- so the derivation is inspectable; only the theorems are checked.
--
--   turn 0   7                   1                   k = -12
--   turn 1   8                   1                   k = 3
--   turn 2   39                  5                   k = -4
--   turn 3   164                 21                  k = -5
--   turn 4   453                 58                  k = 5
--   turn 5   1523                195                 k = 4
--   turn 6   5639                722                 k = -3
--   turn 7   29718               3805                k = -1
--   turn 8   440131              56353               k = 12
--   turn 9   469849              60158               k = -3
--   turn 10  2319527             296985              k = 4
--   turn 11  9747957             1248098             k = 5
--   turn 12  26924344            3447309             k = -5
--   turn 13  90520989            11590025            k = -4
--   turn 14  335159612           42912791            k = 3
--   turn 15  1766319049          226153980           k = 1
------------------------------------------------------------------------

module CakravalaWitness where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat using (ℕ ; _+_ ; _·_)
open import Cubical.Data.Sigma using (_×_ ; _,_)
open import BhavanaSemiring using (cx ; cy ; bhavanaℕ)

D : ℕ
D = 61

------------------------------------------------------------------------
-- THE FUNDAMENTAL SOLUTION.  `refl`: the kernel recomputes both sides.
------------------------------------------------------------------------

a b : ℕ
a = 1766319049
b = 226153980

fundamental : a · a ≡ D · (b · b) + 1
fundamental = refl

------------------------------------------------------------------------
-- BHĀVANĀ (Brahmagupta, Brāhmasphuṭasiddhānta 18, 628) GENERATES ONWARD.
--
-- The next solution is not searched for.  It is Brahmagupta's composition
-- of the solution with itself — tulya-bhāvanā — and `cx`/`cy` below are
-- his own two coordinates, taken from `BhavanaSemiring` rather than
-- rewritten here.
------------------------------------------------------------------------

a² b² : ℕ
a² = 6239765965720528801
b² = 798920165762330040

-- the composite really is Brahmagupta's composite, not a number this
-- generator chose: cx and cy at (a, b, a, b) evaluate to it
compositeIsBhavana : (cx D a b a b ≡ a²) × (cy a b a b ≡ b²)
compositeIsBhavana = refl , refl

-- and it solves the same equation
composed : a² · a² ≡ D · (b² · b²) + 1
composed = refl

------------------------------------------------------------------------
-- THE GENERAL THEOREM, FIRED AT THESE NUMBERS.
--
-- `bhavanaℕ` is proved in `BhavanaSemiring.agda` for ALL naturals, as a
-- commutative-semiring identity.  Instantiating it here is what makes the
-- two `refl`s above an instance of Brahmagupta's law rather than an
-- arithmetic coincidence that happens to hold at one pair of numbers.
------------------------------------------------------------------------

law : cx D a b a b · cx D a b a b
        + (D · (a · a · (b · b)) + D · (a · a · (b · b)))
    ≡ a · a · (a · a)
        + (D · D · (b · b · (b · b))
           + D · (cy a b a b · cy a b a b))
law = bhavanaℕ D a b a b
