{-# OPTIONS --cubical --safe --guardedness #-}
-- GENERATED by machine/Marga_TheRouterTransportsATheoremAlongLandedEdges.hs.
-- Do not edit by hand; regenerate instead.  The kernel, not the router,
-- is the authority: if an edge were forged, THIS file would fail to check.
--
-- THIS IS THE FIRST MECHANICALLY-ROUTED TRANSPORTED THEOREM IN THE CORPUS:
-- the route below was found by BFS in machine/Marga_â¦.hs over the landed
-- edge set (Setubandha âˆ© Lopa's CONTROL AUDIT, ddc71aad), the composite
-- equivalence and this whole file were emitted by the router, and the only
-- hand-written mathematics is the source theorem P and its proof, which
-- were already checked facts of FactoryVICoolingKill restated as a
-- predicate on the type.
--
-- WHAT IS TRANSPORTED.  FactoryVICoolingKill exhibits the T110 strategy
-- kill twice over â” cm3 and cm6 are distinct countermodels (their X fields
-- are 10Â³ and 10â).  Routed across two causeways, that becomes: the census
-- type censusÎ at the doubly-refined Ratri node has two provably distinct
-- inhabitants.  No Ratri module states this; it is bought entirely by the
-- edges, at zero marginal proof cost, which is Sangati Â§à¨ done rather than
-- described.
--
-- HONESTY ABOUT THE TOLL.  The largest landed component (7 nodes, diameter
-- 4: three Ratri census pairs around the hub CoolingCountermodel) has its
-- only theorem-bearing node AT the hub, and the hub is â‰ 2 edges from
-- everything, so 2 is the longest real transport this component affords.
-- The diameter-4 pairs (censusÎ to censusÎ across copies) carry no
-- independent theorem at either end â” routing between them would transport
-- nothing that was not already routed through the hub.  A 2-edge routed
-- transport that is real beats a fabricated 4-edge one.
--
-- THE ROUTE (BFS-shortest in the landed invertible graph):
--   1.  FactoryVICoolingKill.CoolingCountermodel
--         â”âŸ¨ Ratri.Nirdharita_Agda-Builtin-Nat_NirdharanaPoneA_NirdharanaPoneA.DETERMINED (â‰) âŸ©â’
--       Ratri.Nirdharita_Agda-Builtin-Nat_NirdharanaPoneA_NirdharanaPoneA.CensusBase
--       file: formal/cubical/Ratri/Nirdharita_Agda-Builtin-Nat_NirdharanaPoneA_NirdharanaPoneA.agda
--   2.  Ratri.Nirdharita_Agda-Builtin-Nat_NirdharanaPoneA_NirdharanaPoneA.CensusBase
--         â”âŸ¨ Ratri.Nirdharita_Agda-Builtin-Nat_NirdharanaPoneA_NirdharanaPoneA.censusContract (â‰), crossed backwards by invEquiv âŸ©â’
--       Ratri.Nirdharita_Agda-Builtin-Nat_NirdharanaPoneA_NirdharanaPoneA.censusÎ
--       file: formal/cubical/Ratri/Nirdharita_Agda-Builtin-Nat_NirdharanaPoneA_NirdharanaPoneA.agda
--
-- THE TOLL: 2 edge(s).  On this stratum â” road one,
-- the invertible edges, the zero-locus of the gluing defect
-- rank(AB) = rank(B) âˆ’ dim(im B âˆ© ker A) (CAUSAL_MEMORY_SPACETIME Thm 7.1,
-- Lean: Pairfield/ProcessCutRankAdapter.lean) â” every crossing is free and
-- the route is canonical within its component.
--
-- EDGE SET: Setubandha's extraction restricted to the declarations that
-- survive Lopa's CONTROL AUDIT (commit ddc71aad, which found raw Setubandha
-- over-counts ~2—: 167 printed, 88 surviving at commit time).  Road two â”
-- the one-way edges, 1054 at ddc71aad over a largest component of 366
-- against road one's 10 [figures as committed; both graphs move with the
-- corpus] â” is NOT routed here; routing it needs FactorsThrough toll gates
-- and fibre receipts (NaturalMachine/FiniteInformation.agda, Avaccheda_â¦,
-- Sesa_â¦), and is the named next piece.
--
module Marga1_TheDoubleCountermodelCrossesTwoCausewaysAndTheFarCensusHasTwoDistinctInhabitants where

open import Cubical.Foundations.Prelude
open import Cubical.Foundations.Equiv
open import Cubical.Foundations.Univalence

import Ratri.Nirdharita_Agda-Builtin-Nat_NirdharanaPoneA_NirdharanaPoneA
import FactoryVICoolingKill

open import Cubical.Data.Sigma
open import Cubical.Data.Bool using (true; false; falseâ‰¢true)
open import Cubical.Relation.Nullary using (Â¬_)
open import Agda.Builtin.Nat using (_==_)

-- THE THEOREM AT THE SOURCE NODE.  FactoryVICoolingKill proves the T110
-- strategy kill BY EXHIBITION, and exhibits it more than once: cm3
-- (X = 10Â³) and cm6 (X = 10â) are both countermodels, and they are
-- provably distinct â” their X fields differ as naturals, decided by the
-- kernel through _==_.  P is the type-level form of that fact: "this type
-- has (at least) two provably distinct inhabitants".  It mentions only
-- the type, so it crosses causeways.
P : Type â†’ Type
P A = Î£[ x âˆˆ A ] Î£[ y âˆˆ A ] (Â¬ (x â‰¡ y))

sourceTheorem : P FactoryVICoolingKill.CoolingCountermodel
sourceTheorem =
    FactoryVICoolingKill.cm3
  , FactoryVICoolingKill.cm6
  , Î» p â†’ falseâ‰¢true
      (subst (Î» n â†’ (1000 == n) â‰¡ true)
             (cong FactoryVICoolingKill.CoolingCountermodel.X p)
             refl)


-- The composed causeway.  Each factor is a landed edge, crossed in the
-- direction BFS chose; compEquiv chains them; nothing else happens.
marga : FactoryVICoolingKill.CoolingCountermodel â‰ƒ Ratri.Nirdharita_Agda-Builtin-Nat_NirdharanaPoneA_NirdharanaPoneA.censusÎ£
marga = compEquiv Ratri.Nirdharita_Agda-Builtin-Nat_NirdharanaPoneA_NirdharanaPoneA.DETERMINED (invEquiv (Ratri.Nirdharita_Agda-Builtin-Nat_NirdharanaPoneA_NirdharanaPoneA.censusContract))

-- The transported theorem: P held at the source; ua marga
-- carries it to the target.  This term is the transaction.
transported : P (Ratri.Nirdharita_Agda-Builtin-Nat_NirdharanaPoneA_NirdharanaPoneA.censusÎ£)
transported = subst P (ua marga) sourceTheorem
