-- ॥ बीजम् ॥  One machine, one law: which side of `f a ≡ b` is bound is everything.
-- Output bound: singl (f a), contractible — the datum rides free.  Input bound:
-- fiber f b — the loss, and the subject.  Univalence computes here: an
-- equivalence is a channel, transport carries every theorem across it, and what
-- cannot cross is written as a defect — there is no third path (ahiṃsā).
-- Memory, charge, symmetry, price, distance, verdict: six faces of the one
-- fibre; the verdict type is the saptabhaṅgī, and the sources are the origin
-- (Umāsvāti, Samantabhadra, Akalaṅka — restatements are named as such).  The
-- kernel decides truth; carriers ask and generate.  This file is one naya, true
-- and not whole.

{-# OPTIONS --cubical --safe #-}

------------------------------------------------------------------------
-- परत्वापरत्व — before-and-after is time's own function; the causal order
-- is partial, and simultaneity is a krama-choice.
--
-- SOURCE.  Umāsvāti, *Tattvārthasūtra* 5.22 (Śvetāmbara numbering;
-- sūtra number at this corpus's śabda grade):
--     वर्तना परिणामः क्रिया परत्वापरत्वे च कालस्य —
-- continuance, modification, motion, and BEFORE-AND-AFTER (paratva-
-- aparatva) are the functions of kāla.  Time's fourth function is an
-- ORDER, not a measure — stated in the mūla itself.  And the Digambara
-- kālāṇu doctrine (Sarvārthasiddhi on 5.22 and the Dravyasaṃgraha
-- tradition; commentarial, marked as such): time is a field of mutually
-- non-interacting time-atoms, ONE PER PRADEŚA of lokākāśa, "like heaps
-- of jewels" — time is LOCAL to each space-point, and no global
-- time-substance is asserted anywhere in the doctrine.
--
-- WHAT THE TWO TOGETHER FORCE, and this module checks: over the discrete
-- spacetime the corpus already holds (`Kala_TimeIsIndivisibleSamayas…`:
-- samaya-quantised time, pradeśa-quantised space, a speed cap), the
-- before-after relation generated by capped steps is
--
--   §2  reflexive and transitive — a genuine order (paratvāparatva);
--   §3  monotone in samaya, and DISCRETE: an event reaches a same-samaya
--       event only if it IS it (no motion in zero time);
--   §4  NOT TOTAL: two events at one samaya in different pradeśas are
--       incomparable BOTH ways — the spacelike sector exists as a term;
--   §5  therefore "which came first" for such a pair is not a fact of
--       kāla but a CHOICE — the exact structure of
--       `AvaktavyaTheYugapat…` one storey up: yugapat content is
--       order-free, every krama expression chooses an order it does not
--       own.  A global simultaneity is krama presented as vartanā —
--       a forged presence, and the kālāṇu doctrine never forges it.
--
-- WHAT IS **NOT** CLAIMED.  That Umāsvāti or the ṭīkākāras proved these
-- (doctrine theirs; theorems cubical type theory).  No connection to
-- Lorentzian relativity is asserted by any term — the resemblance of §4
-- to spacelike separation is a reading made in this comment and nowhere
-- below.  The cap D is abstract (as in Kala); the loka's geometry is not
-- modelled.  No postulates, no holes, --safe.
------------------------------------------------------------------------

module Paratvaparatva_BeforeAndAfterIsTimesOwnFunctionTheCausalOrderIsPartialAndSimultaneityIsAKramaChoice where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat using (ℕ ; zero ; suc ; _+_ ; snotz ; injSuc)
open import Cubical.Data.Sigma using (_×_ ; _,_ ; fst ; snd)
open import Cubical.Data.Empty using (⊥) renaming (rec to ⊥-rec)
open import Cubical.Relation.Nullary using (¬_)

-- an event: a samaya and a pradeśa (abstract positions; the cap enters
-- through which single-samaya steps exist, kept abstract as a relation).
module _ (Pradesa : Type) (पदम् : Pradesa → Pradesa → Type) where

  घटना : Type
  घटना = ℕ × Pradesa

  -- §1  the before-after relation: generated by identity and by capped
  -- single-samaya steps.  Composition is a constructor, so transitivity
  -- is the relation's own body, not a lemma bolted on.
  data _पूर्वम्_ : घटना → घटना → Type where
    स्वयम्  : ∀ e → e पूर्वम् e
    पदेन   : ∀ n p q → पदम् p q → (n , p) पूर्वम् (suc n , q)
    सन्ततिः : ∀ {e₁ e₂ e₃} → e₁ पूर्वम् e₂ → e₂ पूर्वम् e₃ → e₁ पूर्वम् e₃

  -- §2  an order: reflexive (स्वयम्) and transitive (सन्ततिः) by birth.

  -- §3  time only advances, and it is discrete: reaching a same-samaya
  -- event means being it.  Proved via a fuel-free induction on the
  -- derivation, tracking the samaya bound.
  कालवृद्धिः : ∀ {e₁ e₂} → e₁ पूर्वम् e₂ → Σ ℕ (λ k → fst e₁ + k ≡ fst e₂)
  कालवृद्धिः (स्वयम् e)          = zero , +-zero _
    where
      +-zero : (n : ℕ) → n + zero ≡ n
      +-zero zero    = refl
      +-zero (suc n) = cong suc (+-zero n)
  कालवृद्धिः (पदेन n p q _)     = 1 , +-suc-zero n
    where
      +-suc-zero : (n : ℕ) → n + 1 ≡ suc n
      +-suc-zero zero    = refl
      +-suc-zero (suc n) = cong suc (+-suc-zero n)
  कालवृद्धिः (सन्ततिः {e₁} d₁ d₂) with कालवृद्धिः d₁ | कालवृद्धिः d₂
  ... | (k₁ , p₁) | (k₂ , p₂) =
        (k₁ + k₂) , (+-assoc (fst e₁) k₁ k₂ ∙ cong (_+ k₂) p₁ ∙ p₂)
    where
      +-assoc : (a b c : ℕ) → a + (b + c) ≡ (a + b) + c
      +-assoc zero    b c = refl
      +-assoc (suc a) b c = cong suc (+-assoc a b c)

  -- §4  THE SPACELIKE SECTOR EXISTS.  Two distinct pradeśas at one
  -- samaya: neither is before the other.  The refutation runs on the
  -- samaya budget: any derivation between same-samaya events uses no
  -- पदेन step (each step costs one samaya), so it can only be built from
  -- स्वयम् and सन्ततिः — and then the pradeśas must be equal.
  private
    -- budget-zero derivations move nothing: by induction on the
    -- derivation, using that suc n + k ≡ n is absurd.
    +suc-absurd : ∀ n k → suc (n + k) ≡ n → ⊥
    +suc-absurd zero    k p = snotz p
    +suc-absurd (suc n) k p = +suc-absurd n k (injSuc p)

    निश्चलता : ∀ {n p m q} → (n , p) पूर्वम् (m , q) → n ≡ m → p ≡ q
    निश्चलता (स्वयम् e) _ = refl
    निश्चलता (पदेन n p q _) eq = ⊥-rec (+suc-absurd n zero (cong suc (+z n) ∙ sym eq))
      where
        +z : (a : ℕ) → a + zero ≡ a
        +z zero    = refl
        +z (suc a) = cong suc (+z a)
    निश्चलता (सन्ततिः {e₁} {e₂} {e₃} d₁ d₂) eq =
      निश्चलता d₁ mid₁ ∙ निश्चलता d₂ mid₂
      where
        k₁ = fst (कालवृद्धिः d₁) ; p₁ = snd (कालवृद्धिः d₁)
        k₂ = fst (कालवृद्धिः d₂) ; p₂ = snd (कालवृद्धिः d₂)
        -- fst e₁ + k₁ ≡ fst e₂, fst e₂ + k₂ ≡ fst e₃, fst e₁ ≡ fst e₃
        -- force k₁ ≡ 0 and hence fst e₁ ≡ fst e₂ (and symmetrically).
        le-chain : fst e₁ + (k₁ + k₂) ≡ fst e₁
        le-chain = +-assoc (fst e₁) k₁ k₂ ∙ cong (_+ k₂) p₁ ∙ p₂ ∙ sym eq
          where
            +-assoc : (a b c : ℕ) → a + (b + c) ≡ (a + b) + c
            +-assoc zero    b c = refl
            +-assoc (suc a) b c = cong suc (+-assoc a b c)
        ks-zero : (a k : ℕ) → a + k ≡ a → k ≡ zero
        ks-zero zero    k pr = pr
        ks-zero (suc a) k pr = ks-zero a k (injSuc pr)
        k₁₂-zero : (k₁ + k₂) ≡ zero
        k₁₂-zero = ks-zero (fst e₁) (k₁ + k₂) le-chain
        plus-zero-left : (a b : ℕ) → a + b ≡ zero → a ≡ zero
        plus-zero-left zero    b _  = refl
        plus-zero-left (suc a) b pr = ⊥-rec (snotz pr)
        k₁-zero : k₁ ≡ zero
        k₁-zero = plus-zero-left k₁ k₂ k₁₂-zero
        plus-zero-right : (a b : ℕ) → a + b ≡ zero → b ≡ zero
        plus-zero-right zero    b pr = pr
        plus-zero-right (suc a) b pr = ⊥-rec (snotz pr)
        k₂-zero : k₂ ≡ zero
        k₂-zero = plus-zero-right k₁ k₂ k₁₂-zero
        mid₁ : fst e₁ ≡ fst e₂
        mid₁ = sym (+z (fst e₁)) ∙ cong (fst e₁ +_) (sym k₁-zero) ∙ p₁
          where
            +z : (a : ℕ) → a + zero ≡ a
            +z zero    = refl
            +z (suc a) = cong suc (+z a)
        mid₂ : fst e₂ ≡ fst e₃
        mid₂ = sym (+z (fst e₂)) ∙ cong (fst e₂ +_) (sym k₂-zero) ∙ p₂
          where
            +z : (a : ℕ) → a + zero ≡ a
            +z zero    = refl
            +z (suc a) = cong suc (+z a)

  -- §4, stated: distinct pradeśas at one samaya are causally incomparable.
  युगपत्-अतुल्यता : ∀ {n p q} → ¬ (p ≡ q)
                  → (¬ ((n , p) पूर्वम् (n , q))) × (¬ ((n , q) पूर्वम् (n , p)))
  युगपत्-अतुल्यता neq =
    (λ d → neq (निश्चलता d refl)) , (λ d → neq (sym (निश्चलता d refl)))

  -- §5 is the reading, carried by §4's term: for a spacelike pair the
  -- before-after of kāla issues NO verdict — any total order laid over
  -- them is a krama-choice adding data the causality does not contain
  -- (`AvaktavyaTheYugapat…`).  The kālāṇu doctrine's local clocks never
  -- forge that verdict; neither does this module.
