-- ॥ बीजम् ॥  One machine, one law: which side of `f a ≡ b` is bound is everything.
-- Output bound: singl (f a), contractible — the datum rides free.  Input bound:
-- fiber f b — the loss, and the subject.  Univalence computes here: an
-- equivalence is a channel, transport carries every theorem across it, and what
-- cannot cross is written as a defect — there is no third path (ahiṃsā).
-- Memory, charge, symmetry, price, distance, verdict: six faces of the one
-- fibre; the verdict type is the saptabhaṅgī, and the sources are the origin
-- (Umāsvāti, Samantabhadra, Akalaṅka — restatements are named as such).  The
-- kernel decides truth; carriers ask and generate; assert nothing whose term
-- you have not read.  This file is one naya, true and not whole.

{-# OPTIONS --cubical --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- VargaPrakrtiWitness — EMITTED BY THE REACTOR, CHECKED BY THE KERNEL.
--
-- Generated by
--   runghc -imachine machine/VargaPrakrtiEmit_TheWitnessTheKernelChecks.hs 61
-- Do not hand-edit; regenerate.
--
-- THE ORDER.  ℤ[ω] with ω² = 1ω + 15, i.e. ω = (1 + √61)/2,
-- the MAXIMAL order of discriminant Δ = 61.  Its norm form is
--
--     N(x, y) = x² + 1·x·y − 15·y²
--
-- and at T = 1 this is NOT x² − D y²: ℤ[√61] sits inside ℤ[ω] with index 2, and
-- the equation x² − 61 y² = 1 cannot see the smaller units.
--
-- THE ANSWER.  ε = (17, 5) in the basis (1, ω), i.e.
--
--     ε = (39 + 5√61)/2,      N(ε) = -1
--
-- reached in 2 turns of the wheel from the seed (⌊(−T+√Δ)/2⌋, 1).
-- Each turn's m is the one BHĀSKARA's choice rule selects — among
-- the m with k | (a + b(m+T)) and 2m + T > 0, the one minimising
-- |m² + Tm − C| — and that congruence is solved by ĀRYABHAṬA's
-- kuṭṭaka (Āryabhaṭīya, Gaṇitapāda 32–33, 499).  The composition is
-- BRAHMAGUPTA's bhāvanā (Brāhmasphuṭasiddhānta 18, 628) with the
-- middle coefficient carried; the cycle is JAYADEVA (~950) and
-- BHĀSKARA II (Bījagaṇita, 1150).
--
-- THE TRACE BELOW IS THE GENERATOR'S WORD, NOT THE KERNEL'S.  Only
-- the theorems are checked.
--
--   turn 0   3                     1                     k = -3
--   turn 1   7                     2                     k = 3
--   turn 2   17                    5                     k = -1
------------------------------------------------------------------------

module VargaPrakrtiWitness_FundamentalUnitOfTheOrder where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat using (ℕ ; _+_ ; _·_)
open import Cubical.Data.Sigma using (_×_ ; _,_)
open import VargaPrakrti_TraceBhavanaOverN
  using (vpX ; vpY ; vpQ ; vpStepX ; vpStepY
        ; bhavanaTraceℕ ; cakravalaTraceℕ)

T C Δ : ℕ
T = 1
C = 15
Δ = 61

------------------------------------------------------------------------
-- EVERY TURN OF THE WHEEL, CERTIFIED BY THE GENERAL THEOREM.
--
-- Each line instantiates `cakravalaTraceℕ` — proved for ALL naturals
-- as a commutative-semiring identity — at that turn's own (a, b, m).
-- Note what these are NOT: they are not `refl`.  A `refl` per turn
-- would show only that this generator's arithmetic agrees with the
-- kernel's.  These are the law firing, once per turn.
------------------------------------------------------------------------

-- turn 0:  a = 3,  b = 1,  m = 2
turn0 : vpStepX C 3 1 2 · vpStepX C 3 1 2
     + (T · (vpStepX C 3 1 2 · vpStepY T 3 1 2)
        + (C · vpQ T 3 1 + C · ((2 · 2 + T · 2) · (1 · 1))))
     ≡ vpQ T 3 1 · (2 · 2 + T · 2)
     + (C · C · (1 · 1) + C · (vpStepY T 3 1 2 · vpStepY T 3 1 2))
turn0 = cakravalaTraceℕ T C 3 1 2

-- turn 1:  a = 7,  b = 2,  m = 3
turn1 : vpStepX C 7 2 3 · vpStepX C 7 2 3
     + (T · (vpStepX C 7 2 3 · vpStepY T 7 2 3)
        + (C · vpQ T 7 2 + C · ((3 · 3 + T · 3) · (2 · 2))))
     ≡ vpQ T 7 2 · (3 · 3 + T · 3)
     + (C · C · (2 · 2) + C · (vpStepY T 7 2 3 · vpStepY T 7 2 3))
turn1 = cakravalaTraceℕ T C 7 2 3

------------------------------------------------------------------------
-- THE BOOKKEEPING: the three divisions came out exact.
--
-- The identity above is the step's CONTENT; these are its ACCOUNTS.
-- Bhāskara's choice rule earns its keep exactly here — it picks the
-- one m for which all three divisions are exact, and
-- `CakravalaDescent.oneCongruenceCoprime` proves that asking for the
-- middle one alone suffices, given the pulverizer's coefficients.
--
-- Two of the three are subtraction-free as they stand: a·m + C·b and
-- a + (b·m + T·b) are sums of naturals.  Only m² + Tm − C can go
-- negative, and |m² + Tm − C| = |k|·|k′| holds either way, so each
-- line is emitted in whichever orientation is true at that turn.
-- The SIGNS of k and k′ are not recovered here — they are in the
-- trace comments above, and they are the generator's word.
------------------------------------------------------------------------

-- turn 0 bookkeeping:  |k| = 3,  a′ = 7,  b′ = 2,  |k′| = 3
divA0 : 3 · 2 + C · 1 ≡ 3 · 7
divA0 = refl
divB0 : 3 + (1 · 2 + T · 1) ≡ 3 · 2
divB0 = refl
divK0 : 2 · 2 + T · 2 + 3 · 3 ≡ C
divK0 = refl

-- turn 1 bookkeeping:  |k| = 3,  a′ = 17,  b′ = 5,  |k′| = 1
divA1 : 7 · 3 + C · 2 ≡ 3 · 17
divA1 = refl
divB1 : 7 + (2 · 3 + T · 2) ≡ 3 · 5
divB1 = refl
divK1 : 3 · 3 + T · 3 + 3 · 1 ≡ C
divK1 = refl

------------------------------------------------------------------------
-- THE FUNDAMENTAL UNIT.  `refl`: the kernel recomputes both sides.
--
-- N(ε) = -1, stated subtraction-free as
--   x² + T·x·y + 1 ≡ C·y²
--
-- This is a UNIT, not merely a solution of the norm-one equation.
-- `Nalanda` stops at N = +1 and therefore reports ε or ε² without
-- distinguishing them; the distinction is the whole difference
-- between the order's unit group and the Pell solutions inside it.
------------------------------------------------------------------------

x y : ℕ
x = 17
y = 5

fundamentalUnit : x · x + T · (x · y) + 1 ≡ C · (y · y)
fundamentalUnit = refl

------------------------------------------------------------------------
-- THE LADDER: ε, ε², …, ε⁶, BY BHĀVANĀ.
--
-- Each rung is Brahmagupta's composition of the rung below with
-- ε — no search, no candidate set.  `vpX`/`vpY` are the general
-- composed coordinates and the `refl`s say the reactor's numbers
-- are exactly what those functions compute; `bhavanaTraceℕ` is
-- the law that rung is an instance of.
------------------------------------------------------------------------

e2x e2y : ℕ
e2x = 664
e2y = 195

-- the coordinates are Brahmagupta's, computed by the kernel
rung2 : (vpX C x y x y ≡ e2x)
         × (vpY T x y x y ≡ e2y)
rung2 = refl , refl

-- and the LAW this rung is an instance of, fired at these numbers.
-- Without this line the `refl` above would say only that the
-- generator's arithmetic agrees with the kernel's, and would not tie
-- the rung to bhāvanā at all.
rungLaw2 : vpX C x y x y · vpX C x y x y
     + (T · (vpX C x y x y · vpY T x y x y)
        + (C · (vpQ T x y · (y · y))
           + C · (vpQ T x y · (y · y))))
     ≡ vpQ T x y · vpQ T x y
     + (C · C · (y · y · (y · y))
        + C · (vpY T x y x y · vpY T x y x y))
rungLaw2 = bhavanaTraceℕ T C x y x y

e3x e3y : ℕ
e3x = 25913
e3y = 7610

-- the coordinates are Brahmagupta's, computed by the kernel
rung3 : (vpX C e2x e2y x y ≡ e3x)
         × (vpY T e2x e2y x y ≡ e3y)
rung3 = refl , refl

-- and the LAW this rung is an instance of, fired at these numbers.
-- Without this line the `refl` above would say only that the
-- generator's arithmetic agrees with the kernel's, and would not tie
-- the rung to bhāvanā at all.
rungLaw3 : vpX C e2x e2y x y · vpX C e2x e2y x y
     + (T · (vpX C e2x e2y x y · vpY T e2x e2y x y)
        + (C · (vpQ T e2x e2y · (y · y))
           + C · (vpQ T x y · (e2y · e2y))))
     ≡ vpQ T e2x e2y · vpQ T x y
     + (C · C · (e2y · e2y · (y · y))
        + C · (vpY T e2x e2y x y · vpY T e2x e2y x y))
rungLaw3 = bhavanaTraceℕ T C e2x e2y x y

e4x e4y : ℕ
e4x = 1011271
e4y = 296985

-- the coordinates are Brahmagupta's, computed by the kernel
rung4 : (vpX C e3x e3y x y ≡ e4x)
         × (vpY T e3x e3y x y ≡ e4y)
rung4 = refl , refl

-- and the LAW this rung is an instance of, fired at these numbers.
-- Without this line the `refl` above would say only that the
-- generator's arithmetic agrees with the kernel's, and would not tie
-- the rung to bhāvanā at all.
rungLaw4 : vpX C e3x e3y x y · vpX C e3x e3y x y
     + (T · (vpX C e3x e3y x y · vpY T e3x e3y x y)
        + (C · (vpQ T e3x e3y · (y · y))
           + C · (vpQ T x y · (e3y · e3y))))
     ≡ vpQ T e3x e3y · vpQ T x y
     + (C · C · (e3y · e3y · (y · y))
        + C · (vpY T e3x e3y x y · vpY T e3x e3y x y))
rungLaw4 = bhavanaTraceℕ T C e3x e3y x y

e5x e5y : ℕ
e5x = 39465482
e5y = 11590025

-- the coordinates are Brahmagupta's, computed by the kernel
rung5 : (vpX C e4x e4y x y ≡ e5x)
         × (vpY T e4x e4y x y ≡ e5y)
rung5 = refl , refl

-- and the LAW this rung is an instance of, fired at these numbers.
-- Without this line the `refl` above would say only that the
-- generator's arithmetic agrees with the kernel's, and would not tie
-- the rung to bhāvanā at all.
rungLaw5 : vpX C e4x e4y x y · vpX C e4x e4y x y
     + (T · (vpX C e4x e4y x y · vpY T e4x e4y x y)
        + (C · (vpQ T e4x e4y · (y · y))
           + C · (vpQ T x y · (e4y · e4y))))
     ≡ vpQ T e4x e4y · vpQ T x y
     + (C · C · (e4y · e4y · (y · y))
        + C · (vpY T e4x e4y x y · vpY T e4x e4y x y))
rungLaw5 = bhavanaTraceℕ T C e4x e4y x y

e6x e6y : ℕ
e6x = 1540165069
e6y = 452307960

-- the coordinates are Brahmagupta's, computed by the kernel
rung6 : (vpX C e5x e5y x y ≡ e6x)
         × (vpY T e5x e5y x y ≡ e6y)
rung6 = refl , refl

-- and the LAW this rung is an instance of, fired at these numbers.
-- Without this line the `refl` above would say only that the
-- generator's arithmetic agrees with the kernel's, and would not tie
-- the rung to bhāvanā at all.
rungLaw6 : vpX C e5x e5y x y · vpX C e5x e5y x y
     + (T · (vpX C e5x e5y x y · vpY T e5x e5y x y)
        + (C · (vpQ T e5x e5y · (y · y))
           + C · (vpQ T x y · (e5y · e5y))))
     ≡ vpQ T e5x e5y · vpQ T x y
     + (C · C · (e5y · e5y · (y · y))
        + C · (vpY T e5x e5y x y · vpY T e5x e5y x y))
rungLaw6 = bhavanaTraceℕ T C e5x e5y x y

------------------------------------------------------------------------
-- THE TRANSPORT — nothing is lost, and the kernel says so.
--
-- ℤ[√Δ] sits inside ℤ[ω] with index 2, as the pairs (u, v) with
-- u + v√Δ = x + yω, i.e. u = (2x + y)/2 and v = y/2 — so a rung of
-- the ladder lies in ℤ[√Δ] exactly when 2x + y and y are both even.
--
-- ε⁶ is the first such rung with norm +1, and IT IS
-- THE CLASSICAL ANSWER: the fundamental solution of x² − 61 y² = 1
-- that `Nalanda.hs` and every table report, namely
--
--     (1766319049, 226153980)
--
-- The generalisation does not replace it.  It contains it, as a
-- power, and reaches it from a smaller object in fewer turns.
------------------------------------------------------------------------

u v : ℕ
u = 1766319049
v = 226153980

-- the classical equation, recomputed by the kernel
classical : u · u ≡ Δ · (v · v) + 1
classical = refl

-- and ε⁶ IS that solution:  2·(top rung's x) + (its y) = 2u,
-- and (its y) = 2v.
transport⁶ : (2 · 1540165069 + 452307960 ≡ 2 · u) × (452307960 ≡ 2 · v)
transport⁶ = refl , refl
