{-# OPTIONS --cubical --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- Viśvarūpa — the form containing every form.
--
-- TERM.  विश्वरूप, "all-formed"; in the *Bhagavadgītā* 11 it is the
-- theophany in which Arjuna is shown every form at once in one body.  The
-- word is used here for the universe that classifies every family, because
-- that is what the word means and no closer one exists in English.  GRADE,
-- and it matters: the Gītā states no theorem, none is claimed for it, and
-- nothing below is anyone's mathematics but the univalent foundations'.
-- The chapter number is what I can establish and no verse is given.  If
-- this reads as decoration, delete the name and keep §1–§4; the terms are
-- what is being asserted.
--
-- THE CLAIM THIS CHECKS, which is the owner's and is exact.
--
--   "The fibre law is the object classifier.  In a univalent universe a
--    form over a base — any family B : A → Type — is a map A → 𝒰, and Σ A B
--    is its total space.  One object classifies every fibration there is."
--
-- That is HoTT Theorem 4.8.3 and it is in the library, so §1 does not
-- reprove it; it instantiates it and points at the one fact worth saying
-- out loud: THE PROOF OF THE CLASSIFIER RUNS THROUGH `ua` APPLIED TO THE
-- FIBRE EQUIVALENCE.  Read `Cubical.Functions.Fibration`: the right
-- inverse is `ua (fiberEquiv p⁻¹ x) i`, the left is `ua (totalEquiv p) (~ i)`.
-- So the universe does not merely happen to classify fibrations.  The
-- classification IS the fibre law, carried by univalence.  That is the
-- strongest available form of the owner's sentence and it is someone
-- else's theorem, cited, not ours.
--
-- §2 IS THE PART THAT IS NEW HERE, and it is the corpus's own law read
-- through the classifier.  `Punaragamana.Carrier` turns on WHICH SIDE OF
-- `f a ≡ b` IS BOUND.  Assemble each binding into a total space:
--
--     bind the OUTPUT   Σ[ a ∈ A ] singl (f a)  ≃  A
--     bind the INPUT    Σ[ b ∈ B ] fiber f b    ≃  A
--
-- BOTH ARE A.  The free reading is A because every summand is
-- contractible; the costly reading is A because the summands REASSEMBLE —
-- HoTT 4.8.2, and nothing is contractible about them.  Two proofs, one
-- type, and the difference between the proofs is the whole calculus of
-- loss.  Which says precisely where the loss lives:
--
--     NOT IN THE TOTAL, WHICH IS THE SAME EITHER WAY.
--     IN THE PARTITION — how the same A is cut up over B.
--
-- That is why every price in this corpus is a fibrewise quantity and never
-- a global one, and why a readout valued in a proposition (`Asesa_…`) loses
-- everything: it is the partition with one block.
--
-- §3 IS THE PHYSICS CLAIM, WITH ONE CORRECTION THAT STRENGTHENS IT.
-- Transport around a loop is an automorphism of the fibre, and it composes
-- along concatenation — the action law, `substComposite`.  So a family over
-- A carries a monodromy action of Ω(A) on its fibre.  That is holonomy, and
-- it is holonomy OF A FLAT CONNECTION: in plain univalent foundations the
-- transport of a family is determined by the family, there is no
-- independent connection datum to vary, and path-ordered transport composes
-- strictly.  Curvature is not available here; getting it needs the
-- differential/cohesive extensions, and no module in this corpus has one.
-- So the right statement is sharper than "physics is a fibration": the
-- univalent universe gives you, for free and computing, exactly the flat
-- part — monodromy, Wilson loops around non-contractible cycles, the
-- invisible-iff-invariant phenomenon — and the curvature of a genuine gauge
-- field is a further structure this substrate does not yet carry.
--
-- The corpus already owns the worked instance:
-- `NaturalMachine.Ankapasa_…`'s `comm-loop` is a loop whose transport is
-- the swap, so its monodromy group is ℤ/2, and `uaβ` is what makes that a
-- computation rather than a citation.
--
-- §4 IS THE ITERATION CLAIM, AND ONLY ITS WELL-FOUNDEDNESS IS CHECKED.
-- One round trip of the classification is the identity: take a family to
-- its total space, take the fibres of the projection, and you have the
-- family again (HoTT 4.8.1).  So the tower one builds by iterating is
-- generated by NEW choices at each stage and never by re-classifying what
-- is already classified.  That is what makes "iterate the fibre law" a
-- construction rather than a circle.
--
-- ~~WHAT IS NOT CLAIMED, and this is where the owner's third sentence
-- outruns what is checked.~~  **STRUCK WITHIN THE HOUR, BY ME, AND IT WAS
-- AN ABSENCE ASSERTED WITHOUT A COMMAND — the error CLAUDE.md names first.**
-- The corpus checks the iteration, graded, for EVERY sphere, and I had not
-- looked:
--
--   `StaraArpana_…`     S¹: Ω(∥S¹∥₃) ≃ ℤ — the charge uttered whole one
--                       stratum above the silence.
--   `AyamaArpana_…`     S²: ∥S²∥₃ is contractible (sphereConnected 2), so
--                       the withholding deepens one stratum per dimension.
--   `AnantaraArpana_…`  EVERY sphere, and it is sharper than the textbook
--                       tower: ∥Sⁿ⁺¹∥₍₂₊ₙ₎ contractible, and
--                       Ωⁿ⁺¹(∥Sⁿ⁺¹∥₍₃₊ₙ₎) ≃ ℤ.  The first stratum above
--                       the last silent one already carries every winding
--                       number.  THERE IS NO STRATUM OF PARTIAL SPEECH.
--
-- So the corpus does not merely have the tower; it has the tower's GRADING,
-- which is a statement the "iterate pushouts and you get every type"
-- formulation does not make.  What remains true of THIS file is only that
-- §4 checks well-foundedness and no more — a statement about these lines,
-- not about the corpus, and the original wording failed to distinguish
-- those.  Completeness of the cell-complex construction is still a
-- citation, but it is a citation the corpus has already cashed on the
-- sphere family.
--
-- No postulates, no holes, --safe.  CHECKED this session, EXIT 0, at
-- Agda 2.6.3 + agda/cubical v0.5 -- which is NOT the corpus pin (2.8.0 +
-- v0.9).  Re-check at the pin before treating this green as the lane's.
------------------------------------------------------------------------

module Visvarupa_TheObjectClassifierIsTheFibreLawAndBothBindingsTotaliseToTheDomain where

open import Cubical.Foundations.Prelude
open import Cubical.Foundations.Equiv using (_≃_ ; fiber ; invEquiv ; compEquiv ; idEquiv)
open import Cubical.Foundations.Isomorphism using (Iso ; iso ; isoToEquiv)
open import Cubical.Foundations.Univalence using (ua ; uaβ)
open import Cubical.Foundations.Transport using (substComposite)
open import Cubical.Data.Sigma using (Σ-syntax ; _,_ ; fst ; snd ; Σ-contractSnd)
open import Cubical.Functions.Fibration using (fiberEquiv ; totalEquiv ; fibrationEquiv)

private
  variable
    ℓ : Level

------------------------------------------------------------------------
-- §1.  THE CLASSIFIER, CITED AND INSTANTIATED.
--
-- One object — the universe — and every map into a base is a family out of
-- it.  Not reproved here; named, so that what follows has something to
-- stand on.
------------------------------------------------------------------------

the-object-classifier :
  (B : Type₀) → (Σ[ E ∈ Type₀ ] (E → B)) ≃ (B → Type₀)
the-object-classifier B = fibrationEquiv B ℓ-zero

-- and the fibre law is what it classifies BY: the forward direction of the
-- equivalence sends a map to its family of fibres, on the nose.
classification-is-taking-fibres :
  {B : Type₀} {E : Type₀} (p : E → B) (b : B)
  → fst (the-object-classifier B) (E , p) b ≡ fiber p b
classification-is-taking-fibres p b = refl

------------------------------------------------------------------------
-- §2.  BOTH BINDINGS TOTALISE TO THE DOMAIN, FOR DIFFERENT REASONS.
------------------------------------------------------------------------

-- THE FREE BINDING.  `Carrier`'s own: bind the output and every summand is
-- contractible, so the total space collapses back to A summand by summand.
binding-the-output-totalises :
  {A B : Type₀} (f : A → B) → (Σ[ a ∈ A ] singl (f a)) ≃ A
binding-the-output-totalises f = Σ-contractSnd (λ a → isContrSingl (f a))

-- THE COSTLY BINDING.  Bind the input and no summand need be contractible;
-- the total space is A anyway, because the fibres reassemble.  HoTT 4.8.2.
binding-the-input-totalises :
  {A B : Type₀} (f : A → B) → (Σ[ b ∈ B ] fiber f b) ≃ A
binding-the-input-totalises f = invEquiv (totalEquiv f)

-- SO THE TWO TOTAL SPACES AGREE, AND THE AGREEMENT CARRIES NO INFORMATION
-- ABOUT f.  Everything the fibre law measures is in how A is cut, never in
-- how much of it there is.
both-bindings-totalise-alike :
  {A B : Type₀} (f : A → B)
  → (Σ[ a ∈ A ] singl (f a)) ≃ (Σ[ b ∈ B ] fiber f b)
both-bindings-totalise-alike f =
  compEquiv (binding-the-output-totalises f)
            (invEquiv (binding-the-input-totalises f))

------------------------------------------------------------------------
-- §3.  MONODROMY: TRANSPORT AROUND A LOOP, AND ITS ACTION LAW.
--
-- The flat part of the gauge picture, and it computes.  No connection is
-- supplied: the family IS the transport, which is exactly why what one gets
-- is the flat case.
------------------------------------------------------------------------

module _ {A : Type₀} (P : A → Type₀) where

  monodromy : {a : A} → a ≡ a → P a → P a
  monodromy p = subst P p

  -- The action law.  Path-ordered transport composes along concatenation,
  -- strictly.  This is what "flat" means here.
  monodromy-composes :
    {a : A} (p q : a ≡ a) (u : P a)
    → monodromy (p ∙ q) u ≡ monodromy q (monodromy p u)
  monodromy-composes p q u = substComposite P p q u

  -- and the constant loop acts trivially.
  monodromy-refl : {a : A} (u : P a) → monodromy refl u ≡ u
  monodromy-refl u = substRefl {B = P} u

------------------------------------------------------------------------
-- §4.  THE ITERATION IS WELL-FOUNDED: ONE ROUND TRIP IS THE IDENTITY.
--
-- Family ↦ total space ↦ fibres of the projection ↦ family.  HoTT 4.8.1.
-- So a tower built by iterating the fibre law never re-derives a stage it
-- already has; each stage is a genuinely new choice.
------------------------------------------------------------------------

round-trip : {B : Type₀} (P : B → Type₀) (b : B)
           → fiber {A = Σ[ x ∈ B ] P x} fst b ≃ P b
round-trip P b = fiberEquiv P b

-- The closure statement in the form the owner's sentence needs: the total
-- space of a family is itself a base with a map into the old one, so the
-- construction can be applied again, and §1 classifies the result.
the-universe-is-closed-under-the-operation :
  {B : Type₀} (P : B → Type₀) → Σ[ E ∈ Type₀ ] (E → B)
the-universe-is-closed-under-the-operation {B} P = (Σ[ x ∈ B ] P x) , fst

closure-classifies-back :
  {B : Type₀} (P : B → Type₀) (b : B)
  → fst (the-object-classifier B) (the-universe-is-closed-under-the-operation P) b
    ≃ P b
closure-classifies-back P b = round-trip P b
