"""The invariant/channel library and the minimal-separating-channel search.

CRYSTAL.md §3.2 step 4 says "search the invariant library for a *minimal*
channel separating the collision while preserving previously discharged
tasks".  "Minimal" is ambiguous and the ambiguity is where such systems
usually lie, so this module states which is meant, every time:

``minimum_cardinality_set``
    **Exact minimum cardinality.**  Subsets of the library are enumerated by
    increasing size and the first size that admits a solution is returned.
    This is exact -- an exhaustive proof that no smaller subset works comes
    free with the enumeration -- and exponential; it is guarded by an explicit
    subset budget and raises ``SearchBudgetExceeded`` rather than silently
    degrading.  Ties at the minimum size are broken deterministically by
    ``(number of induced classes, total declared digit reads, names)``.

``greedy_set``
    **Greedy set cover.**  Returned results are labelled ``greedy`` and carry
    the standard approximation bound: for a constraint set of size ``P``,
    ``|greedy| <= H(P) * OPT`` where ``H(P) = 1 + 1/2 + ... + 1/P``, and this
    is tight for set cover.  A greedy result is never called "minimal" without
    that qualification.

``inclusion_minimal_set``
    **Minimal under inclusion.**  Repeatedly drops any single channel whose
    removal preserves the requirement.  The result admits no removable member
    (that is the check the tests plant a false positive against) but is *not*
    claimed to be minimum cardinality.  This is CRYSTAL.md §3.2 step 6 --
    redundant-channel removal -- and is what deletes a null channel.

Two requirement kinds are supported, and they are different claims:

* ``PairRequirement`` -- separate a finite list of collision pairs.  This is
  what the compile loop can actually see at any moment.
* ``PartitionRequirement`` -- refine a whole target partition.  This is the
  global claim, checkable in ``O(|S|)`` per subset because refinement of a
  partition is a class-count identity, not a pair enumeration.

The library itself is generated by a uniform rule so the search is not rigged:
single-digit readouts, residues at every prime power dividing ``b**n`` up to
the length bound plus two primes that do *not* divide it, digit-sum invariants,
palindromy (the fixed-point set of the reversal ``D``, DIGIT_CRYSTAL Thm 3.4),
the ``b``-adic valuation, and a zero count.  Nothing in the library is the
answer to a declared task by construction.
"""

from __future__ import annotations

from itertools import combinations
from typing import Sequence

from .observe import Channel, DigitWordSystem, NullCounter, StepCounter, horner_mod, truncation_length


class SearchBudgetExceeded(Exception):
    """Raised when exact minimum-cardinality search would exceed its budget."""


# --------------------------------------------------------------------------
# channel constructors
# --------------------------------------------------------------------------


def digit_channel(index: int) -> Channel:
    def fn(digits: Sequence[int], counter: StepCounter) -> int:
        counter.tick("digit-read")
        return digits[index]

    return Channel("digit_%d" % index, 1, fn)


def residue_channel(base: int, length: int, modulus: int) -> Channel:
    """``L(w) mod modulus``, reading only the digits that can matter.

    ``truncation_length`` returns the smallest ``k`` with ``b**k == 0 mod m``;
    beyond that point higher digits contribute nothing, so the channel reads
    ``k`` digits, not ``n``.  For ``b = 6``, ``m = 8`` this is 3 digits because
    ``6**3 = 216 = 8 * 27``.  The declared cost equals the actual reads.
    """
    top = truncation_length(base, modulus, length)

    def fn(digits: Sequence[int], counter: StepCounter) -> int:
        return horner_mod(digits, base, modulus, top, counter)

    return Channel("res_%d" % modulus, top, fn)


def digit_sum_mod_channel(length: int, modulus: int) -> Channel:
    def fn(digits: Sequence[int], counter: StepCounter) -> int:
        acc = 0
        for index in range(length):
            counter.tick("digit-read")
            acc += digits[index]
        return acc % modulus

    return Channel("digitsum_mod_%d" % modulus, length, fn)


def alternating_sum_mod_channel(length: int, modulus: int) -> Channel:
    def fn(digits: Sequence[int], counter: StepCounter) -> int:
        acc = 0
        sign = 1
        for index in range(length):
            counter.tick("digit-read")
            acc += sign * digits[index]
            sign = -sign
        return acc % modulus

    return Channel("altsum_mod_%d" % modulus, length, fn)


def palindrome_channel(length: int) -> Channel:
    """Indicator of ``Fix(D)`` -- the palindromes (DIGIT_CRYSTAL Thm 3.4)."""
    half = (length + 1) // 2

    def fn(digits: Sequence[int], counter: StepCounter) -> int:
        for index in range(half):
            counter.tick("digit-read")
            if digits[index] != digits[length - 1 - index]:
                return 0
        return 1

    return Channel("is_palindrome", half, fn)


def valuation_channel(length: int) -> Channel:
    """``v_b`` -- the number of trailing zero digits (DIGIT_CRYSTAL §0)."""

    def fn(digits: Sequence[int], counter: StepCounter) -> int:
        count = 0
        for index in range(length):
            counter.tick("digit-read")
            if digits[index] != 0:
                break
            count += 1
        return count

    return Channel("valuation", length, fn)


def zero_count_channel(length: int) -> Channel:
    def fn(digits: Sequence[int], counter: StepCounter) -> int:
        count = 0
        for index in range(length):
            counter.tick("digit-read")
            if digits[index] == 0:
                count += 1
        return count

    return Channel("zero_count", length, fn)


def reversed_residue_channel(base: int, length: int, modulus: int) -> Channel:
    """``L(rho(w)) mod modulus`` -- reads the word through the reversal ``D``.

    This channel is what the demo's falsification task needs and the declared
    task family never does; it exists in the library so that the recompilation
    after the new task arrives is a search, not a hand-placed answer.
    """

    def fn(digits: Sequence[int], counter: StepCounter) -> int:
        acc = 0
        for index in range(length):
            counter.tick("digit-read")
            acc = (acc * base + digits[index]) % modulus
        return acc

    return Channel("rev_res_%d" % modulus, length, fn)


def prime_powers_dividing(value: int, limit: int) -> tuple[int, ...]:
    """Every prime power ``p**j > 1`` dividing ``value``, ascending by prime."""
    out: list[int] = []
    rest = value
    factor = 2
    while factor * factor <= rest:
        if rest % factor == 0:
            exponent = 0
            while rest % factor == 0:
                rest //= factor
                exponent += 1
            power = factor
            for _ in range(min(exponent, limit)):
                out.append(power)
                power *= factor
        factor += 1
    if rest > 1:
        out.append(rest)
    return tuple(out)


def standard_library(system: DigitWordSystem) -> tuple[Channel, ...]:
    """The invariant library for a digit-word system, in canonical order."""
    base, length = system.base, system.length
    channels: list[Channel] = []
    for index in range(length):
        channels.append(digit_channel(index))
    for power in prime_powers_dividing(system.size, length):
        channels.append(residue_channel(base, length, power))
    for modulus in (5, 7):
        if system.size % modulus != 0:
            channels.append(residue_channel(base, length, modulus))
    for modulus in (2, 3, 5):
        channels.append(digit_sum_mod_channel(length, modulus))
    channels.append(alternating_sum_mod_channel(length, base + 1))
    channels.append(palindrome_channel(length))
    channels.append(valuation_channel(length))
    channels.append(zero_count_channel(length))
    return tuple(channels)


def channel_values(
    system: DigitWordSystem,
    channels: Sequence[Channel],
    counter: StepCounter,
) -> dict[str, tuple[int, ...]]:
    """Compile-time value arrays: one entry per state per channel."""
    silent = NullCounter()
    columns: dict[str, list[int]] = {channel.name: [0] * system.size for channel in channels}
    counter.tick("compile-state-visit", system.size * len(channels))
    for value in range(system.size):
        word = system.digits(value)
        for channel in channels:
            columns[channel.name][value] = channel.eval_word(word, silent)
    return {name: tuple(column) for name, column in columns.items()}


# --------------------------------------------------------------------------
# requirements
# --------------------------------------------------------------------------


class PairRequirement:
    """Separate a finite list of state pairs (the collisions found so far)."""

    kind = "pairs"

    __slots__ = ("pairs",)

    def __init__(self, pairs: Sequence[tuple[int, int]]) -> None:
        self.pairs = tuple(pairs)

    @property
    def size(self) -> int:
        return len(self.pairs)

    def satisfied_by(self, columns: Sequence[Sequence[int]], counter: StepCounter) -> bool:
        for x, y in self.pairs:
            counter.tick("pair-visit")
            separated = False
            for column in columns:
                if column[x] != column[y]:
                    separated = True
                    break
            if not separated:
                return False
        return True

    def covered_by_channel(self, column: Sequence[int], counter: StepCounter) -> frozenset:
        covered = set()
        for index, (x, y) in enumerate(self.pairs):
            counter.tick("pair-visit")
            if column[x] != column[y]:
                covered.add(index)
        return frozenset(covered)


class PartitionRequirement:
    """Refine a target partition -- the global sufficiency claim.

    ``columns`` refine ``target`` exactly when the number of distinct joint
    keys equals the number of distinct ``(key, target)`` pairs, which is an
    ``O(|S|)`` test with no pair enumeration.
    """

    kind = "partition"

    __slots__ = ("target", "n_states")

    def __init__(self, target: Sequence[int]) -> None:
        self.target = tuple(target)
        self.n_states = len(self.target)

    @property
    def size(self) -> int:
        return self.n_states

    def satisfied_by(self, columns: Sequence[Sequence[int]], counter: StepCounter) -> bool:
        counter.tick("state-visit", self.n_states)
        if not columns:
            return len(set(self.target)) <= 1
        joint = set(zip(*columns))
        with_target = set(zip(*columns, self.target))
        return len(joint) == len(with_target)


# --------------------------------------------------------------------------
# search
# --------------------------------------------------------------------------


class ChannelSearchResult:
    """A channel set plus the exact strength of the minimality claim."""

    __slots__ = ("names", "claim", "detail", "subsets_tested", "n_classes")

    def __init__(self, names: Sequence[str], claim: str, detail: str, subsets_tested: int, n_classes: int) -> None:
        self.names = tuple(names)
        self.claim = claim
        self.detail = detail
        self.subsets_tested = subsets_tested
        self.n_classes = n_classes

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return "ChannelSearchResult(%r, claim=%s, classes=%d)" % (list(self.names), self.claim, self.n_classes)


def _class_count(columns: Sequence[Sequence[int]], n_states: int) -> int:
    if not columns:
        return 1
    return len(set(zip(*columns)))


def minimum_cardinality_set(
    library: Sequence[Channel],
    values: dict[str, tuple[int, ...]],
    requirement,
    counter: StepCounter,
    budget: int = 400000,
    max_size: int | None = None,
) -> ChannelSearchResult:
    """Exact minimum-cardinality channel set satisfying ``requirement``.

    Enumerates subsets by increasing size; the first size with a solution is
    the minimum, and the enumeration of all smaller sizes *is* the proof that
    nothing smaller works.  Deterministic tie-break at the minimum size:
    fewest induced classes, then fewest declared digit reads, then names.
    """
    names = [channel.name for channel in library]
    reads = {channel.name: channel.reads for channel in library}
    n_states = len(values[names[0]]) if names else 0
    limit = len(library) if max_size is None else min(max_size, len(library))
    tested = 0
    for size in range(0, limit + 1):
        winners: list[tuple[int, int, tuple[str, ...]]] = []
        for combo in combinations(range(len(library)), size):
            tested += 1
            if tested > budget:
                raise SearchBudgetExceeded(
                    "exact search exceeded %d subsets at size %d; use greedy_set and state the bound" % (budget, size)
                )
            counter.tick("subset-test")
            chosen = tuple(names[i] for i in combo)
            columns = [values[name] for name in chosen]
            if requirement.satisfied_by(columns, counter):
                winners.append((_class_count(columns, n_states), sum(reads[name] for name in chosen), chosen))
        if winners:
            winners.sort()
            classes, _, chosen = winners[0]
            return ChannelSearchResult(
                chosen,
                "exact-minimum-cardinality",
                "no subset of size < %d satisfies the requirement (%d subsets enumerated)" % (size, tested),
                tested,
                classes,
            )
    raise ValueError("no subset of the library satisfies the requirement")


def harmonic_bound_numerator_denominator(n: int) -> tuple[int, int]:
    """``H(n) = 1 + 1/2 + ... + 1/n`` as an exact fraction.  No floating point."""
    num, den = 0, 1
    for k in range(1, n + 1):
        num, den = num * k + den, den * k
        g = _gcd(num, den)
        num, den = num // g, den // g
    return num, den


def harmonic_ceiling(n: int) -> int:
    """The least integer ``k`` with ``H(n) <= k``.  Exact, no floating point."""
    num, den = harmonic_bound_numerator_denominator(max(1, n))
    return -((-num) // den)


def _gcd(a: int, b: int) -> int:
    while b:
        a, b = b, a % b
    return a if a > 0 else 1


def greedy_set(
    library: Sequence[Channel],
    values: dict[str, tuple[int, ...]],
    requirement: PairRequirement,
    counter: StepCounter,
) -> ChannelSearchResult:
    """Greedy set cover over collision pairs.  NOT claimed to be minimum.

    Bound: ``|greedy| <= H(P) * OPT`` with ``P = |pairs|`` and ``H`` the
    harmonic number, computed here as an exact fraction.  Ties are broken by
    (most pairs covered, fewest declared reads, name).
    """
    if requirement.kind != "pairs":
        raise TypeError("greedy_set covers pair requirements only")
    uncovered = set(range(len(requirement.pairs)))
    coverage = {
        channel.name: requirement.covered_by_channel(values[channel.name], counter) for channel in library
    }
    reads = {channel.name: channel.reads for channel in library}
    chosen: list[str] = []
    while uncovered:
        best = None
        for channel in library:
            counter.tick("subset-test")
            gain = len(coverage[channel.name] & uncovered)
            if gain == 0:
                continue
            key = (-gain, reads[channel.name], channel.name)
            if best is None or key < best[0]:
                best = (key, channel.name)
        if best is None:
            raise ValueError("library cannot separate every pair")
        chosen.append(best[1])
        uncovered -= coverage[best[1]]
    columns = [values[name] for name in chosen]
    ceiling = harmonic_ceiling(len(requirement.pairs))
    return ChannelSearchResult(
        tuple(chosen),
        "greedy",
        "|C| <= H(%d) * OPT <= %d * OPT  (H exact, ceiling shown)" % (len(requirement.pairs), ceiling),
        len(library),
        _class_count(columns, len(values[library[0].name])),
    )


def inclusion_minimal_set(
    names: Sequence[str],
    values: dict[str, tuple[int, ...]],
    requirement,
    counter: StepCounter,
    reads: dict[str, int] | None = None,
) -> tuple[tuple[str, ...], tuple[str, ...]]:
    """Drop every channel whose removal preserves the requirement.

    CRYSTAL.md §3.2 step 6.  Returns ``(kept, dropped)``.  ``kept`` is minimal
    **under inclusion** -- no single member can be removed -- and is *not*
    claimed to be minimum cardinality.  Removal order is deterministic:
    most declared digit reads first, then name, so the expensive redundant
    channels go first.
    """
    reads = reads or {name: 0 for name in names}
    current = list(names)
    dropped: list[str] = []
    order = sorted(names, key=lambda name: (-reads.get(name, 0), name))
    for name in order:
        trial = [other for other in current if other != name]
        counter.tick("subset-test")
        if requirement.satisfied_by([values[other] for other in trial], counter):
            current = trial
            dropped.append(name)
    return tuple(current), tuple(dropped)


def is_inclusion_minimal(
    names: Sequence[str],
    values: dict[str, tuple[int, ...]],
    requirement,
    counter: StepCounter,
) -> tuple[bool, tuple[str, ...]]:
    """Check the inclusion-minimality claim; return any removable members."""
    removable: list[str] = []
    for name in names:
        trial = [other for other in names if other != name]
        counter.tick("subset-test")
        if requirement.satisfied_by([values[other] for other in trial], counter):
            removable.append(name)
    return (len(removable) == 0), tuple(removable)
