-- ॥ बीजम् ॥  One machine, one law: which side of `f a ≡ b` is bound is everything.
-- Output bound: singl (f a), contractible — the datum rides free.  Input bound:
-- fiber f b — the loss, and the subject.  Univalence computes here: an
-- equivalence is a channel, transport carries every theorem across it, and what
-- cannot cross is written as a defect — there is no third path (ahiṃsā).
-- Memory, charge, symmetry, price, distance, verdict: six faces of the one
-- fibre; the verdict type is the saptabhaṅgī, and the sources are the origin
-- (Umāsvāti, Samantabhadra, Akalaṅka — restatements are named as such).  The
-- kernel decides truth; carriers ask and generate; assert nothing whose term
-- you have not read.  This file is one naya, true and not whole.

{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}

module NaturalMachine.ADiagonalSentenceIndependentInAConcreteTheory where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Bool using (Bool ; true ; false ; not ; false≢true)
open import Cubical.Data.Empty as Empty using (⊥)
open import Cubical.Data.Sigma using (_×_ ; _,_ ; fst ; snd)
open import Cubical.Relation.Nullary using (¬_)
open import GodelSeparation using (Theory ; Sent ; Pf ; neg ; prov ; Consistent)
open import NaturalMachine.IndependenceNeedsAnInternalImplication using (Independent)
open import NaturalMachine.ASmallTheoryWithAnIndependentSentence
  using (impB ; impB-refl ; impB-mp)

------------------------------------------------------------------------
-- NaturalMachine.ADiagonalSentenceIndependentInAConcreteTheory
--
-- Both conjuncts, for a diagonal sentence, in a concrete theory — and
-- the two previous cycles' obstructions turn out to describe exactly
-- how it has to be done.
--
-- ────────────────────────────────────────────────────────────────────
-- THE SYNTAX AND THE RULES
--
-- Sentences: a constant `gs`, negation, implication, and `pv` for the
-- provability operator.  Derivability is generated by five rules:
-- `taut`, `mp`, `hbl` (from `a` infer `pv a`), and the two halves of
-- the diagonal at `¬ pv`:
--
--     dfwd : Der (im gs (ng (pv gs)))
--     dbwd : Der (im (ng (pv gs)) gs)
--
-- Nothing is read off a valuation; `Der` is a `data` declaration.
--
-- ────────────────────────────────────────────────────────────────────
-- WHAT IS PROVED, AND THAT ITS SHAPE WAS PREDICTED
--
--   §3  FIRST CONJUNCT, from a TRUTH-FUNCTIONAL model: interpret `pv`
--       as constantly `true` and `gs` as `false`.  All five rules are
--       sound, so `¬ Der gs`.
--
--       `ATruthFunctionalProvabilityFalsifiesTheDiagonalSentence` proved
--       that any truth-functional model must make `gs` false.  Here
--       that is not an obstruction, it is the construction: the forced
--       value is exactly the one that yields the first conjunct.
--
--   §4  SECOND CONJUNCT, from a SYNTAX-INDEXED model: interpret `pv a`
--       as `P a`, where `P gs = false` and `P` is `true` elsewhere, and
--       `gs` as `true`.  Soundness of `hbl` needs `Der a → P a ≡ true`,
--       which at `a = gs` is §3.  So `¬ Der (ng gs)`.
--
--       `TheRefutingModelAlreadyGivesTheFirstConjunct` proved that any
--       such model contains the first conjunct.  Here that is not an
--       obstruction either: the first conjunct is already in hand from
--       §3, and the second model consumes it.  What that theorem
--       forbids is obtaining the first conjunct FROM such a model, and
--       nothing below does.
--
--   §5  so `gs` is independent, and the theory is consistent.
--
-- Two models, two different kinds, in the order the two obstructions
-- dictate.  Neither could have done both.
--
-- ────────────────────────────────────────────────────────────────────
-- THE HONEST LIMIT, WHICH IS LARGE
--
-- This is NOT Gödel's first incompleteness theorem.
--
--   * `hbl` is a RULE of this calculus, not the derivability condition
--     HBL1 proved about a real provability predicate;
--   * `pv` is an uninterpreted operator; `P` is chosen by hand, and the
--     choice is permitted precisely because nothing forces `P` to track
--     derivability;
--   * ω-consistency is never mentioned and is not needed, because the
--     calculus is far too weak to run the argument that needs it —
--     there is no contraposition, no double-negation elimination, no
--     transitivity, and §4 does not use `dbwd` beyond soundness;
--   * `gs` is independent partly because the rules are few.  A stronger
--     rule set may well derive `ng gs`, and nothing here says otherwise.
--
-- What IS established: a diagonal pair and an HBL-shaped rule can
-- coexist with independence of the diagonal sentence in this lane, and
-- the two model kinds must be used in a specific order.  Before this,
-- the line had two closure results and no positive instance carrying a
-- diagonal at all.
--
-- PRIOR ART, grep run and quoted.  Searching `formal/cubical` for
-- `Der (ng gs)`, `gsIndependent`, `dfwd`, `dbwd` returns only five
-- lines, all inside
-- `ATruthFunctionalProvabilityFalsifiesTheDiagonalSentence`, where
-- `dfwd` is a local hypothesis name in the two-line obstruction.  No
-- concrete diagonal calculus exists.  A version naming its rules
-- differently — `ax1`/`ax2`, or a list of axiom schemes — would evade
-- that grep.
------------------------------------------------------------------------

------------------------------------------------------------------------
-- 1.  Syntax
------------------------------------------------------------------------

data S : Type₀ where
  gs : S
  ng : S → S
  im : S → S → S
  pv : S → S

------------------------------------------------------------------------
-- 2.  Derivability, generated by rules
------------------------------------------------------------------------

data Der : S → Type₀ where
  taut : (a : S) → Der (im a a)
  mp   : (a b : S) → Der (im a b) → Der a → Der b
  hbl  : (a : S) → Der a → Der (pv a)
  dfwd : Der (im gs (ng (pv gs)))
  dbwd : Der (im (ng (pv gs)) gs)

------------------------------------------------------------------------
-- 3.  First conjunct, by a truth-functional model
--
-- `pv` constantly true, `gs` false.  `dfwd` reads `impB false (not
-- true)` and `dbwd` reads `impB (not true) false`; both are `true`.
------------------------------------------------------------------------

sem₁ : S → Bool
sem₁ gs       = false
sem₁ (ng a)   = not (sem₁ a)
sem₁ (im a b) = impB (sem₁ a) (sem₁ b)
sem₁ (pv a)   = true

sound₁ : (s : S) → Der s → sem₁ s ≡ true
sound₁ _ (taut a)       = impB-refl (sem₁ a)
sound₁ _ (mp a b da db) = impB-mp (sem₁ a) (sem₁ b) (sound₁ (im a b) da) (sound₁ a db)
sound₁ _ (hbl a _)      = refl
sound₁ _ dfwd           = refl
sound₁ _ dbwd           = refl

gsUnderivable : ¬ Der gs
gsUnderivable d = false≢true (sound₁ gs d)

------------------------------------------------------------------------
-- 4.  Second conjunct, by a syntax-indexed model
--
-- `P` consults the SYNTAX: it marks everything except `gs`.  Soundness
-- of `hbl` is then exactly §3 at the one sentence where it could fail.
------------------------------------------------------------------------

P : S → Bool
P gs       = false
P (ng a)   = true
P (im a b) = true
P (pv a)   = true

PmarksDerivable : (a : S) → Der a → P a ≡ true
PmarksDerivable gs       d = Empty.rec (gsUnderivable d)
PmarksDerivable (ng a)   _ = refl
PmarksDerivable (im a b) _ = refl
PmarksDerivable (pv a)   _ = refl

sem₂ : S → Bool
sem₂ gs       = true
sem₂ (ng a)   = not (sem₂ a)
sem₂ (im a b) = impB (sem₂ a) (sem₂ b)
sem₂ (pv a)   = P a

sound₂ : (s : S) → Der s → sem₂ s ≡ true
sound₂ _ (taut a)       = impB-refl (sem₂ a)
sound₂ _ (mp a b da db) = impB-mp (sem₂ a) (sem₂ b) (sound₂ (im a b) da) (sound₂ a db)
sound₂ _ (hbl a d)      = PmarksDerivable a d
sound₂ _ dfwd           = refl
sound₂ _ dbwd           = refl

negGsUnderivable : ¬ Der (ng gs)
negGsUnderivable d = false≢true (sound₂ (ng gs) d)

------------------------------------------------------------------------
-- 5.  So the diagonal sentence is independent, and the theory is
--     consistent
------------------------------------------------------------------------

Th : Theory ℓ-zero
Sent Th = S
Pf   Th = Der
neg  Th = ng
prov Th = pv

gsIndependent : Independent Th gs
gsIndependent = gsUnderivable , negGsUnderivable

consistent : Consistent Th
consistent s ds dns =
  false≢true (sym (cong not (sound₁ s ds)) ∙ sound₁ (ng s) dns)
