{-# OPTIONS --cubical --safe #-}

------------------------------------------------------------------------
-- आप्तमीमांसा — Samantabhadra (c. 2nd–5th c. CE): the title is the
-- doctrine — the examination of the authority.  An āpta is
-- established by examination, never by claim; received text (āgama)
-- is knowledge only downstream of that examination.  The
-- classification is his; the mathematics is not claimed for the
-- source.  School named: Jaina.
--
-- THE TWO-BODY PROBLEM, CROSSED.  Until now the machine's LIVE store
-- — the rewriter's rules in machine/library.terms, grown by सिद्धि's
-- welds and the completion's turns — lived only in the elder Haskell,
-- as text a reader must trust.  Here it crosses: the elder EMITS its
-- store as raw encounters (machine/AgamaLekhaka_….awk — the elder
-- writes, the kernel judges), and every utterance passes through the
-- one body's own knowing — महाप्रमाणम् with the full eye, no record,
-- each rule judged independently on its own content.  No authority:
-- the elder's provenance annotations are not read; a rule enters as
-- नियमः exactly when the body re-derives it, and what the body does
-- not reach is kept, counted, as the residue that names the knowing's
-- present boundary from inside.
--
-- Outside the vocabulary and left with the elder, stated not hidden:
-- 11 store lines naming gcd or the completion's fresh constants
-- (c0 …) — Tm carries neither; that is the vocabulary frontier.
--
-- The counts below are computations, not reports: each ≡ is checked
-- by the kernel normalizing the entire judgment of the entire store.
------------------------------------------------------------------------

module NaturalMachine.AptaMimamsa_TheEldersLiveStoreCrossesAsReceivedTextAndNothingEntersOnAuthority where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat using (ℕ ; zero ; suc)
open import Cubical.Data.Maybe using (Maybe ; nothing ; just)
open import Cubical.Data.List using (List ; [] ; _∷_ ; length)
open import Cubical.Data.Sigma using (_,_)

open import NaturalMachine.EkaBhasha_TheStoreCarriesItsProofsTheGateIsTheTypeAndTheProverLivesInside
open import NaturalMachine.SvarthaAnumana_TheMachineInfersForItselfAndThePervasionIsGraspedWithinWithNoOuterCarrier
  using (इन्धनम्)
open import NaturalMachine.BhavaIndriya_TheNewEyeIsMadeOfTheBodysOwnAttainedTheoremsNotOfExternalMatter
  using (नेत्रम्-पूर्ण)
open import NaturalMachine.YugapadArpana_BothCoordinatesDescendAtOnceAndTheDoubleDescentBecomesSomethingTheMachineInvokes
  using (महाप्रमाणम्)

------------------------------------------------------------------------
-- §1  The received text, as the elder emitted it.
------------------------------------------------------------------------

-- generated by machine/AgamaLekhaka_TheElderEmitsItsStoreAsRawEncountersForTheOneBody.awk
-- from machine/library.terms; 102 unique pairs; 11 gcd lines outside vocabulary, left with the elder
आगमः : List Eq'
आगमः = ( (ze ⊕ (var 0)) , (var 0) )
      ∷ ( (mx (var 0) (var 0)) , (var 0) )
      ∷ ( (ze ⊗ (var 0)) , ze )
      ∷ ( ((var 0) ⊖ (var 0)) , ze )
      ∷ ( ((su ze) ⊗ (var 0)) , (var 0) )
      ∷ ( ((var 0) ⊖ (su (var 0))) , ze )
      ∷ ( (lq (su (var 0)) (var 0)) , ze )
      ∷ ( (lq (var 0) (var 0)) , (su ze) )
      ∷ ( ((su ze) ⊕ (var 0)) , (su (var 0)) )
      ∷ ( (mx (var 0) (su (var 0))) , (su (var 0)) )
      ∷ ( (mx (su (var 0)) (var 0)) , (su (var 0)) )
      ∷ ( ((su (var 0)) ⊖ (var 0)) , (su ze) )
      ∷ ( (lq (var 0) (su (var 0))) , (su ze) )
      ∷ ( (su ((var 0) ⊕ (var 1))) , ((su (var 0)) ⊕ (var 1)) )
      ∷ ( ((var 1) ⊕ (var 0)) , ((var 0) ⊕ (var 1)) )
      ∷ ( ((var 0) ⊖ (lq (var 0) ze)) , (var 0) )
      ∷ ( ((var 0) ⊗ (lq (var 0) ze)) , ze )
      ∷ ( ((lq (var 0) ze) ⊗ (var 0)) , ze )
      ∷ ( ((var 0) ⊖ (su (su (var 0)))) , ze )
      ∷ ( (lq (su (su (var 0))) (var 0)) , ze )
      ∷ ( (lq (var 0) (su (su (var 0)))) , (su ze) )
      ∷ ( ((su (su ze)) ⊗ (var 0)) , ((var 0) ⊕ (var 0)) )
      ∷ ( ((lq (var 0) ze) ⊖ (var 0)) , (lq (var 0) ze) )
      ∷ ( (lq (var 0) (lq (var 0) ze)) , (lq (var 0) ze) )
      ∷ ( (lq ((var 0) ⊕ (var 0)) ze) , (lq (var 0) ze) )
      ∷ ( (lq ((var 0) ⊕ (var 1)) (var 1)) , (lq (var 0) ze) )
      ∷ ( (mx (var 0) (su (su (var 0)))) , (su (su (var 0))) )
      ∷ ( (mx (su (su (var 0))) (var 0)) , (su (su (var 0))) )
      ∷ ( ((su (su (var 0))) ⊖ (var 0)) , (su (su ze)) )
      ∷ ( (lq (lq (var 0) ze) (var 0)) , (lq (su ze) (var 0)) )
      ∷ ( (lq (lq (var 0) ze) ze) , (lq (su ze) (var 0)) )
      ∷ ( (mx (var 0) (lq (var 0) ze)) , (mx (var 0) (su ze)) )
      ∷ ( (mx (lq (var 0) ze) (var 0)) , (mx (var 0) (su ze)) )
      ∷ ( (su ((var 0) ⊖ (su ze))) , (mx (var 0) (su ze)) )
      ∷ ( ((var 1) ⊕ ((var 0) ⊕ (var 0))) , ((var 0) ⊕ ((var 0) ⊕ (var 1))) )
      ∷ ( (su ze) , (lq (var 0) ((var 0) ⊕ (var 1))) )
      ∷ ( ((var 0) ⊕ ((var 1) ⊕ (var 2))) , (((var 0) ⊕ (var 1)) ⊕ (var 2)) )
      ∷ ( (lq (var 0) (var 2)) , (lq ((var 0) ⊕ (var 1)) ((var 2) ⊕ (var 1))) )
      ∷ ( ((var 1) ⊕ ((var 0) ⊗ (var 1))) , ((su (var 0)) ⊗ (var 1)) )
      ∷ ( (mx ((var 0) ⊕ (var 1)) (var 0)) , ((var 0) ⊕ (var 1)) )
      ∷ ( (mx (var 0) (lq (su ze) (var 0))) , (var 0) )
      ∷ ( ((var 0) ⊖ (su ((var 0) ⊕ (var 1)))) , ze )
      ∷ ( ((var 0) ⊖ (su (su (su (var 0))))) , ze )
      ∷ ( ((lq (var 0) ze) ⊖ (su (var 0))) , ze )
      ∷ ( (lq (mx (var 0) (su (var 1))) ze) , ze )
      ∷ ( (lq (mx (su (var 0)) (var 1)) ze) , ze )
      ∷ ( (lq (su ((var 0) ⊕ (var 1))) (var 0)) , ze )
      ∷ ( (lq (su ((var 0) ⊕ (var 1))) (var 1)) , ze )
      ∷ ( (lq (su (su (su (var 0)))) (var 0)) , ze )
      ∷ ( (mx (lq (var 0) ze) (su (var 0))) , (su (var 0)) )
      ∷ ( (mx (su (var 0)) (lq (var 0) ze)) , (su (var 0)) )
      ∷ ( (mx (su (var 0)) (lq (var 1) ze)) , (su (var 0)) )
      ∷ ( (lq (var 0) (su ((var 0) ⊕ (var 1)))) , (su ze) )
      ∷ ( (lq (var 0) (su (su (su (var 0))))) , (su ze) )
      ∷ ( (lq (lq (var 0) ze) (su (var 0))) , (su ze) )
      ∷ ( (lq (lq (var 0) ze) (su (var 1))) , (su ze) )
      ∷ ( (lq (lq (su ze) (var 0)) (var 0)) , (su ze) )
      ∷ ( ((var 0) ⊗ (mx (var 0) (su ze))) , ((var 0) ⊗ (var 0)) )
      ∷ ( ((mx (var 0) (su ze)) ⊗ (var 0)) , ((var 0) ⊗ (var 0)) )
      ∷ ( (lq (lq (su ze) (var 0)) ze) , (lq (var 0) ze) )
      ∷ ( ((var 0) ⊖ (lq (su ze) (var 0))) , ((var 0) ⊖ (su ze)) )
      ∷ ( (lq ((var 0) ⊕ ((var 0) ⊗ (var 0))) ze) , (lq (var 0) ze) )
      ∷ ( (lq ((var 0) ⊕ ((var 0) ⊗ (var 1))) ze) , (lq (var 0) ze) )
      ∷ ( (lq ((var 0) ⊖ (su ze)) (var 1)) , (lq (var 0) (su (var 1))) )
      ∷ ( (lq (var 0) (lq (su ze) (var 0))) , (lq (var 0) (su ze)) )
      ∷ ( (lq ((var 0) ⊕ (var 1)) (su (var 1))) , (lq (var 0) (su ze)) )
      ∷ ( (lq ((var 0) ⊖ (su ze)) ze) , (lq (var 0) (su ze)) )
      ∷ ( (lq (su ze) ((var 0) ⊗ (var 0))) , (lq (su ze) (var 0)) )
      ∷ ( (lq (su ze) ((var 0) ⊕ (var 0))) , (lq (su ze) (var 0)) )
      ∷ ( (mx (var 0) (su ((var 0) ⊕ (var 1)))) , (su ((var 0) ⊕ (var 1))) )
      ∷ ( (mx (su ((var 0) ⊕ (var 1))) (var 0)) , (su ((var 0) ⊕ (var 1))) )
      ∷ ( (mx (var 0) (su (su (su (var 0))))) , (su (su (su (var 0)))) )
      ∷ ( (mx (su (su (su (var 0)))) (var 0)) , (su (su (su (var 0)))) )
      ∷ ( ((su (su (su (var 0)))) ⊖ (var 0)) , (su (su (su ze))) )
      ∷ ( (mx ((var 0) ⊕ (var 0)) (su ze)) , ((var 0) ⊕ (mx (var 0) (su ze))) )
      ∷ ( (mx ((var 0) ⊕ (var 1)) (su (var 0))) , ((var 0) ⊕ (mx (var 1) (su ze))) )
      ∷ ( ((var 0) ⊕ ze) , (var 0) )
      ∷ ( ((var 0) ⊗ ze) , ze )
      ∷ ( (((var 0) ⊗ (var 1)) ⊕ ((var 0) ⊗ ze)) , ((var 0) ⊗ ((var 1) ⊕ ze)) )
      ∷ ( (mx (ze ⊕ ze) ((var 0) ⊕ ze)) , ((mx ze (var 0)) ⊕ ze) )
      ∷ ( (((var 0) ⊕ (var 0)) ⊗ (var 1)) , ((var 0) ⊗ ((var 1) ⊕ (var 1))) )
      ∷ ( (mx ze (var 0)) , (var 0) )
      ∷ ( (ze ⊖ (var 0)) , ze )
      ∷ ( ((var 0) ⊗ (lq ze ze)) , (var 0) )
      ∷ ( (mx (var 0) ((var 1) ⊗ ze)) , (var 0) )
      ∷ ( (mx (ze ⊕ (var 0)) (var 0)) , (var 0) )
      ∷ ( ((var 0) ⊗ (ze ⊕ ze)) , ze )
      ∷ ( (((var 0) ⊗ (var 1)) ⊗ ze) , ze )
      ∷ ( (mx ze ((var 0) ⊗ ze)) , ze )
      ∷ ( (lq ((var 0) ⊗ ze) (var 1)) , (su ze) )
      ∷ ( (lq ((var 0) ⊗ ze) ze) , (su ze) )
      ∷ ( (((var 0) ⊗ ze) ⊗ ((var 0) ⊗ ze)) , ze )
      ∷ ( (((var 0) ⊗ ze) ⊕ (((var 0) ⊗ ze) ⊗ (su ((var 0) ⊗ ze)))) , ze )
      ∷ ( ((((var 0) ⊗ ze) ⊗ ((var 0) ⊗ ze)) ⊗ (((var 0) ⊗ ze) ⊗ ((var 0) ⊗ ze))) , ze )
      ∷ ( ((ze ⊖ (var 0)) ⊗ ze) , ze )
      ∷ ( (ze ⊖ ((var 0) ⊗ ze)) , ze )
      ∷ ( (mx (var 6) ze) , (var 6) )
      ∷ ( (lq (su (var 1)) ze) , ze )
      ∷ ( (lq ze (var 1)) , (su ze) )
      ∷ ( ((var 0) ⊗ (su ze)) , (var 0) )
      ∷ ( (lq (su ze) (su (var 1))) , (su ze) )
      ∷ ( (mx (su (var 6)) (su ze)) , (su (var 6)) )
      ∷ []

------------------------------------------------------------------------
-- §2  The examination.  Each utterance judged by the knowing alone —
--     full eye, single and double descent, no record, no authority.
------------------------------------------------------------------------

न्यायः : List Eq' → List नियमः
न्यायः [] = []
न्यायः ((l , r) ∷ es) with महाप्रमाणम् नेत्रम्-पूर्ण [] इन्धनम् (l , r)
... | just pf = niyama l r pf ∷ न्यायः es
... | nothing = न्यायः es

अपचितम् : List Eq' → List Eq'
अपचितम् [] = []
अपचितम् ((l , r) ∷ es) with महाप्रमाणम् नेत्रम्-पूर्ण [] इन्धनम् (l , r)
... | just _  = अपचितम् es
... | nothing = (l , r) ∷ अपचितम् es

------------------------------------------------------------------------
-- §3  The verdict of the whole store, computed.
------------------------------------------------------------------------

सिद्ध-गणना : length (न्यायः आगमः) ≡ 92
सिद्ध-गणना = refl

शेष-गणना : length (अपचितम् आगमः) ≡ 10
शेष-गणना = refl
