-- ॥ बीजम् ॥  One machine, one law: which side of `f a ≡ b` is bound is everything.
-- Output bound: singl (f a), contractible — the datum rides free.  Input bound:
-- fiber f b — the loss, and the subject.  Univalence computes here: an
-- equivalence is a channel, transport carries every theorem across it, and what
-- cannot cross is written as a defect — there is no third path (ahiṃsā).
-- Memory, charge, symmetry, price, distance, verdict: six faces of the one
-- fibre; the verdict type is the saptabhaṅgī, and the sources are the origin
-- (Umāsvāti, Samantabhadra, Akalaṅka — restatements are named as such).  The
-- kernel decides truth; carriers ask and generate; assert nothing whose term
-- you have not read.  This file is one naya, true and not whole.

{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}

module NaturalMachine.ASmallTheoryWithAnIndependentSentence where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Bool using (Bool ; true ; false ; not ; false≢true)
open import Cubical.Data.Empty as Empty using (⊥)
open import Cubical.Data.Sigma using (_×_ ; _,_ ; fst ; snd)
open import Cubical.Relation.Nullary using (¬_)
open import GodelSeparation using (Theory ; Sent ; Pf ; neg ; prov ; Consistent)
open import NaturalMachine.IndependenceNeedsAnInternalImplication using (Independent)
open import NaturalMachine.NegationCompletenessForbidsIndependence
  using (NegationComplete ; independenceFromTwoModels)

------------------------------------------------------------------------
-- NaturalMachine.ASmallTheoryWithAnIndependentSentence
--
-- The criterion of the previous module, instantiated — so it is not
-- vacuous, and so the lane is shown to contain a theory with an
-- independent sentence at all.
--
-- ────────────────────────────────────────────────────────────────────
-- WHAT WAS REQUIRED, AND WHY EVERY EARLIER MODEL FAILED IT
--
-- Two obstructions accumulated in this thread.  A theory admitting an
-- independent sentence must not be negation-complete, and must not have
-- a provability-determined implication.  Every model built here before
-- this one read provability off a single two-valued assignment, which
-- forces both.
--
-- The repair is the one the criterion names: `Pf` GENERATED BY RULES,
-- and soundness for a CLASS of valuations rather than truth in one.
--
-- ────────────────────────────────────────────────────────────────────
-- WHAT IS BUILT
--
--   §1  sentences as a free inductive type — one atom, negation,
--       implication.  Nothing is a truth-table here: `S` is a syntax.
--
--   §2  `Der` inductively generated by two rules: every `a → a` is
--       derivable, and modus ponens.  This is deliberately the smallest
--       rule set that is closed under `mp` and proves something.
--
--   §3  soundness for EVERY Boolean valuation of the atom, by induction
--       on the derivation.  Two lemmas about `impB`, three lines.
--
--   §4  so the atom is INDEPENDENT: it fails in the valuation sending
--       it to `false`, its negation fails in the valuation sending it
--       to `true`, and `independenceFromTwoModels` finishes.  The
--       theory is also consistent, and §5 witnesses both accumulated
--       obstructions failing here: it is not negation-complete, and its
--       implication is not provability-determined — `Der atom → Der (ng
--       atom)` holds vacuously while `im atom (ng atom)` is refuted by
--       soundness at the valuation sending the atom to `true`.
--
-- ────────────────────────────────────────────────────────────────────
-- THE HONEST LIMIT, WHICH IS LARGE
--
-- This is NOT Gödel's theorem and is not a step of it.  The independent
-- sentence is an atom, independent because the rules never mention it;
-- there is no diagonal, no fixed point, no ω-consistency, and the
-- theory's `prov` is the identity, which is not a provability predicate
-- in any sense beyond typing.  `HasDiagonal` is not claimed for it and
-- would fail: with one atom and these rules there is no formula to
-- diagonalise.
--
-- What this settles is narrower and was genuinely open: the criterion
-- has an instance, the two accumulated obstructions are not jointly
-- exhaustive of the lane, and a theory in this lane can have an
-- independent sentence.  Before this, every model in the thread had
-- none, and it was not shown that any could.
--
-- NOT CLAIMED.  That this theory is interesting as a theory; that
-- adding the diagonal machinery to it preserves independence — that is
-- exactly the open question and it is untouched; that two rules are
-- minimal.
--
-- PRIOR ART, by the conclusion type: a grep of `formal/cubical` for
-- `Independent` finds this thread only; for an inductively generated
-- provability relation over a syntax, nothing.  A version phrased with
-- a list-of-axioms closure operator rather than a `data` declaration
-- would evade that grep.
------------------------------------------------------------------------

------------------------------------------------------------------------
-- 1.  Syntax
------------------------------------------------------------------------

data S : Type₀ where
  atom : S
  ng   : S → S
  im   : S → S → S

------------------------------------------------------------------------
-- 2.  Derivability, generated by rules
------------------------------------------------------------------------

data Der : S → Type₀ where
  taut : (a : S) → Der (im a a)
  mp   : (a b : S) → Der (im a b) → Der a → Der b

------------------------------------------------------------------------
-- 3.  Soundness, for every valuation of the atom
------------------------------------------------------------------------

impB : Bool → Bool → Bool
impB false _ = true
impB true  b = b

impB-refl : (x : Bool) → impB x x ≡ true
impB-refl false = refl
impB-refl true  = refl

impB-mp : (x y : Bool) → impB x y ≡ true → x ≡ true → y ≡ true
impB-mp false y _ p = Empty.rec (false≢true p)
impB-mp true  y q _ = q

val : Bool → S → Bool
val v atom     = v
val v (ng a)   = not (val v a)
val v (im a b) = impB (val v a) (val v b)

sound : (v : Bool) (s : S) → Der s → val v s ≡ true
sound v _ (taut a)       = impB-refl (val v a)
sound v _ (mp a b da db) =
  impB-mp (val v a) (val v b) (sound v (im a b) da) (sound v a db)

------------------------------------------------------------------------
-- 4.  The theory, and the independent sentence
------------------------------------------------------------------------

Th : Theory ℓ-zero
Sent Th = S
Pf   Th = Der
neg  Th = ng
prov Th = λ s → s

atomFails : ¬ (val false atom ≡ true)
atomFails = false≢true

negAtomFails : ¬ (val true (ng atom) ≡ true)
negAtomFails = false≢true

atomIsIndependent : Independent Th atom
atomIsIndependent =
  independenceFromTwoModels Th Bool (λ v s → val v s ≡ true) sound
    atom false true atomFails negAtomFails

-- consistency: a sentence and its negation cannot both be derivable,
-- since soundness at any valuation would make a Bool equal to its own
-- negation.
consistent : Consistent Th
consistent s ds dns =
  false≢true (sym (cong not (sound false s ds)) ∙ sound false (ng s) dns)

------------------------------------------------------------------------
-- 5.  The two obstructions, witnessed as failing here
------------------------------------------------------------------------

notNegationComplete : ¬ NegationComplete Th
notNegationComplete comp =
  snd atomIsIndependent (comp atom (fst atomIsIndependent))

-- and the implication is not provability-determined: `Der atom → Der
-- (ng atom)` holds vacuously, while `im atom (ng atom)` is refuted by
-- soundness at the valuation sending the atom to `true`.
notProvabilityDetermined :
  ¬ ((a b : S) → (Der a → Der b) → Der (im a b))
notProvabilityDetermined r =
  false≢true
    (sound true (im atom (ng atom))
      (r atom (ng atom) (λ d → Empty.rec (fst atomIsIndependent d))))
