{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- IntrinsicRewrite
--
-- The Haskell rewrite gate represents execution and justification twice:
-- first as an untyped candidate assembled outside the logic, then as an
-- Agda term reconstructed for validation.  This module removes that seam at
-- its smallest honest point.
--
-- A `Run t` is not an output paired with a certificate.  Its constructors
-- ARE the executable motions available from `t`.  The intermediate target
-- is an index of `advance`, so an ill-composed next motion cannot be built.
-- `result` executes the run; `run-sound` reads its invariant.  Both recurse
-- over the same mathematical object, and neither parses or validates an
-- external representation.
------------------------------------------------------------------------

module NaturalMachine.IntrinsicRewrite where

open import Cubical.Foundations.Prelude

open import NaturalMachine.RewriteCertificate
  using (Tm ; var ; zero ; suc ; add ; Step ; add-zero ; add-suc ; suc-step
        ; add-left ; add-right ; Env ; eval ; step-sound)

infixr 5 advance

-- The hidden `u` is generated by the chosen motion and becomes the source
-- index of the rest of the run.  This is the Curry--Howard collapse: lawful
-- composition is formation of the program, rather than a later check on it.
data Run : Tm → Type₀ where
  halt    : {t : Tm} → Run t
  advance : {t u : Tm} → Step t u → Run u → Run t

-- Execution is a projection (an eliminator) of the typed transformation.
result : {t : Tm} → Run t → Tm
result {t} halt = t
result (advance _ rest) = result rest

-- Correctness is the other projection of exactly the same transformation.
-- It adds no acceptance bit and consults no external certificate store.
run-sound : {t : Tm} (run : Run t) (rho : Env) →
  eval t rho ≡ eval (result run) rho
run-sound halt rho = refl
run-sound (advance motion rest) rho =
  step-sound motion rho ∙ run-sound rest rho

------------------------------------------------------------------------
-- A closed execution
------------------------------------------------------------------------

-- This value is the running mathematics.  Its first constructor computes
--   var + suc zero  ↦  suc (var + zero),
-- and its second computes
--   suc (var + zero) ↦ suc var.
-- The middle term is forced by the index; replacing the second motion with
-- `add-zero var` is not a `Run (add var (suc zero))` at all.
add-one : Run (add var (suc zero))
add-one =
  advance (add-suc var zero)
    (advance (suc-step (add-zero var)) halt)

-- The endpoint is computed, not separately declared.
add-one-runs-to : result add-one ≡ suc var
add-one-runs-to = refl

-- The same `add-one` term also supplies its extensional mathematical law.
add-one-means : (rho : Env) →
  eval (add var (suc zero)) rho ≡ eval (suc var) rho
add-one-means rho = run-sound add-one rho

------------------------------------------------------------------------
-- Rooted profiles: one local motion transforms every surrounding view
------------------------------------------------------------------------

-- A locus is a one-hole term context.  It is not a coordinate label added
-- after execution: `plug locus t` is the actual rooted view of `t`.
data Locus : Type₀ where
  root       : Locus
  under-suc  : Locus → Locus
  under-left : Locus → Tm → Locus
  under-right : Tm → Locus → Locus

plug : Locus → Tm → Tm
plug root t = t
plug (under-suc locus) t = suc (plug locus t)
plug (under-left locus r) t = add (plug locus t) r
plug (under-right l locus) t = add l (plug locus t)

-- A primitive motion reweaves through any locus.  The surrounding syntax is
-- retained, including which side of addition the motion inhabited.
weave-step : (locus : Locus) {t u : Tm} →
  Step t u → Step (plug locus t) (plug locus u)
weave-step root motion = motion
weave-step (under-suc locus) motion = suc-step (weave-step locus motion)
weave-step (under-left locus r) motion = add-left (weave-step locus motion) r
weave-step (under-right l locus) motion = add-right l (weave-step locus motion)

-- Reweaving is structural recursion on the original transformation.  Thus a
-- failed attempt cannot be silently replaced by a successful endpoint: only
-- motions already present in the local `Run` can appear in any rooted view.
reweave : (locus : Locus) {t : Tm} → Run t → Run (plug locus t)
reweave locus halt = halt
reweave locus (advance motion rest) =
  advance (weave-step locus motion) (reweave locus rest)

-- The global rooted profile generated by one local run.
Profile : {t : Tm} → Run t → Type₀
Profile {t} run = (locus : Locus) → Run (plug locus t)

profile : {t : Tm} (run : Run t) → Profile run
profile run locus = reweave locus run

-- Execution commutes with every rooted view.  This is stronger than saying
-- that each transported run is sound separately: all views retain one common
-- endpoint generated from the local transformation.
reweave-result : (locus : Locus) {t : Tm} (run : Run t) →
  result (reweave locus run) ≡ plug locus (result run)
reweave-result locus halt = refl
reweave-result locus (advance motion rest) = reweave-result locus rest

-- Concrete non-root execution: the same `add-one` transformation runs in the
-- right-hand locus of `var + [-]`; no second derivation is supplied.
add-one-under-right :
  result (profile add-one (under-right var root)) ≡ add var (suc var)
add-one-under-right = refl
