-- ॥ बीजम् ॥  One machine, one law: which side of `f a ≡ b` is bound is everything.
-- Output bound: singl (f a), contractible — the datum rides free.  Input bound:
-- fiber f b — the loss, and the subject.  Univalence computes here: an
-- equivalence is a channel, transport carries every theorem across it, and what
-- cannot cross is written as a defect — there is no third path (ahiṃsā).
-- Memory, charge, symmetry, price, distance, verdict: six faces of the one
-- fibre; the verdict type is the saptabhaṅgī, and the sources are the origin
-- (Umāsvāti, Samantabhadra, Akalaṅka — restatements are named as such).  The
-- kernel decides truth; carriers ask and generate; assert nothing whose term
-- you have not read.  This file is one naya, true and not whole.

{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}

module NaturalMachine.NegationCompletenessForbidsIndependence where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Empty as Empty using (⊥)
open import Cubical.Data.Unit using (tt)
open import Cubical.Data.Sigma using (_×_ ; _,_ ; fst ; snd)
open import Cubical.Relation.Nullary using (¬_)
open import GodelSeparation
  using ( Theory ; Sent ; Pf ; neg
        ; W ; wtop ; wbot ; wg ; wng ; wneg ; wPf ; Wit )
open import NaturalMachine.IndependenceNeedsAnInternalImplication
  using (Independent)

------------------------------------------------------------------------
-- NaturalMachine.NegationCompletenessForbidsIndependence
--
-- The obstruction of the previous module, at its root — and the
-- positive recipe the root immediately suggests.
--
-- ────────────────────────────────────────────────────────────────────
-- WHAT THE PREVIOUS MODULE WAS REALLY ABOUT
--
-- `AProvabilityDeterminedImplicationForbidsIndependence` shows that a
-- provability-determined implication, with contraposition, modus ponens
-- and one unprovable sentence with provable negation, admits no
-- independent sentence.  §1 here shows the same conclusion follows from
-- one hypothesis with no implication in it at all:
--
--     if `¬ Pf T s` implies `Pf T (neg T s)` for every `s`
--     — negation-completeness — then nothing is independent.
--
-- One line, since independence is exactly the conjunction that
-- hypothesis forbids.  And `Wit` is negation-complete (§2, four cases),
-- so `Wit`'s failure was already settled before any of the
-- implication machinery was examined.
--
-- The two statements do not subsume each other.  In the respect of what
-- is assumed about the connectives, §1 asks less: it mentions no `imp`,
-- no contraposition, no modus ponens.  In the respect of what is
-- assumed about the theory, the previous module asks less: it never
-- says the theory decides every sentence, only that its implication is
-- read off provability.  Both are kept; there is no scale here on which
-- to prefer one.
--
-- ────────────────────────────────────────────────────────────────────
-- AND THE POSITIVE RECIPE
--
-- §3 is the classical route, written down: independence follows from
-- SOUNDNESS FOR TWO MODELS.  If every theorem holds in every model, and
-- there is a model where `s` fails and a model where `neg s` fails,
-- then `s` is independent.  Two lines.
--
-- This is exactly the thing every model in this thread lacked.  `Wit`
-- and its kin were built by reading provability off ONE two-valued
-- assignment, which is a single model, and a single model that decides
-- every sentence is negation-complete by construction — §1.  The
-- positive case needs a `Pf` generated by rules and sound for a CLASS
-- of models, with two members of the class disagreeing about `s`.
--
-- ────────────────────────────────────────────────────────────────────
-- NOT CLAIMED
--
-- That any such `Pf` and pair of models is constructed here.  §3 is a
-- criterion; nothing below builds an instance, and the positive case
-- remains open with its requirement now stated twice over — not
-- provability-determined (previous module), and not negation-complete
-- (§1) — with §3 saying what to build instead.
--
-- That negation-completeness is a defect.  `Wit` is a correct model and
-- a decidable finite theory being negation-complete is unremarkable;
-- what §2 establishes is only that it cannot be the witness for an
-- independence result.
--
-- PRIOR ART, by the conclusion type: a grep of `formal/cubical` for
-- `Independent` finds this thread only; for `sound`/`Sound` outside
-- unrelated uses, nothing about a satisfaction relation over
-- `Theory`.  A version phrased with a valuation into `Bool` rather than
-- a satisfaction family would evade that grep.
------------------------------------------------------------------------

private
  variable
    ℓ ℓ' ℓ'' : Level

------------------------------------------------------------------------
-- 1.  Negation-completeness forbids independence
------------------------------------------------------------------------

NegationComplete : Theory ℓ → Type ℓ
NegationComplete T = (s : Sent T) → ¬ Pf T s → Pf T (neg T s)

negationCompleteForbids :
  (T : Theory ℓ) → NegationComplete T → (s : Sent T) → ¬ Independent T s
negationCompleteForbids T comp s ind = snd ind (comp s (fst ind))

------------------------------------------------------------------------
-- 2.  `Wit` is negation-complete
--
-- Four cases.  The two provable sentences discharge the hypothesis;
-- the two unprovable ones have provable negations.
------------------------------------------------------------------------

witNegationComplete : NegationComplete Wit
witNegationComplete wtop h = Empty.rec (h tt)
witNegationComplete wbot _ = tt
witNegationComplete wg   _ = tt
witNegationComplete wng  h = Empty.rec (h tt)

witHasNoIndependentSentence : (s : W) → ¬ Independent Wit s
witHasNoIndependentSentence = negationCompleteForbids Wit witNegationComplete

------------------------------------------------------------------------
-- 3.  Soundness for two models gives independence
--
-- The satisfaction relation is a parameter: nothing is assumed about
-- its shape, only that every theorem holds in every model of the class.
------------------------------------------------------------------------

module _ (T : Theory ℓ) (Model : Type ℓ')
         (_⊨_ : Model → Sent T → Type ℓ'')
         (sound : (m : Model) (s : Sent T) → Pf T s → m ⊨ s)
         where

  independenceFromTwoModels :
    (s : Sent T) (m₀ m₁ : Model)
    → ¬ (m₀ ⊨ s)
    → ¬ (m₁ ⊨ neg T s)
    → Independent T s
  independenceFromTwoModels s m₀ m₁ h₀ h₁ =
      (λ p → h₀ (sound m₀ s p))
    , (λ p → h₁ (sound m₁ (neg T s) p))

  -- and the converse pressure: a class with one member that decides
  -- every sentence collapses to §1.
  singleDecidingModel :
    (m : Model)
    → ((s : Sent T) → ¬ (m ⊨ s) → Pf T (neg T s))
    → ((s : Sent T) → m ⊨ s → Pf T s)
    → NegationComplete T
  singleDecidingModel m decide adequate s notPf =
    decide s (λ sat → notPf (adequate s sat))
