{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}

module NaturalMachine.PolynomialAttachmentGrowth where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat using (ℕ ; zero ; suc)
open import Cubical.Data.Nat.Order.Recursive using (_<_)
open import Cubical.Data.Bool using (Bool ; false ; true ; false≢true)
open import Cubical.Data.List using ([] ; _∷_)
open import Cubical.Data.Vec.Base using (Vec ; [] ; _∷_)
open import Cubical.Relation.Nullary using (¬_)

open import NaturalMachine.PolynomialRewrite
open import NaturalMachine.FiniteIndraWeave using (TotalView)
open import NaturalMachine.ProductiveIndraNet using (Net ; observe)
open import NaturalMachine.ReflectionAttachment
  using (BoundaryRetract ; noBoundaryRetract)

data AttachedOp (S : Signature) : ℕ → Type₀ where
  inherited : {n : ℕ} → Signature.Op S n → AttachedOp S n
  filler-op : AttachedOp S 0

attachSignature : Signature → Signature
Signature.Op (attachSignature S) = AttachedOp S

mutual
  embed : {S : Signature} → Term S → Term (attachSignature S)
  embed var = var
  embed (node operation terms) = node (inherited operation) (embedVec terms)

  embedVec : {S : Signature} {n : ℕ}
    → Vec (Term S) n → Vec (Term (attachSignature S)) n
  embedVec [] = []
  embedVec (term ∷ terms) = embed term ∷ embedVec terms

filler : {S : Signature} → Term (attachSignature S)
filler = node filler-op []

isFiller : {S : Signature} → Term (attachSignature S) → Bool
isFiller var = false
isFiller (node (inherited operation) terms) = false
isFiller (node filler-op []) = true

filler-is-new : {S : Signature} → isFiller (filler {S}) ≡ true
filler-is-new = refl

old-is-not-filler : {S : Signature} (term : Term S)
  → isFiller (embed term) ≡ false
old-is-not-filler var = refl
old-is-not-filler (node operation terms) = refl

old-cannot-fill : {S : Signature} (term : Term S)
  → ¬ (embed term ≡ filler)
old-cannot-fill {S} term equality =
  false≢true
    (sym (old-is-not-filler term) ∙ cong isFiller equality ∙ filler-is-new {S})

-- The attachment is generated by the witnessed tear itself.
extendAtTear : {S : Signature}
  → ¬ BoundaryRetract → Term (attachSignature S)
extendAtTear obstruction = filler

tear-generates-filler : {S : Signature} (obstruction : ¬ BoundaryRetract)
  → isFiller (extendAtTear {S} obstruction) ≡ true
tear-generates-filler obstruction = refl

-- Nullary is the least possible polynomial arity, so no smaller constructor
-- can precede the generated attachment.
data Positive : ℕ → Type₀ where
  positive : (n : ℕ) → Positive (suc n)

noArityBelowFiller : (n : ℕ) → n < 0 → Positive n
noArityBelowFiller n ()

------------------------------------------------------------------------
-- Tear → signature extension → rooted/productive replacement.
------------------------------------------------------------------------

oldView : {Root : Type₀} {S : Signature}
  → TotalView Root (Term S) → TotalView Root (Term (attachSignature S))
oldView view root target = embed (view root target)

filledView : {Root : Type₀} {S : Signature}
  → ¬ BoundaryRetract → TotalView Root (Term (attachSignature S))
filledView obstruction root target = extendAtTear obstruction

old-view-cannot-fill : {Root : Type₀} {S : Signature}
  (view : TotalView Root (Term S)) (root target : Root)
  → ¬ (oldView view root target ≡ filler)
old-view-cannot-fill view root target = old-cannot-fill (view root target)

new-view-fills : {Root : Type₀} {S : Signature}
  (obstruction : ¬ BoundaryRetract) (root target : Root)
  → filledView {S = S} obstruction root target ≡ filler
new-view-fills obstruction root target = refl

mutual
  growthNet : {Root : Type₀} {S : Signature}
    → ¬ BoundaryRetract → TotalView Root (Term S)
    → Net Root (Term (attachSignature S))
  Net.view (growthNet obstruction view) = oldView view
  Net.next (growthNet obstruction view) = filledNet obstruction

  filledNet : {Root : Type₀} {S : Signature}
    → ¬ BoundaryRetract → Net Root (Term (attachSignature S))
  Net.view (filledNet obstruction) = filledView obstruction
  Net.next (filledNet obstruction) = filledNet obstruction

boolSeed : TotalView Bool (Term Arithmetic)
boolSeed root target = aVar

attachmentGrowth : Net Bool (Term (attachSignature Arithmetic))
attachmentGrowth = growthNet noBoundaryRetract boolSeed

growth-three : observe 3 attachmentGrowth ≡
  (λ _ _ → embed aVar) ∷
  (λ _ _ → filler) ∷
  (λ _ _ → filler) ∷ []
growth-three = refl

old-control-cannot-fill :
  ¬ (Net.view attachmentGrowth false true ≡ filler)
old-control-cannot-fill = old-cannot-fill aVar

next-control-fills :
  Net.view (Net.next attachmentGrowth) false true ≡ filler
next-control-fills = refl
