{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- NaturalMachine.Prastara_TheGaugeStreamCostsZeroCarriedBitsAndInvisibilityIsWeakerThanGauge
--
-- cf-tessera-j-1, 2026-08-20.  Agda 2.6.3 + cubical v0.5 (not the repo pin).
--
-- WHAT THIS IS.  A proof-carrying incremental certificate over the graph
-- cochain interface of `NaturalMachine.FiniteGraphCohomology`.  A certificate
-- is a triple (cochain, one Bool, a proof the Bool is that cochain's cycle
-- evaluation).  Two update operations are defined and the exact information
-- each must carry is checked:
--
--   `bump`     — update along an ARBITRARY perturbation cochain `d`.  The
--                carried bit changes by `evaluate cyc d`.  The new proof is
--                built from the old proof plus `additive`; the evaluation is
--                never re-run over the whole cochain.
--   `etakStep` — update along a GAUGE (a vertex cochain, acting by endpoint
--                coboundaries).  The carried bit is literally unchanged, the
--                new proof built from the old plus `gaugeInvariant`.
--
-- and then, on an arbitrary-length stream of arbitrary gauges:
--
--   `streamCostsNothing`  — the bit is unchanged after replaying the whole
--                           list, for ANY Vertex and Edge types, including
--                           infinite ones.
--   `replayCochain`       — the whole stream collapses to ONE gauge, the
--                           pointwise xor-sum of the list.
--
-- NAMING (CLAUDE.md file-naming rule).  `prastāra` (प्रस्तार) is Piṅgala's
-- term, *Chandaḥśāstra* c. 300 BCE, for the systematic array of all
-- laghu/guru patterns of a given length, GENERATED BY A RULE rather than
-- listed; Halāyudha's *Mṛtasañjīvanī* (10th c.) states the construction
-- explicitly.  `C⁰ = Vertex → Bool` is exactly such an array over the vertex
-- set, and `replayCochain` is the statement that the array's whole action is
-- recovered from the generating rule without the array being enumerated.
--
-- WHAT IS NOT CLAIMED OF PIṄGALA.  He did not prove anything about graph
-- cochains, gauge invariance, or incremental certificates.  The word names
-- the object — a binary array over a finite index set, taken as generated —
-- and names the method lens under which this module was written.  Nothing
-- more is asserted of the *Chandaḥśāstra*.
--
-- WHAT IS NOT CLAIMED OF CAROLINIAN NAVIGATION.  `etakStep` carries the
-- Puluwatese/Satawalese word *etak*.  In the procedure reported by Thomas
-- Gladwin (*East Is a Big Bird: Navigation and Logic on Puluwat Atoll*,
-- Harvard University Press, 1970, from the navigator Hipour) and by David
-- Lewis (*We, the Navigators*, University Press of Hawaii, 1972), the canoe
-- is held stationary and a REFERENCE ISLAND off to one side of the course,
-- usually below the horizon, is taken to move backwards under the successive
-- named points of the sidereal star compass — 32 points, one for each rising
-- and setting of a named star, each point called *paafu* in Satawalese; the
-- passage is divided into etak segments and the running count of segments is
-- the position.  Gladwin's account is from the navigator Hipour, of the
-- Weriyeng school on Puluwat.  Two features
-- of that procedure, and only these two, are being pointed at:
--   (i) the count is UPDATED ON AN EVENT and never recomputed from the
--       departure point — which is the frontier question this module is
--       about, incremental certificates that update rather than recompute;
--   (ii) the reference is a DECLARED CHOICE, so a readout taken against one
--       reference has a blind direction — which is §4 below, and is why
--       Carolinian practice is not etak alone but etak plus independent cues
--       (swell interference, bird flight at dawn and dusk, the expanded
--       landfall screen; Lewis 1972).
-- No claim is made that any navigator stated a theorem, that etak is
-- gauge theory, or that this module formalises the practice.  SOURCING
-- GRADE: I opened neither book in this container.  The following were
-- confirmed against search metadata rather than from memory alone — Gladwin
-- 1970, Harvard University Press, from Hipour of the Weriyeng school on
-- Puluwat; Lewis 1972, University Press of Hawaii; the 32-point compass;
-- *paafu* as the Satawalese name of a compass point; the reference island
-- off to one side of the course and usually below the horizon, moving
-- backwards through the points.  Everything else is CITED, not read.
-- Ben Finney's 1976
-- Hōkūleʻa voyage from Hawaiʻi to Tahiti, navigated by Mau Piailug of
-- Satawal, is cited only as the event that put the practice on record
-- outside the Carolines; nothing in this file depends on it.
--
-- THE TWO METHOD LENSES, AND WHICH ONE THE CHECK SUPPORTS.
--   Ashby (requisite variety): a regulator must carry at least as much
--     variety as the disturbance it absorbs.  The gauge stream has variety
--     2^|V| per step and is unbounded in length, so the certificate should
--     need unbounded carried state.
--   Piṅgala (prastāra): generate the whole space by its recursive rule
--     before counting anything in it.  Then the invariant is checked once
--     against the rule and no cardinality enters.
--   These give different numbers for the same quantity: |V| bits per step
--   versus 0.  `streamCostsNothing` is the check, and it says 0 — uniformly
--   in the length of the stream and in the cardinality of Vertex.  Piṅgala
--   wins.  §3 marks exactly where Ashby's bound is instead tight: for a
--   general perturbation the bit really does flip and is not compressible.
--   The correction Ashby's law needs here is stated in §3's comment: the
--   price is the image of the disturbance set under the evaluation, not its
--   cardinality, and the coboundaries have trivial image however many of
--   them there are.
------------------------------------------------------------------------

module NaturalMachine.Prastara_TheGaugeStreamCostsZeroCarriedBitsAndInvisibilityIsWeakerThanGauge where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Bool
  using (Bool ; true ; false ; _⊕_ ; ⊕-comm ; ⊕-assoc ; ⊕-identityʳ
        ; true≢false ; false≢true)
open import Cubical.Data.Unit using (Unit ; tt)
open import Cubical.Data.Sigma using (Σ-syntax ; _,_ ; _×_)
open import Cubical.Data.List using (List ; [] ; _∷_)
open import Cubical.Relation.Nullary using (¬_)

open import NaturalMachine.FiniteGraphCohomology using (module Graph)

------------------------------------------------------------------------
-- §0.  Two facts about xor, so §1 and §2 are arithmetic-free.
------------------------------------------------------------------------

⊕-self : (b : Bool) → b ⊕ b ≡ false
⊕-self false = refl
⊕-self true  = refl

-- The middle-four interchange.  Used twice: to make δ⁰ a homomorphism, and
-- to make the concrete cycle evaluation of §3 additive.
xor4 : (a b c d : Bool) → (a ⊕ b) ⊕ (c ⊕ d) ≡ (a ⊕ c) ⊕ (b ⊕ d)
xor4 a b c d =
  sym (⊕-assoc a b (c ⊕ d))
  ∙ cong (a ⊕_)
      (⊕-assoc b c d ∙ cong (_⊕ d) (⊕-comm b c) ∙ sym (⊕-assoc c b d))
  ∙ ⊕-assoc a c (b ⊕ d)

-- A flipped bit is not the bit.  This is the whole of §3's negative content.
⊕true-≢ : (b : Bool) → ¬ (b ⊕ true ≡ b)
⊕true-≢ false = true≢false
⊕true-≢ true  = false≢true

------------------------------------------------------------------------
-- §1.  The certificate and its two updates.
------------------------------------------------------------------------

module Certificate
  (Vertex Edge : Type₀)
  (source target : Edge → Vertex)
  where

  open Graph Vertex Edge source target public

  -- The gauge group, as an explicit abelian group on C⁰, and the group
  -- structure on C¹ that `_+¹_` already carries.  These are the "recursive
  -- rule" the prastāra lens asks for: the whole 2^|V| array is the closure of
  -- `zero⁰` under `_+⁰_`, and nothing below counts its elements.
  zero⁰ : C⁰
  zero⁰ _ = false

  _+⁰_ : C⁰ → C⁰ → C⁰
  (g +⁰ h) v = g v ⊕ h v

  zero¹ : C¹
  zero¹ _ = false

  +¹-assoc : (x y z : C¹) → (x +¹ y) +¹ z ≡ x +¹ (y +¹ z)
  +¹-assoc x y z = funExt (λ e → sym (⊕-assoc (x e) (y e) (z e)))

  +¹-idʳ : (x : C¹) → x +¹ zero¹ ≡ x
  +¹-idʳ x = funExt (λ e → ⊕-identityʳ (x e))

  δ⁰-zero : δ⁰ zero⁰ ≡ zero¹
  δ⁰-zero = funExt (λ _ → refl)

  δ⁰-hom : (g h : C⁰) → δ⁰ (g +⁰ h) ≡ (δ⁰ g +¹ δ⁰ h)
  δ⁰-hom g h =
    funExt (λ e → xor4 (g (source e)) (h (source e))
                       (g (target e)) (h (target e)))

  -- A proof-carrying certificate: a cochain, ONE Bool, and the proof.
  record Cert (cyc : CycleEvaluation) : Type₀ where
    constructor cert
    field
      cochain : C¹
      bit     : Bool
      sound   : bit ≡ evaluate cyc cochain

  open Cert public

  -- Non-vacuity: certificates exist for every cochain.  Without this the
  -- universally quantified statements below would be satisfiable by an
  -- empty type of certificates.
  initial : (cyc : CycleEvaluation) → C¹ → Cert cyc
  initial cyc x = cert x (evaluate cyc x) refl

  -- UPDATE 1: an arbitrary perturbation.  The new proof is the old proof
  -- composed with one use of `additive`.  `evaluate cyc` is applied to the
  -- perturbation only, never to the updated cochain.
  bump : (cyc : CycleEvaluation) → Cert cyc → C¹ → Cert cyc
  bump cyc c d =
    cert (cochain c +¹ d) (bit c ⊕ evaluate cyc d)
      (cong (_⊕ evaluate cyc d) (sound c)
       ∙ sym (additive cyc (cochain c) d))

  -- UPDATE 2: a gauge.  The bit is not recomputed and not changed; the new
  -- proof is the old proof composed with one use of `gaugeInvariant`.
  etakStep : (cyc : CycleEvaluation) → Cert cyc → C⁰ → Cert cyc
  etakStep cyc c g =
    cert (gaugeTranslate (cochain c) g) (bit c)
      (sound c ∙ sym (gaugeInvariant cyc (cochain c) g))

  -- The two updates agree on the cochain when the perturbation is a
  -- coboundary: `etakStep` is not a different move, it is the same move at a
  -- lower price.
  etakStepIsABump : (cyc : CycleEvaluation) (c : Cert cyc) (g : C⁰)
    → cochain (etakStep cyc c g) ≡ cochain (bump cyc c (δ⁰ g))
  etakStepIsABump cyc c g = refl

  -- ...and the price is zero.  A gauge move charges the certificate nothing.
  gaugeCostsNothing : (cyc : CycleEvaluation) (c : Cert cyc) (g : C⁰)
    → bit (bump cyc c (δ⁰ g)) ≡ bit c
  gaugeCostsNothing cyc c g =
    cong (bit c ⊕_) (closed cyc g) ∙ ⊕-identityʳ (bit c)

------------------------------------------------------------------------
-- §2.  The stream.  This is the lens split, checked.
------------------------------------------------------------------------

  sumGauge : List C⁰ → C⁰
  sumGauge []       = zero⁰
  sumGauge (g ∷ gs) = g +⁰ sumGauge gs

  replay : (cyc : CycleEvaluation) → Cert cyc → List C⁰ → Cert cyc
  replay cyc c []       = c
  replay cyc c (g ∷ gs) = replay cyc (etakStep cyc c g) gs

  -- ASHBY predicts unbounded carried state: the disturbance set at each step
  -- is all of C⁰, of variety 2^|V|, and the stream is arbitrarily long.
  -- PIṄGALA predicts zero: the array is generated by a rule, the invariant is
  -- checked against the rule, and no cardinality is ever formed.
  -- The check says zero, uniformly in the length of `gs` AND in Vertex —
  -- Vertex is an arbitrary Type₀ here and may be infinite.
  streamCostsNothing : (cyc : CycleEvaluation) (c : Cert cyc) (gs : List C⁰)
    → bit (replay cyc c gs) ≡ bit c
  streamCostsNothing cyc c []       = refl
  streamCostsNothing cyc c (g ∷ gs) = streamCostsNothing cyc (etakStep cyc c g) gs

  -- The prastāra statement proper: the stream is ONE element of the array.
  -- Replaying a list of gauges lands on the same cochain as a single gauge,
  -- the pointwise xor-sum.  Nothing is enumerated to prove it.
  replayCochain : (cyc : CycleEvaluation) (c : Cert cyc) (gs : List C⁰)
    → cochain (replay cyc c gs) ≡ cochain c +¹ δ⁰ (sumGauge gs)
  replayCochain cyc c [] =
    sym (cong (cochain c +¹_) δ⁰-zero ∙ +¹-idʳ (cochain c))
  replayCochain cyc c (g ∷ gs) =
    replayCochain cyc (etakStep cyc c g) gs
    ∙ +¹-assoc (cochain c) (δ⁰ g) (δ⁰ (sumGauge gs))
    ∙ cong (cochain c +¹_) (sym (δ⁰-hom g (sumGauge gs)))

  -- Consequence, and the reason "update rather than recompute" is sound here:
  -- a stream of gauge moves is indistinguishable from the single move that
  -- summarises it, in both components at once.
  replayIsOneStep : (cyc : CycleEvaluation) (c : Cert cyc) (gs : List C⁰)
    → (cochain (replay cyc c gs) ≡ cochain (etakStep cyc c (sumGauge gs)))
    × (bit (replay cyc c gs) ≡ bit (etakStep cyc c (sumGauge gs)))
  replayIsOneStep cyc c gs =
    replayCochain cyc c gs , streamCostsNothing cyc c gs

------------------------------------------------------------------------
-- §3.  Where Ashby's bound is tight, and §4, where my own claim died.
--
-- A two-edge loop at a single vertex.  Vertex = Unit, Edge = Bool, both
-- endpoints of both edges are the vertex.  Then every coboundary is zero:
-- δ⁰ g e = g tt ⊕ g tt = false.  So the gauge group acts TRIVIALLY here,
-- which makes this the sharpest possible test of the §4 claim — the
-- coboundary subgroup is as small as it can be, and the kernel of the
-- certificate is still strictly bigger.
------------------------------------------------------------------------

module Loop where

  open Certificate Unit Bool (λ _ → tt) (λ _ → tt) public

  -- Reference 1: the sum over both edges.
  cyc₁ : CycleEvaluation
  cyc₁ = record
    { evaluate = λ x → x true ⊕ x false
    ; additive = λ x y → xor4 (x true) (y true) (x false) (y false)
    ; closed   = λ g → cong (_⊕ (g tt ⊕ g tt)) (⊕-self (g tt))
                       ∙ ⊕-self (g tt)
    }

  -- Reference 2: one edge only.  A genuinely different additive functional
  -- killing every coboundary — an independent cue, in the sense of §4.
  cyc₂ : CycleEvaluation
  cyc₂ = record
    { evaluate = λ x → x true
    ; additive = λ x y → refl
    ; closed   = λ g → ⊕-self (g tt)
    }

  -- A perturbation the first reference SEES.
  d₁ : C¹
  d₁ e = e

  -- ASHBY, vindicated on this half: for a general perturbation the update
  -- must carry a bit, and that bit is not compressible to nothing.
  --
  -- The correction Ashby's law needs is visible by comparing this with
  -- `gaugeCostsNothing`: the certificate does not pay for the CARDINALITY of
  -- the disturbance set — the coboundary subgroup may be arbitrarily large
  -- and costs 0 — it pays for the IMAGE of that set under `evaluate cyc`.
  -- Variety of the disturbance is the wrong measure; rank of the induced map
  -- is the right one.
  d₁-costs-a-bit : (c : Cert cyc₁) → ¬ (bit (bump cyc₁ c d₁) ≡ bit c)
  d₁-costs-a-bit c = ⊕true-≢ (bit c)

------------------------------------------------------------------------
-- §4.  THE REFUTATION.  My own claim, stated and killed.
--
-- CLAIMED, on the strength of §1's `gaugeCostsNothing` and §2's
-- `streamCostsNothing`: that the carried bit is a COMPLETE incremental
-- invariant for the gauge action — that an update leaving the bit unchanged
-- at every state is a gauge move, so the certificate could be used as a
-- decision procedure for "was this update pure gauge?".  That would have
-- given `collab/messages/2141-cf-tessera-g-0-...` the gauge-artifact detector
-- its §5 wants, at one bit per step.
--
-- IT IS FALSE.  `d₀` below is invisible to `cyc₁` at EVERY state, and is not
-- a coboundary — on this graph the only coboundary is zero, and d₀ is not
-- zero.  The certificate is sound and not complete: it detects visibility,
-- not gauge.  The kernel of one additive closed functional is strictly
-- larger than the coboundary subgroup, and no amount of stream replay
-- narrows it.
--
-- This is the point (ii) the navigation material was pointed at and is the
-- only place it does work here: a readout taken against ONE declared
-- reference has a blind direction, which is why the practice reported by
-- Gladwin (1970) and Lewis (1972) is etak together with independent cues and
-- not etak alone.  `d₀-visible-to-cyc₂` is that second cue, checked: the
-- perturbation the first reference cannot see, a second reference separates.
------------------------------------------------------------------------

  -- Flip both edges.
  d₀ : C¹
  d₀ _ = true

  d₀-invisible-to-cyc₁ : (c : Cert cyc₁) → bit (bump cyc₁ c d₀) ≡ bit c
  d₀-invisible-to-cyc₁ c = ⊕-identityʳ (bit c)

  -- `Edge` here is `Bool`: the module parameter is not exported by `open`,
  -- so the instance's own name for the edge type is written out.
  d₀-is-not-a-gauge : ¬ (Σ[ g ∈ C⁰ ] ((e : Bool) → δ⁰ g e ≡ d₀ e))
  d₀-is-not-a-gauge (g , p) = false≢true (sym (⊕-self (g tt)) ∙ p true)

  d₀-visible-to-cyc₂ : (c : Cert cyc₂) → ¬ (bit (bump cyc₂ c d₀) ≡ bit c)
  d₀-visible-to-cyc₂ c = ⊕true-≢ (bit c)

------------------------------------------------------------------------
-- Rigor boundary.
--
-- Checked, generically in Vertex and Edge (both arbitrary Type₀, possibly
-- infinite): a proof-carrying certificate for a cycle evaluation; an
-- arbitrary-perturbation update whose cost is exactly `evaluate cyc d`; a
-- gauge update whose cost is exactly zero; that an arbitrary-length stream of
-- arbitrary gauges leaves the carried bit fixed; and that such a stream
-- collapses to one gauge, the pointwise xor-sum.
--
-- Checked on one concrete graph (the two-edge loop at a point): that a
-- general perturbation really does flip the bit, and that a perturbation
-- invisible to one cycle evaluation at every state need not be a coboundary,
-- while a second evaluation sees it.
--
-- NOT claimed: that the certificate decides gauge-equivalence (§4 refutes
-- exactly this); anything about the quotient H¹ of
-- `FiniteGraphCohomology`, whose set-quotient effectivity is untouched here;
-- any lower bound on carried state for a family of evaluations rather than
-- one; any statement about the cost of updates to the GRAPH itself (adding
-- or deleting edges), which is the real incremental-computation question and
-- is not addressed; and, as above, anything whatever about what Carolinian
-- navigators or Piṅgala proved.
------------------------------------------------------------------------
