{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- Residue observations are capabilities above the atomic ℕ core.
--
-- This file deliberately contains no second arithmetic engine.  Any already
-- established residue/CRT observation is just a map out of ℕ.  Compilation
-- along the existing ℕ ≃ CanWord chart makes it executable on generated digit
-- words; replay reduces to the already-proved odometer round trip.
------------------------------------------------------------------------

open import Cubical.Data.Nat using (ℕ)

module NaturalMachine.ResidueTransport (k : ℕ) where

open import Cubical.Foundations.Prelude
open import NaturalMachine.Digits k

private
  variable
    ℓ : Level
    A : Type ℓ

-- A residue system, CRT decoder, divisibility sensor, or any other established
-- arithmetic observation enters through exactly this minimal interface.
Observation : Type ℓ → Type ℓ
Observation A = ℕ → A

-- Compile the capability to the canonical-word presentation.  There is no
-- privileged steward: decoding the word is the inverse map already carried by
-- ℕ ≃ CanWord.
compile : Observation A → CanWord → A
compile observe word = observe (valueC word)

-- Every input generated by zero/successor replays the original observation.
-- The only proof consumed is `value-digits`, established by Nat recursion over
-- the schoolbook odometer.
compile-generated : (observe : Observation A) (n : ℕ)
                  → compile observe (digitsC n) ≡ observe n
compile-generated observe n = cong observe (value-digits n)

-- Compilation is injective: the atomic zero/successor chart loses no
-- established capability.
compile-injective : (left right : Observation A)
                  → compile left ≡ compile right
                  → left ≡ right
compile-injective left right same = funExt λ n →
    sym (compile-generated left n)
  ∙ funExt⁻ same (digitsC n)
  ∙ compile-generated right n

------------------------------------------------------------------------
-- Cost boundary
--
-- A one-tick atomic clock says nothing about the size of the compiled state,
-- the depth of its distinguishing witness, or the work needed to update and
-- decode it.  Existing exact bounds enter as data and remain visible after
-- transport; this module does not manufacture or erase them.
------------------------------------------------------------------------

record CostedObservation (A : Type ℓ) : Type ℓ where
  field
    observe      : Observation A
    stateSize    : ℕ
    witnessDepth : ℕ
    updateCost   : ℕ
    decodeCost   : ℕ

open CostedObservation public

record CompiledObservation (A : Type ℓ) : Type ℓ where
  field
    onWord       : CanWord → A
    stateSize    : ℕ
    witnessDepth : ℕ
    updateCost   : ℕ
    decodeCost   : ℕ

compileCosted : CostedObservation A → CompiledObservation A
compileCosted source = record
  { onWord       = compile (observe source)
  ; stateSize    = stateSize source
  ; witnessDepth = witnessDepth source
  ; updateCost   = updateCost source
  ; decodeCost   = decodeCost source
  }

-- Transport preserves the declared complexity profile; atomic counted time
-- does not collapse any component to one or zero.
complexity-preserved : (source : CostedObservation A)
  → CompiledObservation.stateSize (compileCosted source) ≡ stateSize source
  × CompiledObservation.witnessDepth (compileCosted source) ≡ witnessDepth source
  × CompiledObservation.updateCost (compileCosted source) ≡ updateCost source
  × CompiledObservation.decodeCost (compileCosted source) ≡ decodeCost source
complexity-preserved source = refl , refl , refl , refl
