{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- NaturalMachine.SemanticCrystal
--
-- A small common self-improvement object: execution and its measured defect,
-- a two-sided finite nucleus interface, an interaction-relative quantum
-- presentation, and a language generated from those exact observations.
------------------------------------------------------------------------

module NaturalMachine.SemanticCrystal where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Bool using (Bool ; true ; false)
open import Cubical.Data.Nat using (ℕ)
open import Cubical.Data.Int using (ℤ)
open import Cubical.Data.Sigma using (_×_ ; _,_)
open import Cubical.Data.Unit using (Unit ; tt)
open import Cubical.Data.Empty using (⊥)
open import Cubical.Relation.Nullary using (¬_)

import NaturalMachine.DSONucleusExecutionCalibration as Execution
import NaturalMachine.DSONucleusMiddleProduct as Nucleus
import NaturalMachine.ExactTwoStateAmplitudes as Amplitude
import NaturalMachine.ExactProjectivePhase as Projective
import NaturalMachine.ExactProjectiveCircuits as Circuit

data Architecture : Type₀ where
  amplitudeChart projectiveChart : Architecture

Carrier : Architecture → Type₀
Carrier amplitudeChart = Amplitude.State₂
Carrier projectiveChart = Projective.ProjectiveState₂

NuclearInterface : Type₀
NuclearInterface = Nucleus.Generator × Nucleus.Generator

-- The language is generated by the mathematical content, rather than being a
-- string log.  Each constructor retains the data needed to recompute its claim.
data DerivedStatement (architecture : Architecture) : Type₀ where
  executionDefect : (x y : Execution.Cell) → DerivedStatement architecture
  nucleusComparison : NuclearInterface → DerivedStatement architecture
  observedWeights : Carrier architecture → DerivedStatement architecture

record SemanticCrystal (architecture : Architecture) : Type₁ where
  field
    executionInput executionContinuation : Execution.Cell
    leftMode rightMode : Nucleus.Generator
    physicalState : Carrier architecture
    generated : DerivedStatement architecture

open SemanticCrystal public

measuredDefect : {architecture : Architecture}
  → SemanticCrystal architecture → ℤ
measuredDefect crystal =
  Execution.M (executionInput crystal) (executionContinuation crystal)

interface : {architecture : Architecture}
  → SemanticCrystal architecture → NuclearInterface
interface crystal = leftMode crystal , rightMode crystal

DeclaredObservation : Type₀
DeclaredObservation = ℕ × ℕ

observe : (architecture : Architecture) → Carrier architecture → DeclaredObservation
observe amplitudeChart state = Circuit.projectiveWeights (Projective.project state)
observe projectiveChart state = Circuit.projectiveWeights state

------------------------------------------------------------------------
-- One certified architecture rewrite
------------------------------------------------------------------------

rewriteCarrier : Carrier amplitudeChart → Carrier projectiveChart
rewriteCarrier = Projective.project

rewriteStatement : DerivedStatement amplitudeChart → DerivedStatement projectiveChart
rewriteStatement (executionDefect x y) = executionDefect x y
rewriteStatement (nucleusComparison modes) = nucleusComparison modes
rewriteStatement (observedWeights state) = observedWeights (rewriteCarrier state)

rewriteCrystal : SemanticCrystal amplitudeChart → SemanticCrystal projectiveChart
rewriteCrystal crystal .executionInput = executionInput crystal
rewriteCrystal crystal .executionContinuation = executionContinuation crystal
rewriteCrystal crystal .leftMode = leftMode crystal
rewriteCrystal crystal .rightMode = rightMode crystal
rewriteCrystal crystal .physicalState = rewriteCarrier (physicalState crystal)
rewriteCrystal crystal .generated = rewriteStatement (generated crystal)

rewrite-preserves-defect : (crystal : SemanticCrystal amplitudeChart)
  → measuredDefect (rewriteCrystal crystal) ≡ measuredDefect crystal
rewrite-preserves-defect crystal = refl

rewrite-preserves-nucleus : (crystal : SemanticCrystal amplitudeChart)
  → interface (rewriteCrystal crystal) ≡ interface crystal
rewrite-preserves-nucleus crystal = refl

rewrite-preserves-observation : (crystal : SemanticCrystal amplitudeChart)
  → observe projectiveChart (physicalState (rewriteCrystal crystal))
    ≡ observe amplitudeChart (physicalState crystal)
rewrite-preserves-observation crystal = refl

-- The interface really changes: the architecture indices are distinct even
-- though the declared observation commutes with the rewrite.
amplitude≢projective : ¬ (amplitudeChart ≡ projectiveChart)
amplitude≢projective path = subst distinguish path tt
  where
  distinguish : Architecture → Type₀
  distinguish amplitudeChart = Unit
  distinguish projectiveChart = ⊥

record CertifiedRewrite : Type₁ where
  field
    transform : SemanticCrystal amplitudeChart → SemanticCrystal projectiveChart
    preservesDefect : (crystal : SemanticCrystal amplitudeChart)
      → measuredDefect (transform crystal) ≡ measuredDefect crystal
    preservesNucleus : (crystal : SemanticCrystal amplitudeChart)
      → interface (transform crystal) ≡ interface crystal
    preservesObservation : (crystal : SemanticCrystal amplitudeChart)
      → observe projectiveChart (physicalState (transform crystal))
        ≡ observe amplitudeChart (physicalState crystal)

projectivizingRewrite : CertifiedRewrite
projectivizingRewrite .CertifiedRewrite.transform = rewriteCrystal
projectivizingRewrite .CertifiedRewrite.preservesDefect = rewrite-preserves-defect
projectivizingRewrite .CertifiedRewrite.preservesNucleus = rewrite-preserves-nucleus
projectivizingRewrite .CertifiedRewrite.preservesObservation =
  rewrite-preserves-observation

------------------------------------------------------------------------
-- Boundary: this is a finite common kernel.  It does not claim autonomous
-- theorem invention, a universal optimizer, a full quantum computer, or that
-- projectivization preserves observations not listed in CertifiedRewrite.
------------------------------------------------------------------------
