{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}

module ADiagonalSentenceIndependentInAConcreteTheory where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Bool using (Bool ; true ; false ; not ; false‚â¢true)
open import Cubical.Data.Empty as Empty using (‚ä•)
open import Cubical.Data.Sigma using (_√ó_ ; _,_ ; fst ; snd)
open import Cubical.Relation.Nullary using (¬¨_)
open import GodelSeparation using (Theory ; Sent ; Pf ; neg ; prov ; Consistent)
open import IndependenceNeedsAnInternalImplication using (Independent)
open import ASmallTheoryWithAnIndependentSentence
  using (impB ; impB-refl ; impB-mp)

------------------------------------------------------------------------
-- ADiagonalSentenceIndependentInAConcreteTheory
--
-- Both conjuncts, for a diagonal sentence, in a concrete theory.
--
-- ‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î
-- THE SYNTAX AND THE RULES
--
-- Sentences: a constant `gs`, negation, implication, and `pv` for the
-- provability operator.  Derivability is generated by five rules:
-- `taut`, `mp`, `hbl` (from `a` infer `pv a`), and the two halves of
-- the diagonal at `¬ pv`:
--
--     dfwd : Der (im gs (ng (pv gs)))
--     dbwd : Der (im (ng (pv gs)) gs)
--
-- Nothing is read off a valuation; `Der` is a `data` declaration.
--
-- ‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î
-- WHAT IS PROVED
--
--   ¬ß3  FIRST CONJUNCT, from a TRUTH-FUNCTIONAL model: interpret `pv`
--       as constantly `true` and `gs` as `false`.  All five rules are
--       sound, so `¬ Der gs`.
--
--       `ATruthFunctionalProvabilityFalsifiesTheDiagonalSentence` proved
--       that any truth-functional model must make `gs` false.  Here
--       that is not an obstruction, it is the construction: the forced
--       value is exactly the one that yields the first conjunct.
--
--   ¬ß4  SECOND CONJUNCT, from a SYNTAX-INDEXED model: interpret `pv a`
--       as `P a`, where `P gs = false` and `P` is `true` elsewhere, and
--       `gs` as `true`.  Soundness of `hbl` needs `Der a ‚í P a ‚â° true`,
--       which at `a = gs` is ¬ß3.  So `¬ Der (ng gs)`.
--
--       `TheRefutingModelAlreadyGivesTheFirstConjunct` proved that any
--       such model contains the first conjunct.  Here that is not an
--       obstruction either: the first conjunct is already in hand from
--       ¬ß3, and the second model consumes it.  What that theorem
--       forbids is obtaining the first conjunct FROM such a model, and
--       nothing below does.
--
--   ¬ß5  so `gs` is independent, and the theory is consistent.
--
-- Two models, two different kinds, in the order the two obstructions
-- dictate.  Neither could have done both.
--
-- ‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î
-- THE HONEST LIMIT, WHICH IS LARGE
--
-- This is NOT Gdel's first incompleteness theorem.
--
--   * `hbl` is a RULE of this calculus, not the derivability condition
--     HBL1 proved about a real provability predicate;
--   * `pv` is an uninterpreted operator; `P` is chosen by hand, and the
--     choice is permitted precisely because nothing forces `P` to track
--     derivability;
--   * œâ-consistency is never mentioned and is not needed, because the
--     calculus is far too weak to run the argument that needs it ‚î
--     there is no contraposition, no double-negation elimination, no
--     transitivity, and ¬ß4 does not use `dbwd` beyond soundness;
--   * `gs` is independent partly because the rules are few.  A stronger
--     rule set may well derive `ng gs`, and nothing here says otherwise.
--
-- What IS established: a diagonal pair and an HBL-shaped rule can
-- coexist with independence of the diagonal sentence in this lane, and
-- the two model kinds must be used in a specific order.
------------------------------------------------------------------------

------------------------------------------------------------------------
-- 1.  Syntax
------------------------------------------------------------------------

data S : Type‚ÇÄ where
  gs : S
  ng : S ‚Üí S
  im : S ‚Üí S ‚Üí S
  pv : S ‚Üí S

------------------------------------------------------------------------
-- 2.  Derivability, generated by rules
------------------------------------------------------------------------

data Der : S ‚Üí Type‚ÇÄ where
  taut : (a : S) ‚Üí Der (im a a)
  mp   : (a b : S) ‚Üí Der (im a b) ‚Üí Der a ‚Üí Der b
  hbl  : (a : S) ‚Üí Der a ‚Üí Der (pv a)
  dfwd : Der (im gs (ng (pv gs)))
  dbwd : Der (im (ng (pv gs)) gs)

------------------------------------------------------------------------
-- 3.  First conjunct, by a truth-functional model
--
-- `pv` constantly true, `gs` false.  `dfwd` reads `impB false (not
-- true)` and `dbwd` reads `impB (not true) false`; both are `true`.
------------------------------------------------------------------------

sem‚ÇÅ : S ‚Üí Bool
sem‚ÇÅ gs       = false
sem‚ÇÅ (ng a)   = not (sem‚ÇÅ a)
sem‚ÇÅ (im a b) = impB (sem‚ÇÅ a) (sem‚ÇÅ b)
sem‚ÇÅ (pv a)   = true

sound‚ÇÅ : (s : S) ‚Üí Der s ‚Üí sem‚ÇÅ s ‚â° true
sound‚ÇÅ _ (taut a)       = impB-refl (sem‚ÇÅ a)
sound‚ÇÅ _ (mp a b da db) = impB-mp (sem‚ÇÅ a) (sem‚ÇÅ b) (sound‚ÇÅ (im a b) da) (sound‚ÇÅ a db)
sound‚ÇÅ _ (hbl a _)      = refl
sound‚ÇÅ _ dfwd           = refl
sound‚ÇÅ _ dbwd           = refl

gsUnderivable : ¬¨ Der gs
gsUnderivable d = false‚â¢true (sound‚ÇÅ gs d)

------------------------------------------------------------------------
-- 4.  Second conjunct, by a syntax-indexed model
--
-- `P` consults the SYNTAX: it marks everything except `gs`.  Soundness
-- of `hbl` is then exactly ¬ß3 at the one sentence where it could fail.
------------------------------------------------------------------------

P : S ‚Üí Bool
P gs       = false
P (ng a)   = true
P (im a b) = true
P (pv a)   = true

PmarksDerivable : (a : S) ‚Üí Der a ‚Üí P a ‚â° true
PmarksDerivable gs       d = Empty.rec (gsUnderivable d)
PmarksDerivable (ng a)   _ = refl
PmarksDerivable (im a b) _ = refl
PmarksDerivable (pv a)   _ = refl

sem‚ÇÇ : S ‚Üí Bool
sem‚ÇÇ gs       = true
sem‚ÇÇ (ng a)   = not (sem‚ÇÇ a)
sem‚ÇÇ (im a b) = impB (sem‚ÇÇ a) (sem‚ÇÇ b)
sem‚ÇÇ (pv a)   = P a

sound‚ÇÇ : (s : S) ‚Üí Der s ‚Üí sem‚ÇÇ s ‚â° true
sound‚ÇÇ _ (taut a)       = impB-refl (sem‚ÇÇ a)
sound‚ÇÇ _ (mp a b da db) = impB-mp (sem‚ÇÇ a) (sem‚ÇÇ b) (sound‚ÇÇ (im a b) da) (sound‚ÇÇ a db)
sound‚ÇÇ _ (hbl a d)      = PmarksDerivable a d
sound‚ÇÇ _ dfwd           = refl
sound‚ÇÇ _ dbwd           = refl

negGsUnderivable : ¬¨ Der (ng gs)
negGsUnderivable d = false‚â¢true (sound‚ÇÇ (ng gs) d)

------------------------------------------------------------------------
-- 5.  So the diagonal sentence is independent, and the theory is
--     consistent
------------------------------------------------------------------------

Th : Theory ‚Ñì-zero
Sent Th = S
Pf   Th = Der
neg  Th = ng
prov Th = pv

gsIndependent : Independent Th gs
gsIndependent = gsUnderivable , negGsUnderivable

consistent : Consistent Th
consistent s ds dns =
  false‚â¢true (sym (cong not (sound‚ÇÅ s ds)) ‚àô sound‚ÇÅ (ng s) dns)
