{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}

module ASmallTheoryWithAnIndependentSentence where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Bool using (Bool ; true ; false ; not ; falseâ‰¢true)
open import Cubical.Data.Empty as Empty using (âŠ¥)
open import Cubical.Data.Sigma using (_Ã—_ ; _,_ ; fst ; snd)
open import Cubical.Relation.Nullary using (Â¬_)
open import GodelSeparation using (Theory ; Sent ; Pf ; neg ; prov ; Consistent)
open import IndependenceNeedsAnInternalImplication using (Independent)
open import NegationCompletenessForbidsIndependence
  using (NegationComplete ; independenceFromTwoModels)

------------------------------------------------------------------------
-- ASmallTheoryWithAnIndependentSentence
--
-- The criterion of the previous module, instantiated â” so it is not
-- vacuous, and so the lane is shown to contain a theory with an
-- independent sentence at all.
--
-- â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”
-- WHAT WAS REQUIRED, AND WHY EVERY EARLIER MODEL FAILED IT
--
-- Two obstructions accumulated in this thread.  A theory admitting an
-- independent sentence must not be negation-complete, and must not have
-- a provability-determined implication.  Every model built here before
-- this one read provability off a single two-valued assignment, which
-- forces both.
--
-- The repair is the one the criterion names: `Pf` GENERATED BY RULES,
-- and soundness for a CLASS of valuations rather than truth in one.
--
-- â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”
-- WHAT IS BUILT
--
--   Â§1  sentences as a free inductive type â” one atom, negation,
--       implication.  Nothing is a truth-table here: `S` is a syntax.
--
--   Â§2  `Der` inductively generated by two rules: every `a â’ a` is
--       derivable, and modus ponens.  This is deliberately the smallest
--       rule set that is closed under `mp` and proves something.
--
--   Â§3  soundness for EVERY Boolean valuation of the atom, by induction
--       on the derivation.  Two lemmas about `impB`, three lines.
--
--   Â§4  so the atom is INDEPENDENT: it fails in the valuation sending
--       it to `false`, its negation fails in the valuation sending it
--       to `true`, and `independenceFromTwoModels` finishes.  The
--       theory is also consistent, and Â§5 witnesses both accumulated
--       obstructions failing here: it is not negation-complete, and its
--       implication is not provability-determined â” `Der atom â’ Der (ng
--       atom)` holds vacuously while `im atom (ng atom)` is refuted by
--       soundness at the valuation sending the atom to `true`.
--
-- â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”
-- What this settles: the criterion
-- has an instance, the two accumulated obstructions are not jointly
-- exhaustive of the lane, and a theory in this lane can have an
-- independent sentence.
--
-- PRIOR ART, by the conclusion type: a grep of `formal/cubical` for
-- `Independent` finds this thread only; for an inductively generated
-- provability relation over a syntax, nothing.  A version phrased with
-- a list-of-axioms closure operator rather than a `data` declaration
-- would evade that grep.
------------------------------------------------------------------------

------------------------------------------------------------------------
-- 1.  Syntax
------------------------------------------------------------------------

data S : Typeâ‚€ where
  atom : S
  ng   : S â†’ S
  im   : S â†’ S â†’ S

------------------------------------------------------------------------
-- 2.  Derivability, generated by rules
------------------------------------------------------------------------

data Der : S â†’ Typeâ‚€ where
  taut : (a : S) â†’ Der (im a a)
  mp   : (a b : S) â†’ Der (im a b) â†’ Der a â†’ Der b

------------------------------------------------------------------------
-- 3.  Soundness, for every valuation of the atom
------------------------------------------------------------------------

impB : Bool â†’ Bool â†’ Bool
impB false _ = true
impB true  b = b

impB-refl : (x : Bool) â†’ impB x x â‰¡ true
impB-refl false = refl
impB-refl true  = refl

impB-mp : (x y : Bool) â†’ impB x y â‰¡ true â†’ x â‰¡ true â†’ y â‰¡ true
impB-mp false y _ p = Empty.rec (falseâ‰¢true p)
impB-mp true  y q _ = q

val : Bool â†’ S â†’ Bool
val v atom     = v
val v (ng a)   = not (val v a)
val v (im a b) = impB (val v a) (val v b)

sound : (v : Bool) (s : S) â†’ Der s â†’ val v s â‰¡ true
sound v _ (taut a)       = impB-refl (val v a)
sound v _ (mp a b da db) =
  impB-mp (val v a) (val v b) (sound v (im a b) da) (sound v a db)

------------------------------------------------------------------------
-- 4.  The theory, and the independent sentence
------------------------------------------------------------------------

Th : Theory â„“-zero
Sent Th = S
Pf   Th = Der
neg  Th = ng
prov Th = Î» s â†’ s

atomFails : Â¬ (val false atom â‰¡ true)
atomFails = falseâ‰¢true

negAtomFails : Â¬ (val true (ng atom) â‰¡ true)
negAtomFails = falseâ‰¢true

atomIsIndependent : Independent Th atom
atomIsIndependent =
  independenceFromTwoModels Th Bool (Î» v s â†’ val v s â‰¡ true) sound
    atom false true atomFails negAtomFails

-- consistency: a sentence and its negation cannot both be derivable,
-- since soundness at any valuation would make a Bool equal to its own
-- negation.
consistent : Consistent Th
consistent s ds dns =
  falseâ‰¢true (sym (cong not (sound false s ds)) âˆ™ sound false (ng s) dns)

------------------------------------------------------------------------
-- 5.  The two obstructions, witnessed as failing here
------------------------------------------------------------------------

notNegationComplete : Â¬ NegationComplete Th
notNegationComplete comp =
  snd atomIsIndependent (comp atom (fst atomIsIndependent))

-- and the implication is not provability-determined: `Der atom â’ Der
-- (ng atom)` holds vacuously, while `im atom (ng atom)` is refuted by
-- soundness at the valuation sending the atom to `true`.
notProvabilityDetermined :
  Â¬ ((a b : S) â†’ (Der a â†’ Der b) â†’ Der (im a b))
notProvabilityDetermined r =
  falseâ‰¢true
    (sound true (im atom (ng atom))
      (r atom (ng atom) (Î» d â†’ Empty.rec (fst atomIsIndependent d))))
