{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}

module NegationCompletenessForbidsIndependence where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Empty as Empty using (‚ä•)
open import Cubical.Data.Unit using (tt)
open import Cubical.Data.Sigma using (_√ó_ ; _,_ ; fst ; snd)
open import Cubical.Relation.Nullary using (¬¨_)
open import GodelSeparation
  using ( Theory ; Sent ; Pf ; neg
        ; W ; wtop ; wbot ; wg ; wng ; wneg ; wPf ; Wit )
open import IndependenceNeedsAnInternalImplication
  using (Independent)

------------------------------------------------------------------------
-- NegationCompletenessForbidsIndependence
--
-- The obstruction of the previous module, at its root ‚î and the
-- positive recipe the root immediately suggests.
--
-- ‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î
-- WHAT THE PREVIOUS MODULE WAS REALLY ABOUT
--
-- `AProvabilityDeterminedImplicationForbidsIndependence` shows that a
-- provability-determined implication, with contraposition, modus ponens
-- and one unprovable sentence with provable negation, admits no
-- independent sentence.  ¬ß1 here shows the same conclusion follows from
-- one hypothesis with no implication in it at all:
--
--     if `¬ Pf T s` implies `Pf T (neg T s)` for every `s`
--     ‚î negation-completeness ‚î then nothing is independent.
--
-- One line, since independence is exactly the conjunction that
-- hypothesis forbids.  And `Wit` is negation-complete (¬ß2, four cases),
-- so `Wit`'s failure was already settled before any of the
-- implication machinery was examined.
--
-- The two statements do not subsume each other.  In the respect of what
-- is assumed about the connectives, ¬ß1 asks less: it mentions no `imp`,
-- no contraposition, no modus ponens.  In the respect of what is
-- assumed about the theory, the previous module asks less: it never
-- says the theory decides every sentence, only that its implication is
-- read off provability.  Both are kept; there is no scale here on which
-- to prefer one.
--
-- ‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î
-- AND THE POSITIVE RECIPE
--
-- ¬ß3 is the classical route, written down: independence follows from
-- SOUNDNESS FOR TWO MODELS.  If every theorem holds in every model, and
-- there is a model where `s` fails and a model where `neg s` fails,
-- then `s` is independent.  Two lines.
--
-- This is exactly the thing every model on this line lacked.  `Wit`
-- and its kin were built by reading provability off ONE two-valued
-- assignment, which is a single model, and a single model that decides
-- every sentence is negation-complete by construction ‚î ¬ß1.  The
-- positive case needs a `Pf` generated by rules and sound for a CLASS
-- of models, with two members of the class disagreeing about `s`.
--
-- ‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î
--
-- `Wit` is a correct model and
-- a decidable finite theory being negation-complete is unremarkable;
-- what ¬ß2 establishes is only that it cannot be the witness for an
-- independence result.
------------------------------------------------------------------------

private
  variable
    ‚Ñì ‚Ñì' ‚Ñì'' : Level

------------------------------------------------------------------------
-- 1.  Negation-completeness forbids independence
------------------------------------------------------------------------

NegationComplete : Theory ‚Ñì ‚Üí Type ‚Ñì
NegationComplete T = (s : Sent T) ‚Üí ¬¨ Pf T s ‚Üí Pf T (neg T s)

negationCompleteForbids :
  (T : Theory ‚Ñì) ‚Üí NegationComplete T ‚Üí (s : Sent T) ‚Üí ¬¨ Independent T s
negationCompleteForbids T comp s ind = snd ind (comp s (fst ind))

------------------------------------------------------------------------
-- 2.  `Wit` is negation-complete
--
-- Four cases.  The two provable sentences discharge the hypothesis;
-- the two unprovable ones have provable negations.
------------------------------------------------------------------------

witNegationComplete : NegationComplete Wit
witNegationComplete wtop h = Empty.rec (h tt)
witNegationComplete wbot _ = tt
witNegationComplete wg   _ = tt
witNegationComplete wng  h = Empty.rec (h tt)

witHasNoIndependentSentence : (s : W) ‚Üí ¬¨ Independent Wit s
witHasNoIndependentSentence = negationCompleteForbids Wit witNegationComplete

------------------------------------------------------------------------
-- 3.  Soundness for two models gives independence
--
-- The satisfaction relation is a parameter: nothing is assumed about
-- its shape, only that every theorem holds in every model of the class.
------------------------------------------------------------------------

module _ (T : Theory ‚Ñì) (Model : Type ‚Ñì')
         (_‚ä®_ : Model ‚Üí Sent T ‚Üí Type ‚Ñì'')
         (sound : (m : Model) (s : Sent T) ‚Üí Pf T s ‚Üí m ‚ä® s)
         where

  independenceFromTwoModels :
    (s : Sent T) (m‚ÇÄ m‚ÇÅ : Model)
    ‚Üí ¬¨ (m‚ÇÄ ‚ä® s)
    ‚Üí ¬¨ (m‚ÇÅ ‚ä® neg T s)
    ‚Üí Independent T s
  independenceFromTwoModels s m‚ÇÄ m‚ÇÅ h‚ÇÄ h‚ÇÅ =
      (Œª p ‚Üí h‚ÇÄ (sound m‚ÇÄ s p))
    , (Œª p ‚Üí h‚ÇÅ (sound m‚ÇÅ (neg T s) p))

  -- and the converse pressure: a class with one member that decides
  -- every sentence collapses to ¬ß1.
  singleDecidingModel :
    (m : Model)
    ‚Üí ((s : Sent T) ‚Üí ¬¨ (m ‚ä® s) ‚Üí Pf T (neg T s))
    ‚Üí ((s : Sent T) ‚Üí m ‚ä® s ‚Üí Pf T s)
    ‚Üí NegationComplete T
  singleDecidingModel m decide adequate s notPf =
    decide s (Œª sat ‚Üí notPf (adequate s sat))
