-- MachineMinted: generated by machine/CandidateGen.hs.
-- Admitted only on agda exit 0 (the MathMachine kernel-gate rule,
-- message 0484).  Instance certificate over the head-depth carrier
-- e_b(q) = v_q(b^ord_q(b) - 1) of formal/cubical/HeadDepthMerge.agda;
-- an extension of the corpus' certified range, not a new law.
-- CLAIM: W4 subgroup counts at fresh (q,a): blindCount 3 2 = 2, blindCount 3 3 = 2, blindCount 7 2 = 6, blindCount 11 2 = 10, blindCount 13 2 = 12, blindCount 17 2 = 16
{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}
module MachineMinted.W4CountsFresh where

open import Cubical.Foundations.Prelude
open import HeadDepthMerge using (blindCount)

-- Corollary W4 instances: the a-blind bases in [1, q^a] form the
-- subgroup of order q − 1 of (ℤ/q^a)^×.  Each count below is a fresh
-- exhaustive kernel computation; each equals q − 1, as W4 proves.

w4-3-2 : blindCount 3 2 ≡ 2
w4-3-2 = refl

w4-3-3 : blindCount 3 3 ≡ 2
w4-3-3 = refl

w4-7-2 : blindCount 7 2 ≡ 6
w4-7-2 = refl

w4-11-2 : blindCount 11 2 ≡ 10
w4-11-2 = refl

w4-13-2 : blindCount 13 2 ≡ 12
w4-13-2 = refl

w4-17-2 : blindCount 17 2 ≡ 16
w4-17-2 = refl

