import Mathlib.GroupTheory.QuotientGroup.Basic
import Mathlib.Algebra.GroupWithZero.Action.Basic

namespace Pairfield.HolonomyDescent

universe u v w

section OrbitSet

variable {G : Type u} [Group G]
variable {X : Type v} [MulAction G X]

/-- Two presentations are identified when a generated holonomy carries one
to the other. This is a set quotient; no additive structure is asserted. -/
def orbitSetoid : Setoid X where
  r x y := ∃ g : G, g • x = y
  iseqv := {
    refl := fun x => ⟨1, by simp⟩
    symm := by
      rintro x y ⟨g, rfl⟩
      exact ⟨g⁻¹, by simp⟩
    trans := by
      rintro x y z ⟨g, rfl⟩ ⟨h, rfl⟩
      exact ⟨h * g, by simp [mul_smul]⟩ }

abbrev OrbitSet := Quotient (orbitSetoid (G := G) (X := X))

def orbitMk : X → OrbitSet (G := G) (X := X) := Quotient.mk _

theorem orbitMk_smul (g : G) (x : X) :
    orbitMk (G := G) (g • x) = orbitMk (G := G) x := by
  apply Quotient.sound
  exact ⟨g⁻¹, by simp⟩

variable {Y : Type w}

/-- A set-valued task descends through path erasure exactly when it is
invariant under every generated holonomy. -/
theorem factors_through_orbit_iff (task : X → Y) :
    (∃ descended : OrbitSet (G := G) (X := X) → Y,
        task = descended ∘ orbitMk (G := G)) ↔
      ∀ g : G, ∀ x : X, task (g • x) = task x := by
  constructor
  · rintro ⟨descended, rfl⟩ g x
    exact congrArg descended (orbitMk_smul g x)
  · intro invariant
    let descended : OrbitSet (G := G) (X := X) → Y :=
      Quotient.lift task (by
        rintro x y ⟨g, rfl⟩
        exact (invariant g x).symm)
    exact ⟨descended, rfl⟩

theorem orbit_factor_unique (task : X → Y)
    (invariant : ∀ g : G, ∀ x : X, task (g • x) = task x) :
    ∃! descended : OrbitSet (G := G) (X := X) → Y,
      task = descended ∘ orbitMk (G := G) := by
  let descended : OrbitSet (G := G) (X := X) → Y :=
    Quotient.lift task (by
      rintro x y ⟨g, rfl⟩
      exact (invariant g x).symm)
  refine ⟨descended, rfl, ?_⟩
  intro other h
  funext q
  refine Quotient.inductionOn q ?_
  intro x
  exact (congrFun h x).symm

end OrbitSet

section Coinvariants

variable {G : Type u} [Group G]
variable {A : Type v} [AddCommGroup A] [DistribMulAction G A]

/-- The subgroup generated by additive holonomy differences. -/
def differenceSubgroup : AddSubgroup A :=
  AddSubgroup.closure {d | ∃ (g : G) (x : A), d = g • x - x}

abbrev Coinvariants := A ⧸ differenceSubgroup (G := G) (A := A)

def coinvariantMk : A →+ Coinvariants (G := G) (A := A) :=
  QuotientAddGroup.mk' (differenceSubgroup (G := G) (A := A))

theorem coinvariantMk_smul (g : G) (x : A) :
    coinvariantMk (G := G) (g • x) = coinvariantMk (G := G) x := by
  rw [← sub_eq_zero]
  change ((g • x - x : A) : Coinvariants (G := G) (A := A)) = 0
  apply (QuotientAddGroup.eq_zero_iff _).2
  change g • x - x ∈ differenceSubgroup (G := G) (A := A)
  exact AddSubgroup.subset_closure ⟨g, x, rfl⟩

variable {B : Type w} [AddCommGroup B]

/-- The additive universal property is a quotient *group*, not the orbit set.
An additive task descends precisely when it kills all holonomy differences. -/
theorem addHom_factors_through_coinvariants_iff (task : A →+ B) :
    (∃ descended : Coinvariants (G := G) (A := A) →+ B,
        task = descended.comp (coinvariantMk (G := G))) ↔
      ∀ g : G, ∀ x : A, task (g • x) = task x := by
  constructor
  · rintro ⟨descended, rfl⟩ g x
    exact congrArg descended (coinvariantMk_smul g x)
  · intro invariant
    have kills : differenceSubgroup (G := G) (A := A) ≤ task.ker := by
      rw [differenceSubgroup, AddSubgroup.closure_le]
      rintro d ⟨g, x, rfl⟩
      change task (g • x - x) = 0
      simp [invariant g x]
    exact ⟨QuotientAddGroup.lift (differenceSubgroup (G := G) (A := A)) task kills, rfl⟩

theorem coinvariant_factor_unique (task : A →+ B)
    (invariant : ∀ g : G, ∀ x : A, task (g • x) = task x) :
    ∃! descended : Coinvariants (G := G) (A := A) →+ B,
      task = descended.comp (coinvariantMk (G := G)) := by
  have kills : differenceSubgroup (G := G) (A := A) ≤ task.ker := by
    rw [differenceSubgroup, AddSubgroup.closure_le]
    rintro d ⟨g, x, rfl⟩
    change task (g • x - x) = 0
    simp [invariant g x]
  let descended :=
    QuotientAddGroup.lift (differenceSubgroup (G := G) (A := A)) task kills
  refine ⟨descended, rfl, ?_⟩
  intro other h
  apply QuotientAddGroup.addMonoidHom_ext
  exact h.symm.trans rfl

end Coinvariants

end Pairfield.HolonomyDescent
