{-# OPTIONS --cubical --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- ChainHomotopyIsCompilerPassCorrectness
--
-- A semantics-preserving compiler pass is a chain map; a proof that two
-- passes have the same semantic action is a chain homotopy.  If two maps
-- F, G differ by a boundary term generated by a higher witness H,
--
--     F x  ≡  G x + (dE (H x) + H (dD x)),        (the homotopy)
--
-- then on a CLOSED input (dD x ≡ 0D) the two outputs differ by exactly a
-- coboundary,
--
--     F x  ≡  G x + dE (H x),
--
-- so F and G are cohomologous: they induce the same map on cohomology.
-- Source and target presentations differ; their semantic action is equal;
-- and the equality is carried by the explicit higher witness H, not
-- asserted.  This is the exact shape wanted for a proof-carrying pass.
--
-- Machine-checked, Agda 2.8.0 + cubical v0.9, --safe, no postulates.
------------------------------------------------------------------------

module ChainHomotopyIsCompilerPassCorrectness where

open import Cubical.Foundations.Prelude

module _
  {ℓ : Level}
  (D E : Type ℓ)
  (dD : D → D) (dE : E → E)
  (F G H : D → E)
  (_+E_ : E → E → E) (0E : E) (0D : D)
  (homotopy : (x : D) → F x ≡ (G x +E (dE (H x) +E H (dD x))))
  (H-0D    : H 0D ≡ 0E)
  (rUnitE  : (y : E) → (y +E 0E) ≡ y)
  where

  -- On a closed input, F and G differ by the coboundary dE (H x):
  -- they are cohomologous, i.e. equal on cohomology.
  cohomologous : (x : D) → dD x ≡ 0D → F x ≡ (G x +E dE (H x))
  cohomologous x closed =
      homotopy x
    ∙ cong (λ z → G x +E (dE (H x) +E z)) (cong H closed ∙ H-0D)
    ∙ cong (λ z → G x +E z) (rUnitE (dE (H x)))
