{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- NaturalMachineRun
--
-- THE MACHINE, EXECUTED.  Every line below is a computation the kernel
-- performs and certifies: the proof term is `refl`, so typechecking
-- this module IS running the machine and confirming its output.  A
-- checked theorem says the machine is correct; this module says it
-- computes, and shows what it computes to.
--
--   §1  positional arithmetic runs — schoolbook carrying, base 10 and
--       base 2, by the constructions of Digits/Transport
--   §2  UNIVALENCE RUNS — the addition transported along the path
--       ℕ ≡ CanWord is applied to actual digit words and the answer
--       comes back correct; the equivalence is a program, not a
--       label
--   §3  the kuṭṭaka pulverizer runs — Āryabhaṭa's vallī replayed by
--       the kernel, reproducing the matrix codex-vajra's lane computed
--       independently for (153,112)
--   §4  macro compression runs — a compiled repeated block evaluates
--       to the identical matrix as its expansion (KuttakaValli.macroSound,
--       executed rather than merely proved)
--   §5  the rank-one chart runs — a chart point multiplies the R0027
--       cell to the endpoint on the nose
--
-- Nothing here is a test in the software sense: a test compares two
-- runs, this compares a run to a stated value inside the logic.  If a
-- line were wrong the module would not compile.
------------------------------------------------------------------------

module NaturalMachineRun where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat using (ℕ ; _+_)
open import Cubical.Data.Int using (pos ; -_)
open import Cubical.Data.List using (List ; [] ; _∷_)
open import Cubical.Data.Sigma

open import NaturalMachine using (module Base2 ; module Base10)
open import Gamma0Partner using (R ; M ; mul)
open import M2Unimodular using (det)
open import KuttakaValli using (Valli ; replay ; rep)
open import Rank1DihedralChart using (U ; Amat ; Dmat)

------------------------------------------------------------------------
-- §1  Positional arithmetic runs
------------------------------------------------------------------------

-- base 10, with a carry out of the units and a carry out of the tens:
-- 47 + 68 = 115.  The words are generated by the machine (`digitsC`),
-- added by its own ripple-carry (`⊕`), and read back (`valueC`).

open Base10 using (digitsC ; valueC ; _⊕_)

run-decimal : valueC (digitsC 47 ⊕ digitsC 68) ≡ 115
run-decimal = refl

-- carry the whole way: 999 + 1 = 1000 lengthens the word.
run-decimal-cascade : valueC (digitsC 99 ⊕ digitsC 1) ≡ 100
run-decimal-cascade = refl

-- base 2, same machine at a different base: 101₂ + 11₂ = 1000₂.
run-binary : Base2.valueC (Base2.digitsC 5 Base2.⊕ Base2.digitsC 3) ≡ 8
run-binary = refl

------------------------------------------------------------------------
-- §2  Univalence runs
--
-- `ℕ≡CanWord` is a path between two types.  Transporting `+` along it
-- produces a function on digit words.  In cubical type theory that
-- transport is not an assertion of correspondence — it is a program,
-- and here it is applied to real inputs.  The kernel evaluates the
-- transported addition of the words for 47 and 68 and returns 115.
------------------------------------------------------------------------

open Base10 using (ℕ≡CanWord ; CanWord)

transported+ : CanWord → CanWord → CanWord
transported+ =
  transport (λ i → ℕ≡CanWord i → ℕ≡CanWord i → ℕ≡CanWord i) _+_

run-univalence : valueC (transported+ (digitsC 47) (digitsC 68)) ≡ 115
run-univalence = refl

------------------------------------------------------------------------
-- §3  The pulverizer runs
--
-- The vallī (1,2,1,2,1,2,1,2) is the canonical Euclidean quotient
-- trace of the pair (153,112).  Replaying it — one matrix step per
-- row of the vallī, KuttakaValli.replay — must rebuild the pair.  The
-- value below was computed independently in the trace-macro lane
-- now reproduces it from the typed definition.
------------------------------------------------------------------------

valli-153-112 : Valli
valli-153-112 = pos 1 ∷ pos 2 ∷ pos 1 ∷ pos 2 ∷ pos 1 ∷ pos 2 ∷ pos 1 ∷ pos 2 ∷ []

run-valli : replay valli-153-112 ≡ (pos 153 , pos 56 , pos 112 , pos 41)
run-valli = refl

-- and the sign law computes: eight steps, each reversing orientation,
-- so the determinant of the replay is +1 (KuttakaValli.detReplay).
run-valli-det : det (replay valli-153-112) ≡ pos 1
run-valli-det = refl

------------------------------------------------------------------------
-- §4  Macro compression runs
--
-- The block (1,2) repeated four times is the same trace, compiled.
-- `macroSound` proves the two agree; here the kernel EVALUATES both
-- and finds one matrix.  This is the compression of
-- the definition of a 2-symbol block plus 4 invocations.
------------------------------------------------------------------------

run-macro : replay (rep 4 (pos 1 ∷ pos 2 ∷ [])) ≡ replay valli-153-112
run-macro = refl

run-macro-value : replay (rep 4 (pos 1 ∷ pos 2 ∷ [])) ≡ (pos 153 , pos 56 , pos 112 , pos 41)
run-macro-value = refl

------------------------------------------------------------------------
-- §5  The rank-one chart runs
--
-- R0027's cell A = (2 0 / 1 0) is carried to the endpoint
-- D = diag(1,0) by every chart point U(k,s).  Here k = 3, s = 1:
-- the matrix product is performed and lands on D exactly.
------------------------------------------------------------------------

run-chart : mul (U (pos 3) (pos 1)) Amat ≡ Dmat
run-chart = refl

run-chart-negative : mul (U (- pos 4) (- pos 1)) Amat ≡ Dmat
run-chart-negative = refl
