{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- Coordination.Serialization
--
-- **K2, the local serialization theorem** — the load-bearing proposition
-- of the owner's Coordination Kernel v0.1
-- (`collab/upstream/library/raw/COORDINATION_KERNEL_V0_1_2026-08-13(1).md`
-- §7), machine-checked, together with the hypothesis this repository's
-- own audit found the spec omits.
--
-- WHY THIS THEOREM.  Every "no global sequencer" claim in the kernel is a
-- corollary of K2: invariants K4 (no mandatory total-order field), K15
-- (consensus only per declared conflict domain), and the whole §7
-- replacement of a global chain by "Merkle dependency DAG + consensus
-- only per actual conflict domain".  The spec proves it in three
-- sentences.  This module supplies the part those sentences assert:
--
--     if two schedules differ only by transpositions of adjacent
--     INDEPENDENT events, they compute the same final state.
--
-- THE CORRECTION THIS MODULE CARRIES.  `notes/RELATIONAL_CONTRACTS_AUDIT.md`
-- audited the upstream Delta's coordination-decomposition and returned
-- SCOPED/CORRECTED: uninformative cross-boundary messages do not by
-- themselves license removing synchronisation, because "a protocol whose
-- control flow branches on an uninformative bit still changes its
-- composite map when the bit is withheld", and the conclusion becomes
-- exact only under a **data-passivity / event-structure-invariance**
-- hypothesis.  That hypothesis is not a footnote here: it is the TYPE.
-- `run` is applied to a FIXED event word, so the event structure is held
-- constant by construction, and the reordering theorem is proved only in
-- that regime.  A protocol that chooses its next event from the state is
-- not an inhabitant of this statement, which is precisely the audit's
-- point made unignorable.
--
-- WHAT THIS MODULE PROVES (no holes, no postulates, --safe):
--
--   step, run                execution of an event word on a state
--   Indep                    declared independence WITH its semantic
--                            obligation (a commutation proof), not a flag
--   _~_                      Mazurkiewicz trace equivalence, generated by
--                            adjacent swaps of independent events
--   trace-sound              **K2**: w ~ w′ ⇒ run w s ≡ run w′ s
--   ~-refl/sym/trans         it is an equivalence relation
--   run-++                   execution composes along concatenation
--   unknown-is-not-independent
--                            **invariant K9 as a checked term**: a
--                            concrete two-event system with no
--                            commutation proof whose two orders give
--                            different states.  "Never infer
--                            independence from absence of known
--                            conflict" (§83) is therefore not advice —
--                            the absence of an `Indep` inhabitant is
--                            exactly the gap, and the gap is inhabited.
--   indep-sym                independence is symmetric
--
-- NOT claimed.  The full K2 of §7 also asserts that any two linear
-- extensions of (dependency order ⊕ per-domain local orders) are
-- connected by such swaps.  That combinatorial half is stated in
-- `linext-connected-STATEMENT` below as an explicit interface with no
-- inhabitant supplied, so the boundary is visible rather than implied:
-- this module proves the semantic half exactly and names the
-- combinatorial half as the open obligation.  Nothing here is about
-- consensus, networks, or agents.
------------------------------------------------------------------------

module Coordination.Serialization where

open import Cubical.Foundations.Prelude
open import Cubical.Data.List using (List ; [] ; _∷_ ; _++_)
open import Cubical.Data.Bool using (Bool ; true ; false ; not ; true≢false)
open import Cubical.Data.Sigma
open import Cubical.Data.Empty as Empty using (⊥)
open import Cubical.Relation.Nullary using (¬_)

private
  variable
    ℓ ℓ′ : Level

------------------------------------------------------------------------
-- §1  Execution of a fixed event word.
--
-- The word is DATA, supplied up front.  This is the data-passivity
-- hypothesis of the audit, discharged structurally: nothing below can
-- branch on the state to choose the next event, because the event list
-- is an argument, not a result.
------------------------------------------------------------------------

record System (ℓ ℓ′ : Level) : Type (ℓ-suc (ℓ-max ℓ ℓ′)) where
  field
    St    : Type ℓ
    Event : Type ℓ′
    step  : Event → St → St

open System public

-- Execute a word left-to-right.
run : (Sys : System ℓ ℓ′) → List (Event Sys) → St Sys → St Sys
run Sys []       s = s
run Sys (e ∷ es) s = run Sys es (step Sys e s)

-- Execution composes along concatenation: the sequential-resumption law.
run-++ : (Sys : System ℓ ℓ′) (xs ys : List (Event Sys)) (s : St Sys)
       → run Sys (xs ++ ys) s ≡ run Sys ys (run Sys xs s)
run-++ Sys []       ys s = refl
run-++ Sys (e ∷ xs) ys s = run-++ Sys xs ys (step Sys e s)

------------------------------------------------------------------------
-- §2  Independence carries its obligation.
--
-- §83: the effect judgement is three-valued —
-- ProvenIndependent / ProvenConflict / Unknown — and "ignorance is not
-- independence".  Here `Indep e f` is inhabited exactly by a PROOF of
-- commutation, so `ProvenIndependent` is an inhabitant and `Unknown` is
-- the absence of one.  There is no Boolean flag to set.
------------------------------------------------------------------------

record Indep (Sys : System ℓ ℓ′) (e f : Event Sys) : Type ℓ where
  field
    comm : (s : St Sys) → step Sys e (step Sys f s) ≡ step Sys f (step Sys e s)

open Indep public

indep-sym : {Sys : System ℓ ℓ′} {e f : Event Sys}
          → Indep Sys e f → Indep Sys f e
comm (indep-sym {Sys = Sys} i) s = sym (comm i s)

------------------------------------------------------------------------
-- §3  Mazurkiewicz trace equivalence.
--
-- Generated by transposing two ADJACENT events that carry a commutation
-- proof.  Reflexivity, symmetry and transitivity are constructors, so
-- `_~_` is the equivalence relation generated by the swaps — the
-- "connected by swaps of adjacent incomparable events" of §7, as data.
------------------------------------------------------------------------

data Trace {ℓ ℓ′} (Sys : System ℓ ℓ′)
     : List (Event Sys) → List (Event Sys) → Type (ℓ-suc (ℓ-max ℓ ℓ′)) where

  swap : {e f : Event Sys}
       → Indep Sys e f
       → (xs ys : List (Event Sys))
       → Trace Sys (xs ++ (e ∷ f ∷ ys)) (xs ++ (f ∷ e ∷ ys))

  ~refl  : (w : List (Event Sys)) → Trace Sys w w

  ~sym   : {w w′ : List (Event Sys)}
         → Trace Sys w w′ → Trace Sys w′ w

  ~trans : {w w′ w″ : List (Event Sys)}
         → Trace Sys w w′ → Trace Sys w′ w″ → Trace Sys w w″

------------------------------------------------------------------------
-- §4  K2, the semantic half: swapping independent adjacent events does
-- not change the computed state.
--
-- The proof is the spec's own argument made exact: peel the common
-- prefix with `run-++`, apply the commutation proof once at the seam,
-- then run the common suffix.  Everything else is congruence.
------------------------------------------------------------------------

private
  -- one swap, at the seam, after the prefix has been executed
  swap-step : (Sys : System ℓ ℓ′) {e f : Event Sys}
            → Indep Sys e f
            → (ys : List (Event Sys)) (s : St Sys)
            → run Sys (e ∷ f ∷ ys) s ≡ run Sys (f ∷ e ∷ ys) s
  swap-step Sys {e} {f} i ys s =
    cong (run Sys ys) (sym (comm i s))

trace-sound : (Sys : System ℓ ℓ′) {w w′ : List (Event Sys)}
            → Trace Sys w w′
            → (s : St Sys) → run Sys w s ≡ run Sys w′ s
trace-sound Sys (swap {e = e} {f = f} i xs ys) s =
    run-++ Sys xs (e ∷ f ∷ ys) s
  ∙ swap-step Sys i ys (run Sys xs s)
  ∙ sym (run-++ Sys xs (f ∷ e ∷ ys) s)
trace-sound Sys (~refl w)      s = refl
trace-sound Sys (~sym p)       s = sym (trace-sound Sys p s)
trace-sound Sys (~trans p q)   s = trace-sound Sys p s ∙ trace-sound Sys q s

------------------------------------------------------------------------
-- §5  Invariant K9, as a checked term: ignorance is not independence.
--
-- §83 of the kernel: "Never infer independence from absence of known
-- conflict. ... ignorance is not independence."  As prose that is a
-- warning.  Here it is a theorem about a two-line system: `setTrue` and
-- `flip` on Bool have NO commutation proof, and the two orders reach
-- different states.  So the absence of an `Indep` inhabitant is a real
-- gap and not a bookkeeping artefact — which is exactly what licenses
-- the three-valued judgement instead of a Boolean.
------------------------------------------------------------------------

data TwoEvents : Type₀ where
  setTrue : TwoEvents
  flip    : TwoEvents

twoStep : TwoEvents → Bool → Bool
twoStep setTrue _ = true
twoStep flip    b = not b

Witness : System ℓ-zero ℓ-zero
St    Witness = Bool
Event Witness = TwoEvents
step  Witness = twoStep

-- The two orders disagree at `false`:
--   setTrue then flip  ↦ not true  = false
--   flip then setTrue  ↦ true
orders-differ :
  ¬ ((s : Bool) → twoStep setTrue (twoStep flip s) ≡ twoStep flip (twoStep setTrue s))
orders-differ h = true≢false (h false)

unknown-is-not-independent : ¬ (Indep Witness setTrue flip)
unknown-is-not-independent i = orders-differ (comm i)

-- …and therefore the swap rule genuinely cannot be applied to this pair:
-- a scheduler that reordered them "because no conflict was recorded"
-- would change the result.
reordering-this-pair-changes-the-state :
  ¬ ((s : Bool) → run Witness (setTrue ∷ flip ∷ []) s
                ≡ run Witness (flip ∷ setTrue ∷ []) s)
reordering-this-pair-changes-the-state h = true≢false (sym (h false))

------------------------------------------------------------------------
-- §6  The open obligation, named rather than implied.
--
-- §7's K2 has a second half: that any two linear extensions of the
-- dependency order augmented by per-conflict-domain local total orders
-- are `~`-connected, given that every non-commuting pair shares a
-- conflict key.  That is a combinatorial statement about posets, it is
-- where the hypotheses actually have to be right, and it is NOT proved
-- here.  It is written as an interface so that a future module either
-- inhabits it or reports what it needs.
--
-- Stating it as a type rather than a comment is the point: an
-- un-inhabited record is an obligation the typechecker can see.
------------------------------------------------------------------------

record LinextConnected (Sys : System ℓ ℓ′) (Schedule : Type ℓ) : Type (ℓ-suc (ℓ-max ℓ ℓ′)) where
  field
    word      : Schedule → List (Event Sys)
    -- every non-commuting pair shares a conflict key, and each key
    -- domain is locally totally ordered: the two hypotheses of §7.
    connected : (u v : Schedule) → Trace Sys (word u) (word v)

-- Given that interface, the kernel's headline follows immediately: every
-- admissible schedule computes the same extensional result, with no
-- global order anywhere in sight.  This is the corollary K4 and K15 rest
-- on, and it is one line once the combinatorial half is supplied.
same-result : (Sys : System ℓ ℓ′) {Schedule : Type ℓ}
            → (L : LinextConnected Sys Schedule)
            → (u v : Schedule) (s : St Sys)
            → run Sys (LinextConnected.word L u) s
            ≡ run Sys (LinextConnected.word L v) s
same-result Sys L u v s =
  trace-sound Sys (LinextConnected.connected L u v) s
