{-# OPTIONS --cubical --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- PairwiseCommutationGivesEveryOrder
--
-- `OrderIndependenceTransfersAlongAnyNumberOfSteps` closed with the one
-- remaining gap in Œî 28 ¬ß36‚ì38's "for every order":
--
--   "PERMUTATIONS ARE NOT MODELLED.  'For every order' is encoded as
--    the HYPOTHESIS that two uncompressed composites agree ‚î which is
--    what Œî 28 means by 'exact elimination commutes' ‚î and NO theorem
--    here derives that hypothesis from pairwise commutation."
--
-- Derived here, and the derivation is where the phrase "exact
-- elimination commutes" finally becomes a hypothesis about STEPS
-- rather than about composites.
--
-- ‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î
-- WHAT IS PROVED
--
--   _~_               permutation, in the standard inductive
--                     presentation: identity, congruence under `‚à`,
--                     the ADJACENT transposition, and transitivity
--   permInvariant     under pairwise commutation of the steps, any two
--                     permutations of a list have the same uncompressed
--                     composite ‚î one line per constructor, and the
--                     transposition case IS the commutation hypothesis
--   everyOrderAgreesAfterCompression
--                     hence, composing with the previous module, the
--                     COMPRESSED composites agree on the image for any
--                     two orders
--   disagreementUnderPermutationIsOffTheImage
--                     and a point where two orders disagree is not `C`
--                     of anything
--
-- **So ¬ß36‚ì38's clause is now hypothesis-free at the level it is
-- stated.**  Œî 28 says exact elimination commutes and that flat
-- compression preserves semantics "for every order".  Three cycles ago
-- that was two orders of two steps; two cycles ago it was any two
-- composites ASSUMED equal; now it is: assume the STEPS commute
-- pairwise, and every order agrees, compressed and uncompressed alike.
--
-- ‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î
-- NO NOVELTY.  That adjacent transpositions generate permutations, and
-- that pairwise-commuting operations give order-independent composites,
-- are both elementary and old.  The content here is only that Œî 28's
-- phrase is now discharged rather than assumed.
------------------------------------------------------------------------

module PairwiseCommutationGivesEveryOrder where

open import Cubical.Foundations.Prelude
open import Cubical.Data.List using (List ; [] ; _‚à∑_)
open import Cubical.Data.Sigma using (Œ£-syntax ; _,_ ; fst ; snd)
open import Cubical.Relation.Nullary using (¬¨_)

open import OrderIndependenceTransfersAlongAnyNumberOfSteps
  using (Step ; runS ; runT ; orderIndependenceTransfers)

module _ {S T : Type} (C : S ‚Üí T) where

  ------------------------------------------------------------------
  -- 1.  Permutation, generated by adjacent transpositions
  ------------------------------------------------------------------

  data _~_ : List (Step C) ‚Üí List (Step C) ‚Üí Type where
    ~nil   : [] ~ []
    ~cons  : {p : Step C} {xs ys : List (Step C)}
             ‚Üí xs ~ ys ‚Üí (p ‚à∑ xs) ~ (p ‚à∑ ys)
    ~swap  : {p q : Step C} {xs : List (Step C)}
             ‚Üí (p ‚à∑ q ‚à∑ xs) ~ (q ‚à∑ p ‚à∑ xs)
    ~trans : {xs ys zs : List (Step C)}
             ‚Üí xs ~ ys ‚Üí ys ~ zs ‚Üí xs ~ zs

  ------------------------------------------------------------------
  -- 2.  Pairwise commutation makes the composite order-independent
  --
  -- The transposition case is exactly the hypothesis; every other case
  -- is a congruence or a composition.
  ------------------------------------------------------------------

  module _ (comm : (p q : Step C) (s : S)
                 ‚Üí fst p (fst q s) ‚â° fst q (fst p s)) where

    -- matching on the RELATION only, never on the lists: pattern
    -- matching that would need injectivity of `_‚à_` is not supported in
    -- cubical Agda and produces a "will not compute on transports"
    -- warning, so the lists stay implicit
    permInvariant :
      {xs ys : List (Step C)} ‚Üí xs ~ ys ‚Üí (s : S) ‚Üí runS C xs s ‚â° runS C ys s
    permInvariant ~nil                          s = refl
    permInvariant (~cons {p = p} r)             s = cong (fst p) (permInvariant r s)
    permInvariant (~swap {p = p} {q = q} {xs = xs}) s = comm p q (runS C xs s)
    permInvariant (~trans r‚ÇÅ r‚ÇÇ)                s =
      permInvariant r‚ÇÅ s ‚àô permInvariant r‚ÇÇ s

    ----------------------------------------------------------------
    -- 3.  So every order agrees after compression too
    ----------------------------------------------------------------

    everyOrderAgreesAfterCompression :
      {xs ys : List (Step C)} ‚Üí xs ~ ys
      ‚Üí (s : S) ‚Üí runT C xs (C s) ‚â° runT C ys (C s)
    everyOrderAgreesAfterCompression {xs} {ys} r =
      orderIndependenceTransfers C xs ys (permInvariant r)

    disagreementUnderPermutationIsOffTheImage :
      {xs ys : List (Step C)} ‚Üí xs ~ ys
      ‚Üí (t : T) ‚Üí ¬¨ (runT C xs t ‚â° runT C ys t) ‚Üí ¬¨ (Œ£[ s ‚àà S ] C s ‚â° t)
    disagreementUnderPermutationIsOffTheImage {xs} {ys} r t bent (s , e) =
      bent (subst (Œª x ‚Üí runT C xs x ‚â° runT C ys x) e
                  (everyOrderAgreesAfterCompression r s))
