{-# OPTIONS --cubical --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- PairwiseCommutationGivesEveryOrder
--
-- `OrderIndependenceTransfersAlongAnyNumberOfSteps` closed with the one
-- remaining gap in Δ 28 §36–38's "for every order":
--
--   "PERMUTATIONS ARE NOT MODELLED.  'For every order' is encoded as
--    the HYPOTHESIS that two uncompressed composites agree — which is
--    what Δ 28 means by 'exact elimination commutes' — and NO theorem
--    here derives that hypothesis from pairwise commutation."
--
-- Derived here, and the derivation is where the phrase "exact
-- elimination commutes" finally becomes a hypothesis about STEPS
-- rather than about composites.
--
-- ────────────────────────────────────────────────────────────────────
-- WHAT IS PROVED
--
--   _~_               permutation, in the standard inductive
--                     presentation: identity, congruence under `∷`,
--                     the ADJACENT transposition, and transitivity
--   permInvariant     under pairwise commutation of the steps, any two
--                     permutations of a list have the same uncompressed
--                     composite — one line per constructor, and the
--                     transposition case IS the commutation hypothesis
--   everyOrderAgreesAfterCompression
--                     hence, composing with the previous module, the
--                     COMPRESSED composites agree on the image for any
--                     two orders
--   disagreementUnderPermutationIsOffTheImage
--                     and a point where two orders disagree is not `C`
--                     of anything
--
-- **So §36–38's clause is now hypothesis-free at the level it is
-- stated.**  Δ 28 says exact elimination commutes and that flat
-- compression preserves semantics "for every order".  Three cycles ago
-- that was two orders of two steps; two cycles ago it was any two
-- composites ASSUMED equal; now it is: assume the STEPS commute
-- pairwise, and every order agrees, compressed and uncompressed alike.
--
-- ────────────────────────────────────────────────────────────────────
-- NO NOVELTY.  That adjacent transpositions generate permutations, and
-- that pairwise-commuting operations give order-independent composites,
-- are both elementary and old.  The content here is only that Δ 28's
-- phrase is now discharged rather than assumed.
--
-- WHAT IS NOT CLAIMED, and one of these is a real weakening.
-- **THE COMMUTATION HYPOTHESIS IS GLOBAL**: `comm` quantifies over ALL
-- steps of the type, not over the steps appearing in the list.  Δ 28's
-- setting plausibly has non-commuting steps elsewhere in the system,
-- and restricting the hypothesis to list members is possible but needs
-- it carried through `swap` and `trans` with a membership index, which
-- is NOT done.  So this covers a system whose elimination steps all
-- commute, not a system with a commuting sub-family.
-- `_~_` is a DEFINITION, not a characterisation: nothing here proves it
-- coincides with "same multiset" or with any other notion of
-- permutation, so "every order" means "every order reachable by
-- adjacent transpositions", which is all of them for the usual reasons
-- and is not proved to be.  No curvature is exhibited, as before.
--
-- CHECKED on the CONTAINER (Agda 2.6.3, cubical v0.5 — NOT the declared
-- pin, Agda 2.8.0 + cubical v0.9).  --safe, no postulates, no holes.
------------------------------------------------------------------------

module PairwiseCommutationGivesEveryOrder where

open import Cubical.Foundations.Prelude
open import Cubical.Data.List using (List ; [] ; _∷_)
open import Cubical.Data.Sigma using (Σ-syntax ; _,_ ; fst ; snd)
open import Cubical.Relation.Nullary using (¬_)

open import OrderIndependenceTransfersAlongAnyNumberOfSteps
  using (Step ; runS ; runT ; orderIndependenceTransfers)

module _ {S T : Type} (C : S → T) where

  ------------------------------------------------------------------
  -- 1.  Permutation, generated by adjacent transpositions
  ------------------------------------------------------------------

  data _~_ : List (Step C) → List (Step C) → Type where
    ~nil   : [] ~ []
    ~cons  : {p : Step C} {xs ys : List (Step C)}
             → xs ~ ys → (p ∷ xs) ~ (p ∷ ys)
    ~swap  : {p q : Step C} {xs : List (Step C)}
             → (p ∷ q ∷ xs) ~ (q ∷ p ∷ xs)
    ~trans : {xs ys zs : List (Step C)}
             → xs ~ ys → ys ~ zs → xs ~ zs

  ------------------------------------------------------------------
  -- 2.  Pairwise commutation makes the composite order-independent
  --
  -- The transposition case is exactly the hypothesis; every other case
  -- is a congruence or a composition.
  ------------------------------------------------------------------

  module _ (comm : (p q : Step C) (s : S)
                 → fst p (fst q s) ≡ fst q (fst p s)) where

    -- matching on the RELATION only, never on the lists: pattern
    -- matching that would need injectivity of `_∷_` is not supported in
    -- cubical Agda and produces a "will not compute on transports"
    -- warning, so the lists stay implicit
    permInvariant :
      {xs ys : List (Step C)} → xs ~ ys → (s : S) → runS C xs s ≡ runS C ys s
    permInvariant ~nil                          s = refl
    permInvariant (~cons {p = p} r)             s = cong (fst p) (permInvariant r s)
    permInvariant (~swap {p = p} {q = q} {xs = xs}) s = comm p q (runS C xs s)
    permInvariant (~trans r₁ r₂)                s =
      permInvariant r₁ s ∙ permInvariant r₂ s

    ----------------------------------------------------------------
    -- 3.  So every order agrees after compression too
    ----------------------------------------------------------------

    everyOrderAgreesAfterCompression :
      {xs ys : List (Step C)} → xs ~ ys
      → (s : S) → runT C xs (C s) ≡ runT C ys (C s)
    everyOrderAgreesAfterCompression {xs} {ys} r =
      orderIndependenceTransfers C xs ys (permInvariant r)

    disagreementUnderPermutationIsOffTheImage :
      {xs ys : List (Step C)} → xs ~ ys
      → (t : T) → ¬ (runT C xs t ≡ runT C ys t) → ¬ (Σ[ s ∈ S ] C s ≡ t)
    disagreementUnderPermutationIsOffTheImage {xs} {ys} r t bent (s , e) =
      bent (subst (λ x → runT C xs x ≡ runT C ys x) e
                  (everyOrderAgreesAfterCompression r s))
