{-# OPTIONS --cubical --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- मात्रा-सङ्ख्या — the mātrā-fibre over n is Fin of the Virahāṅka number.
--
-- Virahāṅka (c. 600-800 CE, Vṛttajātisamuccaya), on Piṅgala's
-- Chandaḥśāstra (c. 300 BCE): counting the mātrā-vṛttas of total duration n
-- — sequences of laghu (1 mātrā) and guru (2 mātrā) summing to n — obeys the
-- two-step recurrence, and the resulting COUNT is the mātrā-meru sequence
-- 1,1,2,3,5,8,... (the recurrence usually cited under Fibonacci's name, five
-- centuries later, though Virahāṅka states it, and Piṅgala's meru-prastāra
-- already tabulates it).  The sibling module `Virahanka_…` proved the fibre
-- RECURRENCE as an equivalence
--     fiber छन्दः (2+n) ≃ (fiber छन्दः (1+n) ⊎ fiber छन्दः n)
-- and anchored it with two contractible base fibres.  This module consumes
-- exactly those three facts and closes the count: the fibre over n is a
-- STANDARD finite type, `Fin (मात्रा-सङ्ख्या n)`, with the census computed
-- by the same recurrence.  No new mathematics on the mātrā side — the census
-- of a fibre minted with a standard type, never estimated (सूत्र ८).
--
-- The chaining is entirely of already-checked equivalences: the corpus's own
-- `विरहाङ्क-आवृत्तिः`, `आदि-शून्यम्`, `आदि-एकम्`, composed with the library's
-- `isContr→≃Unit`, `Unit≃Fin1`, `⊎-equiv`, and `Fin+≅Fin⊎Fin` (the last read
-- backwards, so a sum of two Fins is one Fin of the sum — which is why the
-- census ADDS, exactly the meru's building rule).
--
-- Scope: this does NOT claim Virahāṅka wrote a bijection to Fin; it claims
-- the mātrā-count he named is the cardinality of this fibre, made a type.
-- TERM मात्रा-सङ्ख्या (mātrā-saṅkhyā), the count of mātrā-metres;
-- substrate cubical (Voevodsky).  Written 2026-08-23.
--
-- CHECKED: Agda 2.8.0 + agda/cubical, --cubical --safe, no postulates, no
-- holes.
------------------------------------------------------------------------

module Mula.Matrasankhya_TheMatraFibreIsFinOfTheVirahankaNumber where

open import Cubical.Foundations.Prelude using (isContr)
open import Cubical.Foundations.Equiv using (_≃_ ; fiber ; compEquiv ; invEquiv)
open import Cubical.Foundations.Isomorphism using (isoToEquiv)
open import Cubical.Data.Nat using (ℕ ; zero ; suc ; _+_)
open import Cubical.Data.Unit using (Unit)
open import Cubical.Data.Unit.Properties using (isContr→≃Unit)
open import Cubical.Data.Sum using (_⊎_)
open import Cubical.Data.Sum.Properties using (⊎-equiv)
open import Cubical.Data.Fin using (Fin)
open import Cubical.Data.Fin.Properties using (Unit≃Fin1 ; Fin+≅Fin⊎Fin)

open import Mula.Virahanka_TheMatraFibreSatisfiesTheTwoStepRecurrence
  using (छन्दः ; विरहाङ्क-आवृत्तिः ; आदि-शून्यम् ; आदि-एकम्)

-- The mātrā-meru sequence, generated by exactly the fibre recurrence:
-- one empty metre of total 0, one single-laghu metre of total 1, and above
-- that the head is either a laghu on a (1+n)-tail or a guru on an n-tail.
मात्रा-सङ्ख्या : ℕ → ℕ
मात्रा-सङ्ख्या zero          = 1
मात्रा-सङ्ख्या (suc zero)    = 1
मात्रा-सङ्ख्या (suc (suc n)) = मात्रा-सङ्ख्या (suc n) + मात्रा-सङ्ख्या n

-- The count made a type: the fibre over any total n is Fin of that count.
मात्रा-सङ्ख्या-तन्तुः : (n : ℕ) → fiber छन्दः n ≃ Fin (मात्रा-सङ्ख्या n)
मात्रा-सङ्ख्या-तन्तुः zero =
  compEquiv (isContr→≃Unit आदि-शून्यम्) Unit≃Fin1
मात्रा-सङ्ख्या-तन्तुः (suc zero) =
  compEquiv (isContr→≃Unit आदि-एकम्) Unit≃Fin1
मात्रा-सङ्ख्या-तन्तुः (suc (suc n)) =
  compEquiv (विरहाङ्क-आवृत्तिः n)
    (compEquiv
      (⊎-equiv (मात्रा-सङ्ख्या-तन्तुः (suc n)) (मात्रा-सङ्ख्या-तन्तुः n))
      (invEquiv (isoToEquiv
        (Fin+≅Fin⊎Fin (मात्रा-सङ्ख्या (suc n)) (मात्रा-सङ्ख्या n)))))
