{-# OPTIONS --erased-cubical --erasure --guardedness --no-import-sorts #-}

------------------------------------------------------------------------
-- The elder's store, emitted on the act side so the compiled mouth can
-- speak about it.  Generated from machine/library.terms by
-- machine/AgamaLekhaka_...awk — the same 102 pairs the --cubical body
-- judged; one generator, two habitats, and the body's censuses are the
-- knowledge-portion's warrant for whatever the binary reports.
------------------------------------------------------------------------

module AgamaKanda_TheEldersStoreOnTheActSide where

open import Agda.Builtin.Nat using (Nat ; zero ; suc)
open import Agda.Builtin.List using (List ; [] ; _∷_)
open import Agda.Builtin.Sigma using (_,_)
open import KarmaKanda_TheActPortionOfTheBodyPathFreeAndCompiled

आगमः : List Eq'
आगमः = ( (ze ⊕ (var zero)) , (var zero) )
      ∷ ( (mx (var zero) (var zero)) , (var zero) )
      ∷ ( (ze ⊗ (var zero)) , ze )
      ∷ ( ((var zero) ⊖ (var zero)) , ze )
      ∷ ( ((su ze) ⊗ (var zero)) , (var zero) )
      ∷ ( ((var zero) ⊖ (su (var zero))) , ze )
      ∷ ( (lq (su (var zero)) (var zero)) , ze )
      ∷ ( (lq (var zero) (var zero)) , (su ze) )
      ∷ ( ((su ze) ⊕ (var zero)) , (su (var zero)) )
      ∷ ( (mx (var zero) (su (var zero))) , (su (var zero)) )
      ∷ ( (mx (su (var zero)) (var zero)) , (su (var zero)) )
      ∷ ( ((su (var zero)) ⊖ (var zero)) , (su ze) )
      ∷ ( (lq (var zero) (su (var zero))) , (su ze) )
      ∷ ( (su ((var zero) ⊕ (var (suc zero)))) , ((su (var zero)) ⊕ (var (suc zero))) )
      ∷ ( ((var (suc zero)) ⊕ (var zero)) , ((var zero) ⊕ (var (suc zero))) )
      ∷ ( ((var zero) ⊖ (lq (var zero) ze)) , (var zero) )
      ∷ ( ((var zero) ⊗ (lq (var zero) ze)) , ze )
      ∷ ( ((lq (var zero) ze) ⊗ (var zero)) , ze )
      ∷ ( ((var zero) ⊖ (su (su (var zero)))) , ze )
      ∷ ( (lq (su (su (var zero))) (var zero)) , ze )
      ∷ ( (lq (var zero) (su (su (var zero)))) , (su ze) )
      ∷ ( ((su (su ze)) ⊗ (var zero)) , ((var zero) ⊕ (var zero)) )
      ∷ ( ((lq (var zero) ze) ⊖ (var zero)) , (lq (var zero) ze) )
      ∷ ( (lq (var zero) (lq (var zero) ze)) , (lq (var zero) ze) )
      ∷ ( (lq ((var zero) ⊕ (var zero)) ze) , (lq (var zero) ze) )
      ∷ ( (lq ((var zero) ⊕ (var (suc zero))) (var (suc zero))) , (lq (var zero) ze) )
      ∷ ( (mx (var zero) (su (su (var zero)))) , (su (su (var zero))) )
      ∷ ( (mx (su (su (var zero))) (var zero)) , (su (su (var zero))) )
      ∷ ( ((su (su (var zero))) ⊖ (var zero)) , (su (su ze)) )
      ∷ ( (lq (lq (var zero) ze) (var zero)) , (lq (su ze) (var zero)) )
      ∷ ( (lq (lq (var zero) ze) ze) , (lq (su ze) (var zero)) )
      ∷ ( (mx (var zero) (lq (var zero) ze)) , (mx (var zero) (su ze)) )
      ∷ ( (mx (lq (var zero) ze) (var zero)) , (mx (var zero) (su ze)) )
      ∷ ( (su ((var zero) ⊖ (su ze))) , (mx (var zero) (su ze)) )
      ∷ ( ((var (suc zero)) ⊕ ((var zero) ⊕ (var zero))) , ((var zero) ⊕ ((var zero) ⊕ (var (suc zero)))) )
      ∷ ( (su ze) , (lq (var zero) ((var zero) ⊕ (var (suc zero)))) )
      ∷ ( ((var zero) ⊕ ((var (suc zero)) ⊕ (var (suc (suc zero))))) , (((var zero) ⊕ (var (suc zero))) ⊕ (var (suc (suc zero)))) )
      ∷ ( (lq (var zero) (var (suc (suc zero)))) , (lq ((var zero) ⊕ (var (suc zero))) ((var (suc (suc zero))) ⊕ (var (suc zero)))) )
      ∷ ( ((var (suc zero)) ⊕ ((var zero) ⊗ (var (suc zero)))) , ((su (var zero)) ⊗ (var (suc zero))) )
      ∷ ( (mx ((var zero) ⊕ (var (suc zero))) (var zero)) , ((var zero) ⊕ (var (suc zero))) )
      ∷ ( (mx (var zero) (lq (su ze) (var zero))) , (var zero) )
      ∷ ( ((var zero) ⊖ (su ((var zero) ⊕ (var (suc zero))))) , ze )
      ∷ ( ((var zero) ⊖ (su (su (su (var zero))))) , ze )
      ∷ ( ((lq (var zero) ze) ⊖ (su (var zero))) , ze )
      ∷ ( (lq (mx (var zero) (su (var (suc zero)))) ze) , ze )
      ∷ ( (lq (mx (su (var zero)) (var (suc zero))) ze) , ze )
      ∷ ( (lq (su ((var zero) ⊕ (var (suc zero)))) (var zero)) , ze )
      ∷ ( (lq (su ((var zero) ⊕ (var (suc zero)))) (var (suc zero))) , ze )
      ∷ ( (lq (su (su (su (var zero)))) (var zero)) , ze )
      ∷ ( (mx (lq (var zero) ze) (su (var zero))) , (su (var zero)) )
      ∷ ( (mx (su (var zero)) (lq (var zero) ze)) , (su (var zero)) )
      ∷ ( (mx (su (var zero)) (lq (var (suc zero)) ze)) , (su (var zero)) )
      ∷ ( (lq (var zero) (su ((var zero) ⊕ (var (suc zero))))) , (su ze) )
      ∷ ( (lq (var zero) (su (su (su (var zero))))) , (su ze) )
      ∷ ( (lq (lq (var zero) ze) (su (var zero))) , (su ze) )
      ∷ ( (lq (lq (var zero) ze) (su (var (suc zero)))) , (su ze) )
      ∷ ( (lq (lq (su ze) (var zero)) (var zero)) , (su ze) )
      ∷ ( ((var zero) ⊗ (mx (var zero) (su ze))) , ((var zero) ⊗ (var zero)) )
      ∷ ( ((mx (var zero) (su ze)) ⊗ (var zero)) , ((var zero) ⊗ (var zero)) )
      ∷ ( (lq (lq (su ze) (var zero)) ze) , (lq (var zero) ze) )
      ∷ ( ((var zero) ⊖ (lq (su ze) (var zero))) , ((var zero) ⊖ (su ze)) )
      ∷ ( (lq ((var zero) ⊕ ((var zero) ⊗ (var zero))) ze) , (lq (var zero) ze) )
      ∷ ( (lq ((var zero) ⊕ ((var zero) ⊗ (var (suc zero)))) ze) , (lq (var zero) ze) )
      ∷ ( (lq ((var zero) ⊖ (su ze)) (var (suc zero))) , (lq (var zero) (su (var (suc zero)))) )
      ∷ ( (lq (var zero) (lq (su ze) (var zero))) , (lq (var zero) (su ze)) )
      ∷ ( (lq ((var zero) ⊕ (var (suc zero))) (su (var (suc zero)))) , (lq (var zero) (su ze)) )
      ∷ ( (lq ((var zero) ⊖ (su ze)) ze) , (lq (var zero) (su ze)) )
      ∷ ( (lq (su ze) ((var zero) ⊗ (var zero))) , (lq (su ze) (var zero)) )
      ∷ ( (lq (su ze) ((var zero) ⊕ (var zero))) , (lq (su ze) (var zero)) )
      ∷ ( (mx (var zero) (su ((var zero) ⊕ (var (suc zero))))) , (su ((var zero) ⊕ (var (suc zero)))) )
      ∷ ( (mx (su ((var zero) ⊕ (var (suc zero)))) (var zero)) , (su ((var zero) ⊕ (var (suc zero)))) )
      ∷ ( (mx (var zero) (su (su (su (var zero))))) , (su (su (su (var zero)))) )
      ∷ ( (mx (su (su (su (var zero)))) (var zero)) , (su (su (su (var zero)))) )
      ∷ ( ((su (su (su (var zero)))) ⊖ (var zero)) , (su (su (su ze))) )
      ∷ ( (mx ((var zero) ⊕ (var zero)) (su ze)) , ((var zero) ⊕ (mx (var zero) (su ze))) )
      ∷ ( (mx ((var zero) ⊕ (var (suc zero))) (su (var zero))) , ((var zero) ⊕ (mx (var (suc zero)) (su ze))) )
      ∷ ( ((var zero) ⊕ ze) , (var zero) )
      ∷ ( ((var zero) ⊗ ze) , ze )
      ∷ ( (((var zero) ⊗ (var (suc zero))) ⊕ ((var zero) ⊗ ze)) , ((var zero) ⊗ ((var (suc zero)) ⊕ ze)) )
      ∷ ( (mx (ze ⊕ ze) ((var zero) ⊕ ze)) , ((mx ze (var zero)) ⊕ ze) )
      ∷ ( (((var zero) ⊕ (var zero)) ⊗ (var (suc zero))) , ((var zero) ⊗ ((var (suc zero)) ⊕ (var (suc zero)))) )
      ∷ ( (mx ze (var zero)) , (var zero) )
      ∷ ( (ze ⊖ (var zero)) , ze )
      ∷ ( ((var zero) ⊗ (lq ze ze)) , (var zero) )
      ∷ ( (mx (var zero) ((var (suc zero)) ⊗ ze)) , (var zero) )
      ∷ ( (mx (ze ⊕ (var zero)) (var zero)) , (var zero) )
      ∷ ( ((var zero) ⊗ (ze ⊕ ze)) , ze )
      ∷ ( (((var zero) ⊗ (var (suc zero))) ⊗ ze) , ze )
      ∷ ( (mx ze ((var zero) ⊗ ze)) , ze )
      ∷ ( (lq ((var zero) ⊗ ze) (var (suc zero))) , (su ze) )
      ∷ ( (lq ((var zero) ⊗ ze) ze) , (su ze) )
      ∷ ( (((var zero) ⊗ ze) ⊗ ((var zero) ⊗ ze)) , ze )
      ∷ ( (((var zero) ⊗ ze) ⊕ (((var zero) ⊗ ze) ⊗ (su ((var zero) ⊗ ze)))) , ze )
      ∷ ( ((((var zero) ⊗ ze) ⊗ ((var zero) ⊗ ze)) ⊗ (((var zero) ⊗ ze) ⊗ ((var zero) ⊗ ze))) , ze )
      ∷ ( ((ze ⊖ (var zero)) ⊗ ze) , ze )
      ∷ ( (ze ⊖ ((var zero) ⊗ ze)) , ze )
      ∷ ( (mx (var (suc (suc (suc (suc (suc (suc zero))))))) ze) , (var (suc (suc (suc (suc (suc (suc zero))))))) )
      ∷ ( (lq (su (var (suc zero))) ze) , ze )
      ∷ ( (lq ze (var (suc zero))) , (su ze) )
      ∷ ( ((var zero) ⊗ (su ze)) , (var zero) )
      ∷ ( (lq (su ze) (su (var (suc zero)))) , (su ze) )
      ∷ ( (mx (su (var (suc (suc (suc (suc (suc (suc zero)))))))) (su ze)) , (su (var (suc (suc (suc (suc (suc (suc zero)))))))) )
      ∷ []
