// Checks transport/serialization/verification only. No miner is implemented here.
import test from 'node:test';
import assert from 'node:assert/strict';
import {GENESIS,GENESIS_HASH,compact,hashHeader,validateJob,inputSource,constantsSource,gateSource,link,validateHeader,verifyResults,verifyGate,bitsOf} from './mining.mjs';
const raw={format:'bitcoin-native-job-v1',job_id:'mainnet-genesis-full-nonce',network:'mainnet',headers:[GENESIS],nonce:{base:'00000000',mask:'ffffffff'},max_solutions:1};
const job=()=>validateJob(structuredClone(raw));
const list=bs=>bs.reduceRight((tail,b)=>`#Con{${b},${tail}}`,'#Nil');
const hit=`#Hit{${list(bitsOf(Buffer.from(GENESIS,'hex')))},#PLm{λi.1}}`;
test('real Bitcoin genesis bytes and hash',()=>{assert.equal(GENESIS.length,160);assert.equal(hashHeader(GENESIS),GENESIS_HASH);});
test('compact target',()=>{assert.equal(compact('1d00ffff').toString(16),'ffff'+'00'.repeat(26));assert.equal(compact('01123456'),0x12n);assert.equal(compact('02008000'),0x80n);});
test('invalid targets fail closed',()=>{for(const n of ['00000000','1d80ffff','23000001','22000100','21010000'])assert.throws(()=>compact(n));});
test('full 32-bit family without enumerated candidates',()=>{const j=job(),s=inputSource(j);assert.equal(j.candidate_count,'4294967296');assert.equal((s.match(/&BTCnonce\d+\{/g)||[]).length,32);assert.ok(s.length<20000);assert.ok(s.includes('@btcCandidates = @DbtcAppend(@btcPrefixes, @btcNonces)'));});
test('fixed nonce is exactly one header',()=>{const j=validateJob({...raw,nonce:{base:'7c2bac1d',mask:'00000000'}});assert.equal(j.candidate_count,'1');assert.equal((inputSource(j).match(/&BTCnonce/g)||[]).length,0);assert.equal(validateHeader(j,GENESIS).nonce,2083236893);});
test('nonce base cannot overlap free bits',()=>assert.throws(()=>validateJob({...raw,nonce:{base:'00000001',mask:'ffffffff'}})));
test('templates retain family selection',()=>{const h='02000000'+GENESIS.slice(8);const j=validateJob({...raw,headers:[GENESIS,h]});assert.equal(j.candidate_count,'8589934592');assert.match(inputSource(j),/&BTCtemplate0\{/);});
test('same-prefix histories are not silently deduplicated',()=>assert.throws(()=>validateJob({...raw,headers:[GENESIS,GENESIS.slice(0,152)+'00000000']})));
test('immutable parent/difficulty are not free variables',()=>{assert.throws(()=>validateJob({...raw,headers:[GENESIS,GENESIS.slice(0,8)+'ff'+GENESIS.slice(10)]}));assert.throws(()=>validateJob({...raw,headers:[GENESIS,GENESIS.slice(0,144)+'feff001d'+GENESIS.slice(152)]}));});
test('job width, network, and invented semantics are rejected',()=>{assert.throws(()=>validateJob({...raw,headers:[GENESIS.slice(2)]}));assert.throws(()=>validateJob({...raw,network:'guessed-network'}));assert.throws(()=>validateJob({...raw,rounds:4}));assert.throws(()=>validateJob({...raw,target:'ff'.repeat(32)}));});
test('pool shares cannot masquerade as network blocks',()=>{const j=validateJob({...raw,share_target:'ff'.repeat(32)});const h=GENESIS.slice(0,152)+'00000000';assert.equal(validateHeader(j,h).meets_search_target,true);assert.equal(validateHeader(j,h).meets_block_target,false);});
test('host never supplies a known nonce to the full-family input',()=>{const s=inputSource(job());assert.ok(!s.includes('2083236893'));assert.ok(!s.includes(GENESIS_HASH));});
test('full-runtime linker refuses erased/missing-entry output',()=>{assert.throws(()=>link('@main = 0',''));assert.throws(()=>link('// FULL RUNTIME\n@coe = 0\n@main = 0',''));const s=link('// FULL RUNTIME\n@coe = 0\n@DbtcRun = 0\n@main = 0',inputSource(job()));assert.match(s,/@btcLibraryMain = 0/);assert.equal((s.match(/^@main\s*=/gm)||[]).length,1);});
test('all SHA constants, fixed padding and six native gates are generated',()=>{const s=constantsSource();assert.match(s,/def btcK/);assert.match(s,/def btcPad80/);assert.match(s,/def btcPad32/);assert.match(gateSource(),/btcRestore/);});
test('native gate framing',()=>{const pt=bs=>'#Pair{#List{#Bool{}},'+list(bs)+'}';assert.deepEqual(verifyGate(pt([1,1,1,1,1,1])+'\n- Itrs: 123\n'),[1,1,1,1,1,1]);assert.throws(()=>verifyGate(pt([1,1,1,0,1,1])));assert.throws(()=>verifyGate('ERROR: '+pt([1,1,1,1,1,1])));assert.throws(()=>verifyGate(list([1,1,1,1,1,1])));assert.deepEqual(verifyGate(pt([1,1,1,1,1,1]).replace('#Nil','#Nil{}')),[1,1,1,1,1,1]);});
test('a native-shaped receipt is independently checked, not trusted',()=>{const out=verifyResults(job(),hit+'\n- Itrs: 123\n');assert.equal(out.length,1);assert.equal(out[0].hash,GENESIS_HASH);assert.equal(out[0].meets_block_target,true);assert.throws(()=>validateHeader(job(),GENESIS.slice(0,152)+'00000000'));});
test('unresolved, duplicate, malformed and erased receipt outputs fail',()=>{assert.throws(()=>verifyResults(job(),hit+'\n'+hit));assert.throws(()=>verifyResults(job(),hit.replace('#PLm{λi.1}','&{}')));assert.throws(()=>verifyResults(job(),hit.slice(0,-1)));assert.throws(()=>verifyResults(job(),'#StuckCoe{}'));});
test('empty native output differs from an error message',()=>{assert.deepEqual(verifyResults(job(),'- Itrs: 123\n'),[]);assert.throws(()=>verifyResults(job(),'Out of memory'));});
