-- LANDED BY रात्रिः on 2026-08-22T06:20:57Z.
-- निर्धारण probe accepted by the kernel; see notes/ratri for the pass.
-- Generated by निर्धारण, then CHECKED IN PLACE before landing.  Not
-- hand-written; the only edit is qualifying the module name to its
-- path.  Never overwritten by a later pass.
{-# OPTIONS --cubical --safe --guardedness #-}
module Ratri.Anirdharita_EGBRootedNet_Jewel_NirdharanaPthreeD where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat
open import Cubical.Data.Bool
open import Cubical.Data.Empty
open import EGBRootedNet

censusR0 censusR1 : Jewel
censusR0 = record { centre = 0 ; radius = 0 }
censusR1 = record { centre = 1 ; radius = 0 }

censusAgree-0 : Jewel.radius censusR0 ≡ Jewel.radius censusR1
censusAgree-0 = refl

-- THE VERDICT.  Green here means the field is NOT determined:
-- two inhabitants agree on every other field and are distinct.
NOT-DETERMINED : censusR0 ≡ censusR1 → ⊥
NOT-DETERMINED censusP = znots (cong Jewel.centre censusP)
