-- LANDED BY रात्रिः on 2026-08-22T06:20:59Z.
-- निर्धारण probe accepted by the kernel; see notes/ratri for the pass.
-- Generated by निर्धारण, then CHECKED IN PLACE before landing.  Not
-- hand-written; the only edit is qualifying the module name to its
-- path.  Never overwritten by a later pass.
{-# OPTIONS --cubical --safe --guardedness #-}
module Ratri.Anirdharita_KloostermanExponents_ℤ±_NirdharanaPthreeF where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat
open import Cubical.Data.Bool
open import Cubical.Data.Empty
open import KloostermanExponents

censusR0 censusR1 : ℤ±
censusR0 = record { up = 0 ; dn = 0 }
censusR1 = record { up = 1 ; dn = 0 }

censusAgree-0 : ℤ±.dn censusR0 ≡ ℤ±.dn censusR1
censusAgree-0 = refl

-- THE VERDICT.  Green here means the field is NOT determined:
-- two inhabitants agree on every other field and are distinct.
NOT-DETERMINED : censusR0 ≡ censusR1 → ⊥
NOT-DETERMINED censusP = znots (cong ℤ±.up censusP)
