-- LANDED BY ‡∞‡æ‡‡‡∞‡ø‡ on 2026-08-22T06:24:21Z.
-- ‡®‡ø‡∞‡‡ß‡æ‡∞‡ probe accepted by the kernel; see notes/ratri for the pass.
-- Generated by ‡®‡ø‡∞‡‡ß‡æ‡∞‡, then CHECKED IN PLACE before landing.  Not
-- hand-written; the only edit is qualifying the module name to its
-- path.  Never overwritten by a later pass.
{-# OPTIONS --cubical --safe --guardedness #-}
module Ratri.Anirdharita_Ratri-Nirdharita_VivekaPramana_TheRemainderIsLawfulAndTheNetBeats_NirdharanaPoneC_CensusBase_NirdharanaPthreeAF where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat
open import Cubical.Data.Bool
open import Cubical.Data.Empty
open import Ratri.Nirdharita_VivekaPramana_TheRemainderIsLawfulAndTheNetBeats_NirdharanaPoneC

censusR0 censusR1 : CensusBase
censusR0 = record { ‡§∏‡§Æ = 0 ; ‡§µ‡§æ‡§Æ = 0 }
censusR1 = record { ‡§∏‡§Æ = 0 ; ‡§µ‡§æ‡§Æ = 1 }

censusAgree-0 : CensusBase.‡§∏‡§Æ censusR0 ‚â° CensusBase.‡§∏‡§Æ censusR1
censusAgree-0 = refl

-- THE VERDICT.  Green here means the field is NOT determined:
-- two inhabitants agree on every other field and are distinct.
NOT-DETERMINED : censusR0 ‚â° censusR1 ‚Üí ‚ä•
NOT-DETERMINED censusP = znots (cong CensusBase.‡§µ‡§æ‡§Æ censusP)
