-- LANDED BY रात्रिः on 2026-08-22T06:24:13Z.
-- निर्धारण probe accepted by the kernel; see notes/ratri for the pass.
-- Generated by निर्धारण, then CHECKED IN PLACE before landing.  Not
-- hand-written; the only edit is qualifying the module name to its
-- path.  Never overwritten by a later pass.
{-# OPTIONS --cubical --safe --guardedness #-}
module Ratri.Nirdharita_Agda-Builtin-Nat_NirdharanaPoneA_NirdharanaPoneA where

open import Cubical.Foundations.Prelude
open import Cubical.Foundations.Isomorphism
open import Cubical.Foundations.Equiv
open import Cubical.Data.Sigma
open import FactoryVICoolingKill
open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat using (ℕ; zero; suc; _+_; _·_)
open import Cubical.Data.Nat.Properties using (·-assoc; ·-identityˡ; ·-identityʳ; +-suc)
open import Agda.Builtin.Nat using (_<_; _==_)
open import Cubical.Data.Bool using (Bool; true; false; if_then_else_)
open CoolingCountermodel

record CensusBase : Type where
  field
    a : ℕ
    M : ℕ
    a>1 : (1 < a) ≡ true
    Z0-nonzero : (0 < M) ≡ true
    Z0-large : (1 < M) ≡ true
    Z3-below-1 : (M < a ^ 3) ≡ true
    unitless : units a M ≡ 0

censusFam : CensusBase → Type
censusFam censusB = let a = CensusBase.a censusB ; M = CensusBase.M censusB ; a>1 = CensusBase.a>1 censusB ; Z0-nonzero = CensusBase.Z0-nonzero censusB ; Z0-large = CensusBase.Z0-large censusB ; Z3-below-1 = CensusBase.Z3-below-1 censusB ; unitless = CensusBase.unitless censusB in ℕ

censusF : (censusB : CensusBase) → censusFam censusB
censusF censusB = let a = CensusBase.a censusB ; M = CensusBase.M censusB ; a>1 = CensusBase.a>1 censusB ; Z0-nonzero = CensusBase.Z0-nonzero censusB ; Z0-large = CensusBase.Z0-large censusB ; Z3-below-1 = CensusBase.Z3-below-1 censusB ; unitless = CensusBase.unitless censusB in a ^ 3

censusΣ : Type
censusΣ = Σ[ censusB ∈ CensusBase ] (Σ[ censusY ∈ censusFam censusB ] (censusF censusB ≡ censusY))

censusContract : censusΣ ≃ CensusBase
censusContract = Σ-contractSnd (λ censusB → isContrSingl (censusF censusB))

censusTo : CoolingCountermodel → censusΣ
censusTo censusR =
  record { a = CoolingCountermodel.a censusR ; M = CoolingCountermodel.M censusR ; a>1 = CoolingCountermodel.a>1 censusR ; Z0-nonzero = CoolingCountermodel.Z0-nonzero censusR ; Z0-large = CoolingCountermodel.Z0-large censusR ; Z3-below-1 = CoolingCountermodel.Z3-below-1 censusR ; unitless = CoolingCountermodel.unitless censusR } , ( CoolingCountermodel.X censusR , CoolingCountermodel.cube censusR )

censusFrom : censusΣ → CoolingCountermodel
censusFrom (censusB , (censusY , censusP)) =
  record { a = CensusBase.a censusB ; M = CensusBase.M censusB ; a>1 = CensusBase.a>1 censusB ; Z0-nonzero = CensusBase.Z0-nonzero censusB ; Z0-large = CensusBase.Z0-large censusB ; Z3-below-1 = CensusBase.Z3-below-1 censusB ; unitless = CensusBase.unitless censusB ; X = censusY ; cube = censusP }

censusReshuffle : Iso (CoolingCountermodel) censusΣ
Iso.fun      censusReshuffle = censusTo
Iso.inv      censusReshuffle = censusFrom
Iso.rightInv censusReshuffle _ = refl
Iso.leftInv  censusReshuffle _ = refl

-- THE VERDICT.  Green here is the equivalence itself.
DETERMINED : (CoolingCountermodel) ≃ CensusBase
DETERMINED = compEquiv (isoToEquiv censusReshuffle) censusContract
