# आगम-लेखकः — the elder emits its store as raw encounters for the one
# body.  Compound built here, 2026-08-24; not a source term.
#
# Reads machine/library.terms (small<TAB>large[<TAB>provenance]) and
# emits an Agda module carrying the unique pairs as a List Eq' — bare
# utterances, no authority: the one body's own knowing (RatnaTraya's
# ग्रहणम् / a per-item judge) decides what becomes नियमः.  Rules
# naming gcd are outside the body's present vocabulary (Tm has no gcd
# constructor); they are counted and left with the elder — the
# vocabulary frontier, stated, not hidden.
#
# Usage: awk -f machine/AgamaLekhaka_...awk machine/library.terms

BEGIN { FS = "\t"; n = 0; skipped = 0 }

/^#/            { next }
/gcd\(|c[0-9]\(/ { skipped++; next }   # gcd and the completion's fresh constants: outside Tm's vocabulary
NF >= 2 {
  key = $1 "\t" $2
  if (seen[key]++) next
  big  = translate($2)
  small = translate($1)
  pairs[n++] = "( " big " , " small " )"
}

END {
  print "-- generated by machine/AgamaLekhaka_TheElderEmitsItsStoreAsRawEncountersForTheOneBody.awk"
  print "-- from machine/library.terms; " n " unique pairs; " skipped " gcd lines outside vocabulary, left with the elder"
  print "आगमः : List Eq'"
  for (i = 0; i < n; i++) {
    prefix = (i == 0) ? "आगमः = " : "      ∷ "
    print prefix pairs[i]
  }
  print "      ∷ []"
}

function translate(s) { STR = s; POS = 1; return pterm() }

function pterm(   c, l, r, v) {
  c = substr(STR, POS, 1)
  if (c == "0") { POS++; return "ze" }
  if (c == "s") { POS += 2; l = pterm(); POS++; return "(su " l ")" }
  if (c == "+") { POS += 2; l = pterm(); POS++; r = pterm(); POS++; return "(" l " ⊕ " r ")" }
  if (c == "*") { POS += 2; l = pterm(); POS++; r = pterm(); POS++; return "(" l " ⊗ " r ")" }
  if (c == "-") { POS += 2; l = pterm(); POS++; r = pterm(); POS++; return "(" l " ⊖ " r ")" }
  if (c == "m") { POS += 4; l = pterm(); POS++; r = pterm(); POS++; return "(mx " l " " r ")" }
  if (c == "l") { POS += 3; l = pterm(); POS++; r = pterm(); POS++; return "(lq " l " " r ")" }
  v = index("xyzuvw", c) - 1
  POS++
  while (substr(STR, POS, 1) == "'") { v += 6; POS++ }   # the completion's primed variables
  return "(var " v ")"
}
