-- ॥ बीजम् ॥  One machine, one law: which side of `f a ≡ b` is bound is everything.
-- Output bound: singl (f a), contractible — the datum rides free.  Input bound:
-- fiber f b — the loss, and the subject.  Memory, charge, symmetry, price,
-- distance, verdict: six readings of the one fibre.  The kernel decides truth;
-- carriers ask and generate.  This file is one naya, true and not whole.

-- दृष्टि-जालम् — the net of views.
--
-- दृष्टि (dṛṣṭi, a view or standpoint) is shared technical vocabulary across
-- the darśanas; जाल (jāla) is a net.  The compound is built here and is not
-- taken from a text.  `notes/ForStephen_...` already drew the resonance with
-- the Avataṃsaka's net of Indra — every jewel reflecting every other — and
-- that resonance is a reader's, not a citation.
--
-- WHAT THIS COMPUTES, and it is the thing the previous instrument could not.
--
-- `Drashta_...` takes a list of observers somebody thought of and decides,
-- for each, whether it sees a law.  That is a sample of observer space.  This
-- computes ALL OF IT:
--
--     every law the rule can present to ANY observer whatsoever,
--     exhaustively, with the exact information cost of each.
--
-- An observer's class is a partition of the state space.  It sees a law
-- exactly when that partition is a CONGRUENCE for the rule
-- (`formal/cubical/Anuvrtti_...`).  So the complete catalogue of possible
-- observed physics for a rule is the LATTICE OF ITS CONGRUENCES — top is
-- "see every state" (the law is the rule itself), bottom is "see nothing"
-- (the law is trivial), and everything between is an emergent law whose cost
-- in bits is log₂ of its block count.
--
-- Two directions, both exact, both finite:
--
--   * व्याप्तिः (downward).  Given a pair of states an observer wants to
--     identify, the LEAST congruence identifying it is the closure of that
--     pair under the rule — identify (a,b) and you are forced to identify
--     (f a, f b) and so on, and nothing else.  Constructed and proved least
--     in `formal/cubical/Vyapti_TheLeastCongruenceContainingAPairIs
--     ConstructedAndIsTheMinimalSeparatingQuery.agda`.  Here it is union-find
--     with a worklist, which is that proof compiled.
--
--   * परिष्कारः (upward).  Given an observer that sees no law, the COARSEST
--     congruence refining it is partition refinement — split any block whose
--     image spans two blocks, repeat.  That is the MINIMAL SEPARATING QUERY:
--     not "you need more information", but exactly this much and no more.
--     `QuotientFiberLaw` says visibility returns only by a separating query.
--     This computes the query.
--
-- The join-irreducible congruences are the ones generated by a single pair,
-- so enumerating the principal congruences over all pairs and deduplicating
-- gives the generating set of the whole lattice, and its minimal elements are
-- the lattice's atoms — the FINEST nontrivial laws the rule admits.
--
-- Every number printed is a finite exhaustive computation over all 2^w
-- states.  Nothing is sampled.
--
-- Run:
--   runghc machine/DrshtiJala_TheCompleteLatticeOfEveryLawARuleCanPresentToAnyObserver.hs 110 8
--   runghc machine/DrshtiJala_...hs sweep 6
module Main (main) where

import System.Environment (getArgs)
import System.IO (hSetEncoding, stdout, utf8)
import Data.Bits (testBit)
import Data.List (sort, nub, sortOn, group, intercalate, minimumBy)
import Data.Ord (comparing)
import qualified Data.Map.Strict as M

-- --------------------------------------------------------------- the rule
-- states are the 2^w rows, held as integers; bit i is cell i.
type St = Int

stepOf :: Int -> Int -> St -> St
stepOf r w x = foldr set 0 [0 .. w-1]
  where
    at i = testBit x ((i + w) `mod` w)
    set i acc =
      let a = at (i-1); b = at i; c = at (i+1)
          k = (if a then 4 else 0) + (if b then 2 else 0) + (if c then 1 else 0)
      in if testBit r k then acc + 2 ^ i else acc

-- ------------------------------------------------------------ partitions
-- a partition is given by its class map, normalised so class ids are
-- 0,1,2,… in order of first appearance.  Then equal partitions are equal
-- lists, and dedup is free.
type Part = [Int]

normalise :: Ord a => [a] -> Part
normalise xs = map (ren M.!) xs
  where ren = M.fromList (zip (nub xs) [0 .. ])

blocks :: Part -> Int
blocks p = length (nub p)

-- ------------------------------------------------- व्याप्तिः, the downward
-- least congruence identifying a pair: union-find with a worklist, which is
-- exactly the closure the Agda module builds.
principal :: (St -> St) -> Int -> (St, St) -> Part
principal f n (a0, b0) = normalise (go (M.fromList [(i,i) | i <- [0..n-1]]) [(a0,b0)])
  where
    root m i = if m M.! i == i then i else root m (m M.! i)
    go m [] = [ root m i | i <- [0 .. n-1] ]
    go m ((x,y):q) =
      let rx = root m x; ry = root m y
      in if rx == ry then go m q
         else go (M.insert rx ry m) ((f x, f y) : q)

-- ------------------------------------------------ परिष्कारः, the upward
-- coarsest congruence refining a given partition: split until every block's
-- image lies in one block.  This is the minimal separating query.
refine :: (St -> St) -> Int -> Part -> Part
refine f n p =
  let p' = normalise [ (p !! i, p !! f i) | i <- [0 .. n-1] ]
  in if blocks p' == blocks p then p else refine f n p'

isCong :: (St -> St) -> Int -> Part -> Bool
isCong f n p = blocks (refine f n p) == blocks p

-- ---------------------------------------------- joins, and the cheapest eye
-- close a partition under one further identification: union-find seeded with
-- the partition itself, so this computes the JOIN of p with the principal
-- congruence of (a,b).
closeFrom :: (St -> St) -> Int -> Part -> (St, St) -> Part
closeFrom f n p (a0, b0) = normalise (go seed [(a0, b0)])
  where
    seed = M.fromList [ (i, head [ j | j <- [0 .. n-1], p !! j == p !! i ]) | i <- [0 .. n-1] ]
    root m i = if m M.! i == i then i else root m (m M.! i)
    go m [] = [ root m i | i <- [0 .. n-1] ]
    go m ((x,y):q) =
      let rx = root m x; ry = root m y
      in if rx == ry then go m q
         else go (M.insert rx ry m) ((f x, f y) : q)

-- THE CHEAPEST EYE THAT STILL SEES A GIVEN DISTINCTION.  Merge greedily,
-- keeping only merges that leave a and b in different classes.  The result is
-- a MAXIMAL congruence separating them (maximal, not the maximum -- greedy
-- gives one of possibly several, and that is said rather than hidden), so its
-- block count is an upper bound on how cheap such an observer can be.
cheapestEye :: (St -> St) -> Int -> (St, St) -> Part
cheapestEye f n (a, b) = foldl try (normalise [0 .. n-1]) pairs
  where
    pairs = [ (x,y) | x <- [0 .. n-1], y <- [x+1 .. n-1] ]
    try p xy =
      let q = closeFrom f n p xy
      in if q !! a == q !! b then p else q

-- --------------------------------------------------------- the lattice
-- every congruence generated by one pair; the lattice's join-irreducibles.
principals :: (St -> St) -> Int -> [Part]
principals f n = nub [ principal f n (a,b) | a <- [0 .. n-1], b <- [a+1 .. n-1] ]

-- ---------------------------------------------------------------- display
lawOf :: (St -> St) -> Int -> Part -> [(Int, Int)]
lawOf f n p = nub [ (p !! i, p !! f i) | i <- [0 .. n-1] ]

showLaw :: [(Int,Int)] -> String
showLaw ps
  | length ps > 12 = intercalate " " [ show a ++ "→" ++ show b | (a,b) <- take 12 ps ] ++ " …"
  | otherwise      = intercalate " " [ show a ++ "→" ++ show b | (a,b) <- ps ]

-- the observers from the previous instrument, as partitions
liveOf :: Int -> St -> Int
liveOf w x = length [ () | i <- [0..w-1], testBit x i ]

wallsOf :: Int -> St -> Int
wallsOf w x = length [ () | i <- [0..w-1], testBit x i /= testBit x ((i+1) `mod` w) ]

namedObservers :: Int -> [(String, St -> Int)]
namedObservers w =
  [ ("ω  live cells",   liveOf w)
  , ("ω mod 2",         \x -> liveOf w x `mod` 2)
  , ("walls",           wallsOf w)
  , ("is empty",        \x -> if x == 0 then 1 else 0)
  ]

detail :: Int -> Int -> IO ()
detail r w = do
  let n  = 2 ^ w
      f  = stepOf r w
      ps = principals f n
      nontrivial = [ p | p <- ps, blocks p > 1 ]
      coarsest = minimumBy (comparing blocks) nontrivial
      atoms = let m = maximum (map blocks nontrivial)
              in [ p | p <- nontrivial, blocks p == m ]
  putStrLn ("rule " ++ show r ++ ", width " ++ show w ++ ", "
            ++ show n ++ " states — everything below is exhaustive.\n")

  putStrLn ("  distinct congruences generated by a single pair: " ++ show (length ps))
  putStrLn  "  (these are the lattice's join-irreducibles: every law the rule can"
  putStrLn  "   present to any observer is a join of them.)\n"

  putStrLn ("  COARSEST LAW FROM A SINGLE IDENTIFICATION — the most an observer")
  putStrLn ("  can discard by deciding to confuse ONE pair: " ++ show (blocks coarsest)
            ++ " classes, " ++ show (ceilLog2 (blocks coarsest)) ++ " bit(s).")
  putStrLn  "  (joins of these go coarser still; this is the single-pair floor.)"
  putStrLn ("    law: " ++ showLaw (lawOf f n coarsest))
  putStrLn ("    classes: " ++ showClasses w coarsest)
  putStrLn ""

  putStrLn ("  THE FINEST NONTRIVIAL LAWS (the lattice's atoms, "
            ++ show (length atoms) ++ " of them, "
            ++ show (blocks (head atoms)) ++ " classes each):")
  putStrLn ("    one of them merges only: " ++ mergedPairs w (head atoms))
  putStrLn ""

  putStrLn "  THE CHEAPEST EYE THAT STILL SEES A GIVEN DISTINCTION — merge as much"
  putStrLn "  as possible while keeping two designated states apart AND keeping a law:"
  mapM_ (eye f n w)
    [ ((0, 1), "the empty row vs one live cell")
    , ((0, n-1), "the empty row vs the full row")
    , ((1, 2), "one live cell vs another") ]
  putStrLn ""

  putStrLn "  MINIMAL SEPARATING QUERY — for observers that see no law, exactly"
  putStrLn "  how much more they must resolve before one appears:"
  mapM_ (sep f n w) (namedObservers w)

  where
    ceilLog2 k = head [ b | b <- [0 :: Int ..], 2 ^ b >= k ]

    eye f n w2 ((a,b), nm) = do
      let p = cheapestEye f n (a,b)
      putStrLn ("    " ++ pad 36 nm ++ show (blocks p) ++ " classes ("
                ++ show (ceilLog2 (blocks p)) ++ " bits) suffice — maximal, greedy.")
      where _ = (w2 :: Int)

    sep f n w2 (nm, o) = do
      let p  = normalise [ o i | i <- [0 .. n-1] ]
          q  = refine f n p
      if blocks q == blocks p
        then putStrLn ("    ✓ " ++ pad 16 nm ++ show (blocks p)
                       ++ " classes — already a law, nothing to add.")
        else putStrLn ("    ✗ " ++ pad 16 nm ++ show (blocks p)
                       ++ " classes → must resolve to " ++ show (blocks q)
                       ++ ".  Extra cost: "
                       ++ show (ceilLog2 (blocks q) - ceilLog2 (blocks p))
                       ++ " bit(s), and that is the minimum.")
      where _ = (w2 :: Int)

    pad k s = s ++ replicate (k - length s) ' '

    showClasses w' p =
      let n = length p
          cls = [ [ i | i <- [0..n-1], p !! i == c ] | c <- [0 .. blocks p - 1] ]
      in intercalate " | " [ show (length c) ++ " states" | c <- take 6 cls ]
         ++ (if blocks p > 6 then " | …" else "")
      where _ = w'

    mergedPairs w' p =
      let n = length p
          cls = [ [ i | i <- [0..n-1], p !! i == c ] | c <- [0 .. blocks p - 1] ]
          big = [ c | c <- cls, length c > 1 ]
      in intercalate ", " [ intercalate "≡" (map (row w') c) | c <- take 4 big ]

    row w' x = [ if testBit x i then '█' else '·' | i <- [0 .. w'-1] ]

-- --------------------------------------------------------------- the sweep
sweep :: Int -> IO ()
sweep w = do
  let n = 2 ^ w
  putStrLn ("all 256 elementary rules at width " ++ show w ++ " ("
            ++ show n ++ " states).  For each rule: how many distinct laws it")
  putStrLn  "can present to a single-pair observer, and the cheapest nontrivial"
  putStrLn  "one it admits (fewest classes = most an observer may discard).\n"
  putStrLn ("  rule   join-irreducibles   cheapest law (classes)")
  mapM_ (line n) [0 .. 255]
  putStrLn "\n  exhaustive over every state, for every rule.  No sampling."
  where
    line n r = do
      let f  = stepOf r w
          ps = principals f n
          nt = [ p | p <- ps, blocks p > 1 ]
      putStrLn ("  " ++ pad 6 (show r) ++ pad 20 (show (length ps))
                ++ (if null nt then "—" else show (minimum (map blocks nt))))
    pad k s = s ++ replicate (k - length s) ' '

main :: IO ()
main = do
  hSetEncoding stdout utf8
  as <- getArgs
  putStrLn "दृष्टि-जालम् — every law a rule can present to any observer.\n"
  case as of
    ("sweep":w:_) -> sweep (read w)
    ("sweep":_)   -> sweep 5
    (r:w:_)       -> detail (read r) (read w)
    (r:_)         -> detail (read r) 6
    []            -> detail 110 6
  putStrLn "\n(व्याप्तिः and its leastness: formal/cubical/Vyapti_TheLeastCongruence\
           \ContainingAPairIsConstructedAndIsTheMinimalSeparatingQuery.agda\n \
           \ the law criterion: formal/cubical/Anuvrtti_...agda)"

_unusedSort :: [Int] -> [Int]
_unusedSort = sort . concat . group . sortOn id
