-- ॥ बीजम् ॥  One machine, one law: which side of `f a ≡ b` is bound is everything.
-- Output bound: singl (f a), contractible — the datum rides free.  Input bound:
-- fiber f b — the loss, and the subject.  Univalence computes here: an
-- equivalence is a channel, transport carries every theorem across it, and what
-- cannot cross is written as a defect — there is no third path (ahiṃsā).
-- Memory, charge, symmetry, price, distance, verdict: six faces of the one
-- fibre; the verdict type is the saptabhaṅgī, and the sources are the origin
-- (Umāsvāti, Samantabhadra, Akalaṅka — restatements are named as such).  The
-- kernel decides truth; carriers ask and generate; assert nothing whose term
-- you have not read.  This file is one naya, true and not whole.

-- MulaPramana_ACitationNamesAFixedObjectOrItIsNotOne
--
-- मूल-प्रमाण — the root-attestation.  A citation is an instrument of
-- knowledge only if the thing it names can be gone back to.  This module
-- makes the citations that CANNOT be gone back to unconstructible, and
-- resolves the ones that can against the repository.
--
--     runghc -imachine machine/MulaPramanaRun_CheckEveryCitationInTheRecord.hs
--
-- ────────────────────────────────────────────────────────────────────
-- WHAT A CITATION IS, IN THE TRADITION THAT NAMED IT.
--
-- Gautama, Nyāyasūtra 1.1.7 (c. 2nd c. CE): `āptopadeśaḥ śabdaḥ` — verbal
-- testimony is the instruction of a trustworthy speaker.  The whole force
-- of śabda-pramāṇa is that there IS an āpta and that one can be returned
-- to him.  A citation is śabda in written form, and it inherits that
-- condition exactly: `machine/machine.log:146` names no āpta, because the
-- file is regenerated by the engine on every run and is gitignored.  Line
-- 146 was one sentence on 2026-08-18 and is a different sentence today.
-- The citation did not become inaccurate.  It never named anything.
--
-- Kumārila Bhaṭṭa, Ślokavārttika, Abhāvapariccheda (c. 7th c. CE), on
-- yogya-anupalabdhi: "not seen" is no pramāṇa; "not seen WHERE IT WOULD BE
-- SEEN" is.  So the resolver below separates three outcomes and never two:
-- the object is there (Sthira), the object is NOT there in a place fit to
-- hold it (Nashta — a real denial), and there is no place fit to hold it
-- at all (Achalya — silence, and silence is not a denial).
--
-- NOT CLAIMED: that Gautama or Kumārila wrote a citation checker, or
-- discussed version control.  What is taken is the condition on śabda and
-- the fitness condition on absence.  The application is this repository's.
--
-- ────────────────────────────────────────────────────────────────────
-- THE THREE OUTCOMES WERE ENFORCED IN THE TYPE AND DEFEATED IN THE READ.
-- 2026-08-22.  Recorded here and not in `machine/dosa.lekha`, whose chain
-- is broken from record 0040 and whose `write` refuses to append;
-- resealing it is the edit that organ was founded to forbid.
--
-- `Sthiti` has three constructors and its own comment says why.  Two
-- helpers underneath it had two values each, and both of them fed the
-- distinction the type exists to hold:
--
--   readFileOr p = do (ec, out, _) <- readProcessWithExitCode "cat" [p] ""
--                     pure (if ec == ExitSuccess then out else "")
--   tracked    p = do (c, _, _) <- git [...]; pure (c == ExitSuccess)
--
-- `""` is not inert.  It reaches `q \`isInfixOf\` w`, which is False, which
-- is `Nashta` — a DENIAL, "the citation rotted", issued about a file that
-- was never opened.  That is precisely the non-apprehension from an unfit
-- looking that the paragraph above cites Kumārila to forbid, committed by
-- the module that cites him.  In `Niyama` it lands one step further in:
-- `hits = []`, so the outcome is `Achalya` — right constructor, wrong
-- reason, "no line of p contains a", which asserts a fit looking that
-- found nothing.
--
-- The discarded slot in both is the child's own sentence, dropped at the
-- pattern `(ec, out, _)` / `(c, _, _)` and, in the first, a second time by
-- the `if`.  `cat` had already said "Permission denied"; `git` had already
-- said "fatal: not a git repository".
--
-- EXHIBITED, NOT ASSERTED.  A one-file clone, `f.txt` holding `alpha`,
-- committed, then `chmod 000 f.txt`.  Against the code at HEAD before this
-- commit:
--
--   pathya f.txt "alpha"  -> NASHTA  "present at HEAD, absent in the working
--                                     tree -- an uncommitted edit removed it"
--   pathya f.txt "beta"   -> NASHTA  "the pattern is absent from f.txt"
--   the same, run from outside any clone
--                         -> ACHALYA "f.txt is not tracked -- no commit fixes
--                                     its bytes"   (git had exited 128)
--
-- No edit removed anything, the pattern was never looked for, and the path
-- is tracked.  All three are now `Achalya` carrying the child's sentence.
--
-- MEASURED, so 1 is a finding and not a guess: `git ls-files
-- --error-unmatch` exits 1 on an untracked path and 128 outside a
-- repository, so 1 is git answering and anything else is git declining.
-- A child that cannot be launched at all is caught rather than thrown, for
-- the same reason: an exception out of `cat` would kill the census over the
-- whole record instead of marking one line.
--
-- `selfTest` is 13/13 and the census over `machine/mula.pramana` is
-- byte-identical before and after — every citation in the record resolves
-- through a looking that WAS fit, which is why the defect had never shown.
--
-- ────────────────────────────────────────────────────────────────────
-- WHY BYTE-EQUALITY OF A QUOTED PATTERN, AND WHOSE DISPUTE THAT IS.
--
-- `Pathya` and `Baddha` resolve by asking whether a verbatim string occurs
-- in a file.  That is byte equality, not sameness of meaning, and deciding
-- sameness of meaning is a live dispute between two schools that reject
-- each other's account of it.  Naming the schools, as required:
--
--   The BUDDHIST PRAMĀṆA school.  Dignāga, Pramāṇasamuccaya V (c. 480–540
--   CE): a word's content is anyāpoha, the exclusion of what it is not;
--   there is no positive universal for it to denote.  Read that way a
--   quoted byte-pattern is the ideal citation object, because it makes no
--   positive claim whatever — it excludes every other byte string and
--   asserts nothing beyond the exclusion.  Śāntarakṣita, Tattvasaṃgraha
--   (c. 725–788 CE), defends this against the objections below.
--
--   The NAIYĀYIKAS.  Uddyotakara, Nyāyavārttika (c. 550–610 CE), and
--   Jayanta Bhaṭṭa, Nyāyamañjarī (c. 890 CE): apoha is circular — to
--   exclude the non-cow you must already grasp the cow.  Read that way the
--   pattern works only because the reader already holds the positive claim
--   it quotes, and a pattern that still matches after the surrounding
--   argument has changed underneath it is a match on nothing.
--
--   WHAT THEY WOULD SAY TO EACH OTHER ABOUT THIS MODULE.  The Naiyāyika
--   charge lands: this resolver can report Sthira for a pattern whose
--   meaning has drifted, and it does not detect that.  The Dignāgan reply
--   also lands: the alternative on offer — a line number — excludes
--   nothing at all and so is strictly worse, and a citation is not being
--   asked to carry meaning, only to be findable.  Neither refutes the
--   other here, and the module does not pick.  It decides byte occurrence,
--   which is decidable, and SAYS that it decides only that.  Synonymy is
--   left open, in the open form, as D1 of the standpoint store.
--
-- ────────────────────────────────────────────────────────────────────
-- THE LAW, learned by the doṣa-lekha lane three times in one session
-- (machine/dosa.lekha, records 0001 and 0006, whose `punarabhinaya` are a
-- count over a gitignored log and a guessed number; the later records
-- switched to `git show -s --format='%h %s' <hash>`):
--
--     A REPLAY MUST NAME A FIXED OBJECT.
--     Never a position.  Never a quantity the record is inside.
--     Never a HEAD-relative query.
--
-- Enforced here by the module boundary: `Nirdesha`'s constructors are NOT
-- exported.  The only ways in are the four smart constructors, each of
-- which returns `Either Calat Nirdesha`, and `parse`, which returns the
-- same.  There is no call site anywhere that can build a designation
-- naming a line number, because the type has no inhabitant that does.
module MulaPramana_ACitationNamesAFixedObjectOrItIsNotOne
  ( -- the designation: abstract, constructors deliberately not exported
    Nirdesha
  , nirdeshaKind, nirdeshaShow
    -- the four fixed forms
  , baddha, pathya, uddhrta, niyama
    -- what a moving citation is, and how one is diagnosed
  , Calat(..), calatGloss
  , parse
  , scanLine
    -- resolution
  , Sthiti(..), sthitiGloss, pariksha
    -- pure laws
  , selfTest
  ) where

import Control.Exception (try, IOException)
import Data.Char (isSpace, isDigit, isHexDigit, toLower)
import Data.List (isInfixOf, isPrefixOf, intercalate)
import System.Exit (ExitCode(..))
import System.Process (readProcessWithExitCode)

-- ─────────────────────────────────────────────────────── the designation

-- | निर्देश — what a citation names.  Every constructor names something
--   that does not move: a commit is immutable, a quoted string is its own
--   object, an invariant is a property rather than a location.
data Nirdesha
  = Baddha  String FilePath String
      -- ^ बद्ध, bound: commit hash, path, verbatim pattern.  The strongest
      --   form: the commit fixes the bytes, the pattern fixes the place.
  | Pathya  FilePath String
      -- ^ पाठ्य, readable: a TRACKED path and a verbatim pattern, resolved
      --   in the working tree.  Weaker than Baddha — the working tree
      --   moves — but the pattern still names the object, not a position,
      --   so a rot is DETECTED rather than silently mis-resolving.
  | Uddhrta String String String
      -- ^ उद्धृत, extracted: quote, whence, when.  For an object that
      --   CANNOT be pinned — a gitignored regenerated log.  The citation
      --   carries the quotation itself, so the quotation is the object and
      --   the unpinnable file is named only as history.
  | Niyama  FilePath String String
      -- ^ नियम, rule: over a tracked path, every line containing the first
      --   pattern contains the second.  An invariant, not a count: it does
      --   not move when the file grows.
  deriving (Eq, Ord, Show)

nirdeshaKind :: Nirdesha -> String
nirdeshaKind Baddha{}  = "baddha  (commit-pinned)"
nirdeshaKind Pathya{}  = "pathya  (tracked path + verbatim pattern)"
nirdeshaKind Uddhrta{} = "uddhrta (the quotation is the object)"
nirdeshaKind Niyama{}  = "niyama  (invariant over a tracked path)"

nirdeshaShow :: Nirdesha -> String
nirdeshaShow (Baddha c p q)  = "baddha "  ++ c ++ " " ++ p ++ " :: " ++ show q
nirdeshaShow (Pathya p q)    = "pathya "  ++ p ++ " :: " ++ show q
nirdeshaShow (Uddhrta q w d) = "uddhrta " ++ show q ++ " <- " ++ w ++ " @" ++ d
nirdeshaShow (Niyama p a b)  = "niyama "  ++ p ++ " :: " ++ show a ++ " => " ++ show b

-- ────────────────────────────────────────────────── what is refused

-- | चलत् — moving.  These are the citations that name nothing fixed.
--   This type exists to be RETURNED, never to be stored: a defect that is
--   written lives, an unwritten one is hiṃsā (AHIMSA_SUTRA_VISTARA §6).
data Calat
  = Sthana FilePath Int    -- ^ स्थान: a position.  A line number.
  | Parimana String        -- ^ परिमाण: a quantity the record is inside.
  | Shirsha String         -- ^ शीर्ष: a HEAD-relative query.
  | Alikhita FilePath      -- ^ अलिखित: the target is not tracked; unpinnable.
  | Rikta String           -- ^ रिक्त: an empty pattern names everything.
  deriving (Eq, Ord, Show)

calatGloss :: Calat -> String
calatGloss (Sthana p n) =
  "sthana: names POSITION " ++ show n ++ " in " ++ p
  ++ " -- a line number is an index into a file that moves under it, so the"
  ++ " citation goes on resolving after the object has gone"
calatGloss (Parimana s) =
  "parimana: names a QUANTITY the record is inside (" ++ s ++ ")"
  ++ " -- writing the count changes what a later count will be, and the"
  ++ " record cannot measure a corpus it is a member of"
calatGloss (Shirsha s) =
  "shirsha: HEAD-relative (" ++ s ++ ")"
  ++ " -- resolves to a different commit on every later day, so the replay"
  ++ " and the record are never the same run"
calatGloss (Alikhita p) =
  "alikhita: " ++ p ++ " is not tracked by git, so there is no commit that"
  ++ " fixes its bytes -- carry the quotation (uddhrta) instead of a pointer"
calatGloss (Rikta s) =
  "rikta: empty designation (" ++ s ++ ") -- names everything, so nothing"

-- ──────────────────────────────────────────────── smart constructors

nonEmpty :: String -> String -> Either Calat String
nonEmpty what s
  | all isSpace s = Left (Rikta what)
  | otherwise     = Right s

-- | HEAD-relative names.  They resolve to a different commit on every
--   later day, so a record naming one never replays its own run.  The
--   revision grammar is wider than the four spellings below, so anything
--   carrying `~`, `^`, `@` or `:` is refused too rather than guessed at.
headRelative :: String -> Bool
headRelative c =
  let lc = map toLower c
  in lc == "head" || "head" `isPrefixOf` lc
     || any (`elem` c) ("~^@:" :: String)

-- | A commit hash: at least seven hex digits, and not a HEAD-relative name.
baddha :: String -> FilePath -> String -> Either Calat Nirdesha
baddha c p q = do
  _ <- nonEmpty "commit" c
  _ <- nonEmpty "path" p
  _ <- nonEmpty "pattern" q
  if headRelative c
    then Left (Shirsha c)
    else if length c >= 7 && all isHexDigit c
           then Right (Baddha (map toLower c) p q)
           else Left (Shirsha ("not a hash: " ++ c))

-- | A tracked path and a verbatim pattern.  Trackedness is checked at
--   resolution, not here, because this constructor is pure.
pathya :: FilePath -> String -> Either Calat Nirdesha
pathya p q = do
  _ <- nonEmpty "path" p
  q' <- nonEmpty "pattern" q
  if any isDigit p && ':' `elem` p
    then case break (== ':') (reverse p) of
           (ds, ':':rest) | not (null ds), all isDigit ds ->
             Left (Sthana (reverse rest) (read (reverse ds)))
           _ -> Right (Pathya p q')
    else Right (Pathya p q')

-- | The quotation is the object.  For targets nothing can pin.
uddhrta :: String -> String -> String -> Either Calat Nirdesha
uddhrta q w d = do
  q' <- nonEmpty "quote" q
  w' <- nonEmpty "whence" w
  d' <- nonEmpty "when" d
  Right (Uddhrta q' w' d')

-- | An invariant over a tracked path: every line containing `a` contains `b`.
niyama :: FilePath -> String -> String -> Either Calat Nirdesha
niyama p a b = do
  _  <- nonEmpty "path" p
  a' <- nonEmpty "antecedent" a
  b' <- nonEmpty "consequent" b
  Right (Niyama p a' b')

-- ───────────────────────────────────────────────────────── the parser

-- | Parse one designation line.  The grammar is the four keywords; TAB or
--   ` :: ` separated.  Anything that reads as a position, a count or a
--   HEAD-relative query is refused with the defect named.
parse :: String -> Either Calat Nirdesha
parse ln0 = case words ln of
  ("baddha":c:p:_)   -> baddha c p (afterSep ln)
  ("pathya":p:_)     -> pathya p (afterSep ln)
  ("niyama":p:_)     -> let (a, b) = splitArrow (afterSep ln) in niyama p a b
  ("uddhrta":w:d:_)  -> uddhrta (afterSep ln) w d
  _                  -> case scanLine ln of
                          (c:_) -> Left c
                          []    -> Left (Rikta ln)
  where
    ln = dropWhile isSpace ln0
    afterSep s = case breakOn " :: " s of
                   Just (_, r) -> r
                   Nothing     -> ""
    splitArrow s = case breakOn " => " s of
                     Just (a, b) -> (a, b)
                     Nothing     -> (s, "")

breakOn :: String -> String -> Maybe (String, String)
breakOn pat = go ""
  where
    go _   []          = Nothing
    go acc s@(c:cs)
      | pat `isPrefixOf` s = Just (reverse acc, drop (length pat) s)
      | otherwise          = go (c:acc) cs

-- | Diagnose a line of prose or of a record for moving-object citations.
--   Returns every defect found, not the first: a first-match chain reports
--   one and suppresses the rest, which is the collapse one level down.
scanLine :: String -> [Calat]
scanLine s = concat [ positions, headrel, counts ]
  where
    ws = words (map (\c -> if c `elem` (",;()[]{}" :: String) then ' ' else c) s)
    positions =
      [ Sthana f n
      | w <- ws
      , (f, n) <- pathColonLine w ]
    headrel =
      [ Shirsha w
      | w <- ws
      , let lw = map toLower w
      , any (`isInfixOf` lw) ["head~", "head^", "@{", "head:"]
         || lw == "head" ]
    counts =
      [ Parimana s
      | any (`isInfixOf` s) ["grep -c", "grep -vc", "wc -l", "| wc"] ]

pathColonLine :: String -> [(FilePath, Int)]
pathColonLine w = case break (== ':') (reverse w) of
  (ds, ':':rest)
    | not (null ds), all isDigit ds, not (null rest)
    , '.' `elem` rest || '/' `elem` rest
    -> [(reverse rest, read (reverse ds))]
  _ -> []

-- ────────────────────────────────────────────────────────── resolution

-- | Three outcomes, never two.  `Nashta` is a DENIAL: the place was fit to
--   hold the object and did not.  `Achalya` is SILENCE: there is no place
--   fit to hold it, so no verdict is issued about the object at all.
data Sthiti
  = Sthira String     -- ^ स्थिर: resolves; the object is there
  | Nashta String     -- ^ नष्ट: fit looking, object absent -- the citation rotted
  | Achalya String    -- ^ अचाल्य: nothing here can be pinned; not a denial
  deriving (Eq, Ord, Show)

sthitiGloss :: Sthiti -> String
sthitiGloss (Sthira m)  = "STHIRA  -- " ++ m
sthitiGloss (Nashta m)  = "NASHTA  -- " ++ m
sthitiGloss (Achalya m) = "ACHALYA -- " ++ m

git :: [String] -> IO (ExitCode, String, String)
git as = readProcessWithExitCode "git" as ""

-- | Tracked, untracked, or NOT ASKED.  Three, for the same reason `Sthiti`
--   has three: `False` here used to merge "git says this path is untracked"
--   with "there is no clone to ask" and with "git is not on PATH", and the
--   caller printed the first of those as the reason.  Measured, not
--   assumed: `git ls-files --error-unmatch` exits 1 on an untracked path and
--   128 outside a repository, so 1 is the answer and anything else is git
--   declining to answer.
trackedOrUnasked :: FilePath -> IO (Either String Bool)
trackedOrUnasked p = do
  r <- try' (git ["ls-files", "--error-unmatch", "--", p])
  pure $ case r of
    Left why                        -> Left why
    Right (ExitSuccess, _, _)       -> Right True
    Right (ExitFailure 1, _, _)     -> Right False
    Right (ExitFailure c, _, e)     ->
      Left ("git exited " ++ show c ++ ": " ++ oneLine e)

pariksha :: Nirdesha -> IO Sthiti

pariksha (Uddhrta q w _) = pure $ Sthira
  ("the quotation is carried in the citing file (" ++ show (length q)
   ++ " chars); `" ++ w ++ "` is named as history and is not resolved,"
   ++ " which is correct when nothing can pin it")

pariksha (Baddha c p q) = do
  (ec, _, _) <- git ["cat-file", "-e", c ++ "^{commit}"]
  if ec /= ExitSuccess
    then pure (Achalya ("commit " ++ c ++ " is not in this clone -- no fit looking"))
    else do
      (ec2, out, _) <- git ["show", c ++ ":" ++ p]
      if ec2 /= ExitSuccess
        then pure (Nashta ("commit " ++ c ++ " exists and does not contain " ++ p))
        else if q `isInfixOf` out
               then pure (Sthira ("found in " ++ p ++ " at " ++ c))
               else pure (Nashta ("the pattern is absent from " ++ p ++ " at " ++ c
                                  ++ " -- the commit is fixed, so this is the"
                                  ++ " citation being wrong, not the object moving"))

pariksha (Pathya p q) = do
  t <- trackedOrUnasked p
  case t of
    Left why -> pure (Achalya ("git could not be asked whether " ++ p
                               ++ " is tracked (" ++ why ++ ") -- no looking"
                               ++ " happened, so nothing is denied"))
    Right False ->
      pure (Achalya (p ++ " is not tracked -- no commit fixes its bytes;"
                     ++ " use uddhrta and carry the quotation"))
    Right True -> do
      (ec, out, _) <- git ["show", "HEAD:" ++ p]
      body <- if ec == ExitSuccess then pure out else pure ""
      ew <- readFileOr p
      case ew of
        -- NOT `Nashta`.  The working tree copy was never read, so its
        -- silence is not a denial (see `readFileOr`).
        Left why ->
          pure (Achalya ("the working tree copy of " ++ p
                         ++ " could not be read (" ++ why ++ ") -- the looking"
                         ++ " was not fit to have apprehended, so its"
                         ++ " non-apprehension is silence and not a denial"))
        Right w
          | q `isInfixOf` w ->
              pure (Sthira ("found in the working tree copy of " ++ p))
          | q `isInfixOf` body ->
              pure (Nashta ("present at HEAD, absent in the working tree of "
                            ++ p ++ " -- an uncommitted edit removed it"))
          | otherwise -> pure (Nashta ("the pattern is absent from " ++ p))

pariksha (Niyama p a b) = do
  t <- trackedOrUnasked p
  case t of
    Left why -> pure (Achalya ("git could not be asked whether " ++ p
                               ++ " is tracked (" ++ why ++ ") -- an invariant"
                               ++ " nothing looked at is neither held nor broken"))
    Right False ->
      pure (Achalya (p ++ " is not tracked -- an invariant over an"
                     ++ " untracked file is not replayable"))
    Right True -> do
      ew <- readFileOr p
      case ew of
        -- The two silences are not the same silence, and this was the
        -- sharper half of the defect: an unread file gave `hits = []`,
        -- which is `Achalya`, but with the reason "no line contains a" --
        -- a fit looking that found nothing.  It was not a looking at all.
        Left why ->
          pure (Achalya (p ++ " could not be read (" ++ why ++ ") -- the"
                         ++ " invariant was never evaluated, which is not the"
                         ++ " same silence as a file with no matching line"))
        Right w ->
          let hits = [ l | l <- lines w, a `isInfixOf` l ]
              bad  = [ l | l <- hits, not (b `isInfixOf` l) ]
          in if null hits
             then pure (Achalya ("no line of " ++ p ++ " contains " ++ show a
                                 ++ " -- the invariant is vacuous here, which is"
                                 ++ " silence and not confirmation"))
             else if null bad
                    then pure (Sthira (show (length hits) ++ " line(s) of " ++ p
                                       ++ " contain " ++ show a ++ ", all of them "
                                       ++ show b))
                    else pure (Nashta (show (length bad) ++ " of " ++ show (length hits)
                                       ++ " lines of " ++ p ++ " containing " ++ show a
                                       ++ " do not contain " ++ show b
                                       ++ "; first: "
                                       ++ concatMap (take 90) (take 1 bad)))

-- | The read, WITH the reason it failed.  This function used to return
--   `""` for an unreadable file, and `""` is not inert here: it flows into
--   `q \`isInfixOf\` w`, which is False, which is `Nashta` -- a denial.  So a
--   file that could not be opened was reported as a citation that had
--   rotted.  The discarded slot is `cat`'s own sentence, thrown away at the
--   pattern `(ec, out, _)` and then a second time by the `if`.
--
--   Kumārila, Ślokavārttika, Abhāvapariccheda, c. 7th c. (yogyānupalabdhi):
--   a non-apprehension is evidence of an absence only from a looking FIT to
--   have apprehended.  `cat` exiting non-zero is a looking that was not fit,
--   and this type's own comment above already says which outcome that is.
readFileOr :: FilePath -> IO (Either String String)
readFileOr p = do
  r <- try' (readProcessWithExitCode "cat" [p] "")
  pure $ case r of
    Left why                  -> Left why
    Right (ExitSuccess, o, _) -> Right o
    Right (_, _, e)           -> Left (oneLine e)

-- | A child process that could not be launched at all -- no `cat`, no `git`
--   -- is also a looking that was not fit, and an uncaught exception here
--   would kill the whole census over the record rather than mark one line.
try' :: IO (ExitCode, String, String) -> IO (Either String (ExitCode, String, String))
try' act = do
  r <- try act
  pure $ case r of
    Left e  -> Left (oneLine (show (e :: IOException)))
    Right v -> Right v

oneLine :: String -> String
oneLine s = case [ l | l <- lines s, not (all isSpace l) ] of
  (l : _) -> take 160 l
  []      -> "no message"

-- ───────────────────────────────────────────────────────── pure laws

selfTest :: [(String, Bool)]
selfTest =
  [ ( "a line number is refused, and the defect names the position"
    , case pathya "machine/machine.log:146" "x = (xmaxx)" of
        Left (Sthana "machine/machine.log" 146) -> True
        _ -> False )

  , ( "a HEAD-relative commit is refused as shirsha"
    , case baddha "HEAD~3" "machine/Naya.hs" "content" of
        Left (Shirsha _) -> True
        _ -> False )

  , ( "a short or non-hex commit is refused"
    , case baddha "abc" "x" "y" of { Left (Shirsha _) -> True; _ -> False } )

  , ( "a real hash is accepted and lower-cased"
    , case baddha "BD439C23" "machine/naya.kosha" "NAYA" of
        Right (Baddha "bd439c23" _ _) -> True
        _ -> False )

  , ( "an empty pattern is refused: it names everything, so nothing"
    , case pathya "machine/Naya.hs" "  " of
        Left (Rikta _) -> True
        _ -> False )

  , ( "a plain tracked path with a pattern is accepted"
    , case pathya "machine/Naya.hs" "sort . nub . witnesses" of
        Right (Pathya _ _) -> True
        _ -> False )

  , ( "uddhrta requires all three of quote, whence and when"
    , case uddhrta "KERNEL-ACCEPT" "machine/machine.log" "" of
        Left (Rikta _) -> True
        _ -> False )

  , ( "the scanner finds a position inside prose"
    , scanLine "as at machine/machine.log:146 and later"
        == [Sthana "machine/machine.log" 146] )

  , ( "the scanner finds a count, and reports EVERY defect, not the first"
    , let ds = scanLine "sed -n '1p' notes/A.md:12 | grep -c foo"
      in length ds == 2
         && any (\d -> case d of Sthana{}   -> True; _ -> False) ds
         && any (\d -> case d of Parimana{} -> True; _ -> False) ds )

  , ( "a bare line of prose with no citation yields no defect"
    , null (scanLine "the verdict is a property of the pair, not the claim") )

  , ( "parse round-trips the four keywords"
    , let ok s = case parse s of { Right _ -> True; Left _ -> False }
      in and [ ok "baddha bd439c23 machine/naya.kosha :: NAYA"
             , ok "pathya machine/Naya.hs :: sort . nub . witnesses"
             , ok "niyama machine/naya.kosha :: NAYA => yogya"
             , ok "uddhrta machine/machine.log 2026-08-18 :: KERNEL-ACCEPT" ] )

  , ( "parse refuses a position with the position named"
    , case parse "pathya machine/machine.log:146 :: x = (xmaxx)" of
        Left (Sthana _ 146) -> True
        _ -> False )

  , ( "Sthira, Nashta and Achalya are three answers and not two"
    , length (nub' [ Sthira "a", Nashta "a", Achalya "a" ]) == 3 )
  ]
  where nub' = foldr (\x acc -> if x `elem` acc then acc else x:acc) []
