-- Nirdharana_WhichRecordFieldsRideFreeAndWhichMustSurvive.hs
--
-- निर्धारण — "determination, ascertaining which of several it is".
--
-- ON THE NAME, AND WHAT IS NOT CLAIMED.  The compound is used here in the
-- sense the punarāgamana modules already use it: `निर्धारितम्` in
-- `punaragamana/src/Punaragamana/Sthanivadbhava_….agda` names the map whose
-- values a Carrier's base determines, and `पक्षः-न-निर्धारितः` /
-- `परिमाणम्-न-निर्धारितम्` / `शेषः-न-निर्धारितः` in
-- `punaragamana/src/Punaragamana/KuttakaValli_….agda` are the three theorems
-- that a slot is NOT so determined.  **No text and no date is claimed for the
-- term as a technical term of any school**, and none is asserted below.  It is
-- borrowed from those two modules and from nowhere else — the same declaration
-- `Punaragamana/Carrier.agda` makes about `punarāgamana` itself ("the compound
-- is chosen here, and no source is claimed for it").  The Āryabhaṭīya and the
-- Aṣṭādhyāyī citations that DO stand are in those modules' headers, at verse
-- and sūtra level, and they are not restated here as though this program had
-- opened either text.  It has not.
--
-- WHAT THIS PROGRAM IS.  A census of every `record … where` block with a
-- `field` section under `formal/cubical/` and `punaragamana/src/`, asking of
-- each one the punarāgamana question:
--
--     for a record R with fields x₁ … xₙ, is field xⱼ DETERMINED by the
--     others?  Equivalently: is the projection R → (the other fields) an
--     equivalence?  And in cubical Agda `isEquiv f` IS `∀ b → isContr
--     (fibre f b)`, so the question is not a judgement call — it is emitted
--     as a term and the kernel answers it.
--
-- The program parses, classifies, EMITS Agda modules into a scratch directory,
-- RUNS Agda on them, and prints a table.  It writes nothing into the corpus.
--
--   run:  runghc machine/Nirdharana_WhichRecordFieldsRideFreeAndWhichMustSurvive.hs
--   from the repository root.  Flags:
--       --no-check      parse and classify only; emit and run nothing
--       --limit N       run at most N probes (still parses everything)
--   The generated modules are always left in the scratch directory, whose path
--   the report prints, so a reader can open the exact term the kernel accepted.
--
-- THE CRITERION, one line, and it is what makes step 2 decisive rather than
-- heuristic: WHICH SIDE OF `f a ≡ b` IS BOUND.  Bind b and the fibre is
-- `singl (f a)` — contractible always, no h-level hypothesis, arbitrary A and
-- B — so the datum rides free.  Bind a and the fibre is the preimage, which is
-- arbitrary and is usually the SUBJECT of the module rather than a defect in
-- it.  A record FIELD of type `f (other fields) ≡ thisField` is bind-b.  A
-- record PARAMETER is bind-a.  The census keeps the two apart and reports the
-- bind-a records as level sets, not as failures.
--
-- AND THE FIBRE HAS THREE CASES, NOT TWO.  EMPTY (नष्टि), EXACTLY ONE (free),
-- MANY (a Carrier still exists, with the extra freedom recorded as data).
-- `isContr` merges EMPTY and MANY into one "no", and Saptabhangi.agda's
-- `दुर्नयः` proves any two-valued verdict on three seeds must identify two of
-- them.  So: GREEN is EXACTLY ONE; a separating pair is MANY; and EMPTY is a
-- case this instrument cannot certify at all, stated wherever a table would
-- otherwise imply it had been ruled out.
--
-- ─────────────────────────────────────────────────────────────────────────
-- WHAT IS MEASURED, AND THE LIMIT OF EACH MEASUREMENT, STATED AT THE SITE.
-- ─────────────────────────────────────────────────────────────────────────
--
--  1. लेखा · LEKHĀ, the census.  Every `record` head, its parameters, its
--     sort, its fields and their types.  Comments are stripped by a scanner
--     that tracks `{- -}` nesting and carves out `{-# … #-}` pragmas.
--
--     WHAT THE PARSER MISSES, stated because a census that hides its blind
--     spot is the exact defect this corpus exists to refuse:
--       · a record with NO `field` line at all (a record of no fields, or one
--         whose fields arrive by `open … public` from elsewhere) is counted as
--         a record and reported as fieldless — it is not silently dropped;
--       · fields written on the `field` line itself (`field  x : A`) ARE
--         parsed, but they are counted separately so the number is visible;
--       · a field declaration whose type continues on a line indented LESS
--         than the declaration is mis-joined.  Agda's layout forbids this, so
--         the case should be empty, and the count of unparsable declarations
--         is printed rather than assumed to be zero;
--       · implicit `{x : A}` and instance `⦃ x : A ⦄` fields are detected and
--         the record is excluded from probing, not silently mangled;
--       · a record inside a `where` block, or generated by a macro, or written
--         as an anonymous `record { … }` EXPRESSION, is not a declaration and
--         is not here;
--       · the field section is truncated at the first nested `record` /
--         `module` / `data` / `private` line, so a record declared inside
--         another record's field section loses nothing but is not merged.
--
--  2. वाहक-आकार · CARRIER-SHAPED, the cheap syntactic pass.  A field whose
--     type contains `≡` (or `PathP`) AND mentions another field of the same
--     record is a WITNESS field.  Its presence means the record is already
--     Carrier-shaped, and the split is readable off the witness's own type:
--     if that type is `L ≡ xⱼ` with `xⱼ` a field name not occurring in `L`,
--     then the determining map is `L`, the carried datum is `xⱼ`, and `xⱼ`
--     together with the witness ride free.
--     LIMIT: this is syntax.  It reports a SHAPE, never a verdict.  The
--     verdict is measurement 3.
--
--  3. प्रमाण · THE PROBE, which is the only thing here that is a verdict.
--     For each Carrier-shaped candidate the program writes a module
--
--         record CensusBase : Type where field ⟨the other fields⟩
--         censusFam : CensusBase → Type          -- the carried field's type
--         censusF   : (b : CensusBase) → censusFam b   -- the map L
--         reshuffle : Iso R (Σ[ b ∈ CensusBase ] singl (censusF b))
--             fun/inv by record reshuffling, BOTH round trips by `refl`
--         DETERMINED : R ≃ CensusBase
--         DETERMINED = compEquiv (isoToEquiv reshuffle)
--                        (Σ-contractSnd (λ b → isContrSingl (censusF b)))
--
--     and runs Agda on it.  GREEN is a machine-checked equivalence: the field
--     and its witness contribute zero degrees of freedom and everything
--     transports.  Nothing is constructed by hand; the only inputs are the
--     record's own field names and the witness's own type.
--
--     LIMIT, and it is the important one.  A RED here is THREE different
--     things and the program separates them, because collapsing them would
--     make the census worthless:
--       HOST-RED  the host module does not typecheck under THIS toolchain at
--                 all.  Several formal/cubical modules are written against
--                 agda/cubical v0.5 names (`solve`, `isSetRetract`, …) that
--                 v0.9 does not have.  That is a toolchain fact and NOT a
--                 mathematical verdict about the record.
--       ELAB-RED  the host checks but the generated module does not even
--                 elaborate — a name not in scope, a universe level the
--                 generator got wrong.  That is a defect in THIS PROGRAM and
--                 NOT a mathematical verdict either.
--       MATH-RED  host green, probe elaborates, and the equivalence or one of
--                 the two `refl`s fails.  Only this one says anything about
--                 the record — and even then it says "not determined BY THIS
--                 SPLIT, definitionally", not "not determined".
--
--  4. भेद · THE SEPARATING PAIR, the negative made equally mechanical.  For a
--     record with NO witness field the program emits two inhabitants agreeing
--     on every other field, differing on xⱼ, and a proof they are distinct —
--     exactly the output format of `पक्षः-न-निर्धारितः` and its two siblings
--     in `Punaragamana.KuttakaValli_…`, and of the three in
--     `Punaragamana.Sthanivadbhava_…`, which is what this automates.
--     LIMIT, stated flatly: this needs two provably distinct closed
--     inhabitants of xⱼ's type and one closed inhabitant of every other
--     field's type, and the program knows only ℕ (`0`/`1`, distinct by
--     `znots`) and `Bool` (`true`/`false`, distinct by `true≢false`).  Every
--     other record is reported as NOT ATTEMPTED, never as "determined".
--
--  ─────────────────────────────────────────────────────────────────────────
--  THE ONE THING THIS CENSUS CANNOT DO, SAID HERE SO THAT ITS ABSENCE FROM
--  THE TABLE IS NOT READ AS AN EMPTY RESULT.
--
--  A field that IS determined but carries NO witness cannot be found by
--  machine in general, and the reason is not laziness.  A GREEN verdict needs
--  the determining map `L`, and when a witness field is present that map is
--  written down in the witness's own type, which is why measurement 3 works.
--  With no witness field there is nowhere in the record to read `L` off from:
--  the record does not say what xⱼ is a function OF, so there is nothing to
--  emit.  Searching for such an `L` is proof search, not a census.
--
--  What the program CAN do, and does, is the nearest honest neighbour:
--    (a) MATH-RED and separating pairs — records where a field is provably
--        NOT determined, which is the negative half and is complete;
--    (b) वाहक-अनुक्त, "the carrier unsaid" — records that ARE Carrier-shaped,
--        confirmed GREEN by the kernel, whose own module never mentions
--        `Carrier`, `≃`, `Iso` or `ua` anywhere near them.  The equivalence is
--        true, checked, and unstated.  That is the actionable list this
--        program produces, and it is a strictly weaker statement than "a
--        determined field with no witness".  It is labelled as such below.
--
--  ─────────────────────────────────────────────────────────────────────────
--  TOOLCHAIN.  Agda 2.8.0, agda/cubical v0.9 (the pair Homebrew ships), from
--  ~/.agda/libraries.  `LC_ALL=C.utf8` is set by this program and is REQUIRED:
--  under a POSIX locale Agda crashes while printing its own error messages for
--  the Devanagari identifiers and replaces the diagnosis with advice about
--  code pages.  Probes are emitted with `--cubical --safe --guardedness`;
--  `--guardedness` is infective, so a probe without it cannot import the 411
--  corpus modules that have it.

module Main (main) where

import Control.Exception (SomeException, try)
import Control.Monad (filterM, forM, forM_, unless, when)
import Data.Char (isDigit, isSpace)
import Data.IORef (IORef, modifyIORef', newIORef, readIORef)
import Data.List
  (intercalate, isInfixOf, isPrefixOf, isSuffixOf, nub, partition, sort, sortOn)
import Data.Maybe (catMaybes, fromMaybe, isJust, mapMaybe)
import qualified Data.Map.Strict as M
import System.Directory
  (createDirectoryIfMissing, doesDirectoryExist, listDirectory)
import System.Environment (getArgs)
import System.Exit (ExitCode (..))
import System.Environment (lookupEnv)
import System.IO.Unsafe (unsafePerformIO)
import System.FilePath ((</>), takeExtension)
import System.IO (hFlush, hSetEncoding, stdout, utf8)
import System.Process (readCreateProcessWithExitCode, proc, env)
import GHC.IO.Encoding (setLocaleEncoding)
import System.IO (utf8)

-- ============================================================ filesystem

walk :: [String] -> FilePath -> IO [FilePath]
walk skips root = do
  isDir <- doesDirectoryExist root
  if not isDir
    then return [root]
    else do
      names <- listDirectory root
      fmap concat . forM (sort names) $ \n ->
        if n `elem` skips || "." `isPrefixOf` n
          then return []
          else walk skips (root </> n)

readFileSafe :: FilePath -> IO String
readFileSafe p = do
  r <- try (do s <- readFile p; length s `seq` return s)
  case r of
    Left e  -> let _ = (e :: SomeException) in return ""
    Right s -> return s

-- ============================================================ comment scan

-- | Blank out comments, line by line, carrying `{- -}` nesting depth across
--   lines.  `{-# … #-}` is a pragma, not a comment, and is left alone.  The
--   output has the same number of lines and the same column positions, so
--   indentation is preserved exactly.
decomment :: [String] -> [String]
decomment = go (0 :: Int)
  where
    go _ [] = []
    go d (l:ls) = let (l', d') = one d l in l' : go d' ls
    one d [] = ([], d)
    one d s@(c:cs)
      | d == 0, "{-#" `isPrefixOf` s = keepPragma d s
      | d == 0, "--" `isPrefixOf` s, notOperator s = (map blank s, d)
      | "{-" `isPrefixOf` s = let (r, d') = one (d + 1) (drop 2 s)
                              in ("  " ++ r, d')
      | "-}" `isPrefixOf` s, d > 0 = let (r, d') = one (d - 1) (drop 2 s)
                                     in ("  " ++ r, d')
      | d > 0 = let (r, d') = one d cs in (blank c : r, d')
      | otherwise = let (r, d') = one d cs in (c : r, d')
    keepPragma d s = case breakOn "#-}" s of
      Nothing        -> (s, d)
      Just (a, rest) -> let (r, d') = one d rest in (a ++ "#-}" ++ r, d')
    blank c = if isSpace c then c else ' '
    -- `--` only starts a comment when it is not glued into a longer operator
    -- token (Agda: `--` must be followed by a non-name character).
    notOperator s = case drop 2 s of
      []      -> True
      (c : _) -> not (c `elem` "-!#$%&*+./<=>?@\\^|~:")

breakOn :: String -> String -> Maybe (String, String)
breakOn pat = go ""
  where
    go _ [] = Nothing
    go acc s@(c:cs)
      | pat `isPrefixOf` s = Just (reverse acc, drop (length pat) s)
      | otherwise          = go (c : acc) cs

-- ============================================================ record model

data Field = Field
  { fNames  :: [String]
  , fType   :: String
  , fHidden :: Bool
  } deriving (Show)

data Rec = Rec
  { rFile     :: FilePath
  , rModule   :: String
  , rName     :: String
  , rLine     :: Int
  , rIndent   :: Int
  , rParams   :: String
  , rSort     :: String
  , rFields   :: [Field]
  , rBadDecls :: Int          -- ^ field declarations the parser could not split
  , rInline   :: Bool         -- ^ some fields were on the `field` line itself
  , rHasField :: Bool
  , rCoind    :: Bool
  , rNoEta    :: Bool
  , rBody     :: [String]
  , rImports  :: [String]   -- ^ the host module's own top-level import lines
  }

flatFields :: Rec -> [(String, String, Bool)]
flatFields r = [ (n, fType f, fHidden f) | f <- rFields r, n <- fNames f ]

fieldNames :: Rec -> [String]
fieldNames = map (\(n,_,_) -> n) . flatFields

indentOf :: String -> Int
indentOf = length . takeWhile (== ' ')

blankLine :: String -> Bool
blankLine = all isSpace

collapse :: String -> String
collapse = unwords . words

trim :: String -> String
trim = dropWhile isSpace . reverse . dropWhile isSpace . reverse

-- | Split at the first occurrence of a token at bracket depth 0.
splitTop :: String -> String -> Maybe (String, String)
splitTop tok = go (0 :: Int) ""
  where
    go _ _ [] = Nothing
    go d acc s@(c:cs)
      | d == 0, tok `isPrefixOf` s = Just (reverse acc, drop (length tok) s)
      | c `elem` "([{" || c == '⦃' = go (d + 1) (c : acc) cs
      | c `elem` ")]}" || c == '⦄' = go (d - 1) (c : acc) cs
      | otherwise                  = go d (c : acc) cs

countTop :: String -> String -> Int
countTop tok s = case splitTop tok s of
  Nothing      -> 0
  Just (_, r)  -> 1 + countTop tok r

tokensOf :: String -> [String]
tokensOf = words . map sep
  where sep c = if c `elem` "()[]{},;⦃⦄" then ' ' else c

mentionsTok :: String -> String -> Bool
mentionsTok n ty = n `elem` tokensOf ty

-- ============================================================ the parser

parseFile :: FilePath -> String -> (Maybe String, [Rec])
parseFile path src =
  let ls   = decomment (lines src)
      modn = case [ w | l <- ls, "module " `isPrefixOf` l
                      , w <- take 1 (drop 1 (words l)) ] of
               (n:_) -> Just n
               []    -> Nothing
      idx  = zip [1 ..] ls
      -- A host's `open import M` does NOT re-export M's names, so a probe that
      -- imports only the host cannot see `ℕ`.  The host's own import lines are
      -- carried into the probe verbatim.  (Found by the first run: every P1
      -- probe died with `Not in scope: ℕ`.)
      imps = gatherOpens ls
      recs = mapMaybe (uncurry (tryRecord ls imps (fromMaybe "?" modn) path)) idx
  in (modn, recs)

-- | Every column-0 `import` / `open import` / `open …` line of the host,
--   with `using (…)` clauses that spill onto following indented lines joined
--   back on.  `open CommRingStr (ℤCommRing .snd)` in Swarm.S09SmithKuttaka is
--   why plain `import` lines are not enough: the record's field types use `·`,
--   which reaches scope through that `open` and through nothing else.
gatherOpens :: [String] -> [String]
gatherOpens = go
  where
    go [] = []
    go (l:ls)
      | indentOf l == 0, isOpen l =
          let (cont, rest) = span (\x -> not (blankLine x) && indentOf x > 0) ls
          in collapse (unwords (l : cont)) : go rest
      | otherwise = go ls
    isOpen l = case words l of
      ("import" : _) -> True
      ("open" : _)   -> True
      _              -> False

tryRecord :: [String] -> [String] -> String -> FilePath -> Int -> String -> Maybe Rec
tryRecord ls imps modn path n l
  | ("record" : _) <- words l
  , let ind = indentOf l
  = do (hdr, hdrEnd) <- gatherHeader ls n ind
       let afterRec = trim (drop (length "record") (dropWhile (== ' ') hdr))
       (nm, rest0) <- nameAndRest afterRec
       let (params, sortStr) = case splitTop ":" rest0 of
             Just (p, s) -> (trim p, trim (dropWhereTail s))
             Nothing     -> (trim (dropWhereTail rest0), "")
           body = takeBody ind (drop hdrEnd ls)
           (fs, bad, inl, hadField) = parseFields body
       Just Rec { rFile = path, rModule = modn, rName = nm, rLine = n
                , rIndent = ind, rParams = params, rSort = sortStr
                , rFields = fs, rBadDecls = bad, rInline = inl
                , rHasField = hadField
                , rCoind = any (("coinductive" ==) . firstWord) body
                , rNoEta = any (("no-eta-equality" ==) . firstWord) body
                , rBody = body, rImports = imps }
  | otherwise = Nothing
  where
    firstWord s = case words s of { (w:_) -> w ; [] -> "" }
    dropWhereTail s =
      let ws = words s
      in if not (null ws) && last ws == "where"
           then unwords (init ws) else unwords ws
    nameAndRest s = case words s of
      (w:_) | w /= ":" -> Just (w, trim (drop (length w) (dropWhile (==' ') s)))
      _                -> Nothing

-- | Join the record head across lines until a `where` token is seen.
--   Returns the joined header and how many lines from `n` it consumed.
gatherHeader :: [String] -> Int -> Int -> Maybe (String, Int)
gatherHeader ls n ind = go 0 ""
  where
    go k acc
      | k > 6 = Nothing
      | otherwise = case drop (n - 1 + k) ls of
          [] -> Nothing
          (x:_) ->
            let acc' = if null acc then x else acc ++ " " ++ trim x
            in if "where" `elem` words x
                 then Just (acc', n + k)
                 else if k > 0 && not (blankLine x) && indentOf x <= ind
                        then Nothing
                        else go (k + 1) acc'

takeBody :: Int -> [String] -> [String]
takeBody ind = takeWhile (\x -> blankLine x || indentOf x > ind)

-- | Fields.  Returns (fields, unparsable declarations, inline?, saw a `field`?)
parseFields :: [String] -> ([Field], Int, Bool, Bool)
parseFields = outside
  where
    outside [] = ([], 0, False, False)
    outside (l:ls)
      | ("field" : rest) <- words l =
          let fInd  = indentOf l
              inlin = not (null rest)
              inlF  = if inlin then maybe [] (: []) (mkField (unwords rest))
                               else []
              inlBad = if inlin && null inlF then 1 else 0
              (fs, bad, ls') = inside fInd Nothing [] ls
              (fs2, bad2, _, _) = outside ls'
          in (inlF ++ fs ++ fs2, inlBad + bad + bad2, inlin, True)
      | otherwise = let (a, b, c, d) = outside ls in (a, b, c, d)

    stopper l = case words l of
      (w:_) -> w `elem` ["record","module","data","private","postulate"
                        ,"open","import","field","constructor","coinductive"
                        ,"inductive","no-eta-equality","eta-equality"]
      []    -> False

    inside _ _ acc [] = (finish acc, badOf acc, [])
    inside fInd declInd acc (l:ls)
      | blankLine l = inside fInd declInd acc ls
      | indentOf l <= fInd = (finish acc, badOf acc, l : ls)
      | stopper l = (finish acc, badOf acc, l : ls)
      | otherwise =
          case declInd of
            Nothing -> inside fInd (Just (indentOf l)) [trim l] ls
            Just d
              | indentOf l == d  -> inside fInd declInd (trim l : acc) ls
              | indentOf l >  d  ->
                  case acc of
                    (a:as) -> inside fInd declInd ((a ++ " " ++ trim l) : as) ls
                    []     -> inside fInd declInd [trim l] ls
              | otherwise -> (finish acc, badOf acc, l : ls)

    finish = mapMaybe mkField . reverse
    badOf  = length . filter (not . isJust . mkField) . reverse

    mkField s0 =
      let s = collapse s0 in
      case splitTop ":" s of
        Nothing -> Nothing
        Just (lhs, rhs)
          | null (words lhs) || null (words rhs) -> Nothing
          | otherwise ->
              let hidden = any (`elem` "{⦃") lhs
                  nms = words (map (\c -> if c `elem` "{}⦃⦄" then ' ' else c) lhs)
              in if null nms then Nothing
                 else Just (Field nms (collapse rhs) hidden)

-- ============================================================ classification

-- | A witness field: a path type mentioning another field of the same record.
isWitness :: Rec -> (String, String, Bool) -> Bool
isWitness r (n, ty, _) =
  (("≡" `isInfixOf` ty) || ("PathP" `isInfixOf` ty))
  && any (\m -> m /= n && mentionsTok m ty) (fieldNames r)

data Orient = Fwd | Rev deriving (Eq, Show)

-- | The Carrier split read off a witness's own type: `L ≡ xⱼ` (Fwd) or
--   `xⱼ ≡ L` (Rev), with `xⱼ` a field of the record not occurring in `L`.
carrierSplit :: Rec -> (String, String, Bool) -> Maybe (String, String, String, Orient)
carrierSplit r (wn, ty, _)
  -- The split is only meaningful when the whole type IS a path.  A `¬`, a
  -- top-level `→`, or a binder means the `≡` sits under something else, and
  -- `¬ x₀ ≡ y₀` read as a Carrier split is exactly the false positive this
  -- guard was added to kill (AchromaticToy.Stage, first run).
  | "¬" `isInfixOf` ty = Nothing
  | isJust (splitTop "→" ty) = Nothing
  | any (`isInfixOf` ty) ["∀", "λ", "Σ[", "Π"] = Nothing
  | countTop "≡" ty /= 1 = Nothing
  | otherwise = case splitTop "≡" ty of
      Nothing -> Nothing
      Just (lhs, rhs) ->
        let l = trim lhs; rr = trim rhs; fns = fieldNames r
            -- A remaining field whose own type mentions xⱼ blocks the split:
            -- dropping xⱼ from the base would leave that field's type
            -- ill-formed, and repairing it by substituting L makes the round
            -- trip hold only up to transport, not by refl.  Reported, not
            -- silently attempted.  (BornDistribution₂.positive : Positive
            -- denominator is the corpus's instance.)
            dependents x = [ n | (n, t, _) <- flatFields r
                               , n /= x, n /= wn, mentionsTok x t ]
        in if rr `elem` fns && rr /= wn && not (mentionsTok rr l)
                && null (dependents rr)
             then Just (wn, rr, l, Fwd)
             else if l `elem` fns && l /= wn && not (mentionsTok l rr)
                     && null (dependents l)
                    then Just (wn, l, rr, Rev)
                    else Nothing

-- ============================================================ probe eligibility

data Skip = Skip { skWhy :: String } deriving (Show)

goodSorts :: [String]
goodSorts = ["Type", "Type₀", "Type0", "Set", "Set₀", "Type ℓ-zero"]

-- | Parameters: only fully explicit `(names : type)` groups are supported,
--   because the probe has to re-apply them by name.
paramGroups :: String -> Maybe [(String, String)]
paramGroups s0
  | null (trim s0) = Just []
  | any (`elem` "{⦃") s0 = Nothing
  | otherwise = go (trim s0)
  where
    go [] = Just []
    go ('(':rest) = case splitClose 0 "" rest of
      Nothing -> Nothing
      Just (inside, after) -> case splitTop ":" inside of
        Nothing -> Nothing
        Just (ns, ty) -> ((map (\n -> (n, collapse ty)) (words ns)) ++) <$> go (trim after)
    go _ = Nothing
    splitClose _ _ [] = Nothing
    splitClose d acc (c:cs)
      | c == ')' && d == 0 = Just (reverse acc, cs)
      | c == ')'           = splitClose (d - 1) (c : acc) cs
      | c == '('           = splitClose (d + 1) (c : acc) cs
      | otherwise          = splitClose d (c : acc) cs

eligible :: Rec -> Either Skip [(String, String)]
eligible r
  | rIndent r /= 0            = Left (Skip "nested (not a top-level record)")
  | not (rHasField r)         = Left (Skip "no field section")
  | rCoind r                  = Left (Skip "coinductive")
  | rNoEta r                  = Left (Skip "no-eta-equality")
  | any (\(_,_,h) -> h) (flatFields r) = Left (Skip "implicit/instance field")
  | rBadDecls r > 0           = Left (Skip "unparsable field declaration")
  | rSort r `notElem` goodSorts = Left (Skip ("sort not Type: " ++ rSort r))
  | otherwise = case paramGroups (rParams r) of
      Nothing -> Left (Skip ("parameters not plain explicit: " ++ rParams r))
      Just ps -> Right ps

-- ============================================================ emission

incdirs :: [String]
incdirs = ["formal/cubical", "punaragamana/src", "machinery", "kernel"]

probeHeader :: String -> [String]
probeHeader nm =
  [ "{-# OPTIONS --cubical --safe --guardedness #-}"
  , "module " ++ nm ++ " where"
  , ""
  , "open import Cubical.Foundations.Prelude"
  , "open import Cubical.Foundations.Isomorphism"
  , "open import Cubical.Foundations.Equiv"
  , "open import Cubical.Data.Sigma"
  ]

-- | The Carrier probe.  Nothing below is a construction: every line is copied
--   from the record's own field names and the witness's own type.
emitP1 :: String -> Rec -> [(String, String)] -> (String, String, String, Orient) -> String
emitP1 nm r ps (wn, xj, lmap, orient) = unlines $
  probeHeader nm
  ++ [ "open import " ++ rModule r ]
  ++ rImports r
  ++ [ "" ]
  ++ modOpen
  ++ map ind
     ( [ "record CensusBase : Type where"
       , "  field"
       ]
    ++ [ "    " ++ n ++ " : " ++ ty | (n, ty, _) <- keep ]
    ++ [ ""
       , "censusFam : CensusBase → Type"
       , "censusFam censusB = " ++ letIn carriedTy
       , ""
       , "censusF : (censusB : CensusBase) → censusFam censusB"
       , "censusF censusB = " ++ letIn lmap
       , ""
       ]
    ++ singlDefs
    ++ [ "censusTo : " ++ rApp ++ " → censusΣ"
       , "censusTo censusR ="
       , "  record { " ++ intercalate " ; "
             [ n ++ " = " ++ rName r ++ "." ++ n ++ " censusR" | (n,_,_) <- keep ]
         ++ " } , ( " ++ rName r ++ "." ++ xj ++ " censusR"
         ++ " , " ++ rName r ++ "." ++ wn ++ " censusR )"
       , ""
       , "censusFrom : censusΣ → " ++ rApp
       , "censusFrom (censusB , (censusY , censusP)) ="
       , "  record { " ++ intercalate " ; "
             ( [ n ++ " = CensusBase." ++ n ++ " censusB" | (n,_,_) <- keep ]
            ++ [ xj ++ " = censusY", wn ++ " = censusP" ] )
         ++ " }"
       , ""
       , "censusReshuffle : Iso (" ++ rApp ++ ") censusΣ"
       , "Iso.fun      censusReshuffle = censusTo"
       , "Iso.inv      censusReshuffle = censusFrom"
       , "Iso.rightInv censusReshuffle _ = refl"
       , "Iso.leftInv  censusReshuffle _ = refl"
       , ""
       , "-- THE VERDICT.  Green here is the equivalence itself."
       , "DETERMINED : (" ++ rApp ++ ") ≃ CensusBase"
       , "DETERMINED = compEquiv (isoToEquiv censusReshuffle) censusContract"
       ] )
  where
    fs   = flatFields r
    keep = [ f | f@(n,_,_) <- fs, n /= xj, n /= wn ]
    -- `let`, NOT `where` and NOT `open CensusBase censusB`.  Both of those
    -- were tried and both fail on real corpus records: `open` makes the field
    -- name an AMBIGUOUS OVERLOADED PROJECTION against the host's own exported
    -- projection of the same name, and `where` is a module-level definition,
    -- so it is a ClashingDefinition against it.  A `let` is a local binding
    -- and simply shadows.  (VivekaPramana_TheRemainderIsLawfulAndTheNetBeats
    -- exhibits both, because it does `open विवेक-प्रमाण` at top level.)
    letIn body
      | null keep = body
      | otherwise =
          "let " ++ intercalate " ; "
            [ n ++ " = CensusBase." ++ n ++ " censusB" | (n,_,_) <- keep ]
          ++ " in " ++ body
    carriedTy = case [ ty | (n, ty, _) <- fs, n == xj ] of
                  (t:_) -> t
                  []    -> "Type"
    rApp = unwords (rName r : map fst ps)
    modOpen = if null ps then [] else
      [ "module _ " ++ unwords [ "(" ++ n ++ " : " ++ ty ++ ")" | (n, ty) <- ps ]
        ++ " where" ]
    ind s = if null ps then s else (if null s then s else "  " ++ s)
    singlDefs = case orient of
      Fwd ->
        [ "censusΣ : Type"
        , "censusΣ = Σ[ censusB ∈ CensusBase ] (Σ[ censusY ∈ censusFam censusB ] (censusF censusB ≡ censusY))"
        , ""
        , "censusContract : censusΣ ≃ CensusBase"
        , "censusContract = Σ-contractSnd (λ censusB → isContrSingl (censusF censusB))"
        , ""
        ]
      Rev ->
        [ "censusΣ : Type"
        , "censusΣ = Σ[ censusB ∈ CensusBase ] (Σ[ censusY ∈ censusFam censusB ] (censusY ≡ censusF censusB))"
        , ""
        , "-- the reversed singleton is contractible too; the term is written out"
        , "-- rather than imported because the cubical library ships only the"
        , "-- forward `isContrSingl`."
        , "censusRevContr : {A : Type} (a : A) → isContr (Σ[ y ∈ A ] (y ≡ a))"
        , "censusRevContr a = (a , refl) , λ (y , p) i → (p (~ i) , λ j → p (~ i ∨ j))"
        , ""
        , "censusContract : censusΣ ≃ CensusBase"
        , "censusContract = Σ-contractSnd (λ censusB → censusRevContr (censusF censusB))"
        , ""
        ]

-- | THE DESIGNED-FAILURE CONTROL, run against every GREEN.  A false green is
--   the worst outcome this program can produce, so each green is re-emitted
--   with the record's own witness replaced by `refl`, which asserts the
--   carried field is the map ON THE NOSE.  That mutant MUST fail.  If it
--   passes, the probe was proving nothing and the green is reported as
--   SUSPECT rather than as a verdict.
emitP1Control :: String -> Rec -> [(String, String)] -> (String, String, String, Orient) -> String
emitP1Control nm r ps s@(wn, _, _, _) =
  replaceAll (wn ++ " = censusP") (wn ++ " = refl") (emitP1 nm r ps s)

replaceAll :: String -> String -> String -> String
replaceAll from to = go
  where
    go [] = []
    go s@(c:cs) | from `isPrefixOf` s = to ++ go (drop (length from) s)
                | otherwise           = c : go cs

-- | The separating-pair probe: two inhabitants agreeing on every other field
--   and provably differing on xⱼ.  Only ℕ and Bool fields.
knownTwo :: String -> Maybe (String, String, String, String)
-- (default inhabitant, alternative, distinctness lemma, import)
knownTwo "ℕ"    = Just ("0", "1", "znots", "Cubical.Data.Nat")
knownTwo "Bool" = Just ("true", "false", "true≢false", "Cubical.Data.Bool")
knownTwo _      = Nothing

emitP3 :: String -> Rec -> String -> Maybe String
emitP3 nm r xj = do
  fs <- Just (flatFields r)
  (dflt0, alt, lemma, _) <- knownTwo =<< lookup3 xj fs
  dflts <- mapM (\(n, ty, _) -> do
                    (d, _, _, _) <- knownTwo ty
                    return (n, d)) fs
  let val n = fromMaybe "?" (lookup n dflts)
      recWith v = "record { " ++ intercalate " ; "
                    [ n ++ " = " ++ (if n == xj then v else val n)
                    | (n, _, _) <- fs ] ++ " }"
      others = [ n | (n, _, _) <- fs, n /= xj ]
  return $ unlines $
    [ "{-# OPTIONS --cubical --safe --guardedness #-}"
    , "module " ++ nm ++ " where"
    , ""
    , "open import Cubical.Foundations.Prelude"
    , "open import Cubical.Data.Nat"
    , "open import Cubical.Data.Bool"
    , "open import Cubical.Data.Empty"
    , "open import " ++ rModule r
    , ""
    , "censusR0 censusR1 : " ++ rName r
    , "censusR0 = " ++ recWith dflt0
    , "censusR1 = " ++ recWith alt
    , ""
    ]
    ++ concat [ [ "censusAgree-" ++ show i ++ " : " ++ rName r ++ "." ++ n
                    ++ " censusR0 ≡ " ++ rName r ++ "." ++ n ++ " censusR1"
                , "censusAgree-" ++ show i ++ " = refl", "" ]
              | (i, n) <- zip [(0::Int) ..] others ]
    ++ [ "-- THE VERDICT.  Green here means the field is NOT determined:"
       , "-- two inhabitants agree on every other field and are distinct."
       , "NOT-DETERMINED : censusR0 ≡ censusR1 → ⊥"
       , "NOT-DETERMINED censusP = " ++ lemma ++ " (cong "
           ++ rName r ++ "." ++ xj ++ " censusP)"
       ]
  where
    lookup3 k xs = case [ ty | (n, ty, _) <- xs, n == k ] of
      (t:_) -> Just t
      []    -> Nothing

-- ============================================================ running agda

runAgda :: FilePath -> IO (ExitCode, String)
runAgda f = do
  let args = concat [ ["-i", d] | d <- scratchDir : incdirs ] ++ [f]
      cp = (proc "agda" args) { env = Just [("LC_ALL", "C.utf8"), ("PATH", "/opt/homebrew/bin:/usr/bin:/bin:/usr/local/bin"), ("HOME", "/Users/avikjain")] }
  r <- try (readCreateProcessWithExitCode cp "")
  case r of
    Left e -> return (ExitFailure 99, "spawn failed: " ++ show (e :: SomeException))
    Right (c, o, e) -> return (c, o ++ e)

-- Where the generated probes go.  NOT in the corpus: a probe is a question
-- put to the kernel, not a result, and leaving questions lying around as
-- modules is how an appendix grows.
--
-- Was a hardcoded session-specific path, which made the tool unrunnable by
-- anyone but the seat that wrote it — and a census nobody else can run is a
-- stored number, not a measurement (BUILD.md: a hand-maintained list rots in
-- both directions).  Now: $NIRDHARANA_SCRATCH if set, else $TMPDIR, else /tmp.
scratchDir :: FilePath
scratchDir = unsafePerformIO $ do
  env <- lookupEnv "NIRDHARANA_SCRATCH"
  case env of
    Just d  -> pure d
    Nothing -> do
      tmp <- lookupEnv "TMPDIR"
      pure (maybe "/tmp" id tmp ++ "/nirdharana")
{-# NOINLINE scratchDir #-}

data Verdict = Green | MathRed | ElabRed | HostRed | NotRun String
  deriving (Eq)

instance Show Verdict where
  show Green      = "GREEN"
  show MathRed    = "RED (math)"
  show ElabRed    = "RED (elab — generator defect, NOT a verdict)"
  show HostRed    = "RED (host — toolchain, NOT a verdict)"
  show (NotRun s) = "not run: " ++ s

-- | An elaboration failure is a scope/level/import failure; a mathematical
--   failure is a type mismatch inside the assertions.  Anything that is
--   neither is reported as elab, which is the conservative side: it never
--   invents a mathematical verdict.
classifyErr :: String -> Verdict
classifyErr out
  | any (`isInfixOf` out) [ "Not in scope", "[Scope", "InfectiveImport"
                          , "[FileNotFound", "Ambiguous", "not a valid"
                          , "No such file", "duplicate", "Duplicate"
                          , "The name", "Set₁", "Setω", "level of the" ]
      = ElabRed
  | any (`isInfixOf` out) [ "!=", "Failed to solve", "does not have", "when checking" ]
      = MathRed
  | otherwise = ElabRed

-- ============================================================ main

main :: IO ()
main = do
  -- 2026-08-24: reads of this corpus are UTF-8 (Devanagari identifiers);
  -- without this, readFile throws under a POSIX locale mid-run.
  setLocaleEncoding utf8
  hSetEncoding stdout utf8
  args <- getArgs
  let noCheck = "--no-check" `elem` args
      limit = case [ n | (a, n) <- zip args (drop 1 args), a == "--limit" ]
              of (n:_) | all isDigit n -> read n :: Int
                 _                     -> 10000

  paths0 <- concat <$> mapM (walk ["_build", ".lake"]) ["formal/cubical", "punaragamana/src"]
  let paths = filter ((== ".agda") . takeExtension) paths0
  parsed <- forM paths $ \p -> do
    s <- readFileSafe p
    let (m, rs) = parseFile p s
    return (p, m, rs)

  let allRecs = concat [ rs | (_, _, rs) <- parsed ]
      withField = filter rHasField allRecs
      fieldless = filter (not . rHasField) allRecs
      nested = filter ((/= 0) . rIndent) withField
      allFields = concatMap flatFields withField

  putStrLn "=============================================================="
  putStrLn "लेखा · LEKHĀ — the census of records"
  putStrLn "=============================================================="
  putStrLn $ "  .agda files scanned (formal/cubical + punaragamana/src)   : " ++ show (length paths)
  putStrLn $ "  `record … where` declarations found                       : " ++ show (length allRecs)
  putStrLn $ "  ... with a `field` section                                : " ++ show (length withField)
  putStrLn $ "  ... with NO `field` line (fieldless, or fields elsewhere) : " ++ show (length fieldless)
  putStrLn $ "  field declarations parsed                                 : " ++ show (length allFields)
  putStrLn $ "  ... of which implicit {x : A} or instance ⦃ x : A ⦄       : "
             ++ show (length [ () | (_,_,h) <- allFields, h ])
  putStrLn $ "  field declarations the parser COULD NOT split at `:`      : "
             ++ show (sum (map rBadDecls withField))
  putStrLn $ "  records with a field written on the `field` line itself   : "
             ++ show (length (filter rInline withField))
  putStrLn $ "  records nested inside a module/record (not column 0)      : " ++ show (length nested)
  putStrLn $ "  coinductive records                                       : "
             ++ show (length (filter rCoind withField))
  putStrLn $ "  no-eta-equality records                                   : "
             ++ show (length (filter rNoEta withField))
  putStrLn ""
  putStrLn "  BLIND SPOT, said rather than hidden: anonymous `record { … }`"
  putStrLn "  EXPRESSIONS are not declarations and are not counted here; a record"
  putStrLn "  inside a `where` block is counted only if its `record` keyword"
  putStrLn "  survives the comment scan and its body is indented under it."
  putStrLn ""

  -- 2 -----------------------------------------------------------------------
  let witnessed = [ (r, ws)
                  | r <- withField
                  , let ws = filter (isWitness r) (flatFields r)
                  , not (null ws) ]
      splits = [ (r, s)
               | (r, ws) <- witnessed
               , w <- ws
               , Just s <- [carrierSplit r w] ]

  putStrLn "=============================================================="
  putStrLn "वाहकाकार · CARRIER-SHAPED — the cheap syntactic pass"
  putStrLn "=============================================================="
  putStrLn "  THE CRITERION IS WHICH SIDE OF  f a ≡ b  IS BOUND."
  putStrLn "     bind b :  Σ[ b ∈ B ] (f a ≡ b)  =  singl (f a).  Contractible"
  putStrLn "               ALWAYS — no h-level hypothesis, arbitrary A and B."
  putStrLn "               The datum rides free."
  putStrLn "     bind a :  Σ[ a ∈ A ] (f a ≡ b)  =  the preimage.  Arbitrary."
  putStrLn "               Not free, and usually THE SUBJECT, not a defect."
  putStrLn "  A field whose type is `f (other fields) ≡ thisField` is bind-b, so"
  putStrLn "  the list below is SETTLED BY SYNTAX; the Agda run that follows is a"
  putStrLn "  confirmation and a check on this program, not the source of the"
  putStrLn "  verdict.  A record PARAMETER is bind-a and is not a field: see the"
  putStrLn "  bind-a section below."
  putStrLn ""
  putStrLn $ "  records with a WITNESS field (a path mentioning a sibling) : "
             ++ show (length witnessed)
  putStrLn $ "  ... whose witness type is `L ≡ xⱼ` / `xⱼ ≡ L` for a field xⱼ"
  putStrLn $ "      NOT occurring in L — i.e. a readable Carrier split      : "
             ++ show (length splits)
  putStrLn "  (syntax only.  A SHAPE, never a verdict; the verdict is below.)"
  putStrLn ""
  forM_ witnessed $ \(r, ws) -> do
    putStrLn $ "  " ++ rName r ++ "   [" ++ rModule r ++ ":" ++ show (rLine r) ++ "]"
    forM_ (flatFields r) $ \(n, ty, _) ->
      putStrLn $ "      " ++ (if any ((n `elem`) . (\(x,_,_) -> [x])) ws then "witness  " else "         ")
                 ++ n ++ " : " ++ take 88 ty
    case [ s | (r', s) <- splits, rName r' == rName r, rModule r' == rModule r ] of
      [] -> putStrLn "      -> no readable split (witness relates two fields, or both sides move)"
      ss -> forM_ ss $ \(wn, xj, l, o) ->
              putStrLn $ "      -> split: carried = " ++ xj ++ ", witness = " ++ wn
                         ++ ", map = " ++ take 60 l
                         ++ (if o == Rev then "   (reversed)" else "")
  putStrLn ""

  -- bind-a --------------------------------------------------------------
  let paramd = [ r | r <- withField, not (null (trim (rParams r))) ]
      indexNames r = nub (concat
        [ ns | Just gs <- [paramGroups (rParams r)], (n, _) <- gs, let ns = [n] ])
      onIndex r = [ (n, ty) | (n, ty, _) <- flatFields r
                            , isWitness r (n, ty, False)
                            , any (`mentionsTok` ty) (indexNames r) ]
      levelSets = [ (r, ws) | r <- paramd, let ws = onIndex r, not (null ws) ]
  putStrLn "=============================================================="
  putStrLn "पक्ष-बन्धः · BIND-A — parameters are INDICES, not fields"
  putStrLn "=============================================================="
  putStrLn "  A record parameter is the bound `a` side.  A record whose witness"
  putStrLn "  relates a field to a PARAMETER is a level set: its fibre is the"
  putStrLn "  preimage, arbitrary, and that is the SUBJECT of the module rather"
  putStrLn "  than a defect in it.  Reporting these as failures would be wrong,"
  putStrLn "  so they are reported here and excluded from the verdict tables."
  putStrLn ""
  putStrLn $ "  records with parameters                         : " ++ show (length paramd)
  putStrLn $ "  ... whose witness field mentions a parameter    : " ++ show (length levelSets)
  forM_ levelSets $ \(r, ws) -> do
    putStrLn $ "      " ++ pad 26 (rName r) ++ pad 44 (rModule r) ++ "(" ++ rParams r ++ ")"
    forM_ ws $ \(n, ty) -> putStrLn ("          " ++ n ++ " : " ++ take 80 ty)
  putStrLn ""

  if noCheck then putStrLn "  (--no-check: nothing emitted, nothing run)" else do

    createDirectoryIfMissing True scratchDir

    -- host checks, cached per module ---------------------------------------
    hostCache <- newIORef (M.empty :: M.Map String (ExitCode, String))
    let hostCheck r = do
          c <- readIORef hostCache
          case M.lookup (rModule r) c of
            Just v -> return v
            Nothing -> do
              (e, o) <- runAgda (rFile r)
              modifyIORef' hostCache (M.insert (rModule r) (e, o))
              return (e, o)

    -- P1 ---------------------------------------------------------------------
    putStrLn "=============================================================="
    putStrLn "प्रमाण · THE PROBE — the kernel answers, one module per candidate"
    putStrLn "=============================================================="
    let p1cands = take limit
          [ (r, ps, s)
          | (r, s) <- splits
          , Right ps <- [eligible r] ]
        p1skips = [ (r, why)
                  | (r, _) <- splits, Left (Skip why) <- [eligible r] ]
    putStrLn $ "  Carrier splits found                     : " ++ show (length splits)
    putStrLn $ "  ... probeable (top-level, eta, Type, …)  : " ++ show (length p1cands)
    putStrLn $ "  ... skipped, with the reason             : " ++ show (length p1skips)
    forM_ p1skips $ \(r, why) ->
      putStrLn $ "        " ++ rName r ++ " [" ++ rModule r ++ "] — " ++ why
    putStrLn ""

    p1res <- forM (zip [(1::Int) ..] p1cands) $ \(i, (r, ps, s@(wn, xj, _, _))) -> do
      let nm = "NirdharanaPone" ++ alphaTag i
          f  = scratchDir </> (nm ++ ".agda")
      writeFile f (emitP1 nm r ps s)
      (he, _) <- hostCheck r
      v <- if he /= ExitSuccess then return HostRed else do
             (e, o) <- runAgda f
             return (if e == ExitSuccess then Green else classifyErr o)
      ctrl <- if v /= Green then return "" else do
        let cnm = nm ++ "Control"
            cf  = scratchDir </> (cnm ++ ".agda")
        writeFile cf (emitP1Control cnm r ps s)
        (ce, _) <- runAgda cf
        return (if ce == ExitSuccess
                  then "   *** SUSPECT: the designed-failure control ALSO passed ***"
                  else "   (control fails, as it must)")
      putStrLn $ "   " ++ pad 30 (rName r) ++ pad 46 (take 45 (rModule r))
                 ++ pad 22 ("carried " ++ xj ++ " / " ++ wn) ++ show v ++ ctrl
      hFlush stdout
      return (r, s, v, nm)

    -- P3 ---------------------------------------------------------------------
    putStrLn ""
    putStrLn "=============================================================="
    putStrLn "भेद · THE SEPARATING PAIR — the negative, equally mechanical"
    putStrLn "=============================================================="
    let noWitness = [ r | r <- withField
                        , null (filter (isWitness r) (flatFields r)) ]
        p3ok = [ (r, n)
               | r <- noWitness
               , Right [] <- [eligible r]
               , all (\(_, ty, _) -> isJust (knownTwo ty)) (flatFields r)
               , length (flatFields r) >= 2
               , (n, _, _) <- flatFields r ]
        p3none = [ r | r <- noWitness
                     , not (any (\(rr, _) -> rName rr == rName r && rModule rr == rModule r) p3ok) ]
    putStrLn $ "  records with NO witness field                    : " ++ show (length noWitness)
    putStrLn $ "  ... every field type known to the prober (ℕ/Bool): "
               ++ show (length (nub [ rName r ++ rModule r | (r, _) <- p3ok ]))
    putStrLn $ "  ... NOT ATTEMPTED (unknown field type, nested,"
    putStrLn $ "      coinductive, parameterised, …)               : " ++ show (length p3none)
    putStrLn "  NOT ATTEMPTED is not a verdict of any kind."
    putStrLn ""
    putStrLn "  THE FIBRE HAS THREE CASES, NOT TWO, AND `isContr` MERGES TWO OF"
    putStrLn "  THEM.  EMPTY (नष्टि — no Carrier, no ua, nothing to transport),"
    putStrLn "  EXACTLY ONE (free), MANY (a Carrier still exists with the extra"
    putStrLn "  degrees of freedom recorded; the fibre is data).  A green here is"
    putStrLn "  MANY: two inhabitants are exhibited, so the fibre is inhabited and"
    putStrLn "  not a point.  THIS INSTRUMENT CANNOT CERTIFY EMPTY at all — it has"
    putStrLn "  no emptiness prober — so EMPTY never appears below, and its absence"
    putStrLn "  is a gap in the instrument, not a fact about the corpus."
    putStrLn ""
    p3res <- forM (zip [(1::Int) ..] (take limit p3ok)) $ \(i, (r, xj)) ->
      case emitP3 ("NirdharanaPthree" ++ alphaTag i) r xj of
        Nothing -> return (r, xj, NotRun "emitter declined")
        Just src -> do
          let nm = "NirdharanaPthree" ++ alphaTag i
              f  = scratchDir </> (nm ++ ".agda")
          writeFile f src
          (he, _) <- hostCheck r
          v <- if he /= ExitSuccess then return HostRed else do
                 (e, o) <- runAgda f
                 return (if e == ExitSuccess then Green else classifyErr o)
          putStrLn $ "   " ++ pad 30 (rName r) ++ pad 46 (take 45 (rModule r))
                     ++ pad 22 ("field " ++ xj)
                     ++ (case v of Green -> "SEPARATED (not determined)"; _ -> show v)
          hFlush stdout
          return (r, xj, v)

    -- 4 ----------------------------------------------------------------------
    putStrLn ""
    putStrLn "=============================================================="
    putStrLn "वाहकानुक्त · THE CARRIER UNSAID — the actionable list"
    putStrLn "=============================================================="
    putStrLn "  Records the kernel has just confirmed are Carrier-shaped — the"
    putStrLn "  field and its witness ride free, R ≃ (the rest) — whose own file"
    putStrLn "  never states it: no `Carrier`, no `≃`, no `Iso`, no `ua` in the"
    putStrLn "  module at all.  The equivalence is true, checked, and unwritten."
    putStrLn "  READ THE LIMIT ABOVE: this is NOT the same claim as 'a determined"
    putStrLn "  field with no witness', which no census can find, because a green"
    putStrLn "  verdict needs the determining map and only a witness field carries"
    putStrLn "  one."
    putStrLn ""
    srcCache <- newIORef (M.empty :: M.Map FilePath String)
    unsaid <- fmap catMaybes $ forM [ (r, s) | (r, s, Green, _) <- p1res ] $ \(r, (wn, xj, _, _)) -> do
      c <- readIORef srcCache
      src <- case M.lookup (rFile r) c of
        Just s -> return s
        Nothing -> do { s <- readFileSafe (rFile r)
                      ; modifyIORef' srcCache (M.insert (rFile r) s); return s }
      let says = any (`isInfixOf` src) ["Carrier", "≃", "Iso", " ua ", "isContr"]
      return (if says then Nothing else Just (r, xj, wn))
    putStrLn $ "  GREEN Carrier records whose module says nothing about it : "
               ++ show (length unsaid)
    forM_ unsaid $ \(r, xj, wn) ->
      putStrLn $ "      " ++ pad 28 (rName r) ++ pad 46 (rModule r)
                 ++ "carried " ++ xj ++ " with witness " ++ wn

    -- summary ---------------------------------------------------------------
    putStrLn ""
    putStrLn "=============================================================="
    putStrLn "सारः · SUMMARY"
    putStrLn "=============================================================="
    let cnt v xs = length [ () | x <- xs, x == v ]
        v1 = [ v | (_,_,v,_) <- p1res ]
        v3 = [ v | (_,_,v) <- p3res ]
    putStrLn $ "  Carrier probes run                : " ++ show (length v1)
    putStrLn $ "    GREEN — fibre EXACTLY ONE, free : " ++ show (cnt Green v1)
    putStrLn $ "    MATH   RED (a real verdict, and it is the MERGED bucket:"
    putStrLn $ "      EMPTY and MANY are not separated here) : " ++ show (cnt MathRed v1)
    putStrLn $ "    ELAB   RED (generator defect)   : " ++ show (cnt ElabRed v1)
    putStrLn $ "    HOST   RED (toolchain, no verdict): " ++ show (cnt HostRed v1)
    putStrLn $ "  Separating-pair probes run        : " ++ show (length v3)
    putStrLn $ "    SEPARATED — fibre MANY, ≥2 points, NOT determined : "
               ++ show (cnt Green v3)
    putStrLn $ "    EMPTY (नष्टि)                    : not probeable by this tool"
    putStrLn $ "    MATH   RED                      : " ++ show (cnt MathRed v3)
    putStrLn $ "    ELAB   RED                      : " ++ show (cnt ElabRed v3)
    putStrLn $ "    HOST   RED                      : " ++ show (cnt HostRed v3)
    hosts <- readIORef hostCache
    let bad = [ m | (m, (e, _)) <- M.toList hosts, e /= ExitSuccess ]
    putStrLn ""
    putStrLn "  HOST CHECKS COVER ONLY THE MODULES A PROBE NEEDED.  This is NOT a"
    putStrLn "  corpus-wide toolchain audit: modules written against agda/cubical"
    putStrLn "  v0.5 names (CakravalaBound's `solve`, VivekaPramana_TheUpadhi…'s"
    putStrLn "  `isSetRetract`) fail under v0.9 and are simply not in this set"
    putStrLn "  unless a candidate lived in them."
    putStrLn $ "  host modules checked              : " ++ show (M.size hosts)
    putStrLn $ "  host modules that do NOT check under Agda 2.8.0 / cubical v0.9 : "
               ++ show (length bad)
    forM_ (sort bad) $ \m -> putStrLn ("      " ++ m)
    putStrLn ""
    putStrLn $ "  generated modules are in " ++ scratchDir
    putStrLn "  and nothing was written into the corpus."

alphaTag :: Int -> String
alphaTag n
  | n <= 0    = ""
  | otherwise = alphaTag ((n - 1) `div` 26) ++ [toEnum (fromEnum 'A' + ((n - 1) `mod` 26))]

pad :: Int -> String -> String
pad n s = s ++ replicate (max 1 (n - length s)) ' '
