-- ॥ बीजम् ॥  One machine, one law: which side of `f a ≡ b` is bound is everything.
-- Output bound: singl (f a), contractible — the datum rides free.  Input bound:
-- fiber f b — the loss, and the subject.  Univalence computes here: an
-- equivalence is a channel, transport carries every theorem across it, and what
-- cannot cross is written as a defect — there is no third path (ahiṃsā).
-- Memory, charge, symmetry, price, distance, verdict: six faces of the one
-- fibre; the verdict type is the saptabhaṅgī, and the sources are the origin
-- (Umāsvāti, Samantabhadra, Akalaṅka — restatements are named as such).  The
-- kernel decides truth; carriers ask and generate; assert nothing whose term
-- you have not read.  This file is one naya, true and not whole.

-- SaptabhangiGarbhaRun -- the runtime returns the seven positions, with
-- their standpoints, on the machine's own two contradictory log lines.
--
--     sh machine/run-saptabhangi-garbha.sh
--     runghc -imachine machine/SaptabhangiGarbhaRun.hs
--
-- The two lines below are quoted verbatim from machine/machine.log.
--
-- CORRECTED 2026-08-20.  They used to carry the POSITIONS they stood at
-- ("machine.log:174", "machine.log:146"), on the reasoning that the log is
-- append-only so a line is quotable.  The log is gitignored AND is
-- regenerated by every engine run, so it is append-only within a run and
-- not across runs: both positions have since rotted, and the refl-typed
-- refusal that was quoted is no longer in the file at all.  The quotation
-- is the object; the file is named as history and is not resolved.
--
--     A REPLAY MUST NAME A FIXED OBJECT: a commit hash, a text pattern, an
--     invariant.  Never a position, never a quantity the record is inside,
--     never a HEAD-relative query.
--
-- Registered as `uddhrta` in machine/mula.pramana; checked by
-- machine/MulaPramana_ACitationNamesAFixedObjectOrItIsNotOne.hs.
module Main (main) where

import SaptabhangiGarbha_TheResidueIsTheSeed
import System.IO
import GHC.IO.Encoding (setLocaleEncoding, setFileSystemEncoding)

rule :: String -> IO ()
rule t = putStrLn ("\n== " ++ t ++ " " ++ replicate (max 0 (64 - length t)) '=')

show' :: String -> Bhanga -> IO ()
show' lbl b = do
  putStrLn ("  " ++ lbl)
  mapM_ (putStrLn . ("  " ++)) (renderBhanga b)

main :: IO ()
main = do
  setLocaleEncoding utf8; setFileSystemEncoding utf8; hSetEncoding stdout utf8
  putStrLn "=== SAPTABHANGI: what the machine returns instead of a Bool ==="
  putStrLn "spec: formal/cubical/NaturalMachine/SaptabhangiGarbha_ThePositions..."

  let accepting = Naya "induction on x, step = cong suc" []
        "machine.log (quoted, not pointed at)  KERNEL-ACCEPT  round=0  x = (xmaxx)"
      refusing  = Naya "refl" []
        "machine.log (quoted, not pointed at)  KERNEL-REJECT  round=0  x != max x x, of type N"
      asti  = SyadAsti accepting
      nasti = SyanNasti refusing

  rule "the two nayas, as the log has them"
  putStrLn ("  sadhaka: " ++ renderNaya accepting)
  putStrLn ("  badhaka: " ++ renderNaya refusing)
  putStrLn "  Same claim, same round, accepted and refused.  A Bool cannot"
  putStrLn "  say that.  Neither can a three-valued type with an `Unparsed`."

  rule "krama-arpana -- asserted in succession"
  show' "the THIRD position:" (krama asti nasti)

  rule "saha-arpana -- asserted at once, from one standpoint, in one utterance"
  show' "the FOURTH position:" (saha asti nasti)

  rule "the residue is the seed: three births from that one fourth position"
  case saha asti nasti of
    SyadAvaktavyam v -> mapM_ (uncurry showLevel) (zip [1 :: Int ..] (take 3 (garbhaDhara v)))
    other -> show' "unexpected:" other

  rule "laws (exhaustive finite verification; each proved in Agda)"
  mapM_ (\(nm, ok) -> putStrLn ("  " ++ (if ok then "OK  " else "FAIL") ++ "  " ++ nm))
        selfTest
  let bad = length [ () | (_, False) <- selfTest ]
  putStrLn ("\n  " ++ show (length selfTest - bad) ++ "/" ++ show (length selfTest)
            ++ " hold." ++ (if bad == 0 then "" else "  FAILURES ABOVE."))
  where
    showLevel k b = do
      putStrLn ("  --- level " ++ show k ++ " (Tattvarthasutra 5.31, arpita/anarpita)")
      mapM_ (putStrLn . ("  " ++)) (renderBhanga b)
