-- VargaPrakrtiEmit — the general reactor emits its answer as Agda, and the
-- kernel checks it.
--
--     runghc -imachine machine/VargaPrakrtiEmit_TheWitnessTheKernelChecks.hs 61
--       > formal/cubical/VargaPrakrtiWitness_FundamentalUnitOfTheOrder.agda
--     cd formal/cubical && agda VargaPrakrtiWitness_FundamentalUnitOfTheOrder.agda
--
-- WHY.  A printed number must be trusted — the reader trusts the program,
-- its author and the run, which CLAUDE.md says is exactly what an
-- experiment stands in for.  A checked term is the object itself and is
-- still there tomorrow.
--
-- WHAT THE WITNESS CONTAINS, and this is more than `NalandaEmit` emits:
--
--   1. every turn of the wheel, as an instance of `cakravalaTraceℕ` —
--      proved for ALL naturals, with the middle coefficient carried;
--   2. the bookkeeping, as ℕ `refl`s: the three divisions came out exact;
--   3. the fundamental UNIT, N(ε) = ±1, not merely the norm-one solution;
--   4. THE TRANSPORT.  The ladder ε, ε², …, εⁿ, each rung an instance of
--      `bhavanaTraceℕ`, ending in the identity that εⁿ IS the classical
--      answer to x² − D y² = 1 that `Nalanda` reports.  That rung is the
--      whole point: the generalisation does not replace the received
--      result, it CONTAINS it, and the kernel is what says so.
--      At D = 61 the ladder is six rungs long and its top is Bhāskara's
--      (1766319049, 226153980).
--
-- OVER ℕ, SUBTRACTION-FREE, and that is forced.  Cubical's ℤ product is
-- unary, so a `refl` on ten-digit ℤ literals asks for ~10¹⁸ unfoldings and
-- never returns; cubical's ℕ is `Agda.Builtin.Nat` with GMP-backed
-- operations.  The same discovery `BhavanaSemiring` and `CakravalaNat`
-- made, unchanged.
--
-- TWO PATHS, NO THIRD.  If any coordinate the run produces is negative, ℕ
-- cannot carry it and this emitter REFUSES rather than emitting a
-- statement in the wrong ring or silently taking an absolute value that
-- would change the norm when T ≠ 0.  The refusal names the coordinate.

module Main (main) where

import VargaPrakrti_CompositionLawAsParameter
import System.Environment (getArgs)
import System.Exit
import System.IO (hSetEncoding, stdout, utf8)

main :: IO ()
main = do
  hSetEncoding stdout utf8
  args <- getArgs
  case args of
    [raw] | [(dd, "")] <- reads raw -> emit dd
    _ -> putStrLn "usage: VargaPrakrtiEmit <Δ>   (Δ ≡ 0 or 1 mod 4, non-square)"
           >> exitFailure

-- the ladder: ε, ε², … up to the first power that lands in ℤ[√Δ] with
-- norm 1, i.e. the classical answer.  For T = 1 that power is 6 at Δ = 61.
ladderTo :: Law Quad -> Quad -> [Quad]
ladderTo law e = take 24 (iterate (lawCompose law e) e)

emit :: Integer -> IO ()
emit dd = case maximalOrderLaw dd of
  Left def -> putStrLn ("-- reactor refused:\n-- " ++ renderDefect def) >> exitFailure
  Right law -> case reactor law of
    Left def -> putStrLn ("-- reactor refused:\n-- " ++ renderDefect def) >> exitFailure
    Right trace -> do
      let neg = [ q | q@(Quad x y) <- trace, x < 0 || y < 0 ]
      if not (null neg)
        then putStrLn ("-- refusing to emit: the run produced a negative \
                       \coordinate, which ℕ cannot carry: " ++ show (head neg))
               >> exitFailure
        else case pellLaw dd of
          Left def -> putStrLn ("-- " ++ renderDefect def) >> exitFailure
          Right pl -> case normOneSolution pl of
            Left def -> putStrLn ("-- " ++ renderDefect def) >> exitFailure
            Right (Quad pa pb) -> putStr (render dd law trace pa pb)

render :: Integer -> Law Quad -> [Quad] -> Integer -> Integer -> String
render dd law trace pa pb = unlines $
  header ++ body
  where
    (t, c) = if dd `mod` 4 == 1 then (1, (dd - 1) `div` 4) else (0, dd `div` 4)
    nrm (Quad x y) = x * x + t * x * y - c * y * y
    eps@(Quad ex ey) = last trace
    ladder = ladderTo law eps
    -- the first rung with even coordinates in the (u, v)/2 presentation and
    -- norm +1: that rung IS the classical solution of x² − Δ y² = 1.
    rung = head ([ (n, q) | (n, q@(Quad x y)) <- zip [1 :: Int ..] ladder
                          , nrm q == 1, even (2 * x + y), even y ]
                 ++ [(0, eps)])
    sep = "------------------------------------------------------------------------"

    header =
      -- `--guardedness` added 2026-08-20: Agda's [InfectiveImport] rule makes it
      -- propagate, so a module opening Cubical.Foundations.Prelude without it fails
      -- at SCOPE-CHECKING under a cubical library compiled with it (Agda 2.8.0).
      -- Kept equal to Certificate.kOptionsPragma by
      -- scripts/Anuvrtti_TheOptionsLineIsSaidOnceAndContinues.sh.
      [ "{-# OPTIONS --cubical --guardedness --safe --no-import-sorts #-}"
      , ""
      , sep
      , "-- VargaPrakrtiWitness — EMITTED BY THE REACTOR, CHECKED BY THE KERNEL."
      , "--"
      , "-- Generated by"
      , "--   runghc -imachine machine/VargaPrakrtiEmit_TheWitnessTheKernelChecks.hs "
          ++ show dd
      , "-- Do not hand-edit; regenerate."
      , "--"
      , "-- THE ORDER.  ℤ[ω] with ω² = " ++ show t ++ "ω + " ++ show c
          ++ ", i.e. ω = (" ++ show t ++ " + √" ++ show dd ++ ")/2,"
      , "-- the MAXIMAL order of discriminant Δ = " ++ show dd
          ++ ".  Its norm form is"
      , "--"
      , "--     N(x, y) = x² + " ++ show t ++ "·x·y − " ++ show c ++ "·y²"
      , "--"
      , "-- and at " ++ (if t == 1 then "T = 1 this is NOT x² − D y²: ℤ[√"
                          ++ show dd ++ "] sits inside ℤ[ω] with index 2, and"
                        else "T = 0 this is x² − D y² itself, and")
      , "-- " ++ (if t == 1 then "the equation x² − " ++ show dd
                              ++ " y² = 1 cannot see the smaller units."
                 else "the witness coincides with the classical one.")
      , "--"
      , "-- THE ANSWER.  ε = (" ++ show ex ++ ", " ++ show ey
          ++ ") in the basis (1, ω), i.e."
      , "--"
      , "--     ε = (" ++ show (2 * ex + ey) ++ " + " ++ show ey
          ++ "√" ++ show dd ++ ")/2,      N(ε) = " ++ show (nrm eps)
      , "--"
      , "-- reached in " ++ show (length trace - 1)
          ++ " turns of the wheel from the seed (⌊(−T+√Δ)/2⌋, 1)."
      , "-- Each turn's m is the one BHĀSKARA's choice rule selects — among"
      , "-- the m with k | (a + b(m+T)) and 2m + T > 0, the one minimising"
      , "-- |m² + Tm − C| — and that congruence is solved by ĀRYABHAṬA's"
      , "-- kuṭṭaka (Āryabhaṭīya, Gaṇitapāda 32–33, 499).  The composition is"
      , "-- BRAHMAGUPTA's bhāvanā (Brāhmasphuṭasiddhānta 18, 628) with the"
      , "-- middle coefficient carried; the cycle is JAYADEVA (~950) and"
      , "-- BHĀSKARA II (Bījagaṇita, 1150)."
      , "--"
      , "-- THE TRACE BELOW IS THE GENERATOR'S WORD, NOT THE KERNEL'S.  Only"
      , "-- the theorems are checked."
      , "--" ]
      ++ [ "--   turn " ++ pad 4 (show i) ++ pad 22 (show x) ++ pad 22 (show y)
           ++ "k = " ++ show (nrm q)
         | (i, q@(Quad x y)) <- zip [0 :: Int ..] trace ]
      ++ [ sep
         , ""
         , "module VargaPrakrtiWitness where"
         , ""
         , "open import Cubical.Foundations.Prelude"
         , "open import Cubical.Data.Nat using (ℕ ; _+_ ; _·_)"
         , "open import Cubical.Data.Sigma using (_×_ ; _,_)"
         , "open import VargaPrakrti_TraceBhavanaOverN"
         , "  using (vpX ; vpY ; vpQ ; vpStepX ; vpStepY"
         , "        ; bhavanaTraceℕ ; cakravalaTraceℕ)"
         , ""
         , "T C Δ : ℕ"
         , "T = " ++ show t
         , "C = " ++ show c
         , "Δ = " ++ show dd
         , "" ]

    body = turns ++ books ++ unitBlock ++ ladderBlock ++ transportBlock

    ------------------------------------------------------------------
    turns =
      [ sep
      , "-- EVERY TURN OF THE WHEEL, CERTIFIED BY THE GENERAL THEOREM."
      , "--"
      , "-- Each line instantiates `cakravalaTraceℕ` — proved for ALL naturals"
      , "-- as a commutative-semiring identity — at that turn's own (a, b, m)."
      , "-- Note what these are NOT: they are not `refl`.  A `refl` per turn"
      , "-- would show only that this generator's arithmetic agrees with the"
      , "-- kernel's.  These are the law firing, once per turn."
      , sep
      , "" ]
      ++ concat [ turnBlock i x y m | (i, (Quad x y, m)) <- zip [0 :: Int ..] steps ]

    steps = [ (q, mFor q) | q <- init trace ]

    -- recover the m the reactor used, from the pair and its successor:
    -- b' = (a + b(m+T))/k, so m = (k·b' − a)/b − T when b ≠ 0.
    mFor q@(Quad a b) =
      let k = nrm q
          Quad _ b' = next q
      in head [ m | m <- [0 .. 4 * (abs k + isqrt (t * t + 4 * c) + 2)]
                  , a + b * (m + t) == abs k * b'
                  , (a * m + c * b) `mod` k == 0 ]
      where
        next z = case [ v | (u, v) <- zip trace (drop 1 trace), u == z ] of
                   (v : _) -> v
                   []      -> z

    turnBlock i a b m =
      [ "-- turn " ++ show i ++ ":  a = " ++ show a ++ ",  b = " ++ show b
        ++ ",  m = " ++ show m
      , nm ++ " : vpStepX C " ++ sh3 ++ " · vpStepX C " ++ sh3
      , "     + (T · (vpStepX C " ++ sh3 ++ " · vpStepY T " ++ sh3 ++ ")"
      , "        + (C · vpQ T " ++ show a ++ " " ++ show b
        ++ " + C · ((" ++ show m ++ " · " ++ show m ++ " + T · " ++ show m
        ++ ") · (" ++ show b ++ " · " ++ show b ++ "))))"
      , "     ≡ vpQ T " ++ show a ++ " " ++ show b ++ " · ("
        ++ show m ++ " · " ++ show m ++ " + T · " ++ show m ++ ")"
      , "     + (C · C · (" ++ show b ++ " · " ++ show b ++ ")"
        ++ " + C · (vpStepY T " ++ sh3 ++ " · vpStepY T " ++ sh3 ++ "))"
      , nm ++ " = cakravalaTraceℕ T C " ++ sh3
      , "" ]
      where
        nm = "turn" ++ show i
        sh3 = show a ++ " " ++ show b ++ " " ++ show m

    ------------------------------------------------------------------
    books =
      [ sep
      , "-- THE BOOKKEEPING: the three divisions came out exact."
      , "--"
      , "-- The identity above is the step's CONTENT; these are its ACCOUNTS."
      , "-- Bhāskara's choice rule earns its keep exactly here — it picks the"
      , "-- one m for which all three divisions are exact, and"
      , "-- `CakravalaDescent.oneCongruenceCoprime` proves that asking for the"
      , "-- middle one alone suffices, given the pulverizer's coefficients."
      , "--"
      , "-- Two of the three are subtraction-free as they stand: a·m + C·b and"
      , "-- a + (b·m + T·b) are sums of naturals.  Only m² + Tm − C can go"
      , "-- negative, and |m² + Tm − C| = |k|·|k′| holds either way, so each"
      , "-- line is emitted in whichever orientation is true at that turn."
      , "-- The SIGNS of k and k′ are not recovered here — they are in the"
      , "-- trace comments above, and they are the generator's word."
      , sep
      , "" ]
      ++ concat [ bookBlock i x y m x' y'
                | (i, ((Quad x y, m), Quad x' y'))
                    <- zip [0 :: Int ..] (zip steps (drop 1 trace)) ]

    bookBlock i a b m a' b' =
      [ "-- turn " ++ show i ++ " bookkeeping:  |k| = " ++ show k
        ++ ",  a′ = " ++ show a' ++ ",  b′ = " ++ show b'
        ++ ",  |k′| = " ++ show k'
      , dA ++ " : " ++ show a ++ " · " ++ show m ++ " + C · " ++ show b
        ++ " ≡ " ++ show k ++ " · " ++ show a'
      , dA ++ " = refl"
      , dB ++ " : " ++ show a ++ " + (" ++ show b ++ " · " ++ show m
        ++ " + T · " ++ show b ++ ") ≡ " ++ show k ++ " · " ++ show b'
      , dB ++ " = refl"
      , dK ++ " : " ++ (if m * m + t * m >= c
                          then show m ++ " · " ++ show m ++ " + T · " ++ show m
                               ++ " ≡ C + " ++ show k ++ " · " ++ show k'
                          else show m ++ " · " ++ show m ++ " + T · " ++ show m
                               ++ " + " ++ show k ++ " · " ++ show k' ++ " ≡ C")
      , dK ++ " = refl"
      , "" ]
      where
        k  = abs (nrm (Quad a b))
        k' = abs ((m * m + t * m - c) `div` nrm (Quad a b))
        dA = "divA" ++ show i
        dB = "divB" ++ show i
        dK = "divK" ++ show i

    ------------------------------------------------------------------
    unitBlock =
      [ sep
      , "-- THE FUNDAMENTAL UNIT.  `refl`: the kernel recomputes both sides."
      , "--"
      , "-- N(ε) = " ++ show (nrm eps) ++ ", stated subtraction-free as"
      , "--   x² + T·x·y " ++ (if nrm eps == 1 then "≡ C·y² + 1" else "+ 1 ≡ C·y²")
      , "--"
      , "-- This is a UNIT, not merely a solution of the norm-one equation."
      , "-- `Nalanda` stops at N = +1 and therefore reports ε or ε² without"
      , "-- distinguishing them; the distinction is the whole difference"
      , "-- between the order's unit group and the Pell solutions inside it."
      , sep
      , ""
      , "x y : ℕ"
      , "x = " ++ show ex
      , "y = " ++ show ey
      , ""
      , "fundamentalUnit : " ++ (if nrm eps == 1
          then "x · x + T · (x · y) ≡ C · (y · y) + 1"
          else "x · x + T · (x · y) + 1 ≡ C · (y · y)")
      , "fundamentalUnit = refl"
      , "" ]

    ------------------------------------------------------------------
    ladderBlock
      | fst rung <= 1 = []
      | otherwise =
          [ sep
          , "-- THE LADDER: ε, ε², …, ε" ++ supers (fst rung) ++ ", BY BHĀVANĀ."
          , "--"
          , "-- Each rung is Brahmagupta's composition of the rung below with"
          , "-- ε — no search, no candidate set.  `vpX`/`vpY` are the general"
          , "-- composed coordinates and the `refl`s say the reactor's numbers"
          , "-- are exactly what those functions compute; `bhavanaTraceℕ` is"
          , "-- the law that rung is an instance of."
          , sep
          , "" ]
          ++ concat [ rungBlock n px py | (n, Quad px py) <-
                        zip [2 ..] (take (fst rung - 1) (drop 1 ladder)) ]

    rungBlock n px py =
      [ "e" ++ show (n :: Int) ++ "x e" ++ show n ++ "y : ℕ"
      , "e" ++ show n ++ "x = " ++ show px
      , "e" ++ show n ++ "y = " ++ show py
      , ""
      , "-- the coordinates are Brahmagupta's, computed by the kernel"
      , "rung" ++ show n ++ " : (vpX C " ++ prev ++ " x y ≡ e" ++ show n ++ "x)"
      , "         × (vpY T " ++ prev ++ " x y ≡ e" ++ show n ++ "y)"
      , "rung" ++ show n ++ " = refl , refl"
      , ""
      , "-- and the LAW this rung is an instance of, fired at these numbers."
      , "-- Without this line the `refl` above would say only that the"
      , "-- generator's arithmetic agrees with the kernel's, and would not tie"
      , "-- the rung to bhāvanā at all."
      , "rungLaw" ++ show n ++ " : vpX C " ++ pxy ++ " · vpX C " ++ pxy
      , "     + (T · (vpX C " ++ pxy ++ " · vpY T " ++ pxy ++ ")"
      , "        + (C · (vpQ T " ++ prev ++ " · (y · y))"
      , "           + C · (vpQ T x y · (" ++ pv ++ "y · " ++ pv ++ "y))))"
      , "     ≡ vpQ T " ++ prev ++ " · vpQ T x y"
      , "     + (C · C · (" ++ pv ++ "y · " ++ pv ++ "y · (y · y))"
      , "        + C · (vpY T " ++ pxy ++ " · vpY T " ++ pxy ++ "))"
      , "rungLaw" ++ show n ++ " = bhavanaTraceℕ T C " ++ pxy
      , "" ]
      where
        prev = if n == 2 then "x y" else "e" ++ show (n - 1) ++ "x e"
                                          ++ show (n - 1) ++ "y"
        pv   = if n == 2 then "" else "e" ++ show (n - 1)
        pxy  = prev ++ " x y"

    ------------------------------------------------------------------
    -- THE TRANSPORT.  The received answer, recovered from the general one.
    transportBlock =
      [ sep
      , "-- THE TRANSPORT — nothing is lost, and the kernel says so."
      , "--"
      , "-- ℤ[√Δ] sits inside ℤ[ω]" ++ (if t == 1 then " with index 2" else "")
        ++ ", as the pairs (u, v) with"
        , "-- u + v√Δ = x + yω, i.e. u = (2x + y)/2 and v = y/2 — so a rung of"
      , "-- the ladder lies in ℤ[√Δ] exactly when 2x + y and y are both even."
      , "--"
      , "-- ε" ++ supers (fst rung) ++ " is the first such rung with norm +1, and IT IS"
      , "-- THE CLASSICAL ANSWER: the fundamental solution of x² − " ++ show dd
        ++ " y² = 1"
      , "-- that `Nalanda.hs` and every table report, namely"
      , "--"
      , "--     (" ++ show pa ++ ", " ++ show pb ++ ")"
      , "--"
      , "-- The generalisation does not replace it.  It contains it, as a"
      , "-- power, and reaches it from a smaller object in fewer turns."
      , sep
      , ""
      , "u v : ℕ"
      , "u = " ++ show pa
      , "v = " ++ show pb
      , ""
      , "-- the classical equation, recomputed by the kernel"
      , "classical : u · u ≡ Δ · (v · v) + 1"
      , "classical = refl"
      , ""
      , "-- and ε" ++ supers (fst rung) ++ " IS that solution:  2·(top rung's x) + (its y) = 2u,"
      , "-- and (its y) = 2v."
      , "transport" ++ supers (fst rung) ++ " : (2 · " ++ show rx ++ " + " ++ show ry
        ++ " ≡ 2 · u) × (" ++ show ry ++ " ≡ 2 · v)"
      , "transport" ++ supers (fst rung) ++ " = refl , refl" ]
      where Quad rx ry = snd rung

    pad n s = s ++ replicate (max 0 (n - length s)) ' '
    supers n = concatMap sup (show n)
    sup ch = case ch of
      '0' -> "⁰"; '1' -> "¹"; '2' -> "²"; '3' -> "³"; '4' -> "⁴"
      '5' -> "⁵"; '6' -> "⁶"; '7' -> "⁷"; '8' -> "⁸"; '9' -> "⁹"; _ -> [ch]
