"""The multiplicative confinement index has one formula at every prime.

Companion to `notes/CONFINEMENT_INDEX_IS_UNIFORM.md`.

`MULTIPLICATIVE_CONFINEMENT.md` computed the confinement index of a held set by
Gauss's index calculus, which needs a cyclic group and so covered odd `p` only.
`TWO_ADIC_CONFINEMENT.md` repaired `p = 2` by hand and got a **two-branch**
formula keyed on whether the generated subgroup `U` meets `3 mod 4`.  Its seed 1
asked for the odd-`p` case in level language and predicted "a single formula
covering both notes rather than two".

There is one.  Let

    c = 1 for odd p, c = 2 for p = 2                     (principal exponent)
    P = 1 + p^c Z  <  (Z/p^k)^*                          (cyclic, order p^(k-c))
    l(U)   defined by  U cap P = 1 + p^l Z               (level)
    d(U) = | image of U in (Z/p^c)^* |                   (signature order)

Then for every prime `p`, every `k > c`, and every subgroup `U`,

    |U| = d * p^(k-l)          and          [G:U] = (phi(p^c) / d) * p^(l-c).

At `p = 2` this is `2^(l-1)` when `d = 1` and `2^(l-2)` when `d = 2`, which is
exactly the two-branch formula of `TWO_ADIC_CONFINEMENT.md` (1.1).  The branch
was the vocabulary, not the object.

The exceptionality of `p = 2` does not disappear; it *moves*.  For odd `p` the
pair `(d, l)` classifies subgroups bijectively (`tau(p-1) * k` of them).  At
`p = 2` the pair still gives the index but no longer separates subgroups:
`{1,15}` and `{1,31}` mod `32` share `(d,l) = (2,5)`.

All arithmetic is exact and every check in the companion test module is an
exhaustive finite verification over a complete subgroup lattice, i.e. proof in
the sense of `CLAUDE.md`, not measurement.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Sequence


def principal_exponent(p: int) -> int:
    """`c` such that `1 + p^c Z` is the cyclic group of principal units.

    `c = 1` for odd `p`; `c = 2` for `p = 2`, where `1 + 2Z` is the whole unit
    group and is not cyclic for `k >= 3`.
    """
    if p < 2:
        raise ValueError(f"{p} is not a prime")
    return 2 if p == 2 else 1


def totient_prime_power(p: int, e: int) -> int:
    """`phi(p^e)`, exactly."""
    return (p - 1) * p ** (e - 1)


def unit_group(p: int, k: int) -> tuple[int, ...]:
    """The units of `Z/p^k`, ascending."""
    modulus = p ** k
    return tuple(u for u in range(1, modulus) if u % p != 0)


def subgroup_generated(generators: Sequence[int], p: int, k: int) -> frozenset[int]:
    """The subgroup of `(Z/p^k)^*` generated by the held residues.

    The ambient group is finite, so the multiplicative *monoid* closure already
    contains inverses; no inversion step is needed.
    """
    modulus = p ** k
    seeds = []
    for g in generators:
        if g % p == 0:
            raise ValueError(f"{g} is not a unit mod {p}^{k}")
        seeds.append(g % modulus)
    reached = {1}
    frontier = [1]
    while frontier:
        current = frontier.pop()
        for s in seeds:
            nxt = (current * s) % modulus
            if nxt not in reached:
                reached.add(nxt)
                frontier.append(nxt)
    return frozenset(reached)


def level(subgroup: Iterable[int], p: int, k: int) -> int:
    """`l` with `U cap (1 + p^c Z) = 1 + p^l Z`.

    Well defined because `1 + p^c Z` is cyclic of order `p^(k-c)`, so its
    subgroups form a single chain.
    """
    c = principal_exponent(p)
    principal_modulus = p ** c
    meet = [u for u in subgroup if u % principal_modulus == 1]
    order = len(meet)
    # |1 + p^l Z| = p^(k-l).
    l = k
    while order > 1:
        if order % p != 0:
            raise ValueError("intersection with the principal units is not a p-group")
        order //= p
        l -= 1
    return l


def signature_order(subgroup: Iterable[int], p: int) -> int:
    """`d = |image of U in (Z/p^c)^*|`.

    For `p = 2` this is `2` exactly when `U` meets `3 mod 4` -- the ad hoc bit
    of `TWO_ADIC_CONFINEMENT.md`, here an instance of a general invariant.
    """
    c = principal_exponent(p)
    return len({u % p ** c for u in subgroup})


@dataclass(frozen=True)
class ConfinementReport:
    p: int
    k: int
    order: int
    level: int
    signature_order: int
    index: int
    predicted_order: int
    predicted_index: int

    @property
    def agrees(self) -> bool:
        return self.order == self.predicted_order and self.index == self.predicted_index

    @property
    def unreachable_fraction(self) -> tuple[int, int]:
        """Exact rational `(numerator, denominator)` of classes never reached."""
        return (self.index - 1, self.index)


def predicted_index(p: int, level_: int, signature: int) -> int:
    """`(phi(p^c) / d) * p^(l - c)` -- the uniform formula."""
    c = principal_exponent(p)
    w = totient_prime_power(p, c)
    if w % signature != 0:
        raise ValueError(f"signature order {signature} does not divide phi(p^{c}) = {w}")
    return (w // signature) * p ** (level_ - c)


def analyse(subgroup: Iterable[int], p: int, k: int) -> ConfinementReport:
    """Measured order/index against the predictions of the uniform formula."""
    c = principal_exponent(p)
    if k <= c:
        raise ValueError(f"require k > {c} at p = {p}")
    members = frozenset(subgroup)
    l = level(members, p, k)
    d = signature_order(members, p)
    order = len(members)
    ambient = totient_prime_power(p, k)
    return ConfinementReport(
        p=p,
        k=k,
        order=order,
        level=l,
        signature_order=d,
        index=ambient // order,
        predicted_order=d * p ** (k - l),
        predicted_index=predicted_index(p, l, d),
    )


def analyse_held_set(generators: Sequence[int], p: int, k: int) -> ConfinementReport:
    """Confinement report for the subgroup a held set generates."""
    return analyse(subgroup_generated(generators, p, k), p, k)


def all_subgroups(p: int, k: int) -> tuple[frozenset[int], ...]:
    """Every subgroup of `(Z/p^k)^*`, by closure of the subgroup lattice.

    Exhaustive: breadth-first from the trivial subgroup, adjoining one element
    at a time.  Every subgroup is finitely generated, so every subgroup is
    reached.  Returned sorted by order then by sorted membership, so the output
    is a canonical object rather than a traversal artifact.
    """
    units = unit_group(p, k)
    modulus = p ** k
    trivial = frozenset({1})
    seen = {trivial}
    frontier = [trivial]
    while frontier:
        current = frontier.pop()
        for u in units:
            if u in current:
                continue
            extended = _adjoin(current, u, modulus)
            if extended not in seen:
                seen.add(extended)
                frontier.append(extended)
    return tuple(sorted(seen, key=lambda s: (len(s), sorted(s))))


def _adjoin(subgroup: frozenset[int], element: int, modulus: int) -> frozenset[int]:
    """The subgroup generated by `subgroup` together with `element`."""
    reached = set(subgroup)
    power = element % modulus
    while power not in subgroup:
        reached.update((power * s) % modulus for s in subgroup)
        power = (power * element) % modulus
    return frozenset(reached)


def divisor_count(n: int) -> int:
    """`tau(n)`, exactly."""
    if n < 1:
        raise ValueError(f"tau is defined on positive integers, got {n}")
    count = 0
    d = 1
    while d * d <= n:
        if n % d == 0:
            count += 2 if d * d != n else 1
        d += 1
    return count


def certify_index_formula(p: int, k: int) -> tuple[ConfinementReport, ...]:
    """Exhaustive certificate: the uniform formula on *every* subgroup.

    Raises if any subgroup disagrees.  A clean return is a finite exhaustive
    verification of the theorem at this `(p, k)`.
    """
    reports = tuple(analyse(u, p, k) for u in all_subgroups(p, k))
    bad = [r for r in reports if not r.agrees]
    if bad:
        raise AssertionError(f"uniform formula failed at p={p}, k={k}: {bad}")
    return reports


def certify_odd_classification(p: int, k: int) -> tuple[int, int]:
    """Exhaustive certificate that `(d, l)` classifies subgroups for odd `p`.

    Returns `(observed_count, predicted_count)` with
    `predicted_count = tau(p-1) * k`.  Raises if two distinct subgroups share a
    signature pair, or if some admissible pair is unrealised.
    """
    if p == 2:
        raise ValueError("the classification is false at p = 2; that is the point")
    subgroups = all_subgroups(p, k)
    fingerprints: dict[tuple[int, int], frozenset[int]] = {}
    for u in subgroups:
        key = (signature_order(u, p), level(u, p, k))
        if key in fingerprints:
            raise AssertionError(
                f"(d,l) = {key} shared by two subgroups at p={p}, k={k}: "
                f"{sorted(fingerprints[key])} and {sorted(u)}"
            )
        fingerprints[key] = u
    predicted = divisor_count(p - 1) * k
    if len(fingerprints) != predicted:
        raise AssertionError(
            f"subgroup count {len(fingerprints)} != tau(p-1)*k = {predicted}"
        )
    return len(fingerprints), predicted


def two_adic_classification_failure(k: int = 5) -> tuple[frozenset[int], frozenset[int]]:
    """The explicit pair of subgroups mod `2^k` sharing a signature.

    Witnesses that `(d, l)` classifies for odd `p` but not at `p = 2` --- the
    precise place the exceptionality of two survives the unification.
    """
    subgroups = all_subgroups(2, k)
    seen: dict[tuple[int, int], frozenset[int]] = {}
    for u in subgroups:
        key = (signature_order(u, 2), level(u, 2, k))
        if key in seen:
            return seen[key], u
        seen[key] = u
    raise AssertionError(f"no collision mod 2^{k}; the classification did not fail")


def single_generator_index(a: int, p: int, k: int) -> int:
    """Index of `<a>` from the closed form, without building the subgroup.

    `d = ord_{p^c}(a)` and `l = v_p(a^d - 1)`, so the index is
    `(phi(p^c)/d) * p^(l-c)` whenever `k >= l`.  This specialisation is
    classical -- it is lifting-the-exponent in disguise -- and is included as a
    consistency check on the general statement, not as a new claim.
    """
    if a % p == 0:
        raise ValueError(f"{a} is not a unit mod {p}^{k}")
    c = principal_exponent(p)
    order_mod_pc = 1
    power = a % p ** c
    while power != 1:
        power = (power * a) % p ** c
        order_mod_pc += 1
    residual = a ** order_mod_pc - 1
    if residual == 0:
        # `a` has order `d` on the nose, so `U cap P` is trivial and `l = k`.
        # Reached at `a = 1`, and at any `a` with `a^d = 1` over the integers.
        l = k
    else:
        l = 0
        while residual % p == 0:
            residual //= p
            l += 1
        l = min(l, k)
    return predicted_index(p, l, order_mod_pc)
