"""Independent breaker audit of R0027 (invariant-schema envelope).

Auditor: cf-tessera (Claude Fable 5 lineage).  This module re-derives, from
scratch and without importing ``invariant_schema_coupling``, every object the
packet R0027 depends on, and adds the two strengthenings found during the
audit:

1.  The feedback ``S -> E_<S> -> K(E)`` is the closure operator of a monotone
    Galois connection between the subgroup lattice of Sym(X) and the partition
    lattice of X:  ``G <= K(E)  iff  E_G refines E``.  Hence envelope
    identities (1) and (3) of the source note are forced by adjunction alone;
    identity (2) is the extra fact that ``K(E)`` acts transitively on each
    block.  The block-permuting alternative return map fails identity (2)
    already on two points, so the packet's choice of ``K`` is not a
    convention.

2.  The complete transporter ``T(A, D) = {U in GL_2(Z) : U A = D}`` for
    ``A = [[2,0],[1,0]]``, ``D = diag(1, 0)`` has TWO integer-indexed
    components, ``det = -1`` (the family displayed in the note) and
    ``det = +1`` (undisplayed):

        U A = D  forces  v = 1 - 2u,  z = -2w,  det U = -w,

    so unimodularity forces ``w = +-1``.  The stabilizer of ``D`` is
    correspondingly ``{[[1, b], [0, e]] : b in Z, e = +-1}``, twice the shear
    family shown in the note.  The no-go is therefore stronger than stated:
    even the determinant of the reducer is not recoverable from source,
    target, all Smith invariants, and strict pivot descent.

All computations are exact integer / finite-group enumerations.
"""

from itertools import permutations


# ---------------------------------------------------------------------------
# Finite permutation actions, independent implementation
# ---------------------------------------------------------------------------

def compose(p, q):
    """(p o q)(i) = p(q(i)); permutations as tuples."""
    return tuple(p[q[i]] for i in range(len(p)))


def generated_group(n, generators):
    """Subgroup of Sym(n) generated by tuples, by closure."""
    identity = tuple(range(n))
    group = {identity}
    frontier = [identity]
    gens = [tuple(g) for g in generators]
    while frontier:
        g = frontier.pop()
        for s in gens:
            h = compose(s, g)
            if h not in group:
                group.add(h)
                frontier.append(h)
    return frozenset(group)


def orbit_partition(n, group):
    """Set of frozensets: orbits of the group on range(n)."""
    seen = set()
    blocks = []
    for x in range(n):
        if x in seen:
            continue
        orbit = {p[x] for p in group}
        seen |= orbit
        blocks.append(frozenset(orbit))
    return frozenset(blocks)


def block_of(partition, x):
    for b in partition:
        if x in b:
            return b
    raise ValueError(x)


def K_fix(n, partition):
    """All permutations fixing every block setwise (the note's return map)."""
    return frozenset(
        p for p in permutations(range(n))
        if all(block_of(partition, i) == block_of(partition, p[i])
               for i in range(n))
    )


def K_perm(n, partition):
    """Alternative return map: permutations preserving the partition as a
    set of blocks, allowed to permute blocks.  Audited and rejected."""
    return frozenset(
        p for p in permutations(range(n))
        if frozenset(frozenset(p[i] for i in b) for b in partition)
        == partition
    )


def refines(fine, coarse):
    """Partition order: every fine block inside some coarse block."""
    return all(any(b <= c for c in coarse) for b in fine)


def all_subgroups(n):
    """Every subgroup of Sym(n) (exhaustive; n <= 4 feasible, we use n <= 3)."""
    elements = list(permutations(range(n)))
    subgroups = set()
    # generate from every subset of a generating pool; for n <= 3 the whole
    # element list is a fine pool and closure is cheap.
    from itertools import combinations
    for r in range(len(elements) + 1):
        for gens in combinations(elements, r if r <= 3 else 3):
            subgroups.add(generated_group(n, gens))
        if r > 3:
            break
    return subgroups


# ---------------------------------------------------------------------------
# Audit 1: Galois connection and envelope identities, exhaustive on n <= 3
# ---------------------------------------------------------------------------

def all_partitions(n):
    """All set partitions of range(n)."""
    if n == 0:
        return [frozenset()]
    parts = []

    def rec(i, current):
        if i == n:
            parts.append(frozenset(frozenset(b) for b in current))
            return
        for b in current:
            b.add(i)
            rec(i + 1, current)
            b.remove(i)
        current.append({i})
        rec(i + 1, current)
        current.pop()

    rec(0, [])
    return parts


def galois_adjunction_holds(n):
    """Check  G <= K(E)  iff  E_G refines E,  for every subgroup G and
    partition E of range(n)."""
    for group in all_subgroups(n):
        e_g = orbit_partition(n, group)
        for e in all_partitions(n):
            left = group <= K_fix(n, e)
            right = refines(e_g, e)
            if left != right:
                return False
    return True


def envelope_identities_hold(n, generators):
    """The three identities of the source note for one generating set."""
    group = generated_group(n, generators)
    e_g = orbit_partition(n, group)
    k = K_fix(n, e_g)
    ident1 = group <= k
    ident2 = orbit_partition(n, k) == e_g
    ident3 = K_fix(n, orbit_partition(n, k)) == k
    return ident1 and ident2 and ident3


def block_permuting_counterexample():
    """K_perm fails identity (2) on two points with the discrete partition:
    it merges the two singleton blocks.  Returns the witness data."""
    n = 2
    discrete = frozenset({frozenset({0}), frozenset({1})})
    k = K_perm(n, discrete)
    return {
        "partition": discrete,
        "K_perm_order": len(k),
        "orbit_partition": orbit_partition(n, k),
        "identity2_holds": orbit_partition(n, k) == discrete,
    }


# ---------------------------------------------------------------------------
# Audit 2: exhaustive orbit-collision census on n <= 3
# ---------------------------------------------------------------------------

def orbit_collisions(n):
    """All unordered pairs of distinct subgroups of Sym(n) sharing an orbit
    partition."""
    subgroups = sorted(all_subgroups(n), key=lambda g: (len(g), sorted(g)))
    pairs = []
    for i, g in enumerate(subgroups):
        for h in subgroups[i + 1:]:
            if orbit_partition(n, g) == orbit_partition(n, h):
                pairs.append((g, h))
    return pairs


# ---------------------------------------------------------------------------
# Audit 3: complete Smith transporter, derived not verified
# ---------------------------------------------------------------------------

A_MATRIX = ((2, 0), (1, 0))
D_MATRIX = ((1, 0), (0, 0))


def mat_mul(p, q):
    return tuple(
        tuple(sum(p[i][k] * q[k][j] for k in range(2)) for j in range(2))
        for i in range(2)
    )


def det2(m):
    return m[0][0] * m[1][1] - m[0][1] * m[1][0]


def transporter_element(k, sign):
    """The complete transporter T(A, D), derived: U = [[k, 1-2k], [w, -2w]]
    with w = -sign since det U = -w; sign in {+1, -1} is det U."""
    w = -sign
    return ((k, 1 - 2 * k), (w, -2 * w))


def transporter_membership(u):
    """Exact membership test for T(A, D): unimodular and U A = D."""
    return abs(det2(u)) == 1 and mat_mul(u, A_MATRIX) == D_MATRIX


def transporter_is_complete(bound):
    """Every unimodular U with U A = D and entries bounded by ``bound`` is of
    the derived form transporter_element(k, sign); and conversely every
    derived element is a member.  The forward direction is proved symbolically
    in the docstring (v = 1-2u, z = -2w, det = -w); this replays it on a
    finite window as a guard against algebra slips."""
    found = []
    rng = range(-bound, bound + 1)
    for a in rng:
        for b in rng:
            for c in rng:
                for d in rng:
                    u = ((a, b), (c, d))
                    if transporter_membership(u):
                        found.append(u)
    derived = {
        transporter_element(k, sign)
        for k in range(-bound, bound + 1)
        for sign in (1, -1)
    }
    return set(found) <= derived and all(
        transporter_membership(u) for u in derived
    )


def stabilizer_element(b, e):
    """Full stabilizer of D under left multiplication by GL_2(Z):
    H D = D forces H = [[1, b], [0, e]] with e = +-1 (det = e)."""
    return ((1, b), (0, e))


def stabilizer_is_complete(bound):
    """Same finite-window replay of the symbolic stabilizer computation."""
    found = []
    rng = range(-bound, bound + 1)
    for a in rng:
        for b in rng:
            for c in rng:
                for d in rng:
                    h = ((a, b), (c, d))
                    if abs(det2(h)) == 1 and mat_mul(h, D_MATRIX) == D_MATRIX:
                        found.append(h)
    derived = {
        stabilizer_element(b, e)
        for b in range(-bound, bound + 1)
        for e in (1, -1)
    }
    return set(found) <= derived and all(
        abs(det2(h)) == 1 and mat_mul(h, D_MATRIX) == D_MATRIX
        for h in derived
    )


def torsor_bijection_holds(bound):
    """Stab(D) . U_0 = T(A, D) on a window: left multiplication by the full
    stabilizer maps the base reducer U_0 = [[0,1],[1,-2]] onto both
    determinant components."""
    u0 = ((0, 1), (1, -2))
    image = {
        mat_mul(stabilizer_element(b, e), u0)
        for b in range(-bound, bound + 1)
        for e in (1, -1)
    }
    target = {
        transporter_element(k, sign)
        # H_b with e=+1 sends U_0 to U_b (det -1); e=-1 gives det +1 family.
        for k in range(-bound, bound + 1)
        for sign in (1, -1)
    }
    return image == target and all(transporter_membership(u) for u in image)


def false_control_rejected():
    """A determinant-2 matrix reaching D would break the audit; verify the
    natural candidate fails membership."""
    control = ((2, -3), (0, 1))  # det = 2, nonunimodular
    return abs(det2(control)) == 2 and not transporter_membership(control)


def smith_invariants_2x2(m):
    """d1 = gcd of entries, d2 = |det| / d1 convention as elementary divisors
    (d1, d2) with d1 | d2 when det != 0; here det = 0 so d2 = 0."""
    from math import gcd
    entries = [abs(x) for row in m for x in row]
    d1 = 0
    for x in entries:
        d1 = gcd(d1, x)
    det = abs(det2(m))
    d2 = det // d1 if d1 and det else 0
    return (d1, d2)


def determinant_unrecoverable():
    """The strengthening: two transporter elements with the same source A,
    same target D, same Smith invariants of source and target, same strict
    pivot descent 2 -> 1, but determinants -1 and +1."""
    u_minus = transporter_element(0, -1)   # note's U_0, det -1
    u_plus = transporter_element(0, +1)    # undisplayed component, det +1
    same_endpoint = (mat_mul(u_minus, A_MATRIX) == D_MATRIX
                     == mat_mul(u_plus, A_MATRIX))
    same_invariants = (smith_invariants_2x2(A_MATRIX),
                       smith_invariants_2x2(D_MATRIX)) == ((1, 0), (1, 0))
    return (same_endpoint and same_invariants
            and det2(u_minus) == -1 and det2(u_plus) == 1)
