#!/usr/bin/env python3
"""Minimal rational translation module generated by a periodic task signal."""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
from math import gcd

try:
    from machinery.ramanujan_trace import cyclotomic_polynomials, divisors
except ModuleNotFoundError:
    from ramanujan_trace import cyclotomic_polynomials, divisors

Polynomial = tuple[int, ...]


def polynomial_remainder(poly: Polynomial, monic: Polynomial) -> Polynomial:
    work = list(poly)
    degree = len(monic) - 1
    for k in range(len(work) - 1, degree - 1, -1):
        coefficient = work[k]
        for j in range(degree):
            work[k - degree + j] -= coefficient * monic[j]
    return tuple((work + [0] * degree)[:degree])


def rational_rank(matrix: tuple[tuple[int, ...], ...]) -> int:
    work = [[Fraction(value) for value in row] for row in matrix]
    rows, columns = len(work), len(work[0]) if work else 0
    rank = 0
    for column in range(columns):
        pivot = next((i for i in range(rank, rows) if work[i][column]), None)
        if pivot is None:
            continue
        work[rank], work[pivot] = work[pivot], work[rank]
        scale = work[rank][column]
        work[rank] = [value / scale for value in work[rank]]
        for i in range(rows):
            if i != rank and work[i][column]:
                scale = work[i][column]
                work[i] = [a - scale * b for a, b in zip(work[i], work[rank])]
        rank += 1
    return rank


def cyclic_shift(signal: tuple[int, ...], shift: int) -> tuple[int, ...]:
    n = len(signal)
    return tuple(signal[(i - shift) % n] for i in range(n))


def cyclic_autocorrelation(signal: tuple[int, ...]) -> tuple[int, ...]:
    n = len(signal)
    return tuple(sum(signal[x] * signal[(x + h) % n] for x in range(n))
                 for h in range(n))


@dataclass(frozen=True)
class TaskProjectorCertificate:
    modulus: int
    signal: tuple[int, ...]
    supported_orders: tuple[int, ...]
    sector_dimensions: tuple[int, ...]
    predicted_rank: int
    orbit_matrix_rank: int
    correlation: tuple[int, ...]


def compile_task_projector(signal: tuple[int, ...]) -> TaskProjectorCertificate:
    """Compute Q[C_W]F, the minimal translation-stable space containing F.

    Q[C_W] decomposes as the product of Q[x]/Phi_d over d|W. The generated
    ideal has the full d-sector iff F mod Phi_d is nonzero. Hence its dimension
    is the sum of phi(d) over exactly those supported sectors.
    """
    if not signal:
        raise ValueError("signal must be nonempty")
    w = len(signal)
    phis = cyclotomic_polynomials(w)
    supported = tuple(d for d in divisors(w)
                      if any(polynomial_remainder(signal, phis[d])))
    dimensions = tuple(len(phis[d]) - 1 for d in supported)
    predicted = sum(dimensions)
    orbit_matrix = tuple(cyclic_shift(signal, h) for h in range(w))
    actual = rational_rank(orbit_matrix)
    if predicted != actual:
        raise AssertionError("cyclotomic support and translation rank disagree")
    return TaskProjectorCertificate(
        w, signal, supported, dimensions, predicted, actual,
        cyclic_autocorrelation(signal),
    )


def wheel_unit_projector(wheel: int) -> TaskProjectorCertificate:
    return compile_task_projector(tuple(int(gcd(x, wheel) == 1)
                                        for x in range(wheel)))


if __name__ == "__main__":
    result = wheel_unit_projector(30)
    print(result)
    print("ALL EXACT CHECKS PASS")
