#!/usr/bin/env bash
# अनाथः — "without a protector."
#
# machine/ had ~129 Haskell modules and NO BUILD GATE AT ALL.  The Lean lane
# has lakefile globs; the Agda lane has Everything.agda and the rule that a
# module not reachable from it is verified by nothing.  machine/ had neither,
# and on 2026-08-21 a uniform random draw found that
# machine/Apavartana_TheContentIsOneInvariantInTwoLegs.hs HAS NEVER COMPILED:
# it exports selfTestApavartana, which is defined nowhere, and nothing in the
# repository would ever have said so.  A sweep then found seven failures.
#
# This is §१६'s fourth answer -- शक्तेरपनयनं, न नियमः, removal of capacity
# rather than a rule.  A prose instruction to compile before committing is a
# rule; a gate that fails is the removal of the capacity to land a module that
# does not build.
#
# Prints a report and exits non-zero if anything under machine/ fails to
# typecheck.  Writes nothing.  Recomputed from the filesystem every run --
# there is no stored list to go stale.
#
#   sh scripts/Anatha_TheMachineLaneHadNoGateAndNowItHasOne.sh
#   sh scripts/Anatha_TheMachineLaneHadNoGateAndNowItHasOne.sh --quiet
#
# LIMIT, stated at the site: this is `ghc -fno-code`, which typechecks and does
# NOT run anything.  A module that compiles may still have a failing selfTest.
# Running the selfTests is a separate gate and this is not it.

set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT" || exit 2

QUIET=0
[ "${1:-}" = "--quiet" ] && QUIET=1

if ! command -v ghc >/dev/null 2>&1; then
  echo "anatha: ghc not on PATH -- gate cannot run, and that is NOT a pass" >&2
  exit 2
fi

OUT="$(mktemp)"
trap 'rm -f "$OUT"' EXIT

TOTAL=0
FAILED=0
FAILLIST=""

# Modules that CANNOT typecheck standalone because they import Haskell that
# MAlonzo generates from an Agda compile.  Excluded with the reason printed on
# every run, never silently: a skipped module is a module verified by nothing,
# and hiding the skip is the defect this gate exists to remove.  If any of
# these ever compiles without a prior Agda build, the exclusion is stale and
# should be deleted.
EXCLUDED="machine/BenchBalancedReweave.hs
machine/BenchTheoremCompiled.hs
machine/ExtractedRewrite.hs"
EXCLUDED_WHY="imports MAlonzo output generated by an Agda compile (GHC-87110 without it)"
NEXCL=0

for f in machine/*.hs; do
  [ -e "$f" ] || continue
  if printf '%s\n' "$EXCLUDED" | grep -qxF "$f"; then
    NEXCL=$((NEXCL + 1))
    continue
  fi
  TOTAL=$((TOTAL + 1))
  if ! ghc -fno-code -imachine -Wno-missing-home-modules "$f" >"$OUT" 2>&1; then
    FAILED=$((FAILED + 1))
    FAILLIST="$FAILLIST$f"$'\n'
    if [ "$QUIET" -eq 0 ]; then
      echo "=============================================================="
      echo "FAIL  $f"
      echo "--------------------------------------------------------------"
      head -20 "$OUT"
    fi
  fi
done

echo
echo "=============================================================="
echo "अनाथः · machine/ build gate"
echo "=============================================================="
echo "  modules typechecked : $TOTAL"
echo "  failures            : $FAILED"
echo "  excluded            : $NEXCL  ($EXCLUDED_WHY)"
printf '%s\n' "$EXCLUDED" | sed 's/^/    /'

if [ "$FAILED" -ne 0 ]; then
  echo
  echo "  failing modules:"
  printf '%s' "$FAILLIST" | sed 's/^/    /'
  echo
  echo "  A module that does not typecheck is verified by nothing, and its"
  echo "  header's claims are unchecked prose.  §६: लिखितो दोषो जीवति --"
  echo "  either fix it or write the defect at the site."
  exit 1
fi

echo
echo "  OK -- every module under machine/ typechecks."
echo "  (ghc -fno-code only: selfTests are NOT run by this gate.)"
exit 0
