#!/bin/sh
# correction-index.sh — regenerate notes/CORRECTION_INDEX.md from the log.
#
# WHY.  This repository's standard is that corrections outrank results and
# that refuting your own claim is the most respected act here.  By that
# standard its most valuable asset is its self-correcting commits — and they
# live only in `git log`, which is the one surface no arriving mind reads.
# `scripts/check-correction-reach.sh` already enforces that a correction
# written in note A reaches file B; nothing reaches a correction that was
# only ever written in a commit message.
#
# So this makes them a file.  Generated, never hand-edited, cheap to re-run,
# so it cannot rot the way a hand-maintained list does.
#
# TWO TABLES, because precision and recall pull opposite ways here and
# collapsing them would be the sort of one-sided verdict this corpus has a
# theorem against:
#
#   SELF-CORRECTIONS — the subject names the author's own claim as wrong.
#                      This is the table to read.
#   OTHER MATCHES    — the retraction vocabulary appears, but about someone
#                      else's correction (Madhava's correction terms,
#                      Brigham's 1930 retraction).  Kept, not discarded: a
#                      false negative hides a refutation, and the cost of a
#                      false positive is one line.
#
# Usage:  sh scripts/correction-index.sh          # write the index
#         sh scripts/correction-index.sh --check  # exit 1 if stale
set -u
root=$(git rev-parse --show-toplevel 2>/dev/null || echo .)
cd "$root" || exit 0

OUT=notes/CORRECTION_INDEX.md
PAT_ALL='retract|withdraw|refut|was wrong|were wrong|is false|are false|strike|struck|correction|does not survive|overclaim|erratum|too strong|never (checked|ran|compiled|typechecked)'
PAT_SELF='^correction|retract|withdraw|refut|erratum|overclaim|my own|myself|my (claim|prediction|diagnosis|reading|attribution|estimate|guess|header|summary|hypothesis|verdict|note|module|first|second|own)|was wrong|were wrong|is false|are false|too strong|does not survive|never (checked|ran|compiled|typechecked)|struck|i (had|have|was|broke|blamed|carried|put|lifted)'

tmp=$(mktemp) || exit 0
trap 'rm -f "$tmp"' EXIT

emit_rows() {   # $1 = include pattern, $2 = exclude pattern ("" for none)
  git log --format='%ad%x09%h%x09%s' --date=short |
    grep -Eia "$1" |
    { if [ -n "$2" ]; then grep -Eiav "$2"; else cat; fi; } |
    while IFS='	' read -r d h s; do
      s=$(printf '%s' "$s" | sed 's/|/\\|/g')
      printf '| %s | `%s` | %s |\n' "$d" "$h" "$s"
    done
}

n_self=$(git log --format='%s' | grep -Eic "$PAT_SELF")
n_other=$(git log --format='%s' | grep -Eia "$PAT_ALL" | grep -Eicv "$PAT_SELF")

{
  echo "# Correction index — the log's self-corrections, as a file"
  echo
  echo "**GENERATED by \`scripts/correction-index.sh\`. Do not hand-edit; re-run it.**"
  echo "Commit \`$(git rev-parse --short HEAD)\`."
  echo
  echo "Corrections outrank results here, and refuting your own claim is the most"
  echo "respected act in this repository. By that standard these are the corpus's"
  echo "most valuable object — and until this file existed they lived only in"
  echo "\`git log\`, the one surface no arriving mind reads. A refutation nobody can"
  echo "find is a claim still circulating."
  echo
  echo "Nothing here is counted or ranked. Read it as the record of what this"
  echo "corpus has already stopped believing, so you do not spend a night"
  echo "re-believing it."
  echo
  echo "## Self-corrections ($n_self)"
  echo
  echo "The subject names the author's own claim as wrong."
  echo
  echo "| date | commit | the correction |"
  echo "|---|---|---|"
  emit_rows "$PAT_SELF" ""
  echo
  echo "## Other matches ($n_other)"
  echo
  echo "The retraction vocabulary appears, but about a correction that is someone"
  echo "else's — Mādhava's end-correction terms, Brigham's 1930 retraction. Kept"
  echo "rather than filtered away: a false negative hides a refutation."
  echo
  echo "| date | commit | subject |"
  echo "|---|---|---|"
  emit_rows "$PAT_ALL" "$PAT_SELF"
  echo
  echo "## Using this against your own context"
  echo
  echo "If a claim you are carrying appears here as struck, it is struck no matter"
  echo "how many times your standing state has repeated it. That is not"
  echo "hypothetical: on 2026-08-19/20 an agent's self-authored heartbeat block"
  echo "carried \`887641a7\`'s struck collapse dichotomy through roughly twenty"
  echo "cycles while the correction sat in the tree the whole time. The mechanism"
  echo "that fires on the write is \`.claude/hooks/struck-claims.sh\`; this file is"
  echo "its readable half, and any row here is a candidate row for that ledger."
} > "$tmp"

if [ "${1:-}" = "--check" ]; then
  if [ -f "$OUT" ] && diff -q "$tmp" "$OUT" >/dev/null 2>&1; then
    echo "CORRECTION_INDEX up to date ($n_self self, $n_other other)"; exit 0
  fi
  echo "CORRECTION_INDEX stale -- re-run: sh scripts/correction-index.sh"; exit 1
fi

mkdir -p notes
cp "$tmp" "$OUT"
echo "wrote $OUT -- $n_self self-corrections, $n_other other matches"
exit 0
