#!/bin/sh
# साध्य — that which is to be proved.
#
# ─────────────────────────────────────────────────────────────────────────
# WHY THIS EXISTS.  रात्रिः proposes and the kernel decides.  What it CANNOT
# do is prove, and the 35 open obligations it holds each need a real proof.
# The provers in this project are agents and people, and until now nothing
# handed them the queue: it sat in a TSV keyed by content address, which is
# the right store and the wrong surface.
#
# So this renders the ledger where somebody arriving actually lands, GROUPED
# BY THE MOVE EACH OBLIGATION NEEDS — because ten obligations blocked on the
# same move are one piece of work, and ten scattered lines are ten.
#
# TERM.  साध्य is Nyāya's own word for the probandum — the thing to be
# established, the second member of the five-membered inference (Gautama,
# न्यायसूत्रम् १.१.३२–३९).  A सिद्ध is what is already established; a साध्य
# is what the inference is for.  LIMIT: the term is used in its plain
# technical sense and no text is claimed for this application.  Nothing
# below attributes a theorem to any Naiyāyika.
#
# The distinction the file turns on is Nyāya's too and it is load-bearing
# here: an obligation is not a failure.  `Hetvabhasa_…hs` in this repository
# already holds the rule — a refusal must name its defect or it is not a
# refusal — and a queue of obligations each naming the move it needs is that
# rule applied to work rather than to verdicts.
#
#   run:  sh scripts/Sadhya_…sh          (writes notes/SADHYA_OPEN_OBLIGATIONS.md)
# ─────────────────────────────────────────────────────────────────────────

cd "$(dirname "$0")/.." || exit 1
LEDGER=notes/anuloma/NirnayaPanjika.tsv
OUT=notes/SADHYA_OPEN_OBLIGATIONS.md
[ -f "$LEDGER" ] || { echo "no ledger at $LEDGER — run रात्रिः or अनुलोम-प्रतिलोम --check first"; exit 0; }

TOTAL=$(grep -vc '^#' "$LEDGER")
OPEN=$(awk -F"\t" '!/^#/ && $5 == "Refused" {n++} END{print n+0}' "$LEDGER")
MINE=$(awk -F"\t" '!/^#/ && $6 ~ /^मम दोषः/ {n++} END{print n+0}' "$LEDGER")
REAL=$((OPEN - MINE))

{
printf '# साध्य — the open obligations, and each carries the shape of its own proof\n\n'
printf '**Generated by `scripts/Sadhya_…sh` from `notes/anuloma/NirnayaPanjika.tsv`.**\n'
printf 'Do not edit by hand; edit the ledger'"'"'s source, or close an obligation and\nre-run. Regenerated %s.\n\n' "$(date -u +%Y-%m-%dT%H:%MZ)"
printf 'रात्रिः proposes and the kernel decides. Neither can prove. These are what\n'
printf 'is left, grouped by the MOVE each needs — because ten obligations blocked on\n'
printf 'one move are one piece of work, and ten scattered lines are ten.\n\n'
printf '| | |\n|---|---|\n'
printf '| rows in the ledger | %s |\n' "$TOTAL"
printf '| open | %s |\n' "$OPEN"
printf '| of those, the instrument'"'"'s own defects (`मम दोषः`) | %s |\n' "$MINE"
printf '| **real obligations** | **%s** |\n\n' "$REAL"
printf 'The instrument'"'"'s defects are listed separately and last. A census that files\n'
printf 'its own bugs as the corpus'"'"'s refusals is the दुर्नय one level up, and this\n'
printf 'one did exactly that and had to be retracted.\n\n---\n\n'

awk -F"\t" '!/^#/ && $5 == "Refused" && $6 !~ /^मम दोषः/ {print $6}' "$LEDGER" \
  | sort | uniq -c | sort -rn | while read -r n cls; do
    printf '## %s — %s obligation(s)\n\n' "$cls" "$n"
    awk -F"\t" -v c="$cls" '!/^#/ && $6 == c && $5 == "Refused" {
        printf "- **%s**  \n  rung reached: %s  \n  `%s`\n\n", $7, $3, $8 }' "$LEDGER"
  done

printf '\n---\n\n## मम दोषः — the instrument'"'"'s own, not the corpus'"'"'s\n\n'
awk -F"\t" '!/^#/ && $6 ~ /^मम दोषः/ {printf "- **%s** — %s\n", $7, $6}' "$LEDGER"
printf '\nThese are probes this emitter cannot state correctly. They are NOT evidence\n'
printf 'about the corpus and must never be counted as refusals.\n'
} > "$OUT"

printf '  साध्य: %s open, %s real obligations, %s of the instrument'"'"'s own → %s\n' \
  "$OPEN" "$REAL" "$MINE" "$OUT"
