#!/bin/sh
# theorem-index.sh — the theorem corpus, mapped to domains.
#
# WHY.  formal/cubical/NaturalMachine/ is not a subject.  Its commit
# messages are research work in progress from a dozen parallel lanes
# ("Formalize Theorem B", "prime-pair-field-research", "Prove the K-flow
# trichotomy"), each writing into the namespace that happened to exist.
# Nothing in it imports the kernel.  So there is no directory name that
# describes it, and the way to find a theorem is a MAP, not a tree.
#
# A module gets every tag it matches.  Untagged is reported as `-` and is
# a defect in this file, not in the module: add the marker.
#
#   sh scripts/theorem-index.sh            > THEOREM_INDEX.tsv
#   sh scripts/theorem-index.sh --domains  domain counts only
#   sh scripts/theorem-index.sh --untagged names that match no domain
set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT/formal/cubical"

tags() {   # $1 = lowercased header+name
  s="$1"; o=""
  case "$s" in *prime*|*divisor*|*gcd*|*bezout*|*totient*|*mertens*|*goldbach*|*cakravala*|*kuttaka*|*coprime*|*factoriz*) o="$o,number-theory";; esac
  case "$s" in *smith*|*unimodular*|*sl2*|*lattice*|*cokernel*|*"normal form"*|*matrix*|*determinant*) o="$o,lattices-and-matrices";; esac
  case "$s" in *holonomy*|*cohomolog*|*fibration*|*torsor*|*groupoid*|*monodromy*|*truncation*|*univalen*|*"loop space"*|*equivalence*) o="$o,homotopy";; esac
  case "$s" in *automat*|*observab*|*bisimulat*|*transducer*|*behavio*|*future*|*nerode*|*congruence*) o="$o,automata-and-observation";; esac
  case "$s" in *metre*|*matra*|*guru*|*prastara*|*chandas*|*syllab*|*virahanka*|*pingala*|*meru*) o="$o,prosody-and-combinatorics";; esac
  case "$s" in *panini*|*asiddha*|*anuvrtti*|*pratyahara*|*rewrit*|*apavada*|*utsarga*|*sutra*) o="$o,grammar-and-rewriting";; esac
  case "$s" in *saptabhang*|*anekant*|*avaktavya*|*durnaya*|*catuskoti*|*naya*|*syadvada*|*verdict*) o="$o,jaina-logic";; esac
  case "$s" in *born*|*karma*|*moksa*|*dravya*|*spacetime*|*noether*|*conserv*|*charge*|*flux*|*jiva*|*ahimsa*) o="$o,physics-and-jaina-ontology";; esac
  case "$s" in *cost*|*price*|*laghava*|*pareto*|*cheap*|*expensive*) o="$o,cost";; esac
  case "$s" in *galois*|*closure*|*"order"*|*stratif*|*antichain*|*"partial order"*|*monotone*) o="$o,order-theory";; esac
  case "$s" in *quotient*|*"equivalence relation"*|*effectiv*|*"set-truncat"*|*coequal*) o="$o,quotients";; esac
  case "$s" in *walk*|*tower*|*descent*|*orbit*|*trajector*|*capacity*|*reachab*) o="$o,walks-and-descent";; esac
  case "$s" in *transport*|*chart*|*presentation*|*atlas*|*setu*|*bridge*|*seam*|*ford*) o="$o,transport-and-charts";; esac
  case "$s" in *symmetry*|*group*|*permut*|*involut*|*automorph*|*action*|*invariant*) o="$o,symmetry";; esac
  case "$s" in *bhavana*|*samasa*|*sankalita*|*composition*|*compose*|*semiring*|*monoid*) o="$o,composition-laws";; esac
  case "$s" in *finite*|*counted*|*enumerat*|*census*|*cardinal*|*decidab*) o="$o,finiteness-and-counting";; esac
  case "$s" in *obstruct*|*"no-go"*|*refut*|*impossib*|*"cannot"*|*fails*|*blind*) o="$o,no-go";; esac
  case "$s" in *residual*|*remainder*|*sesa*|*fibre*|*fiber*|*witness*|*carrier*|*loss*) o="$o,loss-and-residue";; esac
  [ -z "$o" ] && o=",-"
  printf '%s' "${o#,}"
}

emit() {
  for f in $(find . -name '*.agda' ! -path './_build/*' | sort); do
    n=$(basename "$f" .agda)
    hdr=$(sed -n '1,45p' "$f" | grep -E '^-- ' | sed 's/^-- \{0,1\}//' | grep -vE '^[A-Za-z_]+(\.[A-Za-z0-9_-]+)+ *$' | grep -m1 -E '[a-z]{3}.*[a-z]{3}.*[a-z]{3}' | cut -c1-115 | tr -d '\t')
    [ -z "$hdr" ] && hdr="(no header line)"
    body=$(sed -n '1,45p' "$f" | tr 'A-Z' 'a-z' | tr -d '\t')
    t=$(tags "$(printf '%s %s' "$hdr" "$n" | sed -E 's/([a-z])([A-Z])/\1 \2/g' | tr 'A-Z' 'a-z')")
    printf '%s\t%s\t%s\n' "${f#./}" "$t" "$hdr"
  done
}

case "${1:-}" in
  --domains)  emit | cut -f2 | tr ',' '\n' | sort | uniq -c | sort -rn ;;
  --untagged) emit | awk -F'\t' '$2=="-"{print $1}' ;;
  *)          printf '# path\tdomains\theadline\n'
              printf '# regenerated by scripts/theorem-index.sh\n'
              emit ;;
esac
