"""The four views, as formal local sections of a claim.

CRYSTAL.md sec.1 says every entity has four inseparable faces generated by its
native term.  This module makes that a *cover*: for a claim ``C`` of the
runtime, four partial descriptions, each with its own vocabulary, each a real
computation over runtime objects, and each with a stated blind spot.

    truth      what the kernel certifies      (proof paths, checked edges)
    action     what it does operationally     (rewrites, routes, procedures)
    cost       its cost-vector effect         (steps, size, width, verify)
    residual   what it leaves undetermined    (fibres, omitted locus, cone,
                                               unresolved obligations)

THE ONE STRUCTURAL RULE
-----------------------
A view is *local*.  Its reader function is handed **only its own slice** of the
claim, so it is not merely conventional that ``cost`` cannot consult ``truth``
-- it is not passed the data.  ``assert_independent`` proves it: every reader
is re-run against a claim in which the other three slices have been replaced by
a ``Poison`` object that raises on every access, and the reading must come out
byte-identical.  A reader that secretly reads another view's data raises there,
and ``runtime/tests/test_nerve.py`` plants exactly such a reader as a control.

THE COMMON ALPHABET
-------------------
Each view reads a *different kind of record* and projects it onto one shared
alphabet -- ``admit(s) in {0, 1}``, "does the claim deliver at site ``s``, as
this view is able to tell".  That projection is the *common quotient both views
factor through* which `runtime/nerve/cech.py` needs on an overlap.  The four
projections are:

    truth      admit = the certificate discharged at this site
    action     admit = a route/rewrite/procedure was actually opened here
    cost       admit = strictly cheaper here, and not at the price of search
    residual   admit = nothing omitted and no obligation outstanding here

The four source schemas are disjoint: no one of them can be computed from
another, which is why the projections are four measurements and not four names
for one.

WHAT EACH VIEW CANNOT SEE -- the load-bearing half of the design
----------------------------------------------------------------
``CANNOT_SEE`` states it per view, and ``LocalSection.visible`` records it per
claim: a site absent from a view's source is a site that view is **blind** at,
and blindness deletes that view's vertex from the site's nerve support (see
``cech.build_presheaf``).  Blindness is data, not an error.

Exact, CPU-only, stdlib-only, integer arithmetic.  Deterministic: every
iteration is over ``sorted()`` or a fixed tuple.
"""

from __future__ import annotations

from typing import Any, Callable, Dict, Iterable, Mapping, Sequence, Tuple


class NerveError(Exception):
    """Any structural refusal from the coherence layer."""


# --------------------------------------------------------------------------
# the four views
# --------------------------------------------------------------------------

class View:
    """The four faces, as fixed small integers.

    The integer order is the simplex vertex order and is never changed: every
    simplex of the nerve is a *sorted* tuple of these, so the orientation of a
    cochain is canonical and two runs agree byte for byte.
    """

    TRUTH = 0
    ACTION = 1
    COST = 2
    RESIDUAL = 3


ALL_VIEWS: Tuple[int, ...] = (View.TRUTH, View.ACTION, View.COST, View.RESIDUAL)

VIEW_NAMES: Tuple[str, ...] = ("truth", "action", "cost", "residual")


def view_name(v: int) -> str:
    if v not in ALL_VIEWS:
        raise NerveError("not a view: %r" % (v,))
    return VIEW_NAMES[v]


def view_by_name(name: str) -> int:
    try:
        return VIEW_NAMES.index(name)
    except ValueError:
        raise NerveError("not a view name: %r" % (name,))


#: What each view is structurally unable to see.  Not a disclaimer -- the
#: reader is not given the data, and ``assert_independent`` proves it.
CANNOT_SEE: Dict[int, Tuple[str, ...]] = {
    View.TRUTH: (
        "cost: a certificate has no step count; the checker's counters are read "
        "by `cost`, and `truth` is handed the verdict, never the counter",
        "operational reach: whether a checked equality ever fires as a rewrite, "
        "or whether a route is materialised, is `action`'s measurement",
        "the omitted locus: `truth` certifies what is present; a statement that "
        "was never addressable has no certificate to be false",
        "on the Fermat family specifically: the min/max type of a stationary "
        "point -- the reflection-law residual is exactly 0 at both",
    ),
    View.ACTION: (
        "truth: firing is not soundness; `action` observes that a rule matched "
        "and a route opened, and takes the verdict from the checker it calls",
        "price: `action` knows an application happened, not what it cost",
        "what did not fire: a route to a term nobody materialised is invisible "
        "(execute/README.md sec.10.2), and so is a maximum of the action "
        "(physics/README.md sec.5)",
    ),
    View.COST: (
        "licence: `cost` prices whatever it is handed; that the route is "
        "checked, or that a Quotient edge is task-sufficient, is not its call",
        "residual: a cost vector has no slot for what was destroyed; the fibre "
        "size and the omitted locus do not appear in (steps,size,width,verify)",
        "on this runtime specifically: `verify` is near-collinear with `steps` "
        "on flat proof paths (execute/README.md sec.10.7)",
    ),
    View.RESIDUAL: (
        "truth: naming what is undetermined is not deciding it; `residual` "
        "reports a fibre, never which of its members is the answer",
        "cost: an obligation has no price until somebody routes it",
        "action: what fires is exactly what `residual` is the complement of, so "
        "it cannot re-derive it -- that is the point of the pairing",
    ),
}


#: The record schema each view's source must supply, per site.  Disjoint by
#: construction: no schema is a function of another.
SOURCE_SCHEMA: Dict[int, Tuple[str, ...]] = {
    View.TRUTH: ("certified", "witness"),
    View.ACTION: ("opened", "fires", "witness"),
    View.COST: ("before", "after", "search_before", "search_after"),
    View.RESIDUAL: ("omitted", "unresolved", "fibre"),
}


VOCABULARY: Dict[int, str] = {
    View.TRUTH: "certificate discharged / not discharged",
    View.ACTION: "route or rewrite opened / not opened",
    View.COST: "strictly cheaper without paying for it in search / not",
    View.RESIDUAL: "nothing omitted and nothing outstanding / something is",
}


# --------------------------------------------------------------------------
# the locality apparatus
# --------------------------------------------------------------------------

class Poison:
    """An object that raises on every access.

    Substituted for the *other* views' sources when ``assert_independent``
    re-runs a reader.  A reader that reaches for a neighbour's slice raises
    here instead of quietly succeeding.
    """

    __slots__ = ("owner",)

    def __init__(self, owner: str = "") -> None:
        object.__setattr__(self, "owner", owner)

    def _die(self, what: str) -> None:
        raise NerveError(
            "locality violation: a view reader touched %s of another view's "
            "source (%s)" % (what, self.owner))

    def __getattr__(self, name: str) -> Any:
        self._die("attribute %r" % name)

    def __getitem__(self, key: Any) -> Any:
        self._die("item %r" % (key,))

    def __iter__(self):
        self._die("iteration")

    def __len__(self) -> int:
        self._die("len")
        return 0                                   # pragma: no cover

    def __contains__(self, item: Any) -> bool:
        self._die("membership")
        return False                               # pragma: no cover

    def keys(self):
        self._die("keys")

    def values(self):
        self._die("values")

    def items(self):
        self._die("items")

    def get(self, *a, **k):
        self._die("get")

    def __repr__(self) -> str:                     # pragma: no cover - view
        return "<Poison %s>" % self.owner


# --------------------------------------------------------------------------
# claims
# --------------------------------------------------------------------------

class Claim:
    """A claim of the runtime, presented to the coherence layer.

    ``sites``     the finite, ordered index set the claim ranges over.  The
                  atoms about which the four views have anything to say.
    ``sources``   one slice per view.  A reader is handed *only* its slice.
    ``licence``   for every simplex of dimension >= 1, whether the views in it
                  share a quotient at all, and why.  Absent means licensed.
                  The licensed set must be closed under taking faces of
                  dimension >= 1: three views cannot jointly compare something
                  two of them cannot.
    """

    __slots__ = ("name", "sites", "sources", "licence", "provenance")

    def __init__(self, name: str, sites: Sequence[str],
                 sources: Mapping[int, Mapping[str, Mapping[str, Any]]],
                 licence: Mapping[Tuple[int, ...], Tuple[bool, str]] = (),
                 provenance: str = "") -> None:
        self.name = name
        seen = []
        for s in sites:
            if not isinstance(s, str):
                raise NerveError("a site id must be a string: %r" % (s,))
            if s in seen:
                raise NerveError("duplicate site %r" % s)
            seen.append(s)
        self.sites: Tuple[str, ...] = tuple(seen)
        if sorted(sources) != sorted(ALL_VIEWS):
            raise NerveError(
                "a claim must supply exactly the four views; got %r"
                % (sorted(sources),))
        self.sources: Dict[int, Mapping[str, Mapping[str, Any]]] = dict(sources)
        self.licence: Dict[Tuple[int, ...], Tuple[bool, str]] = dict(licence or {})
        self.provenance = provenance
        self._check_licence()

    # -- licence ---------------------------------------------------------
    def _check_licence(self) -> None:
        for sigma, entry in sorted(self.licence.items()):
            if not isinstance(sigma, tuple) or tuple(sorted(set(sigma))) != sigma:
                raise NerveError("a licence key must be a sorted simplex: %r"
                                 % (sigma,))
            if len(sigma) < 2:
                raise NerveError("licences are declared on overlaps, not on "
                                 "vertices: %r" % (sigma,))
            if not (isinstance(entry, tuple) and len(entry) == 2):
                raise NerveError("a licence must be (bool, reason): %r" % (entry,))
        # face closure among dimension >= 1
        for sigma in self.licensed_simplices():
            if len(sigma) < 3:
                continue
            for j in range(len(sigma)):
                face = sigma[:j] + sigma[j + 1:]
                if not self.is_licensed(face):
                    raise NerveError(
                        "licence is not face-closed: %r is licensed but its "
                        "face %r is not" % (sigma, face))

    def is_licensed(self, sigma: Tuple[int, ...]) -> bool:
        if len(sigma) < 2:
            return True
        entry = self.licence.get(tuple(sigma))
        return True if entry is None else bool(entry[0])

    def licence_reason(self, sigma: Tuple[int, ...]) -> str:
        entry = self.licence.get(tuple(sigma))
        return "" if entry is None else str(entry[1])

    def licensed_simplices(self) -> Tuple[Tuple[int, ...], ...]:
        from .cech import SIMPLICES                # local: cech imports views
        return tuple(s for s in SIMPLICES if self.is_licensed(s))

    def __repr__(self) -> str:                     # pragma: no cover - view
        return "Claim(%r, %d sites)" % (self.name, len(self.sites))


# --------------------------------------------------------------------------
# local sections
# --------------------------------------------------------------------------

class LocalSection:
    """One view's partial description of a claim.

    ``visible``   the sites this view can say anything about.  A site outside
                  it is a site this view is *blind* at; blindness is recorded,
                  never guessed around.
    ``reading``   the projection onto the shared alphabet: site -> 0 | 1.
    ``detail``    the view's own vocabulary, kept for reporting.  Nothing in
                  ``cech.py`` reads it; only ``reading`` crosses an overlap.
    """

    __slots__ = ("view", "sites", "visible", "reading", "detail", "vocabulary",
                 "blind_spots", "provenance")

    def __init__(self, view: int, sites: Sequence[str],
                 visible: Iterable[str], reading: Mapping[str, int],
                 detail: Mapping[str, Any] = (), provenance: str = "") -> None:
        self.view = view
        self.sites = tuple(sites)
        vis = tuple(s for s in self.sites if s in set(visible))
        self.visible: Tuple[str, ...] = vis
        for s in vis:
            val = reading[s]
            if val not in (0, 1):
                raise NerveError(
                    "the shared alphabet is {0,1}; view %s read %r at %r"
                    % (view_name(view), val, s))
        self.reading: Dict[str, int] = {s: int(reading[s]) for s in vis}
        self.detail: Dict[str, Any] = dict(detail or {})
        self.vocabulary = VOCABULARY[view]
        self.blind_spots = CANNOT_SEE[view]
        self.provenance = provenance

    # -- derived ---------------------------------------------------------
    def admits(self) -> Tuple[str, ...]:
        return tuple(s for s in self.visible if self.reading[s] == 1)

    def refuses(self) -> Tuple[str, ...]:
        return tuple(s for s in self.visible if self.reading[s] == 0)

    def blind_at(self) -> Tuple[str, ...]:
        vis = set(self.visible)
        return tuple(s for s in self.sites if s not in vis)

    def partition(self) -> Tuple[Tuple[str, ...], Tuple[str, ...]]:
        """The view's web: the fibres of its reading.  CROSS_LENS sec.2."""
        return (self.admits(), self.refuses())

    def name(self) -> str:
        return view_name(self.view)

    def render(self) -> str:
        cells = []
        for s in self.sites:
            if s in self.reading:
                cells.append("1" if self.reading[s] else "0")
            else:
                cells.append(".")
        return "%-9s %s" % (self.name(), "".join(cells))

    def __repr__(self) -> str:                     # pragma: no cover - view
        return "LocalSection(%s, %d/%d visible)" % (
            self.name(), len(self.visible), len(self.sites))


# --------------------------------------------------------------------------
# the four readers -- each sees only its own slice
# --------------------------------------------------------------------------

def _require(record: Mapping[str, Any], keys: Sequence[str], view: int,
             site: str) -> None:
    for k in keys:
        if k not in record:
            raise NerveError(
                "view %s: site %r is missing the required field %r of its "
                "schema %r" % (view_name(view), site, k, SOURCE_SCHEMA[view]))


def read_truth(source: Mapping[str, Mapping[str, Any]],
               sites: Sequence[str]) -> LocalSection:
    """What the kernel certifies.

    Reads ``certified`` -- the verdict of a checker, a gate battery, or an
    exact residual being zero -- and nothing else.  It has no counter, no
    route, and no fibre.
    """
    visible, reading, detail = [], {}, {}
    for s in sites:
        if s not in source:
            continue
        rec = source[s]
        _require(rec, ("certified", "witness"), View.TRUTH, s)
        visible.append(s)
        reading[s] = 1 if int(rec["certified"]) else 0
        detail[s] = str(rec["witness"])
    return LocalSection(View.TRUTH, sites, visible, reading, detail,
                        provenance="kernel/check.py verdicts, gate batteries, "
                                   "exact zero residuals")


def read_action(source: Mapping[str, Mapping[str, Any]],
                sites: Sequence[str]) -> LocalSection:
    """What the claim does operationally.

    Reads ``opened`` (a rewrite fired, a route was returned, a decision
    procedure ran) and ``fires`` (how many times).  It never asks whether the
    thing opened was true or what it cost.
    """
    visible, reading, detail = [], {}, {}
    for s in sites:
        if s not in source:
            continue
        rec = source[s]
        _require(rec, ("opened", "fires", "witness"), View.ACTION, s)
        visible.append(s)
        reading[s] = 1 if int(rec["opened"]) else 0
        detail[s] = "fires=%d %s" % (int(rec["fires"]), rec["witness"])
    return LocalSection(View.ACTION, sites, visible, reading, detail,
                        provenance="rule applications, opened routes, "
                                   "materialised frontiers")


def read_cost(source: Mapping[str, Mapping[str, Any]],
              sites: Sequence[str]) -> LocalSection:
    """The cost-vector effect.

    ``admit`` is exactly CRYSTAL.md sec.0's criterion applied at one site:
    strictly fewer steps, and not bought with more search.  Both halves are
    required -- a step reduction paid for by unbounded search is the failure
    mode sec.0 exists to exclude.
    """
    visible, reading, detail = [], {}, {}
    for s in sites:
        if s not in source:
            continue
        rec = source[s]
        _require(rec, ("before", "after", "search_before", "search_after"),
                 View.COST, s)
        before, after = int(rec["before"]), int(rec["after"])
        wb, wa = int(rec["search_before"]), int(rec["search_after"])
        visible.append(s)
        reading[s] = 1 if (after < before and wa <= wb) else 0
        detail[s] = "steps %d->%d  search %d->%d" % (before, after, wb, wa)
    return LocalSection(View.COST, sites, visible, reading, detail,
                        provenance="exact step counters and search-work "
                                   "counters, before and after")


def read_residual(source: Mapping[str, Mapping[str, Any]],
                  sites: Sequence[str]) -> LocalSection:
    """What the claim leaves undetermined or destroys.

    ``omitted``     the site lies in the omitted locus (CRYSTAL.md sec.4)
    ``unresolved``  obligations still owed at this site
    ``fibre``       the size of the fibre the claim collapses here; 1 is exact,
                    n > 1 is what a lossy channel returns instead of a guess
    """
    visible, reading, detail = [], {}, {}
    for s in sites:
        if s not in source:
            continue
        rec = source[s]
        _require(rec, ("omitted", "unresolved", "fibre"), View.RESIDUAL, s)
        omitted = 1 if int(rec["omitted"]) else 0
        unresolved = int(rec["unresolved"])
        fibre = int(rec["fibre"])
        if fibre < 1:
            raise NerveError("a fibre has at least one member: %r at %r"
                             % (fibre, s))
        visible.append(s)
        reading[s] = 1 if (omitted == 0 and unresolved == 0 and fibre == 1) else 0
        detail[s] = "omitted=%d unresolved=%d fibre=%d" % (
            omitted, unresolved, fibre)
    return LocalSection(View.RESIDUAL, sites, visible, reading, detail,
                        provenance="omitted loci, invalidated cones, "
                                   "obligation ledgers, decode fibres")


READERS: Dict[int, Callable[[Mapping[str, Mapping[str, Any]], Sequence[str]],
                            LocalSection]] = {
    View.TRUTH: read_truth,
    View.ACTION: read_action,
    View.COST: read_cost,
    View.RESIDUAL: read_residual,
}


def read_view(claim: Claim, view: int) -> LocalSection:
    """Run one view's reader against *only* that view's slice."""
    if view not in ALL_VIEWS:
        raise NerveError("not a view: %r" % (view,))
    return READERS[view](claim.sources[view], claim.sites)


def read_all(claim: Claim) -> Dict[int, LocalSection]:
    return {v: read_view(claim, v) for v in ALL_VIEWS}


# --------------------------------------------------------------------------
# locality, enforced
# --------------------------------------------------------------------------

class IndependenceReport:
    """Result of the fake-locality check."""

    __slots__ = ("ok", "offenders", "checked")

    def __init__(self, ok: bool, offenders: Sequence[Tuple[str, str]],
                 checked: int) -> None:
        self.ok = ok
        self.offenders = tuple(offenders)
        self.checked = checked

    def render(self) -> str:
        if self.ok:
            return ("locality: %d readers re-run against poisoned neighbours, "
                    "all %d readings identical" % (self.checked, self.checked))
        return "locality VIOLATED: " + "; ".join(
            "%s: %s" % (v, why) for v, why in self.offenders)

    def __repr__(self) -> str:                     # pragma: no cover - view
        return "IndependenceReport(ok=%r, %d offenders)" % (
            self.ok, len(self.offenders))


def assert_independent(claim: Claim,
                       readers: Mapping[int, Callable] = None
                       ) -> IndependenceReport:
    """Prove each view is computable without the other three.

    For each view, rebuild the claim with the other three sources replaced by
    ``Poison`` and re-run that view's reader.  The reading must be identical.
    A reader that reaches across raises inside ``Poison``; a reader that reads
    across without raising (because it captured the data in a closure) changes
    nothing here -- so the check is paired, in the suite, with a control that
    plants exactly that and is caught by the ``Poison`` path.
    """
    use = dict(READERS if readers is None else readers)
    offenders = []
    reference = {}
    for v in ALL_VIEWS:
        reference[v] = use[v](claim.sources[v], claim.sites)
    for v in ALL_VIEWS:
        isolated = {w: (claim.sources[w] if w == v
                        else Poison(view_name(w))) for w in ALL_VIEWS}
        try:
            got = use[v](isolated[v], claim.sites)
        except NerveError as exc:
            offenders.append((view_name(v), str(exc)))
            continue
        except Exception as exc:                   # pragma: no cover - defence
            offenders.append((view_name(v), "reader raised %r" % (exc,)))
            continue
        ref = reference[v]
        if got.reading != ref.reading or got.visible != ref.visible:
            offenders.append((view_name(v),
                              "reading changed when the neighbours were removed"))
    return IndependenceReport(not offenders, offenders, len(ALL_VIEWS))


def require_four_views(claim: Claim) -> Tuple[bool, Tuple[str, ...]]:
    """The gate's entry condition: all four views, non-empty, schema-complete.

    Returns ``(ok, complaints)``.  It never raises: a claim that cannot supply
    four views is not thereby false, it is *unassessable*, and the certificate
    says so.
    """
    complaints = []
    for v in ALL_VIEWS:
        src = claim.sources.get(v)
        if src is None:
            complaints.append("view %s is missing" % view_name(v))
            continue
        if isinstance(src, Poison):
            complaints.append("view %s is poisoned" % view_name(v))
            continue
        try:
            section = READERS[v](src, claim.sites)
        except NerveError as exc:
            complaints.append("view %s: %s" % (view_name(v), exc))
            continue
        if not section.visible:
            complaints.append(
                "view %s is blind at every site of the claim" % view_name(v))
    return (not complaints, tuple(complaints))


__all__ = [
    "NerveError", "View", "ALL_VIEWS", "VIEW_NAMES", "view_name", "view_by_name",
    "CANNOT_SEE", "SOURCE_SCHEMA", "VOCABULARY", "Poison", "Claim",
    "LocalSection", "read_truth", "read_action", "read_cost", "read_residual",
    "READERS", "read_view", "read_all", "IndependenceReport",
    "assert_independent", "require_four_views",
]
