#!/usr/bin/env python3
"""Exercise the actual HVM prelude, without checker normalization hiding a bug.

No third-party Python packages are needed. Supply a compiled HVM4 binary with
--hvm. --check-only checks extraction and patch applicability, NOT execution.
"""
from __future__ import annotations

import argparse
from collections import Counter
import json
from pathlib import Path
import re
import shutil
import subprocess
import tempfile

MODULE = "src/Target/HVM4Full.hs"


def source_from_patch(text: str) -> str:
    """Recover this new-file hunk exactly; reject unexpected patch layouts."""
    marker = f"diff --git a/{MODULE} b/{MODULE}\n"
    if text.count(marker) != 1:
        raise ValueError(f"expected exactly one patch section for {MODULE}")
    section = text.split(marker, 1)[1].split("\ndiff --git ", 1)[0]
    match = re.search(r"^@@ -0,0 \+1,(\d+) @@\n", section, re.MULTILINE)
    if match is None:
        raise ValueError("expected a single new-file hunk")
    lines = section[match.end():].splitlines()
    if not lines or any(not line.startswith("+") for line in lines):
        raise ValueError("unexpected context/deletions in the new-file hunk")
    if len(lines) != int(match.group(1)):
        raise ValueError("new-file hunk length does not match its header")
    return "\n".join(line[1:] for line in lines) + "\n"


def runtime_prelude(source: str) -> str:
    """Decode the emitter's literal prelude; never reimplement @coe in Python."""
    block = source.split("prelude = unlines\n", 1)[1].split("\nhvmName ::", 1)[0]
    result = []
    for line in block.splitlines():
        stripped = line.strip()
        if stripped in ("", "]"):
            continue
        if not stripped.startswith(("[ ", ", ")):
            raise ValueError(f"non-literal Haskell prelude line: {line!r}")
        literal = stripped[2:].rstrip()
        # The last literal and closing bracket share a line in the emitter.
        if literal.endswith(" ]"):
            literal = literal[:-2].rstrip()
        value = json.loads(literal)
        if not isinstance(value, str):
            raise ValueError("prelude item is not a string")
        result.append(value)
    # Exactly the dispatch generated by hitPrelude for a book with no HITs.
    result.append("@hitCoe = λ&L. λ&r. λ&s. λ&x. λ{λt. #StuckCoe{t, x}}")
    return "\n".join(result) + "\n"


def apply_fix(source: str, patch: Path, directory: Path) -> str:
    target = directory / MODULE
    target.parent.mkdir(parents=True)
    target.write_text(source, encoding="utf-8")
    for args in (("--check",), ()):
        subprocess.run(["git", "-C", str(directory), "apply", *args, str(patch)],
                       check=True, capture_output=True, text=True)
    return target.read_text(encoding="utf-8")


def list_term(*items: str) -> str:
    tail = "#Nil"
    for item in reversed(items):
        tail = f"#Con{{{item}, {tail}}}"
    return tail


def coe(line: str, value: str, r: str = "#I0", s: str = "#I1") -> str:
    return f"@coe({line}, {r}, {s}, {value})"


EXTRA = r"""
@neg = λ{0: 1; λn. 0}
@negPath = #UaU{#Bool, #Bool, @neg, @neg}
@negLine = λi. #List{@pathAt(@negPath, i)}
@idLine = λi. #List{#Bool}
@nestedLine = λi. #List{#List{@pathAt(@negPath, i)}}
@inverseLine = λi. #List{@pathAt(@negPath, @inot(i))}
@doublePath = #CompU{λi. @pathAt(@negPath, i), λi. @pathAt(@negPath, i)}
@doubleLine = λi. #List{@pathAt(@doublePath, i)}
@rename = #UaU{#Bool, #Enum, λ{0: #Off; λn. #On}, λ{#Off: 0; #On: 1}}
@renameLine = λi. #List{@pathAt(@rename, i)}
@head = λ{#Con: λh. λt. h; #Nil: 0}
@loop = @loop
@twice = λ&tltShared. #Pair{tltShared, tltShared}
@functionLine = λi. #List{#Pi{@pathAt(@negPath, i), λv. #Bool}}
@pairLine = λi. #List{#Sig{@pathAt(@negPath, i), λv. #Nat}}
@applyTrue = λ{#Nil: #Nil; #Con: λf. λtail. #Con{f(1), @applyTrue(tail)}}
@cycle3 = λ{#Red: #Green; #Green: #Blue; #Blue: #Red}
@uncycle3 = λ{#Red: #Blue; #Green: #Red; #Blue: #Green}
@cyclePath = #UaU{#Enum, #Enum, @cycle3, @uncycle3}
@cycleLine = λi. #List{@pathAt(@cyclePath, i)}
"""


def cases() -> list[tuple[str, str, list[str]]]:
    xs = list_term("1", "0", "1")
    ys = list_term("0", "1", "0")
    nested = list_term(list_term("1", "0"), "#Nil", list_term("0"))
    nested_expected = list_term(list_term("0", "1"), "#Nil", list_term("1"))
    a, b = list_term("1", "1"), list_term("0", "1")
    na, nb = list_term("0", "0"), list_term("1", "0")
    return [
        ("singleton", coe("@negLine", list_term("1")), [list_term("0")]),
        ("multi-element", coe("@negLine", xs), [ys]),
        ("backward", coe("@negLine", xs, "#I1", "#I0"), [ys]),
        ("round-trip", coe("@negLine", coe("@negLine", xs), "#I1", "#I0"), [xs]),
        ("constant-line", coe("@idLine", xs), [xs]),
        ("empty", coe("@negLine", "#Nil"), ["#Nil"]),
        ("nested", coe("@nestedLine", nested), [nested_expected]),
        ("composite-element-path", coe("@doubleLine", xs), [xs]),
        ("inverse-element-path", coe("@inverseLine", xs), [ys]),
        ("equal-endpoints", coe("@loop", xs, "#I0", "#I0"), [xs]),
        ("empty-does-not-force-element", coe("λi. #List{@loop}", "#Nil"), ["#Nil"]),
        ("head-does-not-force-tail", f"@head({coe('@negLine', '#Con{1, @loop}')})", ["0"]),
        ("change-element-representation", coe("@renameLine", xs),
         [list_term("#On", "#Off", "#On")]),
        ("change-element-representation-backward",
         coe("@renameLine", list_term("#On", "#Off"), "#I1", "#I0"), [list_term("1", "0")]),
        ("superposed-values", coe("@negLine", f"&B{{{a}, {b}}}"), [na, nb]),
        ("correlated-line-and-values",
         coe("λi. &A{#List{@pathAt(@negPath, i)}, #List{#Bool}}", f"&A{{{a}, {b}}}"),
         [na, b]),
        ("independent-line-and-values",
         coe("λi. &A{#List{@pathAt(@negPath, i)}, #List{#Bool}}", f"&B{{{a}, {b}}}"),
         [na, nb, a, b]),
        ("shared-result", f"@twice({coe('@negLine', xs)})", [f"#Pair{{{ys}, {ys}}}"]),
        ("correlated-nested",
         coe("λi. &A{#List{#List{@pathAt(@negPath, i)}}, #List{#List{#Bool}}}",
             f"&A{{{nested}, {nested_expected}}}"), [nested_expected, nested_expected]),
        ("correlated-different-element-types",
         coe("λi. &A{#List{@pathAt(@negPath, i)}, #List{#Nat}}",
             f"&A{{{a}, {list_term('#Suc{#Zer}')}}}"), [na, list_term("#Suc{#Zer}")]),
        ("triply-nested",
         coe("λi. #List{#List{#List{@pathAt(@negPath, i)}}}", list_term(nested)),
         [list_term(nested_expected)]),
        ("function-elements",
         f"@applyTrue({coe('@functionLine', list_term('λx. x', '@neg'))})",
         [list_term("0", "1")]),
        ("dependent-pair-elements",
         coe("@pairLine", list_term("#Pair{1,#Suc{#Zer}}", "#Pair{0,#Zer}")),
         [list_term("#Pair{0,#Suc{#Zer}}", "#Pair{1,#Zer}")]),
        ("correlated-empty",
         coe("λi. &A{#List{@pathAt(@negPath, i)}, #List{#Bool}}", f"&A{{#Nil, {xs}}}"),
         ["#Nil", xs]),
        ("non-involutive-forward", coe("@cycleLine", list_term("#Red", "#Green", "#Blue")),
         [list_term("#Green", "#Blue", "#Red")]),
        ("non-involutive-backward",
         coe("@cycleLine", list_term("#Red", "#Green", "#Blue"), "#I1", "#I0"),
         [list_term("#Blue", "#Red", "#Green")]),
    ]


def canonical_output(value: str) -> str:
    """HVM prints nullary constructors as #Nil{}; source permits #Nil."""
    compact = re.sub(r"\s+", "", value)
    return re.sub(r"(#\w+)\{\}", r"\1", compact)


def evaluate(hvm: str, prelude: str, expression: str, path: Path) -> list[str]:
    program = prelude + EXTRA + f"\n@main = {expression}\n"
    definitions = re.findall(r"^@(\w+)\s*=", program, re.MULTILINE)
    if len(definitions) != len(set(definitions)):
        raise ValueError("duplicate runtime definition")
    uncommented = re.sub(r"//[^\n]*", "", program)
    missing = set(re.findall(r"@(\w+)", uncommented)) - set(definitions)
    if missing:
        raise ValueError(f"undefined runtime references: {sorted(missing)}")
    path.write_text(program, encoding="utf-8")
    try:
        run = subprocess.run([hvm, str(path), "-C32"], capture_output=True,
                             text=True, timeout=30, check=True)
    except subprocess.CalledProcessError as error:
        raise RuntimeError(f"HVM failed for {path.name}:\n{error.stdout}\n{error.stderr}") from error
    return [canonical_output(line) for line in run.stdout.splitlines() if line.strip()]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--hvm", help="HVM4 executable (defaults to hvm on PATH)")
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args()
    here = Path(__file__).resolve().parent
    original = source_from_patch((here / "cubical-paths.patch").read_text(encoding="utf-8"))
    with tempfile.TemporaryDirectory(prefix="list-coe-") as tmp:
        directory = Path(tmp)
        fixed = apply_fix(original, here / "list-transport.patch", directory)
        before, after = runtime_prelude(original), runtime_prelude(fixed)
        assert "#List: λe. x;" in before
        assert "#List: λe. x;" not in after
        assert "#List: λe. @coeList(L, r, s, e, x);" in after
        print("PASS: original prelude extracted; corrective patch applies")
        if args.check_only:
            print("Native execution not run (--check-only)")
            return
        hvm = shutil.which(args.hvm or "hvm")
        if hvm is None:
            raise SystemExit("HVM4 not found; provide --hvm /path/to/hvm")
        # The baseline MUST exhibit the concrete wrong result, not merely fail
        # to parse. This prevents unrelated build failures from passing a test.
        baseline = evaluate(hvm, before, coe("@negLine", list_term("1")), directory / "before.hvm")
        assert baseline == [canonical_output(list_term("1"))], baseline
        print("PASS: baseline reproduces incorrect unchanged singleton")
        for name, expression, expected in cases():
            actual = evaluate(hvm, after, expression, directory / f"{name}.hvm")
            expected = [canonical_output(value) for value in expected]
            assert Counter(actual) == Counter(expected), f"{name}: got {actual}, expected {expected}"
            print(f"PASS: {name}")
        print(f"PASS: {len(cases())} native HVM4 regression cases")


if __name__ == "__main__":
    main()
