{-# OPTIONS --cubical --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- NaturalMachine.CommutationPreservesEveryPredicateAndMultiplicityWhereItIsStatable
--
-- ON THE NAME.  The enumeration of permutations is an Indian subject —
-- प्रस्तार (prastāra) in Piṅgala's *Chandaḥśāstra* (~300 BCE) and its
-- commentarial line, and अङ्कपाश (aṅkapāśa), Nārāyaṇa Paṇḍita's chapter
-- on permutations and combinations in the *Gaṇitakaumudī* (1356).
-- **This module is not that object and does not take its name.**  The
-- prastāra line in this repository belongs to other identities
-- (`PrastaraPankti`, `PingalaPrastara`, `Dvipada`); what is here is an
-- equivalence RELATION on step lists, not an enumeration of
-- arrangements.  Taking their subject's name for a different object
-- would claim the wrong provenance and collide with their line, so per
-- CLAUDE.md's naming guard this file carries an English name and this
-- paragraph.
--
-- ────────────────────────────────────────────────────────────────────
-- `PairwiseCommutationGivesEveryOrder` has carried one admission since
-- it was written: `_~_` is generated by adjacent transpositions and is
-- NOT proved to be "same multiset".  Addressed here, in two halves.
--
-- WHAT IS PROVED
--
--   ~preservesAny     `xs ~ ys → Any P xs → Any P ys`, for ANY
--                     predicate — no decidability, no equality
--   ~preservesAll     the same for `All`
--   ~preservesLength  the length is invariant
--   count / ~preservesCount
--                     given `Discrete` on the step type, the
--                     MULTIPLICITY of every element is invariant —
--                     which is precisely "same multiset"
--
-- **THE POINT IS WHERE THE HYPOTHESIS SITS.**  The predicate invariants
-- need nothing.  Multiplicity is different: to STATE "the same number
-- of copies of a" one must decide `x ≡ a`, so on a step type without
-- decidable equality the question "is `_~_` the same-multiset
-- relation?" cannot be posed, let alone answered — and `Step C` is a
-- type of functions with data attached, where `Discrete` is not
-- available in general and assuming it would be assuming decidable
-- equality of functions.
--
-- So the standing gap resolves into this: `_~_` implies same-multiset
-- wherever same-multiset is statable, and the question is ill-posed
-- exactly where the corpus actually uses `_~_`.
--
-- WHAT IS NOT CLAIMED.  **The CONVERSE is not proved.**  Equal counts
-- everywhere does not obviously give `xs ~ ys`; the standard route
-- (sort both, then transpose) needs a total order on steps, which is
-- less available than decidable equality.  `_~_` may be strictly finer
-- than same-multiset even on discrete step types, and nothing here
-- settles it.  Nor do the `Any`/`All` invariants CHARACTERISE `_~_` —
-- they cannot see multiplicity, which is why `count` is separate.
--
-- CHECKED on the CONTAINER (Agda 2.6.3, cubical v0.5 — NOT the declared
-- pin, Agda 2.8.0 + cubical v0.9).  --safe, no postulates, no holes.
------------------------------------------------------------------------

module SourcedProofs.CommutationPreservesEveryPredicateAndMultiplicityWhereItIsStatable where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat using (ℕ ; zero ; suc)
open import Cubical.Data.List using (List ; [] ; _∷_)
open import Cubical.Data.Sum using (inl ; inr)
open import Cubical.Data.Sigma using (_×_ ; _,_)
open import Cubical.Data.Unit using (Unit ; tt)
open import Cubical.Data.Empty as ⊥ using (⊥)
open import Cubical.Relation.Nullary using (¬_ ; Dec ; yes ; no ; Discrete)

open import NaturalMachine.KramaAstiNasti_TheFourthCornerCannotLiveOverAnEnumerableDecidableInstanceSet
  using (Any)
open import NaturalMachine.TheParetoStratumIsDecidableAndTheFilterIsExact using (All)
open import NaturalMachine.TheRemainderIsStrictlyShorterSoTheStratificationHasAMeasure
  using (lengthL)
open import NaturalMachine.OrderIndependenceTransfersAlongAnyNumberOfSteps using (Step)
open import NaturalMachine.PairwiseCommutationGivesEveryOrder
  using (_~_ ; ~nil ; ~cons ; ~swap ; ~trans)

------------------------------------------------------------------------
-- 0.  Counting, where equality is decidable
------------------------------------------------------------------------

count : {X : Type} → Discrete X → X → List X → ℕ
count eq a []       = 0
count eq a (x ∷ xs) with eq x a
... | yes _ = suc (count eq a xs)
... | no  _ = count eq a xs

countConsYes :
  {X : Type} (eq : Discrete X) (a x : X) (xs : List X)
  → x ≡ a → count eq a (x ∷ xs) ≡ suc (count eq a xs)
countConsYes eq a x xs e with eq x a
... | yes _ = refl
... | no ¬e = ⊥.rec (¬e e)

countConsNo :
  {X : Type} (eq : Discrete X) (a x : X) (xs : List X)
  → ¬ (x ≡ a) → count eq a (x ∷ xs) ≡ count eq a xs
countConsNo eq a x xs ¬e with eq x a
... | yes e = ⊥.rec (¬e e)
... | no  _ = refl

-- The two decisions are taken as ARGUMENTS rather than by `with`: a
-- `with` here would abstract the goal over the scrutinee and the two
-- cons equations above would no longer apply to it.
swapCount :
  {X : Type} (eq : Discrete X) (a p q : X) (xs : List X)
  → count eq a (p ∷ q ∷ xs) ≡ count eq a (q ∷ p ∷ xs)
swapCount eq a p q xs = go (eq p a) (eq q a)
  where
    go : Dec (p ≡ a) → Dec (q ≡ a)
       → count eq a (p ∷ q ∷ xs) ≡ count eq a (q ∷ p ∷ xs)
    go (yes ep) (yes eqa) =
        countConsYes eq a p (q ∷ xs) ep ∙ cong suc (countConsYes eq a q xs eqa)
      ∙ sym (countConsYes eq a q (p ∷ xs) eqa ∙ cong suc (countConsYes eq a p xs ep))
    go (yes ep) (no ¬eqa) =
        countConsYes eq a p (q ∷ xs) ep ∙ cong suc (countConsNo eq a q xs ¬eqa)
      ∙ sym (countConsNo eq a q (p ∷ xs) ¬eqa ∙ countConsYes eq a p xs ep)
    go (no ¬ep) (yes eqa) =
        countConsNo eq a p (q ∷ xs) ¬ep ∙ countConsYes eq a q xs eqa
      ∙ sym (countConsYes eq a q (p ∷ xs) eqa ∙ cong suc (countConsNo eq a p xs ¬ep))
    go (no ¬ep) (no ¬eqa) =
        countConsNo eq a p (q ∷ xs) ¬ep ∙ countConsNo eq a q xs ¬eqa
      ∙ sym (countConsNo eq a q (p ∷ xs) ¬eqa ∙ countConsNo eq a p xs ¬ep)

------------------------------------------------------------------------
-- 1.  The invariants that need no hypothesis
--
-- The lists are IMPLICIT and only the derivation is matched: matching
-- the lists as well would need injectivity of `_∷_`, which cubical Agda
-- does not support and which costs the function its computation on
-- transports (warning, not error — but a clean check here means zero
-- warning lines).
------------------------------------------------------------------------

module _ {S T : Type} (C : S → T) where

  ~preservesAny :
    (P : Step C → Type) {xs ys : List (Step C)}
    → _~_ C xs ys → Any P xs → Any P ys
  ~preservesAny P ~nil          e             = ⊥.rec e
  ~preservesAny P (~cons r)     (inl h)       = inl h
  ~preservesAny P (~cons r)     (inr k)       = inr (~preservesAny P r k)
  ~preservesAny P ~swap         (inl h)       = inr (inl h)
  ~preservesAny P ~swap         (inr (inl h)) = inl h
  ~preservesAny P ~swap         (inr (inr k)) = inr (inr k)
  ~preservesAny P (~trans r₁ r₂) a            =
    ~preservesAny P r₂ (~preservesAny P r₁ a)

  ~preservesAll :
    (P : Step C → Type) {xs ys : List (Step C)}
    → _~_ C xs ys → All P xs → All P ys
  ~preservesAll P ~nil           _                  = tt
  ~preservesAll P (~cons r)      (h , rest)         = h , ~preservesAll P r rest
  ~preservesAll P ~swap          (hp , (hq , rest)) = hq , (hp , rest)
  ~preservesAll P (~trans r₁ r₂) a                  =
    ~preservesAll P r₂ (~preservesAll P r₁ a)

  ~preservesLength :
    {xs ys : List (Step C)} → _~_ C xs ys → lengthL xs ≡ lengthL ys
  ~preservesLength ~nil           = refl
  ~preservesLength (~cons r)      = cong suc (~preservesLength r)
  ~preservesLength ~swap          = refl
  ~preservesLength (~trans r₁ r₂) =
    ~preservesLength r₁ ∙ ~preservesLength r₂

  ------------------------------------------------------------------
  -- 2.  …and multiplicity, exactly where it is statable
  ------------------------------------------------------------------

  ~preservesCount :
    (eq : Discrete (Step C)) (a : Step C) {xs ys : List (Step C)}
    → _~_ C xs ys → count eq a xs ≡ count eq a ys
  ~preservesCount eq a ~nil = refl
  ~preservesCount eq a (~cons {p} {xs} {ys} r) = consCase (eq p a)
    where
      consCase : Dec (p ≡ a) → count eq a (p ∷ xs) ≡ count eq a (p ∷ ys)
      consCase (yes ep) =
          countConsYes eq a p xs ep
        ∙ cong suc (~preservesCount eq a r)
        ∙ sym (countConsYes eq a p ys ep)
      consCase (no ¬ep) =
          countConsNo eq a p xs ¬ep
        ∙ ~preservesCount eq a r
        ∙ sym (countConsNo eq a p ys ¬ep)
  ~preservesCount eq a (~swap {p} {q} {xs}) = swapCount eq a p q xs
  ~preservesCount eq a (~trans r₁ r₂) =
    ~preservesCount eq a r₁ ∙ ~preservesCount eq a r₂
