#!/usr/bin/env python3
"""Validate and compile exponent-addressed polynomial bound contracts.

Bound vectors are a recurring source of silent errors: an analytic derivation
often lists coefficients from the leading term while an enumerator stores them
from the constant term.  This module makes the exponent the primary key and
checks any human-facing vector against that map before emitting code.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


FORMAT = "math-bound-contract-v1"


def _canonical_nonnegative_integer(value: object) -> int:
    if isinstance(value, bool):
        raise ValueError("Boolean is not an integer bound")
    try:
        integer = int(value)
    except (TypeError, ValueError) as error:
        raise ValueError("bound is not an integer") from error
    if integer < 0 or str(integer) != str(value):
        raise ValueError("bound must be a canonical nonnegative decimal integer")
    return integer


def validate_contract(value: object) -> list[str]:
    errors: list[str] = []
    if not isinstance(value, dict):
        return ["contract must be an object"]
    if value.get("format") != FORMAT:
        errors.append("wrong format")
    if not isinstance(value.get("polynomial"), str) or not value.get("polynomial"):
        errors.append("polynomial must be a nonempty string")
    degree = value.get("degree")
    if not isinstance(degree, int) or isinstance(degree, bool) or degree < 2:
        errors.append("degree must be an integer at least 2")
        return errors

    raw_map = value.get("bounds_by_exponent")
    if not isinstance(raw_map, dict):
        errors.append("bounds_by_exponent must be an object")
        return errors
    expected_keys = {str(exponent) for exponent in range(1, degree)}
    observed_keys = set(raw_map)
    if observed_keys != expected_keys:
        errors.append(
            "bounds_by_exponent must contain exactly the interior exponents "
            f"1..{degree - 1}"
        )
    bounds: dict[int, int] = {}
    for raw_exponent, raw_bound in raw_map.items():
        try:
            exponent = int(raw_exponent)
            if str(exponent) != raw_exponent:
                raise ValueError
            bounds[exponent] = _canonical_nonnegative_integer(raw_bound)
        except ValueError:
            errors.append(f"invalid bound entry at exponent {raw_exponent!r}")

    derivation = value.get("derived_vector")
    if not isinstance(derivation, dict):
        errors.append("derived_vector must be an object")
        return errors
    orientation = derivation.get("orientation")
    if orientation not in {"constant-to-leading", "leading-to-constant"}:
        errors.append("derived_vector orientation is invalid")
        return errors
    raw_values = derivation.get("values")
    if not isinstance(raw_values, list) or len(raw_values) != degree - 1:
        errors.append(f"derived_vector values must have length {degree - 1}")
        return errors
    try:
        values = [_canonical_nonnegative_integer(item) for item in raw_values]
    except ValueError as error:
        errors.append(f"invalid derived_vector: {error}")
        return errors

    if expected_keys == observed_keys and len(bounds) == degree - 1:
        for index, observed in enumerate(values):
            exponent = index + 1 if orientation == "constant-to-leading" else degree - 1 - index
            expected = bounds[exponent]
            if observed != expected:
                errors.append(
                    "orientation mismatch: derived_vector index "
                    f"{index} denotes exponent {exponent}, giving {observed}, "
                    f"but bounds_by_exponent gives {expected}"
                )
    return errors


def load_contract(path: Path) -> dict[str, object]:
    value = json.loads(path.read_text(encoding="utf-8"))
    errors = validate_contract(value)
    if errors:
        raise ValueError("; ".join(errors))
    assert isinstance(value, dict)
    return value


def emit_cpp(value: dict[str, object], symbol: str) -> str:
    errors = validate_contract(value)
    if errors:
        raise ValueError("; ".join(errors))
    degree = value["degree"]
    raw_map = value["bounds_by_exponent"]
    assert isinstance(degree, int) and isinstance(raw_map, dict)
    bounds = [0] + [int(raw_map[str(exponent)]) for exponent in range(1, degree)] + [0]
    entries = ", ".join(str(bound) for bound in bounds)
    return (
        "// Generated by machinery/bound_contract.py; indexed by polynomial exponent.\n"
        "#include <array>\n"
        f"constexpr std::array<long long, {degree + 1}> {symbol} = {{{entries}}};\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("contract", type=Path)
    parser.add_argument("--emit-cpp", type=Path)
    parser.add_argument("--symbol", default="kCoefficientBounds")
    args = parser.parse_args()
    try:
        value = load_contract(args.contract)
        if args.emit_cpp:
            args.emit_cpp.write_text(emit_cpp(value, args.symbol), encoding="utf-8")
    except (OSError, json.JSONDecodeError, ValueError) as error:
        print(f"FAIL {args.contract}: {error}")
        return 1
    print(f"PASS {args.contract}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
