#!/usr/bin/env python3
"""A tiny exact law finder for the first natural-crystal theorem.

This proposes expressions; it does not prove them.  The proof remains in
notes/BINARY_DIVISIBILITY_CRYSTAL.md.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, Mapping, Sequence

try:
    from machinery.natural_crystal import crystallize, divisibility_world
except ModuleNotFoundError:  # Direct execution from the repository root.
    from natural_crystal import crystallize, divisibility_world


@dataclass(frozen=True)
class Expression:
    text: str
    size: int
    values: tuple[int, ...]


def features(modulus: int) -> tuple[int, int]:
    """Return odd part q and two-adic exponent a of a positive modulus."""
    if modulus < 1:
        raise ValueError("modulus must be positive")
    q, a = modulus, 0
    while q % 2 == 0:
        q //= 2
        a += 1
    return q, a


def dynamical_features(modulus: int) -> tuple[int, int]:
    """Derive persistent-core size and transient depth from zero-digit motion."""
    if modulus < 1:
        raise ValueError("modulus must be positive")
    image = frozenset(range(modulus))
    depth = 0
    while True:
        next_image = frozenset((2 * state) % modulus for state in image)
        if next_image == image:
            return len(image), depth
        image = next_image
        depth += 1


def observed_count(modulus: int) -> int:
    """Compute the target without using the closed-form theorem."""
    world, observation = divisibility_world(2, modulus)
    return len(crystallize(
        world.states, (0, 1), world.transition, observation
    ).fibers)


def discover(
    moduli: Sequence[int],
    target: Callable[[int], int] = observed_count,
    variables: Mapping[str, Callable[[int], int]] | None = None,
) -> Expression | None:
    """Find the smallest exact expression generated by variables,0,1,+,*.

    Expressions are identified extensionally on the training set.  The first
    expression at the smallest syntax-tree size matching every target wins.
    """
    xs = tuple(moduli)
    if not xs or any(modulus < 1 for modulus in xs):
        raise ValueError("training moduli must be nonempty and positive")
    wanted = tuple(target(modulus) for modulus in xs)
    variable_functions = variables or {
        "q": lambda modulus: dynamical_features(modulus)[0],
        "a": lambda modulus: dynamical_features(modulus)[1],
    }
    atoms = {
        tuple(function(modulus) for modulus in xs): Expression(
            name, 1, tuple(function(modulus) for modulus in xs)
        )
        for name, function in variable_functions.items()
    }
    atoms[(0,) * len(xs)] = Expression("0", 1, (0,) * len(xs))
    atoms[(1,) * len(xs)] = Expression("1", 1, (1,) * len(xs))
    by_size: dict[int, dict[tuple[int, ...], Expression]] = {1: atoms}
    if wanted in by_size[1]:
        return by_size[1][wanted]
    for size in range(3, 12, 2):
        level: dict[tuple[int, ...], Expression] = {}
        for left_size in range(1, size - 1, 2):
            right_size = size - left_size - 1
            for left in by_size.get(left_size, {}).values():
                for right in by_size.get(right_size, {}).values():
                    for symbol, operation in (("+", lambda x, y: x + y),
                                               ("*", lambda x, y: x * y)):
                        values = tuple(operation(x, y)
                                       for x, y in zip(left.values, right.values))
                        level.setdefault(values, Expression(
                            f"({left.text}{symbol}{right.text})", size, values
                        ))
        by_size[size] = level
        if wanted in level:
            return level[wanted]
    return None


def evaluate(expression: str, modulus: int) -> int:
    """Evaluate the intentionally tiny emitted expression language."""
    q, a = features(modulus)
    if expression in ("(q+a)", "(a+q)"):
        return q + a
    raise ValueError("expression is outside the accepted tiny language")


def main() -> None:
    training = tuple(range(1, 33))
    held_out = tuple(range(33, 129))
    blind = discover(training, variables={"m": lambda modulus: modulus})
    law = discover(training)
    if law is None:
        raise SystemExit("no law found")
    if any(evaluate(law.text, modulus) != observed_count(modulus)
           for modulus in held_out):
        raise SystemExit("candidate failed held-out worlds")
    print(f"training worlds: {training[0]}..{training[-1]}")
    print(f"raw-modulus language: {blind}")
    print("new coordinates: m = 2^a q with q odd")
    print(f"smallest exact candidate: {law.text} (tree size {law.size})")
    print(f"held-out worlds: {held_out[0]}..{held_out[-1]} PASS")
    print("status: conjecture proposed by search; proof is separate")


if __name__ == "__main__":
    main()
