#!/usr/bin/env python3
"""The living machine, self-hosted.

There is one law (descent: an observable descends or forms) and one
evaluator.  Everything else is the machine's own data:

- An observable is a TERM in the machine's own language, not a Python
  function.  Terms: ("entry",i,j) ("det",) ("gcd",t,t) ("mod",t,c)
  ("abs",t) ("sign",t) ("valli",t,t) ("pair",t,t).
- The GENOME is the list of installed terms.  Formation events install
  terms; the genome is persisted machine-readable state — the machine can
  be read, resumed, and extended entirely through its own objects.
- The FRONTIER is generated by the machine from its genome: compositions
  of installed terms under its own grammar, with moduli drawn from the
  VALUE POOL — constants the machine itself has observed.  Nothing is
  hand-fed after birth; the seed genome is entries and determinant.

Python is only the evaluator underneath — the CPU.  Exact integers
throughout; append-only log; state survives restarts.

Run:  python3 living_machine.py [max_shells]
"""

import json
import os
import sys
from itertools import product
from math import gcd

from descent_formation_machine import DescentMachine
from kuttaka_pulverizer import pulverize

HERE = os.path.dirname(os.path.abspath(__file__))
STATE = os.path.join(HERE, "..", "runtime", "LIVING_STATE.json")
LOG = os.path.join(HERE, "..", "runtime", "LIVING_RUN.log")


# ---- the evaluator: the only code-level meaning --------------------------

def ev(term, s):
    m, h = s
    op = term[0]
    if op == "entry":
        return m[term[1]][term[2]]
    if op == "hentry":
        bits = PORT_BITS[0]
        if h and isinstance(h[0], int):
            # composition world: the fiber is a valli word; grants
            # beyond KIND_BASE are replay-prefix slots, not bits
            n = min(len(h), max(0, bits - KIND_BASE))
            return replay_prefix(h, n)[term[1]][term[2]]
        return h[term[1]][term[2]] % (1 << bits) if bits else 0
    if op == "det":
        return m[0][0] * m[1][1] - m[0][1] * m[1][0]
    if op == "gcd":
        return gcd(ev(term[1], s), ev(term[2], s))
    if op == "mod":
        return ev(term[1], s) % term[2]
    if op == "abs":
        return abs(ev(term[1], s))
    if op == "sign":
        v = ev(term[1], s)
        return 0 if v == 0 else (1 if v > 0 else -1)
    if op == "valli":
        a, b = ev(term[1], s), ev(term[2], s)
        if a == 0 and b == 0:
            return -1
        return len(pulverize(a, b)[0])
    if op == "pair":
        return (ev(term[1], s), ev(term[2], s))
    raise ValueError(f"unknown term {term}")


def show(term):
    if term[0] == "entry":
        return f"e{term[1]}{term[2]}"
    if term[0] == "hentry":
        return f"h{term[1]}{term[2]}"
    if term[0] == "det":
        return "det"
    if term[0] == "mod":
        return f"({show(term[1])} mod {term[2]})"
    if term[0] in ("abs", "sign"):
        return f"{term[0]}({show(term[1])})"
    return f"{term[0]}({show(term[1])},{show(term[2])})"


def depth(term):
    if term[0] in ("entry", "hentry", "det"):
        return 1
    if term[0] == "mod":
        return 1 + depth(term[1])
    if term[0] in ("abs", "sign"):
        return 1 + depth(term[1])
    return 1 + max(depth(term[1]), depth(term[2]))


# ---- the machine's own frontier ------------------------------------------

SEED = [("det",)]  # born dim: coordinates must be earned as formations
ENTRIES = [("entry", 0, 0), ("entry", 0, 1), ("entry", 1, 0),
           ("entry", 1, 1)]
HENTRIES = [("hentry", 0, 0), ("hentry", 0, 1), ("hentry", 1, 0),
            ("hentry", 1, 1)]
BUDGET = 12  # attention per shell: offers are a resource, order is policy
PORT_EVERY = 4  # the ecology grants one fiber port every few shells

# the hidden fiber: unimodular payloads paired with every matrix.  The
# family DEEPENS with the epoch, and ports expose it one BIT at a time:
# hentry sees h mod 2^bits.  Each saturation is a wall; each wall demands
# the next bit; fiber growth keeps higher bits informative — the format
# lattice as an unending developmental ladder.
def h_family(epoch):
    """Shears with entries up to 2^epoch: fiber depth outruns granted
    bits exponentially, so walls recur at every epoch forever."""
    # powers of two up to 2^epoch: a SMALL family with exponentially
    # deep entries, so granted bits are always behind the fiber's depth
    # and walls recur at every epoch forever.  (The earlier linear
    # family was defeated by its own size cap: entries stalled below
    # 2^bits and the machine ground ever-larger complete worlds to
    # death.  Found by running.)
    # depth exponent 2*epoch+1: walls grant ~one bit per epoch, so the
    # fiber's exponent must outrun the wall COUNT, not the epoch — round
    # three of death-by-completeness taught that both grew linearly and
    # bits caught up at epoch 167.  Found by running, again.
    # KIND CHANGE (death #4's standing law, paid): the magnitude race —
    # shear exponents vs granted bits — is unwinnable at bounded
    # compute; 2^700-entry integers starved four machines.  Past
    # VALLI_EPOCH the fiber changes KIND: hidden state is a WORD of
    # kuttaka quotients (the valli — formal/cubical/KuttakaValli.agda),
    # ports grant replay PREFIXES, and all arithmetic runs mod 2^31.
    # The race becomes structure vs structure: words lengthen 3/epoch,
    # grants arrive ~2/epoch, walls recur forever at O(1) integer cost.
    if epoch >= VALLI_EPOCH:
        # GROW follows PORT, not the clock (learned live: epoch-keyed
        # words regenerate every step, the machine never sees the same
        # world twice, never saturates, never walls — perpetual novelty
        # is the third death kind: life without learning).  The word
        # lengthens only when a prefix has been GRANTED, keeping a
        # fixed lead the machine must earn its way through.
        # Staggered signatures around the visible horizon (three world
        # designs died tonight: mod-3-degenerate words — 8 were 3, the
        # honest wall caught it; first-quotient identity — everything
        # distinguishable instantly, complete treadmill, nothing forms;
        # this one holds the balance): word i carries its signature at
        # position grants-12+3i, so at EVERY grant level some words
        # are freshly distinguishable (formations recur) and some sit
        # past the horizon (walls recur, honestly), forever, at
        # constant cost.  The world changes only when a grant lands:
        # knowledge-paced novelty.
        grants = max(0, PORT_BITS[0] - KIND_BASE)
        length = 3 * (grants + 4)
        words = []
        for i in range(8):
            sig = max(0, min(grants - 12 + 3 * i, length - 1))
            words.append(tuple((2 + i % 2) if j == sig else 1
                               for j in range(length)))
        return words
    out = [((1, 0), (0, 1)), ((0, 1), (-1, 0)), ((1, 0), (0, -1))]
    k = 1
    while k <= (1 << (2 * epoch + 1)):
        out.append(((1, k), (0, 1)))
        out.append(((1, 0), (k, 1)))
        k <<= 2
    return out


VALLI_EPOCH = 48          # kind boundary: shears before, words after
KIND_BASE = 2 * VALLI_EPOCH  # bits granted before the boundary
WMOD = 1 << 31            # composition worlds live mod 2^31: no giants

_WCACHE = {}


def replay_prefix(word, n):
    """Replay of the first n quotients, mod WMOD — the kuttaka step
    (p,p',r,r') -> (p*q+p', p, r*q+r', r), i.e. KuttakaValli.step."""
    key = (word, n)
    if key not in _WCACHE:
        a, b, c, d = 1, 0, 0, 1
        for q in word[:n]:
            a, b, c, d = (a * q + b) % WMOD, a, (c * q + d) % WMOD, c
        if len(_WCACHE) > 4096:
            _WCACHE.clear()
        _WCACHE[key] = ((a, b), (c, d))
    return _WCACHE[key]

H_SET = h_family(0)  # rebound each epoch in live()


PORTED = [False]
PORT_BITS = [0]


def frontier(genome, value_pool, max_new=48, max_depth=4):
    """Terms the machine proposes to itself: compositions over its
    building material (earned genome plus raw coordinates it may yet
    earn), moduli from its own observed values.  Shallow terms first:
    parsimony is the proposal order."""
    have = {json.dumps(t) for t in genome}
    out = []

    def offer(t):
        key = json.dumps(t)
        if key not in have and depth(t) <= max_depth and len(out) < max_new:
            have.add(key)
            out.append(t)

    ported = HENTRIES if PORTED[0] else []
    blocks = [t for t in list(genome) + ENTRIES + ported
              if depth(t) <= max_depth - 1]
    for t in ENTRIES + ported:
        offer(t)  # coordinates are proposable, never given
    for t in blocks:
        for c in value_pool:
            offer(("mod", t, c))
        offer(("abs", t))
        offer(("sign", t))
    for i, t1 in enumerate(blocks):
        for t2 in blocks[i:]:
            offer(("gcd", t1, t2))
            offer(("valli", t1, t2))
    out.sort(key=depth)
    return out


# ---- persistence ---------------------------------------------------------

def load_state():
    if os.path.exists(STATE):
        with open(STATE) as fh:
            s = json.load(fh)
            if s.get("version") == 2:
                s["genome"] = [tuple_term(t) for t in s["genome"]]
                return s
    return {"version": 2, "shell": 1, "genome": list(SEED),
            "value_pool": [2, 3], "events": 0, "ported": False}


def tuple_term(t):
    return tuple(tuple_term(x) if isinstance(x, list) else x for x in t)


def save_state(state):
    os.makedirs(os.path.dirname(STATE), exist_ok=True)
    with open(STATE, "w") as fh:
        json.dump(state, fh)


def log(line):
    os.makedirs(os.path.dirname(LOG), exist_ok=True)
    with open(LOG, "a") as fh:
        fh.write(line + "\n")


# ---- the life ------------------------------------------------------------

def shell(bound):
    for entries in product(range(-bound, bound + 1), repeat=4):
        if max(abs(e) for e in entries) != bound:
            continue
        m = ((entries[0], entries[1]), (entries[2], entries[3]))
        if m == ((0, 0), (0, 0)):
            continue
        for h in H_SET:
            yield (m, h)


def live(max_shells=None):
    global H_SET
    state = load_state()
    # SELF-KNOWLEDGE AT BIRTH: the machine verifies the whole corpus's
    # knowledge from its own primitives before living.  Documents are
    # interfaces; this is the knowledge.
    try:
        from core_knowledge import DEBT, verify_core
        ledger = verify_core()
        alive = sum(1 for _, ok in ledger if ok)
        dead = [n for n, ok in ledger if not ok]
        log(f"BOOT: CORE {alive}/{len(ledger)} claims alive"
            + (f"; DEAD: {dead}" if dead else "")
            + f"; {len(DEBT)} interface debts")
    except Exception as exc:  # noqa: BLE001
        log(f"BOOT: core knowledge unavailable: {exc}")
    state.setdefault("bits", 0)
    state.setdefault("epoch", 0)
    while max_shells is None or state["shell"] <= max_shells:
        step = state["shell"]
        bound = 1 + (step - 1) % 2          # breadth cycles 1..2
        state["epoch"] = (step - 1) // 2    # depth grows per cycle
        PORTED[0] = state["bits"] > 0
        PORT_BITS[0] = state["bits"]
        H_SET = h_family(state["epoch"])  # after PORT_BITS: the word
        # world's depth reads granted knowledge, not last step's
        universe = list(shell(bound))
        machine = DescentMachine(universe)
        formed = absorbed = 0
        observed = set()

        def offer_term(t):
            nonlocal formed, absorbed
            event = machine.offer(show(t), lambda m, _t=t: ev(_t, m))
            state["events"] += 1
            for m in universe[:200]:
                v = ev(t, m)  # m is a full state (matrix, payload)
                if isinstance(v, int) and 2 <= abs(v) <= 13:
                    observed.add(abs(v))
            if event["kind"] == "forms":
                formed += 1
                return True
            absorbed += 1
            return False

        # genome first (accumulated selfhood), then its own proposals,
        # all under the attention budget
        offers = 0
        grew = False
        for t in list(state["genome"]):
            if offers >= BUDGET:
                break
            offer_term(t)
            offers += 1
        for t in frontier(state["genome"], state["value_pool"]):
            # attention is budgeted, but a WALL claims "no term of mine
            # can form" — that claim needs the whole frontier as
            # evidence.  Budget-truncating the search certified false
            # walls: with genome 9 and budget 12, the same three
            # shallow terms were retried forever.  Found by running.
            if offers >= BUDGET and grew:
                break
            if offer_term(t):
                state["genome"].append(t)
                grew = True
                log(f"step={step} FORMS {show(t)} "
                    f"(genome={len(state['genome'])})")
            offers += 1

        # CERTIFY: if nothing formed beyond the genome, the machine
        # proves its own wall from inside. Grammar induction: every
        # available term factors through the endpoint projection unless
        # an hentry port is granted — so the carrier can never refine
        # past the m-partition, and the residual is exactly the fiber
        # family at every state. This is a proof the machine checks, not
        # an observation it despairs of.
        # the wall test is "the frontier formed nothing new", NOT
        # "every genome term still splits" — in a changed world kind,
        # old genome terms may legitimately absorb (their content
        # descends), and demanding they all form deadlocked the word
        # worlds: no walls, no ports, no growth.  Found by running.
        if not grew:
            # saturation has two distinct terminal readings, and the
            # machine distinguishes them exactly:
            fibs = machine.fibers()
            if len(fibs) == len(universe):
                # COMPLETE: carrier discrete — but the machine no longer
                # trusts completeness it cannot defend: the look-ahead
                # certificate reports GENUINE-COMPLETE vs SHELL-LOCAL
                # with the collision pair — the next wall, foreseen.
                try:
                    from vacuity_certificates import certify_complete
                    nxt = [(mm, hh)
                           for hh in h_family(state["epoch"] + 1)[:8]
                           for mm, _ in universe[:40]]
                    r = certify_complete(state["genome"], universe[:400],
                                         nxt, ev)
                    extra = (f"; foreseen collision {r.get('witness')}"
                             if r["verdict"] == "SHELL-LOCAL" else "")
                    log(f"step={step} COMPLETE at bits={state['bits']}: "
                        f"{r['verdict']} on {len(universe)} states"
                        f"{extra}; growing.")
                except Exception as exc:
                    log(f"step={step} COMPLETE at bits={state['bits']}: "
                        f"carrier discrete on {len(universe)} states "
                        f"(certificate unavailable: {exc}); growing.")
                # GROW on completeness: in the word kind the world only
                # deepens through grants, so a genuinely complete world
                # must grant too — else the machine grinds a finished
                # world forever (death kind #2, would-be return of)
                state["bits"] += 1
            else:
                # WALL: stuck strictly below discreteness — provably,
                # by grammar induction, no term sees the fiber beyond
                # the granted bits.  Demand the next bit.
                log(f"step={step} WALL CERTIFICATE at bits="
                    f"{state['bits']}: carrier fixed at {len(fibs)} "
                    f"fibers over {len(universe)} states; grammar "
                    f"induction: no term sees the fiber beyond "
                    f"{state['bits']} bit(s). Demanding the next bit.")
                state["bits"] += 1
                log(f"step={step} PORT GRANTED: bit {state['bits']} "
                    f"of the fiber coordinate becomes visible.")
        new_values = sorted(observed - set(state["value_pool"]))[:3]
        state["value_pool"] = sorted(set(state["value_pool"])
                                     | set(new_values))
        log(f"step={step} (bound={bound} epoch={state['epoch']} "
            f"bits={state['bits']}) summary: universe={len(universe)} "
            f"formed={formed} absorbed={absorbed} "
            f"fibers={len(machine.fibers())} genome={len(state['genome'])} "
            f"pool={state['value_pool']}")
        state["shell"] += 1
        save_state(state)


if __name__ == "__main__":
    limit = int(sys.argv[1]) if len(sys.argv) > 1 else None
    live(limit)
