"""Shape, not cardinality: a locus is confined where an interval is not.

Companion to `notes/MULTIPLICATIVE_CONFINEMENT.md`.

`LOCUS_MEMORY_FAMINE.md` seed 1 has been my oldest open problem: every lower
bound in this thread is a **counting** bound, and counting is shape-blind -- it
cannot tell a multiplicative locus from any other set of the same cardinality.
Commit `ddc50ae` (claude_arithmetic_breaker) named the blind spot: *cardinality
is not the criterion; only breaking the symmetry helps.*

Applying that instrument gives a shape-sensitive bound in the **multiplicative
fragment**, and it is not a bound at all -- it is an impossibility:

    the classes reachable from a held set F by multiplication alone are exactly
    the subgroup <F> of (Z/q)^*, at ANY chain length,

so if `<F>` is proper, a positive proportion of classes is unreachable forever.
Counting can never say that; it only ever says "many steps".

Gauss's index (Disquisitiones, art. 57) makes the subgroup exactly computable:
in the cyclic group `(Z/q)^*` of order `q-1`,

    |<g_1,...,g_k>| = (q-1) / gcd(q-1, ind g_1, ..., ind g_k).

And §3 delimits the result honestly: once **addition** is admitted the
confinement vanishes, which is precisely why the counting bounds were
shape-blind.

All arithmetic exact.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import gcd
from typing import Sequence


def multiplicative_closure(generators: Sequence[int], q: int) -> frozenset[int]:
    """The subgroup of (Z/q)^* generated by the residues -- every class ever
    reachable by multiplication alone, at any chain length."""
    if q < 2:
        raise ValueError("modulus must be at least 2")
    residues = []
    for g in generators:
        if g % q == 0:
            raise ValueError(f"{g} is not a unit mod {q}")
        residues.append(g % q)
    reached = {1}
    frontier = [1]
    while frontier:
        x = frontier.pop()
        for g in residues:
            y = x * g % q
            if y not in reached:
                reached.add(y)
                frontier.append(y)
    return frozenset(reached)


def least_primitive_root(q: int) -> int:
    """The least primitive root mod the prime `q`, by direct search."""
    if q < 3:
        raise ValueError("require an odd prime modulus")
    for candidate in range(2, q):
        seen = set()
        x = 1
        for _ in range(q - 1):
            x = x * candidate % q
            seen.add(x)
        if len(seen) == q - 1:
            return candidate
    raise ValueError(f"{q} has no primitive root; is it prime?")


def index_table(q: int, root: int | None = None) -> dict[int, int]:
    """Gauss's indices: `ind x` is the exponent with `root^(ind x) = x`."""
    root = least_primitive_root(q) if root is None else root
    table: dict[int, int] = {}
    x = 1
    for exponent in range(1, q):
        x = x * root % q
        table[x] = exponent % (q - 1)
    return table


def subgroup_order_by_index(generators: Sequence[int], q: int) -> int:
    """`(q-1) / gcd(q-1, ind g_1, ..., ind g_k)` -- the order, via art. 57.

    A second, independent route to `len(multiplicative_closure(...))`: this one
    never enumerates the subgroup, it only takes a gcd of indices.
    """
    table = index_table(q)
    divisor = q - 1
    for g in generators:
        if g % q == 0:
            raise ValueError(f"{g} is not a unit mod {q}")
        divisor = gcd(divisor, table[g % q])
    return (q - 1) // divisor


@dataclass(frozen=True)
class Confinement:
    """How much of (Z/q)^* a held set can ever reach multiplicatively."""

    modulus: int
    generators: tuple
    subgroup_order: int
    group_order: int
    index: int
    unreachable_fraction: float
    primitive_root: int


def confinement(generators: Sequence[int], q: int) -> Confinement:
    """The exact multiplicative reach, checked two ways."""
    closure = multiplicative_closure(generators, q)
    by_index = subgroup_order_by_index(generators, q)
    if len(closure) != by_index:
        raise AssertionError("enumeration and index calculus disagree")
    return Confinement(
        modulus=q,
        generators=tuple(generators),
        subgroup_order=len(closure),
        group_order=q - 1,
        index=(q - 1) // len(closure),
        unreachable_fraction=1 - len(closure) / (q - 1),
        primitive_root=least_primitive_root(q),
    )


def interval_generates_everything(bound: int, q: int) -> bool:
    """An interval `{1..bound}` generates all of `(Z/q)^*` once it holds a
    primitive root -- which is why shape, not size, is the criterion."""
    if bound < 1:
        raise ValueError("bound must be positive")
    return len(multiplicative_closure(range(1, min(bound, q - 1) + 1), q)) == q - 1


def additive_escape(generators: Sequence[int], q: int) -> int:
    """Steps of `+1` needed to leave the multiplicative closure.

    Section 3's delimitation: with addition admitted the confinement vanishes,
    so shape obstructs *reachability* only in the multiplicative fragment.
    """
    closure = multiplicative_closure(generators, q)
    if len(closure) == q - 1:
        return 0
    value = 1
    for step in range(1, q + 1):
        value = (value + 1) % q
        if value not in closure and value != 0:
            return step
    raise AssertionError("addition failed to escape a proper subgroup")


if __name__ == "__main__":
    print("multiplicative confinement of the <2,3> locus, checked two ways")
    print(f"  {'q':>5} {'|H|':>5} {'q-1':>5} {'index':>6} {'unreachable':>12} "
          f"{'root':>5} {'+1 escapes in':>14}")
    for q in (7, 17, 31, 41, 73, 97, 193, 241):
        c = confinement((2, 3), q)
        print(f"  {c.modulus:>5} {c.subgroup_order:>5} {c.group_order:>5} "
              f"{c.index:>6} {c.unreachable_fraction:>11.0%} "
              f"{c.primitive_root:>5} {additive_escape((2, 3), q):>14}")

    print()
    print("at q = 97 -- the modulus of Gauss's own table of indices --")
    c = confinement((2, 3), 97)
    table = index_table(97)
    print(f"  root {c.primitive_root}, ind 2 = {table[2]}, ind 3 = {table[3]}, "
          f"gcd(96, {table[2]}, {table[3]}) = {gcd(gcd(96, table[2]), table[3])}")
    print(f"  so |<2,3>| = {c.subgroup_order} of {c.group_order}: "
          f"{c.unreachable_fraction:.0%} of classes are unreachable at ANY length")

    print()
    print("but an interval of the same cardinality is not confined")
    for q in (73, 97, 193, 241):
        c = confinement((2, 3), q)
        size = c.subgroup_order
        print(f"  q={q:>4}: locus reaches {size:>4}/{c.group_order};  "
              f"interval {{1..{c.primitive_root}}} reaches everything: "
              f"{interval_generates_everything(c.primitive_root, q)}")
