#!/usr/bin/env python3
"""Exact finite transport when an observation is deliberately forgotten."""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from typing import Hashable, Mapping, Sequence

from natural_crystal import Crystal, crystallize


@dataclass(frozen=True)
class ForgettingResult:
    rich: Crystal
    coarse: Crystal
    state_map: tuple[int, ...]
    rich_monoid: tuple[tuple[int, ...], ...]
    coarse_monoid: tuple[tuple[int, ...], ...]
    monoid_map: tuple[int, ...]


def transformation_monoid(crystal: Crystal) -> tuple[tuple[int, ...], ...]:
    """Enumerate the monoid generated by a finite crystal's actions."""
    n = len(crystal.fibers)
    identity = tuple(range(n))
    generators = tuple(
        tuple(crystal.transitions[x][a] for x in range(n))
        for a in range(len(crystal.actions))
    )
    found = {identity}
    queue = deque([identity])
    while queue:
        current = queue.popleft()
        for generator in generators:
            composite = tuple(generator[current[x]] for x in range(n))
            if composite not in found:
                found.add(composite)
                queue.append(composite)
    return tuple(sorted(found))


def _block_index(crystal: Crystal) -> dict[Hashable, int]:
    return {
        state: index
        for index, fiber in enumerate(crystal.fibers)
        for state in fiber
    }


def forget_observation(
    states: Sequence[Hashable],
    actions: Sequence[Hashable],
    transition: Mapping[tuple[Hashable, Hashable], Hashable],
    rich_observation: Mapping[Hashable, Hashable],
    coarse_observation: Mapping[Hashable, Hashable],
) -> ForgettingResult:
    """Compile a coarser predictive system and its action-algebra quotient.

    ``coarse_observation`` must factor through ``rich_observation``.  This is
    the declared act of forgetting; accidental unrelated observations are
    rejected.
    """
    decoder: dict[Hashable, Hashable] = {}
    for state in states:
        rich_value = rich_observation[state]
        coarse_value = coarse_observation[state]
        if rich_value in decoder and decoder[rich_value] != coarse_value:
            raise ValueError("coarse observation does not factor through rich")
        decoder[rich_value] = coarse_value

    rich = crystallize(states, actions, transition, rich_observation)
    coarse = crystallize(states, actions, transition, coarse_observation)
    rich_index, coarse_index = _block_index(rich), _block_index(coarse)

    state_map = []
    for fiber in rich.fibers:
        targets = {coarse_index[state] for state in fiber}
        if len(targets) != 1:
            raise AssertionError("rich predictive class crossed coarse class")
        state_map.append(targets.pop())

    rich_monoid = transformation_monoid(rich)
    coarse_monoid = transformation_monoid(coarse)
    coarse_lookup = {transformation: i for i, transformation in enumerate(coarse_monoid)}
    monoid_map = []
    for transformation in rich_monoid:
        induced = []
        for coarse_state in range(len(coarse.fibers)):
            representatives = [
                i for i, target in enumerate(state_map) if target == coarse_state
            ]
            images = {state_map[transformation[i]] for i in representatives}
            if len(images) != 1:
                raise AssertionError("rich action does not descend")
            induced.append(images.pop())
        induced_tuple = tuple(induced)
        if induced_tuple not in coarse_lookup:
            raise AssertionError("induced action absent from coarse monoid")
        monoid_map.append(coarse_lookup[induced_tuple])

    if set(monoid_map) != set(range(len(coarse_monoid))):
        raise AssertionError("forgetting map on action monoids is not surjective")
    return ForgettingResult(
        rich, coarse, tuple(state_map), rich_monoid, coarse_monoid,
        tuple(monoid_map)
    )


def is_group(monoid: Sequence[tuple[int, ...]]) -> bool:
    """A finite transformation monoid is a group iff every map is bijective."""
    return all(len(set(transformation)) == len(transformation)
               for transformation in monoid)


def minimal_reversibility_example() -> ForgettingResult:
    """Nonidentity idempotent upstairs, identity action after forgetting."""
    states = (0, 1, 2)
    actions = ("collapse",)
    transition = {
        (0, "collapse"): 0,
        (1, "collapse"): 0,
        (2, "collapse"): 2,
    }
    rich = {state: state for state in states}
    coarse = {0: 0, 1: 0, 2: 1}
    return forget_observation(states, actions, transition, rich, coarse)


if __name__ == "__main__":
    result = minimal_reversibility_example()
    print("rich fibers:", result.rich.fibers)
    print("forgotten fibers:", result.coarse.fibers)
    print("rich monoid:", result.rich_monoid, "group:", is_group(result.rich_monoid))
    print("forgotten monoid:", result.coarse_monoid, "group:", is_group(result.coarse_monoid))
    print("surjection:", result.monoid_map)
