"""Transport of ambient valuation minimality, decided by a repetend.

Companion to `notes/PERIOD_PARITY_TRANSPORT.md`.

Settles the claim of `collab/messages/0146-codex-ananta-cyclic-world-converse-claim.md`.

For an odd prime `p` and a formed multiplicative world `S = <G>` consisting of
units mod `p`, ambient valuation minimality transports at every pair of `S` if
and only if `-1` lies in the image of `S` in `(Z/p)^*`.  For a single generator
that says `ord_p(g)` is even -- and `ord_p(g)` is exactly the length of the
repeating block of `1/p` written in base `g`.  So the criterion is decidable by
long division, and by Midy's theorem (1836) it is visible directly in the
digits: the repetend splits into two halves summing to `g^m - 1`.

Two loci are distinguished throughout, because they answer differently:

    S = <G>            units only; the world of msg 0146
    F = p^N * <G>      the organism has also formed the prime p

Transport can fail on `S` and always holds on `F` at odd `p` (Theorem A').

All computations are exact integer arithmetic.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence


def multiplicative_order(g: int, m: int) -> int:
    """Least k >= 1 with g^k = 1 (mod m).  Requires gcd(g, m) = 1."""
    if m < 2:
        raise ValueError("modulus must be >= 2")
    g %= m
    if g == 0:
        raise ValueError("g must be a unit mod m")
    x, k = g, 1
    seen = 0
    while x != 1:
        x = x * g % m
        k += 1
        seen += 1
        if seen > m:
            raise ValueError(f"{g} is not a unit modulo {m}")
    return k


def repetend(p: int, g: int) -> list[int]:
    """The repeating block of 1/p written in base g, as a list of digits.

    Exact long division: the state is the remainder, and the block begins when
    a remainder repeats.  For p prime not dividing g the expansion is purely
    periodic and the block starts immediately.
    """
    if p < 2 or g < 2:
        raise ValueError("require p >= 2 and base g >= 2")
    if g % p == 0:
        raise ValueError("require p not dividing the base g")
    seen: dict[int, int] = {}
    r = 1 % p
    digits: list[int] = []
    while r not in seen:
        seen[r] = len(digits)
        r *= g
        digits.append(r // p)
        r %= p
    return digits[seen[r]:]


def midy_halves(digits: Sequence[int], g: int) -> tuple[int, int, int]:
    """Split an even-length repetend and return (first, second, g^m - 1).

    Midy's theorem: for prime p and even period 2m, first + second = g^m - 1.
    Raises if the period is odd -- that is exactly the non-transport case.
    """
    n = len(digits)
    if n % 2 != 0:
        raise ValueError("Midy's theorem needs an even period")
    m = n // 2

    def value(block: Sequence[int]) -> int:
        acc = 0
        for d in block:
            acc = acc * g + d
        return acc

    return value(digits[:m]), value(digits[m:]), g ** m - 1


def unit_image(p: int, generators: Sequence[int]) -> frozenset[int]:
    """The subgroup of (Z/p)^* generated by the formed numbers."""
    gens = []
    for g in generators:
        if g % p == 0:
            raise ValueError(f"generator {g} is not a unit mod {p}")
        gens.append(g % p)
    seen = {1}
    frontier = [1]
    while frontier:
        x = frontier.pop()
        for g in gens:
            y = x * g % p
            if y not in seen:
                seen.add(y)
                frontier.append(y)
    return frozenset(seen)


def transports_by_group(p: int, generators: Sequence[int]) -> bool:
    """Theorem A: transport at every pair of S iff -1 is in the image."""
    return (p - 1) % p in unit_image(p, generators)


def transports_by_period(p: int, g: int) -> bool:
    """Corollary B/C: for one generator, iff the base-g period of 1/p is even."""
    return len(repetend(p, g)) % 2 == 0


@dataclass(frozen=True)
class TransportCertificate:
    """Why transport holds or fails, in both languages."""

    prime: int
    generators: tuple
    transports: bool
    period: int | None          # base-g period of 1/p, single generator only
    midy: tuple | None          # (first half, second half, g^m - 1)
    cancelling_pair: tuple | None   # u, w in S with p | u + w, when transport holds
    reason: str


def certify(p: int, generators: Sequence[int], exponent_bound: int = 64
            ) -> TransportCertificate:
    """Decide transport on the units-only locus S = <generators>, with witness."""
    if p == 2:
        raise ValueError("Theorem A is stated for odd p")
    image = unit_image(p, generators)
    holds = (p - 1) in image
    period = midy = pair = None
    if len(generators) == 1:
        g = generators[0]
        digits = repetend(p, g)
        period = len(digits)
        if period % 2 == 0:
            midy = midy_halves(digits, g)
    if holds:
        pair = _cancelling_pair(p, generators, exponent_bound)
    reason = (
        f"-1 = {p-1} is in the image of S in (Z/{p})^*; some formed pair "
        f"cancels, so the depth-0 chart is defeated"
        if holds else
        f"-1 = {p-1} is not in the image of S in (Z/{p})^*; no two formed "
        f"numbers ever sum to a multiple of {p}, so depth 0 already decides"
    )
    return TransportCertificate(p, tuple(generators), holds, period, midy,
                                pair, reason)


def _cancelling_pair(p: int, generators: Sequence[int], bound: int):
    """An explicit u, w in S with p | u + w, found by breadth-first growth."""
    reached = {1: 1}
    frontier = [1]
    while frontier and len(reached) <= bound:
        x = frontier.pop(0)
        for g in generators:
            y = x * g
            r = y % p
            if r not in reached:
                reached[r] = y
                frontier.append(y)
    for r, u in reached.items():
        s = (-r) % p
        if s in reached:
            return u, reached[s]
    return None


def transports_by_fiber(p: int, generators: Sequence[int]) -> bool:
    """Independent replay: is the depth-0 chart insufficient somewhere on S?

    The depth-0 fiber is all of S x S, so transport at every pair is equivalent
    to `v_p(u+w)` taking more than one value on S x S.  This route computes
    actual integer valuations of actual formed sums, rather than asking whether
    `-1` lies in a subgroup.

    It is exhaustive, not a sampled window: `_representatives` returns one
    integer of `S` per residue class mod `p` reached by `S`, and whether
    `v_p(u+w) >= 1` depends only on those residues.
    """
    reps = _representatives(p, generators)
    values = {_val(u + w, p) for u in reps for w in reps}
    return len(values) > 1


def _representatives(p: int, generators: Sequence[int]) -> list[int]:
    """One integer of S per residue class mod p that S reaches."""
    for g in generators:
        if g % p == 0:
            raise ValueError(f"generator {g} is not a unit mod {p}")
    reached = {1 % p: 1}
    frontier = [1]
    while frontier:
        x = frontier.pop()
        for g in generators:
            y = x * g
            r = y % p
            if r not in reached:
                reached[r] = y
                frontier.append(y)
    return sorted(reached.values())


def _val(n: int, p: int) -> int:
    k = 0
    while n % p == 0:
        n //= p
        k += 1
    return k


def transports_with_prime_formed(p: int, generators: Sequence[int]) -> bool:
    """Theorem A': on F = p^N * S the answer is yes at every odd p.

    Kept as a function so the asymmetry is executable rather than only
    asserted: forming the prime p supplies the depth-0 witness that a
    units-only world lacks.
    """
    if p == 2:
        raise ValueError("Theorem A' is stated for odd p")
    unit_image(p, generators)      # validates the generators
    return True


if __name__ == "__main__":
    print("base-10 organism: transport status of each odd prime, read off 1/p")
    print(f"{'p':>4} {'period':>7} {'even':>6} {'-1 in <10>':>11}  Midy halves")
    for p in [3, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43]:
        cert = certify(p, [10])
        midy = ""
        if cert.midy:
            a, b, target = cert.midy
            midy = f"{a} + {b} = {target}"
        print(f"{p:>4} {cert.period:>7} {str(cert.transports):>6} "
              f"{str(cert.transports):>11}  {midy}")
    print()
    print("transport fails at p = 3, 31, 37 for a decimal organism:")
    for p in (3, 31, 37):
        print(f"  p={p}: no two powers of 10 sum to a multiple of {p}; "
              f"depth 0 decides where the ambient theorem demands depth 1")
