#!/usr/bin/env python3
"""Exact tests for the uniform confinement index, at every prime.

Run: python3 -m unittest test_confinement_index_uniform -v   (from machinery/)

Every test here is either an exhaustive finite verification over a complete
subgroup lattice or an exact identity check.  Nothing is measured.
"""

import unittest

from confinement_index_uniform import (
    all_subgroups,
    analyse,
    analyse_held_set,
    certify_index_formula,
    certify_odd_classification,
    divisor_count,
    level,
    predicted_index,
    principal_exponent,
    signature_order,
    single_generator_index,
    subgroup_generated,
    totient_prime_power,
    two_adic_classification_failure,
    unit_group,
)

# Kept small enough that every subgroup lattice below is enumerated in full.
EXHAUSTIVE_CASES = ((2, 4), (2, 5), (2, 6), (3, 3), (3, 4), (5, 3), (7, 3),
                    (11, 2), (13, 2))

ODD_CASES = ((3, 3), (3, 4), (5, 2), (5, 3), (7, 2), (7, 3), (11, 2), (13, 2))


class SubgroupLatticeTests(unittest.TestCase):
    """The enumeration itself must be trustworthy before it certifies anything."""

    def test_enumeration_returns_genuine_subgroups(self):
        for p, k in EXHAUSTIVE_CASES:
            modulus = p ** k
            for u in all_subgroups(p, k):
                self.assertIn(1, u)
                for x in u:
                    for y in u:
                        self.assertIn((x * y) % modulus, u)

    def test_lagrange_holds_in_the_enumeration(self):
        for p, k in EXHAUSTIVE_CASES:
            ambient = totient_prime_power(p, k)
            for u in all_subgroups(p, k):
                self.assertEqual(ambient % len(u), 0)

    def test_enumeration_is_complete_against_brute_force_generation(self):
        """Every subgroup generated by a pair of units is in the enumeration."""
        for p, k in ((2, 5), (3, 3), (5, 2)):
            found = set(all_subgroups(p, k))
            units = unit_group(p, k)
            for a in units:
                for b in units:
                    self.assertIn(subgroup_generated((a, b), p, k), found)

    def test_enumeration_is_canonical_not_traversal_dependent(self):
        for p, k in ((2, 5), (3, 3)):
            self.assertEqual(all_subgroups(p, k), all_subgroups(p, k))


class UniformIndexFormulaTests(unittest.TestCase):
    def test_formula_holds_on_every_subgroup_at_every_case(self):
        for p, k in EXHAUSTIVE_CASES:
            reports = certify_index_formula(p, k)
            self.assertGreater(len(reports), 0)
            for r in reports:
                self.assertTrue(r.agrees)
                self.assertEqual(r.order * r.index, totient_prime_power(p, k))

    def test_index_is_independent_of_precision_once_k_exceeds_the_level(self):
        for gens in ((3,), (5,), (7,), (17,), (31,), (3, 5)):
            indices = {analyse_held_set(gens, 2, k).index for k in (8, 9, 10, 11)}
            self.assertEqual(len(indices), 1)
        for gens in ((2,), (4,), (5,), (2, 5)):
            indices = {analyse_held_set(gens, 3, k).index for k in (6, 7, 8)}
            self.assertEqual(len(indices), 1)

    def test_level_and_signature_are_the_only_inputs(self):
        """Two subgroups sharing `(d, l)` share an index, at every prime."""
        for p, k in EXHAUSTIVE_CASES:
            by_signature: dict[tuple[int, int], int] = {}
            for u in all_subgroups(p, k):
                key = (signature_order(u, p), level(u, p, k))
                r = analyse(u, p, k)
                if key in by_signature:
                    self.assertEqual(by_signature[key], r.index)
                by_signature[key] = r.index


class TwoAdicSpecialisationTests(unittest.TestCase):
    """The uniform formula must reproduce `TWO_ADIC_CONFINEMENT.md` (1.1)."""

    PUBLISHED_TABLE = (((3,), 3, True, 2), ((5,), 2, False, 2), ((7,), 4, True, 4),
                       ((17,), 4, False, 8), ((31,), 6, True, 16),
                       ((3, 5), 2, True, 1), ((3, 7), 2, True, 1))

    def test_published_table_reproduces_row_for_row(self):
        for gens, expected_level, meets_three, expected_index in self.PUBLISHED_TABLE:
            for k in (8, 10):
                r = analyse_held_set(gens, 2, k)
                self.assertEqual(r.level, expected_level, gens)
                self.assertEqual(r.signature_order, 2 if meets_three else 1, gens)
                self.assertEqual(r.index, expected_index, gens)

    def test_two_branches_are_the_two_values_of_the_signature(self):
        for u in all_subgroups(2, 6):
            d, l = signature_order(u, 2), level(u, 2, 6)
            expected = 2 ** (l - 2) if d == 2 else 2 ** (l - 1)
            self.assertEqual(predicted_index(2, l, d), expected)

    def test_signature_order_two_means_meets_three_mod_four(self):
        for k in (4, 5, 6):
            for u in all_subgroups(2, k):
                meets = any(x % 4 == 3 for x in u)
                self.assertEqual(signature_order(u, 2) == 2, meets)


class OddClassificationTests(unittest.TestCase):
    def test_signature_pair_classifies_subgroups_for_odd_p(self):
        for p, k in ODD_CASES:
            observed, predicted = certify_odd_classification(p, k)
            self.assertEqual(observed, predicted)
            self.assertEqual(predicted, divisor_count(p - 1) * k)

    def test_every_odd_subgroup_splits_as_a_direct_product(self):
        """For odd `p`, `U = (U cap mu) x (U cap P)` -- coprime orders."""
        for p, k in ODD_CASES:
            for u in all_subgroups(p, k):
                principal = {x for x in u if x % p == 1}
                prime_to_p = {x for x in u if _order(x, p ** k) % p != 0}
                self.assertEqual(len(u), len(principal) * len(prime_to_p))


class TwoIsStillExceptionalTests(unittest.TestCase):
    """The exceptionality survives -- in the classification, not the index."""

    def test_classification_fails_at_two_with_an_explicit_pair(self):
        left, right = two_adic_classification_failure(5)
        self.assertNotEqual(left, right)
        self.assertEqual(signature_order(left, 2), signature_order(right, 2))
        self.assertEqual(level(left, 2, 5), level(right, 2, 5))
        self.assertEqual({frozenset({1, 15}), frozenset({1, 31})}, {left, right})

    def test_the_colliding_pair_still_obeys_the_index_formula(self):
        left, right = two_adic_classification_failure(5)
        self.assertEqual(analyse(left, 2, 5).index, analyse(right, 2, 5).index)
        self.assertTrue(analyse(left, 2, 5).agrees)
        self.assertTrue(analyse(right, 2, 5).agrees)

    def test_subgroup_count_at_two_exceeds_the_odd_prediction(self):
        """`tau(p-1)*k` undercounts at `p = 2`; that is the failure, quantified."""
        for k in (4, 5, 6):
            self.assertGreater(len(all_subgroups(2, k)), divisor_count(1) * k)

    def test_proposition_T_counting_law(self):
        """(a) `3k-4` subgroups, (b) `2(k-1)` classes, (c) deficiency `k-2`."""
        for k in range(3, 9):
            subgroups = all_subgroups(2, k)
            classes = {(signature_order(u, 2), level(u, 2, k)) for u in subgroups}
            self.assertEqual(len(subgroups), 3 * k - 4, k)
            self.assertEqual(len(classes), 2 * (k - 1), k)
            self.assertEqual(len(subgroups) - len(classes), k - 2, k)

    def test_proposition_T_locates_the_collisions_exactly(self):
        """(d) exactly two subgroups per `(d=2, l)` with `l >= 3`; else one."""
        for k in range(3, 8):
            multiplicity: dict[tuple[int, int], int] = {}
            for u in all_subgroups(2, k):
                key = (signature_order(u, 2), level(u, 2, k))
                multiplicity[key] = multiplicity.get(key, 0) + 1
            for (d, l), count in multiplicity.items():
                self.assertEqual(count, 2 if (d == 2 and l >= 3) else 1, (k, d, l))

    def test_minimal_witness_is_mod_eight(self):
        """`k = 3` is the smallest non-cyclic case and it already fails."""
        left, right = two_adic_classification_failure(3)
        self.assertEqual({frozenset({1, 3}), frozenset({1, 7})}, {left, right})


class SingleGeneratorTests(unittest.TestCase):
    def test_closed_form_matches_the_constructed_subgroup(self):
        for p, k in ((2, 10), (3, 6), (5, 5), (7, 4), (11, 3)):
            for a in range(1, min(p ** k, 60)):
                if a % p == 0:
                    continue
                self.assertEqual(
                    single_generator_index(a, p, k),
                    analyse_held_set((a,), p, k).index,
                    (p, k, a),
                )


class KnownFalseControlTests(unittest.TestCase):
    """Statements that must fire as false, and do."""

    def test_level_alone_does_not_determine_the_index(self):
        """The predecessor's retracted title, still false, now at every prime."""
        collisions = 0
        for p, k in EXHAUSTIVE_CASES:
            by_level: dict[int, set[int]] = {}
            for u in all_subgroups(p, k):
                by_level.setdefault(level(u, p, k), set()).add(analyse(u, p, k).index)
            collisions += sum(1 for v in by_level.values() if len(v) > 1)
        self.assertGreater(collisions, 0)

    def test_odd_principal_exponent_is_not_two(self):
        """Using `c = 2` at odd `p` breaks the formula -- `c` is not cosmetic."""
        self.assertEqual(principal_exponent(3), 1)
        broken = [analyse(u, 3, 3).index // 3 for u in all_subgroups(3, 3)]
        actual = [analyse(u, 3, 3).index for u in all_subgroups(3, 3)]
        self.assertNotEqual(broken, actual)

    def test_group_is_not_cyclic_at_two(self):
        """No primitive root mod `2^k`, `k >= 3` -- why art. 57 fails there."""
        for k in (3, 4, 5):
            modulus = 2 ** k
            self.assertLess(
                max(_order(u, modulus) for u in unit_group(2, k)),
                totient_prime_power(2, k),
            )

    def test_group_is_cyclic_at_odd_p(self):
        for p, k in ((3, 3), (5, 2), (7, 2)):
            modulus = p ** k
            self.assertEqual(
                max(_order(u, modulus) for u in unit_group(p, k)),
                totient_prime_power(p, k),
            )


def _order(x: int, modulus: int) -> int:
    """Multiplicative order of a unit, exactly."""
    order, power = 1, x % modulus
    while power != 1:
        power = (power * x) % modulus
        order += 1
    return order


if __name__ == "__main__":
    unittest.main()
