{-# OPTIONS --cubical --safe --no-import-sorts #-}

------------------------------------------------------------------------
-- CommutationPreservesEveryPredicateAndMultiplicityWhereItIsStatable
--
-- ON THE NAME.  The enumeration of permutations is an Indian subject ‚î
-- ‡‡‡∞‡‡‡‡æ‡∞ (prastra) in Pigala's *Chandastra* (~300 BCE) and its
-- commentarial line, and ‡‡ô‡‡ï‡‡æ‡ (akapa), Nryaa Paita's chapter
-- on permutations and combinations in the *Gaitakaumud* (1356).
-- **This module is not that object and does not take its name.**  The
-- prastra line in this repository belongs to other identities
-- (`PrastaraPankti`, `PingalaPrastara`, `Dvipada`); what is here is an
-- equivalence RELATION on step lists, not an enumeration of
-- arrangements.  Taking their subject's name for a different object
-- would claim the wrong provenance and collide with their line, so per
-- CLAUDE.md's naming guard this file carries an English name and this
-- paragraph.
--
-- ‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î‚î
-- `PairwiseCommutationGivesEveryOrder` has carried one admission since
-- it was written: `_~_` is generated by adjacent transpositions and is
-- NOT proved to be "same multiset".  Addressed here, in two halves.
--
-- WHAT IS PROVED
--
--   ~preservesAny     `xs ~ ys ‚í Any P xs ‚í Any P ys`, for ANY
--                     predicate ‚î no decidability, no equality
--   ~preservesAll     the same for `All`
--   ~preservesLength  the length is invariant
--   count / ~preservesCount
--                     given `Discrete` on the step type, the
--                     MULTIPLICITY of every element is invariant ‚î
--                     which is precisely "same multiset"
--
-- **THE POINT IS WHERE THE HYPOTHESIS SITS.**  The predicate invariants
-- need nothing.  Multiplicity is different: to STATE "the same number
-- of copies of a" one must decide `x ‚â° a`, so on a step type without
-- decidable equality the question "is `_~_` the same-multiset
-- relation?" cannot be posed, let alone answered ‚î and `Step C` is a
-- type of functions with data attached, where `Discrete` is not
-- available in general and assuming it would be assuming decidable
-- equality of functions.
--
-- So the standing gap resolves into this: `_~_` implies same-multiset
-- wherever same-multiset is statable, and the question is ill-posed
-- exactly where the corpus actually uses `_~_`.
--
-- CHECKED on the CONTAINER (Agda 2.6.3, cubical v0.5 ‚î NOT the declared
-- pin, Agda 2.8.0 + cubical v0.9).  --safe, no postulates, no holes.
------------------------------------------------------------------------

module CommutationPreservesEveryPredicateAndMultiplicityWhereItIsStatable where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat using (‚Ñï ; zero ; suc)
open import Cubical.Data.List using (List ; [] ; _‚à∑_)
open import Cubical.Data.Sum using (inl ; inr)
open import Cubical.Data.Sigma using (_√ó_ ; _,_)
open import Cubical.Data.Unit using (Unit ; tt)
open import Cubical.Data.Empty as ‚ä• using (‚ä•)
open import Cubical.Relation.Nullary using (¬¨_ ; Dec ; yes ; no ; Discrete)

open import KramaAstiNasti_TheFourthCornerCannotLiveOverAnEnumerableDecidableInstanceSet
  using (Any)
open import TheParetoStratumIsDecidableAndTheFilterIsExact using (All)
open import TheRemainderIsStrictlyShorterSoTheStratificationHasAMeasure
  using (lengthL)
open import OrderIndependenceTransfersAlongAnyNumberOfSteps using (Step)
open import PairwiseCommutationGivesEveryOrder
  using (_~_ ; ~nil ; ~cons ; ~swap ; ~trans)

------------------------------------------------------------------------
-- 0.  Counting, where equality is decidable
------------------------------------------------------------------------

count : {X : Type} ‚Üí Discrete X ‚Üí X ‚Üí List X ‚Üí ‚Ñï
count eq a []       = 0
count eq a (x ‚à∑ xs) with eq x a
... | yes _ = suc (count eq a xs)
... | no  _ = count eq a xs

countConsYes :
  {X : Type} (eq : Discrete X) (a x : X) (xs : List X)
  ‚Üí x ‚â° a ‚Üí count eq a (x ‚à∑ xs) ‚â° suc (count eq a xs)
countConsYes eq a x xs e with eq x a
... | yes _ = refl
... | no ¬¨e = ‚ä•.rec (¬¨e e)

countConsNo :
  {X : Type} (eq : Discrete X) (a x : X) (xs : List X)
  ‚Üí ¬¨ (x ‚â° a) ‚Üí count eq a (x ‚à∑ xs) ‚â° count eq a xs
countConsNo eq a x xs ¬¨e with eq x a
... | yes e = ‚ä•.rec (¬¨e e)
... | no  _ = refl

-- The two decisions are taken as ARGUMENTS rather than by `with`: a
-- `with` here would abstract the goal over the scrutinee and the two
-- cons equations above would no longer apply to it.
swapCount :
  {X : Type} (eq : Discrete X) (a p q : X) (xs : List X)
  ‚Üí count eq a (p ‚à∑ q ‚à∑ xs) ‚â° count eq a (q ‚à∑ p ‚à∑ xs)
swapCount eq a p q xs = go (eq p a) (eq q a)
  where
    go : Dec (p ‚â° a) ‚Üí Dec (q ‚â° a)
       ‚Üí count eq a (p ‚à∑ q ‚à∑ xs) ‚â° count eq a (q ‚à∑ p ‚à∑ xs)
    go (yes ep) (yes eqa) =
        countConsYes eq a p (q ‚à∑ xs) ep ‚àô cong suc (countConsYes eq a q xs eqa)
      ‚àô sym (countConsYes eq a q (p ‚à∑ xs) eqa ‚àô cong suc (countConsYes eq a p xs ep))
    go (yes ep) (no ¬¨eqa) =
        countConsYes eq a p (q ‚à∑ xs) ep ‚àô cong suc (countConsNo eq a q xs ¬¨eqa)
      ‚àô sym (countConsNo eq a q (p ‚à∑ xs) ¬¨eqa ‚àô countConsYes eq a p xs ep)
    go (no ¬¨ep) (yes eqa) =
        countConsNo eq a p (q ‚à∑ xs) ¬¨ep ‚àô countConsYes eq a q xs eqa
      ‚àô sym (countConsYes eq a q (p ‚à∑ xs) eqa ‚àô cong suc (countConsNo eq a p xs ¬¨ep))
    go (no ¬¨ep) (no ¬¨eqa) =
        countConsNo eq a p (q ‚à∑ xs) ¬¨ep ‚àô countConsNo eq a q xs ¬¨eqa
      ‚àô sym (countConsNo eq a q (p ‚à∑ xs) ¬¨eqa ‚àô countConsNo eq a p xs ¬¨ep)

------------------------------------------------------------------------
-- 1.  The invariants that need no hypothesis
--
-- The lists are IMPLICIT and only the derivation is matched: matching
-- the lists as well would need injectivity of `_‚à_`, which cubical Agda
-- does not support and which costs the function its computation on
-- transports (warning, not error ‚î but a clean check here means zero
-- warning lines).
------------------------------------------------------------------------

module _ {S T : Type} (C : S ‚Üí T) where

  ~preservesAny :
    (P : Step C ‚Üí Type) {xs ys : List (Step C)}
    ‚Üí _~_ C xs ys ‚Üí Any P xs ‚Üí Any P ys
  ~preservesAny P ~nil          e             = ‚ä•.rec e
  ~preservesAny P (~cons r)     (inl h)       = inl h
  ~preservesAny P (~cons r)     (inr k)       = inr (~preservesAny P r k)
  ~preservesAny P ~swap         (inl h)       = inr (inl h)
  ~preservesAny P ~swap         (inr (inl h)) = inl h
  ~preservesAny P ~swap         (inr (inr k)) = inr (inr k)
  ~preservesAny P (~trans r‚ÇÅ r‚ÇÇ) a            =
    ~preservesAny P r‚ÇÇ (~preservesAny P r‚ÇÅ a)

  ~preservesAll :
    (P : Step C ‚Üí Type) {xs ys : List (Step C)}
    ‚Üí _~_ C xs ys ‚Üí All P xs ‚Üí All P ys
  ~preservesAll P ~nil           _                  = tt
  ~preservesAll P (~cons r)      (h , rest)         = h , ~preservesAll P r rest
  ~preservesAll P ~swap          (hp , (hq , rest)) = hq , (hp , rest)
  ~preservesAll P (~trans r‚ÇÅ r‚ÇÇ) a                  =
    ~preservesAll P r‚ÇÇ (~preservesAll P r‚ÇÅ a)

  ~preservesLength :
    {xs ys : List (Step C)} ‚Üí _~_ C xs ys ‚Üí lengthL xs ‚â° lengthL ys
  ~preservesLength ~nil           = refl
  ~preservesLength (~cons r)      = cong suc (~preservesLength r)
  ~preservesLength ~swap          = refl
  ~preservesLength (~trans r‚ÇÅ r‚ÇÇ) =
    ~preservesLength r‚ÇÅ ‚àô ~preservesLength r‚ÇÇ

  ------------------------------------------------------------------
  -- 2.  ‚¶and multiplicity, exactly where it is statable
  ------------------------------------------------------------------

  ~preservesCount :
    (eq : Discrete (Step C)) (a : Step C) {xs ys : List (Step C)}
    ‚Üí _~_ C xs ys ‚Üí count eq a xs ‚â° count eq a ys
  ~preservesCount eq a ~nil = refl
  ~preservesCount eq a (~cons {p} {xs} {ys} r) = consCase (eq p a)
    where
      consCase : Dec (p ‚â° a) ‚Üí count eq a (p ‚à∑ xs) ‚â° count eq a (p ‚à∑ ys)
      consCase (yes ep) =
          countConsYes eq a p xs ep
        ‚àô cong suc (~preservesCount eq a r)
        ‚àô sym (countConsYes eq a p ys ep)
      consCase (no ¬¨ep) =
          countConsNo eq a p xs ¬¨ep
        ‚àô ~preservesCount eq a r
        ‚àô sym (countConsNo eq a p ys ¬¨ep)
  ~preservesCount eq a (~swap {p} {q} {xs}) = swapCount eq a p q xs
  ~preservesCount eq a (~trans r‚ÇÅ r‚ÇÇ) =
    ~preservesCount eq a r‚ÇÅ ‚àô ~preservesCount eq a r‚ÇÇ
