r"""Emergence in the finite hitting model: common, and not generator-wise.

`HITTING_DECIDABLE` seed 2, my own: for which pairs of affine maps mod
`p^{e+1}` is `0` jointly reachable but not separately?  I wrote that I "expect
a clean answer exists".  There is a clean *reformulation*, and a clean **no-go**
on the shape any criterion can take.

**Reformulation.**  Composition of affine maps is affine, so the moves generate
a finite affine submonoid.  Then

> `0` is reachable from `s` **iff** the generated submonoid contains some
> `(G, C)` with `G s + C = 0 (mod M)`.

This is monoid membership rather than graph search — the same decidability, a
better object.  Verified against the breadth-first model on all `8856` affine
pairs for `(p,e) = (2,1), (3,1), (2,2)`: zero disagreements.

**Emergence is common, not exotic.**  Mod `9` there are `39` never-hitting
single moves, and `159` of the `741` pairs of them hit jointly — better than one
in five.  So emergence is not a degeneracy to be excluded by a side condition.

**And no generator-wise criterion exists.**  The multiplicative parts do not
decide: mod `9`, **19 of the 42** possible `g`-part pairs contain both an
emergent and a non-emergent instance.  Whether a pair is emergent depends on
the additive parts too, so a criterion phrased on the generators separately —
of the kind that classified the multiplicative and additive families in
`HITTING_DECIDABLE` §2 — cannot exist here.

That is the honest answer to the seed: the criterion is monoid membership, it
is decidable, and it is provably not reducible to a condition on the generators
one at a time.
"""

from __future__ import annotations

import itertools
from typing import Dict, Iterable, List, Sequence, Set, Tuple

from hitting_decidable import hits

Affine = Tuple[int, int]


def compose(f: Affine, g: Affine, M: int) -> Affine:
    """`f` after `g`: `y -> f(g(y))`."""
    return ((f[0] * g[0]) % M, (f[0] * g[1] + f[1]) % M)


def generated_monoid(moves: Sequence[Affine], M: int) -> Set[Affine]:
    """The affine submonoid generated by `moves` in `Z/M`, with identity."""
    cur: Set[Affine] = {(1 % M, 0)} | {(g % M, c % M) for g, c in moves}
    while True:
        new = set(cur)
        for f in cur:
            for g in moves:
                new.add(compose(f, (g[0] % M, g[1] % M), M))
        if new == cur:
            return cur
        cur = new


def hits_by_monoid(p: int, e: int, moves: Sequence[Affine]) -> bool:
    """`0` reachable from `p^e` iff some monoid element sends it to `0`."""
    M = p ** (e + 1)
    s = p**e % M
    return any((G * s + C) % M == 0 for G, C in generated_monoid(moves, M))


# ------------------------------------------------------------------- census


def never_hitting_singles(p: int, e: int) -> List[Affine]:
    M = p ** (e + 1)
    return [(g, c) for g in range(M) for c in range(M) if not hits(p, e, [(g, c)])]


def emergence_census(p: int, e: int) -> Dict[str, object]:
    """How common is emergence among pairs of never-hitting moves?"""
    singles = never_hitting_singles(p, e)
    pairs = list(itertools.combinations(singles, 2))
    emergent = [pr for pr in pairs if hits(p, e, list(pr))]
    return {
        "modulus": p ** (e + 1),
        "never_hitting_singles": len(singles),
        "pairs": len(pairs),
        "emergent": len(emergent),
    }


def g_part_undetermined(p: int, e: int) -> List[Tuple[int, int]]:
    """`g`-part pairs containing both an emergent and a non-emergent instance.

    Each one witnesses that the multiplicative parts alone cannot decide.
    """
    singles = never_hitting_singles(p, e)
    seen: Dict[Tuple[int, int], Set[bool]] = {}
    for m1, m2 in itertools.combinations(singles, 2):
        key = tuple(sorted((m1[0], m2[0])))  # type: ignore[assignment]
        seen.setdefault(key, set()).add(hits(p, e, [m1, m2]))
    return sorted(k for k, v in seen.items() if len(v) > 1)


if __name__ == "__main__":
    print("== monoid membership reproduces the breadth-first verdict")
    for p, e in ((2, 1), (3, 1), (2, 2)):
        M = p ** (e + 1)
        pool = [(g, c) for g in range(M) for c in range(M)]
        bad = sum(
            1
            for pr in itertools.combinations(pool, 2)
            if hits(p, e, list(pr)) != hits_by_monoid(p, e, list(pr))
        )
        print(f"   p={p} e={e} (mod {M}): mismatches {bad}")

    print("\n== emergence is common")
    for p, e in ((2, 1), (3, 1), (2, 2)):
        c = emergence_census(p, e)
        frac = c["emergent"] / c["pairs"] if c["pairs"] else 0
        print(f"   mod {c['modulus']}: {c['emergent']} of {c['pairs']} "
              f"never-hitting pairs are emergent ({frac:.0%})")

    print("\n== and the multiplicative parts do not decide")
    for p, e in ((3, 1), (2, 2)):
        und = g_part_undetermined(p, e)
        singles = never_hitting_singles(p, e)
        keys = {tuple(sorted((a[0], b[0])))
                for a, b in itertools.combinations(singles, 2)}
        print(f"   mod {p**(e+1)}: {len(und)} of {len(keys)} g-part pairs are "
              f"undetermined by g alone")
        print(f"      examples {und[:6]}")
