#!/usr/bin/env python3
"""A finite arithmetic process in which one observation forms a new action."""

from __future__ import annotations

from collections import defaultdict, deque
from dataclasses import dataclass


State = int
Pair = tuple[State, State]


@dataclass(frozen=True)
class Witness:
    distance: int
    action: str | None
    successor_pair: Pair | None
    observation: str


def _ordered_pair(x: int, y: int) -> Pair:
    return (x, y) if x < y else (y, x)


class SixClock:
    """Learn Z/6 from successor, parity, and a formed ternary boundary."""

    states = tuple(range(6))

    def __init__(self) -> None:
        self.observations: dict[str, callable] = {"parity": lambda x: x % 2}
        self.actions: dict[str, callable] = {"successor": lambda x: (x + 1) % 6}
        self.certificates: dict[Pair, Witness] = {}
        self.capabilities = {"successor", "parity"}

    def immediate_profile(self, x: int) -> tuple[int, ...]:
        return tuple(observation(x) for observation in self.observations.values())

    def form_multiple_of_three(self) -> None:
        """Install the boundary predicate generated by grouping into threes."""
        self.observations["multiple-of-3"] = lambda x: int(x % 3 == 0)
        self.certificates = self._shortest_witness_forest()
        if len({self.behavioral_profile(x) for x in self.states}) != 6:
            raise AssertionError("formed observation did not separate Z/6")
        self.capabilities.update({"residue-mod-6", "add-mod-6", "divisible-by-6"})

    def form_from_collision(self, left: int, right: int) -> int:
        """Generate the least additive quotient lens separating a collision."""
        if "multiple-of-3" in self.observations:
            raise ValueError("the generated lens is already installed")
        if left == right or self.immediate_profile(left) != self.immediate_profile(right):
            raise ValueError("formation requires a distinct unresolved pair")
        difference = abs(left - right)
        modulus = next(m for m in range(2, difference + 2) if difference % m)
        if modulus != 3:
            raise ValueError("this six-clock realizes only its generated mod-3 lens")
        self.form_multiple_of_three()
        return modulus

    def behavioral_profile(self, x: int) -> tuple[int, tuple[int, int, int]]:
        """Finite future profile: parity plus three successive boundary readings."""
        boundary = self.observations.get("multiple-of-3")
        if boundary is None:
            return (x % 2, (0, 0, 0))
        return (x % 2, tuple(boundary((x + step) % 6) for step in range(3)))

    def decode_residue(self, profile: tuple[int, tuple[int, int, int]]) -> int:
        if "residue-mod-6" not in self.capabilities:
            raise ValueError("mod-6 reconstruction has not formed")
        matches = [x for x in self.states if self.behavioral_profile(x) == profile]
        if len(matches) != 1:
            raise ValueError("profile is not a realized unique residue")
        return matches[0]

    def add(self, left: int, right: int) -> int:
        if "add-mod-6" not in self.capabilities:
            raise ValueError("mod-6 addition has not formed")
        return (self.decode_residue(self.behavioral_profile(left))
                + self.decode_residue(self.behavioral_profile(right))) % 6

    def divisible_by_six(self, x: int) -> bool:
        if "divisible-by-6" not in self.capabilities:
            raise ValueError("divisibility-by-6 has not formed")
        return self.decode_residue(self.behavioral_profile(x)) == 0

    def replay(self, pair: Pair) -> tuple[str, tuple[int, ...]]:
        """Replay a shortest stored experiment and return its terminal readings."""
        pair = _ordered_pair(*pair)
        word: list[str] = []
        while True:
            witness = self.certificates[pair]
            if witness.action is None:
                observation = self.observations[witness.observation]
                return witness.observation, tuple(observation(x) for x in pair)
            word.append(witness.action)
            pair = witness.successor_pair  # type: ignore[assignment]

    def witness_word(self, pair: Pair) -> tuple[str, ...]:
        pair = _ordered_pair(*pair)
        word: list[str] = []
        while self.certificates[pair].action is not None:
            witness = self.certificates[pair]
            word.append(witness.action)  # type: ignore[arg-type]
            pair = witness.successor_pair  # type: ignore[assignment]
        return tuple(word)

    def _shortest_witness_forest(self) -> dict[Pair, Witness]:
        pairs = [(x, y) for x in self.states for y in self.states if x < y]
        predecessors: dict[Pair, list[tuple[Pair, str]]] = defaultdict(list)
        for pair in pairs:
            for name, action in self.actions.items():
                image = _ordered_pair(action(pair[0]), action(pair[1]))
                predecessors[image].append((pair, name))

        certificates: dict[Pair, Witness] = {}
        queue: deque[Pair] = deque()
        for pair in pairs:
            for name, observation in self.observations.items():
                if observation(pair[0]) != observation(pair[1]):
                    certificates[pair] = Witness(0, None, None, name)
                    queue.append(pair)
                    break
        while queue:
            image = queue.popleft()
            for source, action in predecessors[image]:
                if source not in certificates:
                    certificates[source] = Witness(
                        certificates[image].distance + 1,
                        action,
                        image,
                        certificates[image].observation,
                    )
                    queue.append(source)
        return certificates


def main() -> None:
    clock = SixClock()
    print("before:", sorted(clock.capabilities))
    print("2 and 4 collide immediately:", clock.immediate_profile(2), clock.immediate_profile(4))
    modulus = clock.form_from_collision(2, 4)
    print(f"formed from collision: mod {modulus} zero-fiber")
    print("shortest experiment separating 2,4:", clock.witness_word((2, 4)))
    print("terminal readings:", clock.replay((2, 4)))
    print("after:", sorted(clock.capabilities))
    print("5 + 4 mod 6 =", clock.add(5, 4))
    print("12 divisible by 6:", clock.divisible_by_six(12 % 6))


if __name__ == "__main__":
    main()
