"""Blind hostile audit of claim R0040 (fleet-blind-r0040).

Independent implementation from the conventions of
notes/HECKE_COSET_SMITH_ASSEMBLY.md ONLY (the owner's derivation in
notes/BIJECTIVE_SMITH_ASSEMBLY.md and machinery/bijective_smith_assembly.py
was NOT read).

Conventions: column lattices L = M Z^2; Hermite basis ((a,0),(b,d)) meaning
columns (a,b) and (0,d), ad = m, 0 <= b < d; first Smith invariant
e_1 = gcd(a,b,d); ambient action gamma . L = gamma L.  All exact integers.

Claim under attack (R0040):
  (i)   Phi(L) = (e_1(L), (1/e_1)L) is a bijection from index-m sublattices
        onto the disjoint union over c^2 | m of cyclic index-(m/c^2)
        sublattices, with inverse (c, L') -> c L'.
  (ii)  In Hermite coordinates the divided basis ((a/c,0),(b/c,d/c)) is
        already reduced: b, d are distinct multiples of c with b < d, so
        b <= d - c and 0 <= b/c <= d/c - 1.
  (iii) Fiberwise #{L : e_1(L) = c} = psi(m/c^2); refines
        sigma_1(m) = sum_{c^2|m} psi(m/c^2).
  (iv)  Phi is SL_2(Z)-equivariant: e_1(gamma L) = e_1(L),
        (1/c)(gamma L) = gamma ((1/c) L).
  (v)   S(m) = sum_L e_1(L) = sum_{c^2|m} c psi(m/c^2)
             = sum_{c^2|m} phi(c) sigma_1(m/c^2),
        multiplicative, S(p^k) = (p^{k+1}+p^k-p^{ceil(k/2)}-p^{floor(k/2)})/(p-1),
        Dirichlet series zeta(s) zeta(s-1) zeta(2s-1) / zeta(2s);
        not a standard sigma-variant, first diverging from all at m = 4.
"""

from math import gcd, isqrt

from hecke_coset_smith_assembly import (
    divisors,
    sigma1,
    psi,
    hnf_bases,
    content,
    cyclic_bases,
    mat_mul,
    det2,
)


# ---------------------------------------------------------------------------
# elementary multiplicative functions (independent implementations)
# ---------------------------------------------------------------------------

def factorize(n):
    out = []
    p = 2
    while p * p <= n:
        if n % p == 0:
            k = 0
            while n % p == 0:
                n //= p
                k += 1
            out.append((p, k))
        p += 1
    if n > 1:
        out.append((n, 1))
    return out


def phi(n):
    result = n
    for p, _ in factorize(n):
        result = result // p * (p - 1)
    return result


def sigma_k(n, k):
    return sum(d ** k for d in divisors(n))


def jordan2(n):
    """Jordan totient J_2(n) = n^2 prod_{p|n} (1 - 1/p^2), exactly."""
    result = n * n
    for p, _ in factorize(n):
        result = result // (p * p) * (p * p - 1)
    return result


def square_divisor_roots(m):
    """All c >= 1 with c^2 | m."""
    return [c for c in range(1, isqrt(m) + 1) if m % (c * c) == 0]


# ---------------------------------------------------------------------------
# independent canonical HNF from arbitrary generating columns
# ---------------------------------------------------------------------------

def hnf_of_columns(cols):
    """Canonical Hermite basis ((a,0),(b,d)) of the lattice generated by the
    given list of integer column vectors (must have full rank).  Pure
    integer column operations (right GL_2(Z) action fixes the lattice)."""
    cols = [list(c) for c in cols]
    # fold everything into two columns by repeated gcd elimination on row 0
    work = [c for c in cols if c != [0, 0]]
    assert work, "zero lattice"
    # eliminate row-0 entries down to a single column with nonzero row 0
    # using pairwise Euclid; keep all columns (they still generate).
    changed = True
    while changed:
        changed = False
        # pick pivot: nonzero minimal |row0|
        piv = None
        for i, c in enumerate(work):
            if c[0] != 0 and (piv is None or abs(c[0]) < abs(work[piv][0])):
                piv = i
        assert piv is not None, "rank < 2 in row 0? not full rank"
        for i, c in enumerate(work):
            if i != piv and c[0] != 0:
                q = c[0] // work[piv][0]
                c[0] -= q * work[piv][0]
                c[1] -= q * work[piv][1]
                changed = True
    first = work.pop(piv)
    # remaining columns have row0 == 0; reduce their row 1 to one gcd
    g = 0
    for c in work:
        assert c[0] == 0
        g = gcd(g, c[1])
    assert g != 0, "not full rank"
    a, b = first[0], first[1]
    d = g
    if a < 0:
        a, b = -a, -b
    if d < 0:
        d = -d
    b %= d
    return ((a, 0), (b, d))


def basis_columns(basis):
    """Columns (a,b) and (0,d) of Hermite basis ((a,0),(b,d))."""
    (a, _), (b, d) = basis
    return [(a, b), (0, d)]


def scale_basis(basis, c):
    (a, _), (b, d) = basis
    return ((c * a, 0), (c * b, c * d))


def divide_basis(basis, c):
    (a, _), (b, d) = basis
    assert a % c == 0 and b % c == 0 and d % c == 0
    return ((a // c, 0), (b // c, d // c))


def index_of(basis):
    (a, _), (b, d) = basis
    return a * d


def is_reduced_hnf(basis):
    (a, _), (b, d) = basis
    return a >= 1 and d >= 1 and 0 <= b < d


# ---------------------------------------------------------------------------
# direct (HNF-free) sublattice enumeration for small m, as ground truth
# ---------------------------------------------------------------------------

def sublattices_direct(m):
    """All index-m sublattices of Z^2, enumerated WITHOUT Hermite theory:
    every such L contains m Z^2, so L <-> subgroup of (Z/m)^2 of order m.
    Brute-force subgroup generation over all generator pairs; each lattice
    is returned as its canonical HNF computed by hnf_of_columns from the
    lifted generators plus (m,0),(0,m)."""
    n = m
    elems = [(x, y) for x in range(n) for y in range(n)]
    lattices = set()
    for v in elems:
        for w in elems:
            # generate subgroup <v, w> (no pruning: pairs inside a large
            # subgroup generate SUB-subgroups, so any pair-level dedup
            # across groups is unsound)
            group = {(0, 0)}
            frontier = [(0, 0)]
            while frontier:
                g0 = frontier.pop()
                for h in (v, w):
                    ng = ((g0[0] + h[0]) % n, (g0[1] + h[1]) % n)
                    if ng not in group:
                        group.add(ng)
                        frontier.append(ng)
            if len(group) == m:  # index m^2/m = m in (Z/m)^2 -> index m in Z^2
                cols = [list(g) for g in group] + [[m, 0], [0, m]]
                lattices.add(hnf_of_columns(cols))
    return lattices


# ---------------------------------------------------------------------------
# the map Phi and its inverse (independent implementation)
# ---------------------------------------------------------------------------

def phi_map(basis):
    """Phi(L) = (e_1, canonical HNF of (1/e_1) L), computed WITHOUT the
    claimed always-reduced shortcut: divide the columns and re-canonicalize
    from scratch with hnf_of_columns."""
    c = content(basis)
    cols = basis_columns(basis)
    divided = [(x // c, y // c) for (x, y) in cols]
    return c, hnf_of_columns(divided)


def phi_inverse(c, cyclic_basis):
    """(c, L') -> c L', re-canonicalized independently."""
    cols = [(c * x, c * y) for (x, y) in basis_columns(cyclic_basis)]
    return hnf_of_columns(cols)


# ---------------------------------------------------------------------------
# the moment S(m): three routes
# ---------------------------------------------------------------------------

def S_direct(m):
    return sum(content(basis) for basis in hnf_bases(m))


def S_c_psi(m):
    return sum(c * psi(m // (c * c)) for c in square_divisor_roots(m))


def S_phi_sigma(m):
    return sum(phi(c) * sigma1(m // (c * c)) for c in square_divisor_roots(m))


def S_prime_power_closed(p, k):
    num = p ** (k + 1) + p ** k - p ** ((k + 1) // 2) - p ** (k // 2)
    assert num % (p - 1) == 0
    return num // (p - 1)


def S_multiplicative(m):
    result = 1
    for p, k in factorize(m):
        result *= S_prime_power_closed(p, k)
    return result


# ---------------------------------------------------------------------------
# bivariate polynomial arithmetic over Z, variables (p, x), for the
# Euler-factor identity — dict {(i, j): coeff} meaning coeff * p^i x^j
# ---------------------------------------------------------------------------

def poly_mul(f, g):
    out = {}
    for (i1, j1), c1 in f.items():
        for (i2, j2), c2 in g.items():
            key = (i1 + i2, j1 + j2)
            out[key] = out.get(key, 0) + c1 * c2
    return {k: v for k, v in out.items() if v != 0}


def poly_sub(f, g):
    out = dict(f)
    for k, v in g.items():
        out[k] = out.get(k, 0) - v
    return {k: v for k, v in out.items() if v != 0}


ONE = {(0, 0): 1}
X = {(0, 1): 1}
P = {(1, 0): 1}
PX = {(1, 1): 1}
PX2 = {(1, 2): 1}
P2X3 = {(2, 3): 1}

# Euler factors at a prime p, x = p^{-s}:
#   zeta(s)    -> 1/(1-x)
#   zeta(s-1)  -> 1/(1-px)
#   zeta(2s-1) -> 1/(1-px^2)
#   1/zeta(2s) -> (1-x^2)
# claimed factor of the quotient: (1+x)/((1-px)(1-px^2))
ONE_MINUS_X = poly_sub(ONE, X)
ONE_PLUS_X = {(0, 0): 1, (0, 1): 1}
ONE_MINUS_X2 = poly_sub(ONE, {(0, 2): 1})
ONE_MINUS_PX = poly_sub(ONE, PX)
ONE_MINUS_PX2 = poly_sub(ONE, PX2)


def S_pk_polynomial(k):
    """S(p^k) as an exact polynomial in Z[p] (dict {i: coeff} for p^i),
    from the c-psi sum with symbolic psi(p^t) = p^t + p^{t-1} (t>=1),
    psi(1) = 1 — my own derivation route, no closed form used."""
    out = {}
    for j in range(k // 2 + 1):
        t = k - 2 * j
        if t == 0:
            terms = {0: 1}
        else:
            terms = {t: 1, t - 1: 1}
        for i, c in terms.items():
            out[i + j] = out.get(i + j, 0) + c
    return {i: c for i, c in out.items() if c != 0}


def S_pk_closed_polynomial(k):
    """The claimed closed form (p^{k+1}+p^k-p^{ceil(k/2)}-p^{floor(k/2)})/(p-1)
    as an exact polynomial in Z[p], via exact univariate division."""
    num = {}
    for i, c in ((k + 1, 1), (k, 1), ((k + 1) // 2, -1), (k // 2, -1)):
        num[i] = num.get(i, 0) + c  # additive build: exponents can collide
    num = {i: c for i, c in num.items() if c != 0}
    # divide by (p - 1) exactly
    quo = {}
    rem = dict(num)
    while rem:
        deg = max(rem)
        if deg == 0:
            break
        c = rem[deg]
        quo[deg - 1] = quo.get(deg - 1, 0) + c
        rem[deg - 1] = rem.get(deg - 1, 0) + c
        del rem[deg]
        rem = {i: v for i, v in rem.items() if v != 0}
    assert not rem, "not divisible by (p-1): %r" % rem
    return quo
