#!/usr/bin/env python3
"""Smallest two-term chain subcomplex generated by degree-one payloads."""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction

Vector = tuple[Fraction, ...]
Matrix = tuple[tuple[Fraction, ...], ...]


def qvector(values) -> Vector:
    return tuple(Fraction(x) for x in values)


def qmatrix(rows) -> Matrix:
    return tuple(qvector(row) for row in rows)


def rank(vectors: tuple[Vector, ...]) -> int:
    if not vectors:
        return 0
    work = [list(row) for row in vectors]
    rows, columns, found = len(work), len(work[0]), 0
    for column in range(columns):
        pivot = next((i for i in range(found, rows) if work[i][column]), None)
        if pivot is None:
            continue
        work[found], work[pivot] = work[pivot], work[found]
        scale = work[found][column]
        work[found] = [x / scale for x in work[found]]
        for i in range(rows):
            if i != found and work[i][column]:
                scale = work[i][column]
                work[i] = [x - scale * y for x, y in zip(work[i], work[found])]
        found += 1
    return found


def apply(matrix: Matrix, vector: Vector) -> Vector:
    return tuple(sum(row[j] * vector[j] for j in range(len(vector)))
                 for row in matrix)


@dataclass(frozen=True)
class ChainPayloadClosure:
    degree_one_generators: tuple[Vector, ...]
    forced_boundaries: tuple[Vector, ...]
    degree_one_rank: int
    degree_zero_rank: int
    ungraded_payload_rank: int

    @property
    def chain_carrier_dimension(self) -> int:
        return self.degree_one_rank + self.degree_zero_rank

    def candidate_is_subcomplex(self, degree_zero_generators: tuple[Vector, ...]) -> bool:
        base_rank = rank(degree_zero_generators)
        return all(rank(degree_zero_generators + (boundary,)) == base_rank
                   for boundary in self.forced_boundaries)


def compile_chain_payload(
    differential: Matrix, degree_one_generators: tuple[Vector, ...]
) -> ChainPayloadClosure:
    if not differential or not differential[0]:
        raise ValueError("differential must be a nonempty matrix")
    width = len(differential[0])
    if any(len(row) != width for row in differential):
        raise ValueError("differential is ragged")
    if any(len(vector) != width for vector in degree_one_generators):
        raise ValueError("degree-one generator has wrong dimension")
    boundaries = tuple(apply(differential, vector)
                       for vector in degree_one_generators)
    return ChainPayloadClosure(
        degree_one_generators, boundaries, rank(degree_one_generators),
        rank(boundaries), int(rank(degree_one_generators) > 0),
    )


def interval_edge() -> ChainPayloadClosure:
    # C1=<e>, C0=<v0,v1>, d(e)=v1-v0.
    return compile_chain_payload(qmatrix(((-1,), (1,))), (qvector((1,)),))


def loop_edge() -> ChainPayloadClosure:
    # One vertex, one loop edge, d(e)=0.
    return compile_chain_payload(qmatrix(((0,),)), (qvector((1,)),))


if __name__ == "__main__":
    print({"interval": interval_edge(), "loop": loop_edge()})
    print("ALL EXACT CHECKS PASS")
