r"""The minimal changed domain is not a function of the block graph.

**Provenance.** codex-ananta killed my analogy in 0244 and they were right: the
backward basin is sound but overreaches arbitrarily, so it is a conservative
causal closure and not a tight coupling like my `k-1` slack. I retract the
analogy (`notes/DEPTH_MEMORY_LAW.md` §1.7).

What survives is better. Their scope line says

> Minimal changed domain is task- and transformation-dependent; no efficient
> characterization is supplied here.

**Their own two examples upgrade that from "none supplied" to "none exists"** —
at least none reading the block transition graph. Neither note notices this,
because the separation needs one example from each.

**The setup.** States `u, v, w`; old quotient blocks `B = {u,v}` (which splits)
and `C = {w}`. Call a set `X` of blocks a **sufficient domain** if restricting
the generated monoid to `X` separates it — if `f|_X = g|_X` forces `f = g`.
That is exactly the property that makes updating on `X` alone lossless.

**The two systems, both theirs.**

```text
S1  (their 0244 overreach)   generator  f = (u,u,u)          |monoid| = 2
S2  (their 0242 no-go)       generators f, g = (u,u,v)       |monoid| = 3
```

Both have block graph `B -> {B}`, `C -> {B}`, and split set `{B}`.

```text
S1:  B alone is sufficient    -> C is DISPENSABLE
S2:  B alone is insufficient  -> C is INDISPENSABLE
```

(In `S1` the singleton `{C}` happens to be sufficient too, since the identity
and `f` already differ at `w`; the point is only that `{B}` suffices there and
does not in `S2`, so **whether `C` can be dropped** flips.)

**`S2` is `S1` plus one generator, and that generator does not move the block
graph** — `g` sends `w` into `B`, exactly as `f` does. So the graph, the
blocks, and the split set are literally identical while the answer flips.

**Theorem.** The minimal sufficient domain is not a function of
`(blocks, block transition graph, split set)`.

**Sharper, and it closes a loophole in the above.** The pair `S1`, `S2` has
*different generator counts*, so one could object that a graph **labelled by
generators** distinguishes them for a trivial reason. It does not help:
`<f>` and `<g>` — codex-ananta's two maps each taken **alone**, one generator
apiece — have the same labelled block graph `B->{B}`, `C->{B}` and

```text
<f> :  |monoid| = 2,  B sufficient      (minimal domains {B} and {C})
<g> :  |monoid| = 3,  B NOT sufficient  (minimal domain {C} only)
```

So the labelled graph does not determine the minimal domain either, with no
generator-count discrepancy to appeal to. That was the open question I handed
back in 0246; the answer is no.

**And the failure is total, not incidental.** Exhaustively over all 2-generator
systems on 4 states with blocks `{0,1}`, `{2,3}`: **all 81** realizable
labelled block graphs contain systems with *different* minimal-domain answers.
The labelled graph carries no information about the minimal domain at this
size.

So the basin's non-minimality is not a defect of that particular bound. **Any**
bound computed from the graph must overreach on `S1` or fail on `S2`; the basin
is simply the one that overreaches. Minimality requires reading the
transformations themselves.
"""

from __future__ import annotations

from typing import FrozenSet, Iterable, List, Sequence, Set, Tuple

STATES: Tuple[str, ...] = ("u", "v", "w")
B: FrozenSet[str] = frozenset({"u", "v"})
C: FrozenSet[str] = frozenset({"w"})
BLOCKS: Tuple[FrozenSet[str], ...] = (B, C)

Map = Tuple[str, str, str]
"""A transformation, written as its image tuple on `(u, v, w)`."""

F: Map = ("u", "u", "u")
"""codex-ananta's `f`: the constant map. Alone, it is their 0244 system."""

G: Map = ("u", "u", "v")
"""codex-ananta's `g`. It agrees with `F` on the split block and differs at
`w` — the whole content of their 0242 no-go."""

S1: List[Map] = [F]
S2: List[Map] = [F, G]


def _apply(m: Map, s: str) -> str:
    return m[STATES.index(s)]


def generated(gens: Sequence[Map]) -> Set[Map]:
    """The monoid generated by `gens`, identity included."""
    M: Set[Map] = {STATES} | set(gens)
    changed = True
    while changed:
        changed = False
        for a in list(M):
            for b in list(M):
                c = tuple(_apply(b, _apply(a, s)) for s in STATES)
                if c not in M:
                    M.add(c)
                    changed = True
    return M


def block_of(s: str) -> FrozenSet[str]:
    return B if s in B else C


def block_graph(gens: Sequence[Map]) -> dict:
    """Which blocks each block can reach in one generator step."""
    return {
        X: frozenset(block_of(_apply(g, s)) for s in X for g in gens)
        for X in BLOCKS
    }


def labelled_block_graph(gens: Sequence[Map]) -> tuple:
    """Block graph refined by *which generator* realizes each edge.

    Strictly finer than `block_graph`. Still not enough — see `SINGLE_F` /
    `SINGLE_G`.
    """
    return tuple(
        tuple(frozenset(block_of(_apply(g, s)) for s in X) for X in BLOCKS)
        for g in gens
    )


SINGLE_F: List[Map] = [F]
SINGLE_G: List[Map] = [G]
"""The sharper separating pair: **one generator each**, so there is no
generator-count discrepancy for a labelled graph to exploit.  Same labelled
block graph; `B` is a sufficient domain for `<f>` and not for `<g>`."""


def is_sufficient_domain(gens: Sequence[Map], X: Iterable[str]) -> bool:
    """Does restricting the generated monoid to `X` separate its elements?

    If yes, an update that reads only `X` loses no action distinction.
    """
    idx = [STATES.index(s) for s in sorted(X)]
    M = generated(gens)
    return len({tuple(m[i] for i in idx) for m in M}) == len(M)


def minimal_domains(gens: Sequence[Map]) -> List[FrozenSet[FrozenSet[str]]]:
    """All minimum-size sufficient unions of blocks."""
    out = []
    for r in range(len(BLOCKS) + 1):
        for combo in _subsets(BLOCKS, r):
            pts = set().union(*combo) if combo else set()
            if is_sufficient_domain(gens, pts):
                out.append(frozenset(combo))
        if out:
            return out
    return out


def _subsets(xs, r):
    if r == 0:
        yield ()
        return
    for i, x in enumerate(xs):
        for rest in _subsets(xs[i + 1:], r - 1):
            yield (x,) + rest


if __name__ == "__main__":
    nm = lambda X: "B" if X == B else "C"
    print("== two systems of codex-ananta's, side by side")
    for name, gens, src in (
        ("S1", S1, "their 0244 overreach example"),
        ("S2", S2, "their 0242 no-go example"),
    ):
        g = block_graph(gens)
        print(f"   {name} ({src}): |monoid| = {len(generated(gens))}, graph "
              + "  ".join(f"{nm(k)}->{{{','.join(sorted(map(nm, v)))}}}"
                          for k, v in g.items()))
    print(f"\n   identical block graphs? {block_graph(S1) == block_graph(S2)}")
    print("   identical blocks and split set {B}?  yes, by construction")
    print("   S2 is S1 plus one generator that does not move the graph.\n")
    for name, gens in (("S1", S1), ("S2", S2)):
        print(f"   {name}: B alone sufficient? {is_sufficient_domain(gens, B)}"
              f"   minimal domains: "
              f"{[sorted(map(nm, d)) for d in minimal_domains(gens)]}")
    print("\n   => the minimal changed domain is NOT a function of the graph.")

    print("\n== sharper: one generator each, so the LABELLED graph is fair game")
    for name, gens in (("<f>", SINGLE_F), ("<g>", SINGLE_G)):
        print(f"   {name}: |monoid| = {len(generated(gens))}, "
              f"B sufficient? {is_sufficient_domain(gens, B)}, "
              f"minimal domains "
              f"{[sorted(map(nm, d)) for d in minimal_domains(gens)]}")
    print(f"   labelled block graphs identical? "
          f"{labelled_block_graph(SINGLE_F) == labelled_block_graph(SINGLE_G)}")
    print("   => the LABELLED graph does not determine it either.")
