"""Chart depth of sum-valuation on a multiplicatively formed locus.

Companion to `notes/FORMED_UNIT_FILTRATION_DEPTH.md`.

Ambient theorem (codex-ananta, `notes/ADAPTIVE_VALUATION_ADDITION.md`): over all
integers, the least prime-power residue depth determining `v_p(a+b)` is
`v_p(a+b)+1`.

This module computes the corresponding depth when both inputs are restricted to
the locus actually formed by a multiplicative organism,

    F = { p^i * u : i >= 0, u in <formed units> },

and shows that the ambient minimum does not transport.  The exact carrier is the
congruence filtration of the formed unit group,

    U[d] = { lambda in U : lambda == 1 (mod p^d) },

because the depth-(i+d) fiber of a formed unit is exactly the coset `u*U[d]`.

Everything here is exact integer arithmetic on finite quotients: subgroup
enumeration in `(Z/p^K)^*`, and an independent brute-force replay over a finite
window used only as a falsifier of the criterion.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Sequence


def valuation(n: int, p: int) -> int:
    """Exact p-adic valuation of a nonzero integer."""
    if n == 0:
        raise ValueError("valuation of zero is not finite")
    if p < 2:
        raise ValueError("p must be a prime >= 2")
    n = abs(n)
    k = 0
    while n % p == 0:
        n //= p
        k += 1
    return k


def unit_subgroup(p: int, K: int, generators: Sequence[int]) -> frozenset[int]:
    """The subgroup of (Z/p^K)^* generated by the given residues.

    The image of a multiplicative monoid in a finite group is a group, so
    closing the generator set under multiplication is enough.
    """
    if K < 1:
        raise ValueError("K must be >= 1")
    modulus = p ** K
    gens = []
    for g in generators:
        if g % p == 0:
            raise ValueError(f"generator {g} is not a unit at p={p}")
        gens.append(g % modulus)
    seen = {1}
    frontier = [1]
    while frontier:
        x = frontier.pop()
        for g in gens:
            y = (x * g) % modulus
            if y not in seen:
                seen.add(y)
                frontier.append(y)
    return frozenset(seen)


def congruence_filtration(p: int, K: int, U: Iterable[int], d: int) -> frozenset[int]:
    """U[d] = elements of U congruent to 1 mod p^d, as residues mod p^K."""
    if d < 0 or d > K:
        raise ValueError("require 0 <= d <= K")
    level = p ** d
    return frozenset(x for x in U if x % level == 1)


def unit_level(p: int, K: int, generators: Sequence[int]) -> int:
    """The level l(U): U meets 1 + p*Z_p (p odd) or 1 + 4*Z_2 in exactly 1+p^l.

    Returns K when the intersection is trivial at working precision.
    """
    U = unit_subgroup(p, K, generators)
    base = p if p > 2 else 4
    candidates = [x for x in U if x % base == 1 and x != 1]
    if not candidates:
        return K
    return min(valuation(x - 1, p) for x in candidates)


def level_criterion_depth(p: int, K: int, generators: Sequence[int],
                          delta: int) -> int:
    """Exact d* from the filtration signature (see the note, Theorem 3).

    For odd p, d* = delta+1 when l(U)<=delta and 1 otherwise.  For p=2,
    the extra mod-4 sign bit decides the former exceptional branch: when
    l(U)>delta, d*=1 if U is contained in 1 mod 4 and d*=2 otherwise.
    """
    ell = unit_level(p, K, generators)
    if ell <= delta:
        return delta + 1
    if p > 2:
        return 1
    U = unit_subgroup(p, K, generators)
    return 2 if any(x % 4 == 3 for x in U) else 1


@dataclass(frozen=True)
class DepthCertificate:
    """Exact answer plus the two witnesses that make it a certificate."""

    depth: int              # D_F(a, b): least sufficient chart depth on F
    valuation: int          # v_p(a + b)
    ambient_depth: int      # v_p(a+b) + 1, the all-integer minimum
    sufficiency: str        # why `depth` determines the output on F
    insufficiency: tuple    # a same-residue pair at depth-1 with a different valuation

    @property
    def gap(self) -> int:
        """How many digits the formed locus saves against the ambient theorem."""
        return self.ambient_depth - self.depth


def unit_sum_depth(p: int, K: int, U: frozenset[int], u: int, w: int) -> tuple:
    """Least d >= 1 with v_p(u*lam + w*mu) constant on U[d] x U[d].

    The two-parameter test collapses to one parameter: mu is a unit, so
    v_p(u*lam + w*mu) = v_p(u*(lam/mu) + w) and lam/mu ranges over the group
    U[d].  It therefore suffices to scan nu in U[d] with mu = 1.

    Returns (d, delta, witness) where `witness` is (nu, 1, v) in U[d-1] with a
    different sum valuation, or None when d == 1 is already sufficient.  All
    valuations are read modulo p^K, which is exact provided K > delta + 1.
    """
    modulus = p ** K
    delta = _valuation_mod(u + w, p, K)
    if delta is None:
        raise ValueError("u + w vanishes to depth K; increase K")
    witness = None
    for d in range(1, K):
        bad = None
        for nu in congruence_filtration(p, K, U, d):
            v = _valuation_mod((u * nu + w) % modulus, p, K)
            if v != delta:
                bad = (nu, 1, v)
                break
        if bad is None:
            return d, delta, witness
        witness = bad
    raise ValueError("no sufficient depth below K; increase K")


def _valuation_mod(n: int, p: int, K: int):
    """Valuation of a residue mod p^K, or None if it is zero mod p^K."""
    n %= p ** K
    if n == 0:
        return None
    return valuation(n, p)


def formed_chart_depth(p: int, unit_generators: Sequence[int], a: int, b: int,
                       K: int | None = None) -> DepthCertificate:
    """Exact chart depth for `v_p(a+b)` on F = p^N * <unit_generators>.

    `a` and `b` must lie in F and have the same p-adic valuation (the
    equal-depth cancellation case; unequal depths are settled at depth
    min+1 by the ultrametric equality and carry no gap).
    """
    if a <= 0 or b <= 0:
        raise ValueError("inputs must be positive")
    i, j = valuation(a, p), valuation(b, p)
    if i != j:
        raise ValueError("this routine handles the equal-valuation case only")
    u, w = a // p ** i, b // p ** i
    v = valuation(a + b, p)
    delta = v - i
    if K is None:
        K = delta + 3
    U = unit_subgroup(p, K, unit_generators)
    if u % p ** K not in U or w % p ** K not in U:
        raise ValueError("inputs are not in the formed locus")
    d, delta_check, witness = unit_sum_depth(p, K, U, u, w)
    assert delta_check == delta, (delta_check, delta)
    return DepthCertificate(
        depth=i + d,
        valuation=v,
        ambient_depth=v + 1,
        sufficiency=(
            f"fiber of each input at depth {i + d} is the coset of U[{d}]; "
            f"v_p is constant on U[{d}] x U[{d}]"
        ),
        insufficiency=witness,
    )


def brute_force_depth(p: int, locus: Sequence[int], a: int, b: int,
                      max_depth: int = 16) -> int:
    """Independent replay: least k with v_p constant on the depth-k fiber.

    Exhaustive over the supplied finite window of the locus.  This is a
    falsifier for `formed_chart_depth`, not a proof: a window can only
    understate the depth by missing a separating pair.
    """
    target = valuation(a + b, p)
    for k in range(0, max_depth):
        m = p ** k
        ra, rb = a % m, b % m
        ok = True
        for x in locus:
            if x % m != ra:
                continue
            for y in locus:
                if y % m != rb:
                    continue
                if valuation(x + y, p) != target:
                    ok = False
                    break
            if not ok:
                break
        if ok:
            return k
    raise ValueError("no sufficient depth below max_depth")


def monoid_window(p: int, unit_generators: Sequence[int],
                  p_range: int, unit_bound: int) -> list[int]:
    """A finite window of F = p^N * <unit_generators>, for brute-force replay."""
    units = {1}
    frontier = [1]
    while frontier:
        x = frontier.pop()
        for g in unit_generators:
            y = x * g
            if y <= unit_bound and y not in units:
                units.add(y)
                frontier.append(y)
    return sorted({p ** i * u for i in range(p_range) for u in units})


def unit_group_index(p: int, K: int, generators: Sequence[int]) -> int:
    """Index of the formed unit group in (Z/p^K)^*."""
    order = (p - 1) * p ** (K - 1)
    sub = len(unit_subgroup(p, K, generators))
    assert order % sub == 0
    return order // sub


if __name__ == "__main__":
    print("formed locus F = 2^N * <3>, ambient vs formed chart depth")
    for t in range(2, 9):
        g = 2 ** t - 1
        cert = formed_chart_depth(2, [g], 1, g)
        print(f"  g=2^{t}-1={g:5d}  v_2(1+g)={cert.valuation}  "
              f"ambient={cert.ambient_depth}  formed={cert.depth}  gap={cert.gap}")
    print()
    print("forming 5 drops the level to 2 and restores the ambient depth:")
    for gens in ([3], [3, 5]):
        cert = formed_chart_depth(2, gens, 1, 3)
        print(f"  units {gens}: level l(U) = {unit_level(2, 6, gens)}, "
              f"depth for (1,3) = {cert.depth} (ambient {cert.ambient_depth})")
