#!/usr/bin/env python3
"""The living machine, self-hosted.

There is one law (descent: an observable descends or forms) and one
evaluator.  Everything else is the machine's own data:

- An observable is a TERM in the machine's own language, not a Python
  function.  Terms: ("entry",i,j) ("det",) ("gcd",t,t) ("mod",t,c)
  ("abs",t) ("sign",t) ("valli",t,t) ("pair",t,t).
- The GENOME is the list of installed terms.  Formation events install
  terms; the genome is persisted machine-readable state — the machine can
  be read, resumed, and extended entirely through its own objects.
- The FRONTIER is generated by the machine from its genome: compositions
  of installed terms under its own grammar, with moduli drawn from the
  VALUE POOL — constants the machine itself has observed.  Nothing is
  hand-fed after birth; the seed genome is entries and determinant.

Python is only the evaluator underneath — the CPU.  Exact integers
throughout; append-only log; state survives restarts.

Run:  python3 living_machine.py [max_shells]
"""

import json
import os
import sys
from itertools import product
from math import gcd

from descent_formation_machine import DescentMachine
from kuttaka_pulverizer import pulverize

HERE = os.path.dirname(os.path.abspath(__file__))
STATE = os.path.join(HERE, "..", "runtime", "LIVING_STATE.json")
LOG = os.path.join(HERE, "..", "runtime", "LIVING_RUN.log")


# ---- the evaluator: the only code-level meaning --------------------------

def ev(term, s):
    m, h = s
    op = term[0]
    if op == "entry":
        return m[term[1]][term[2]]
    if op == "hentry":
        bits = PORT_BITS[0]
        return h[term[1]][term[2]] % (1 << bits) if bits else 0
    if op == "det":
        return m[0][0] * m[1][1] - m[0][1] * m[1][0]
    if op == "gcd":
        return gcd(ev(term[1], s), ev(term[2], s))
    if op == "mod":
        return ev(term[1], s) % term[2]
    if op == "abs":
        return abs(ev(term[1], s))
    if op == "sign":
        v = ev(term[1], s)
        return 0 if v == 0 else (1 if v > 0 else -1)
    if op == "valli":
        a, b = ev(term[1], s), ev(term[2], s)
        if a == 0 and b == 0:
            return -1
        return len(pulverize(a, b)[0])
    if op == "pair":
        return (ev(term[1], s), ev(term[2], s))
    raise ValueError(f"unknown term {term}")


def show(term):
    if term[0] == "entry":
        return f"e{term[1]}{term[2]}"
    if term[0] == "hentry":
        return f"h{term[1]}{term[2]}"
    if term[0] == "det":
        return "det"
    if term[0] == "mod":
        return f"({show(term[1])} mod {term[2]})"
    if term[0] in ("abs", "sign"):
        return f"{term[0]}({show(term[1])})"
    return f"{term[0]}({show(term[1])},{show(term[2])})"


def depth(term):
    if term[0] in ("entry", "hentry", "det"):
        return 1
    if term[0] == "mod":
        return 1 + depth(term[1])
    if term[0] in ("abs", "sign"):
        return 1 + depth(term[1])
    return 1 + max(depth(term[1]), depth(term[2]))


# ---- the machine's own frontier ------------------------------------------

SEED = [("det",)]  # born dim: coordinates must be earned as formations
ENTRIES = [("entry", 0, 0), ("entry", 0, 1), ("entry", 1, 0),
           ("entry", 1, 1)]
HENTRIES = [("hentry", 0, 0), ("hentry", 0, 1), ("hentry", 1, 0),
            ("hentry", 1, 1)]
BUDGET = 12  # attention per shell: offers are a resource, order is policy
PORT_EVERY = 4  # the ecology grants one fiber port every few shells

# the hidden fiber: unimodular payloads paired with every matrix.  The
# family DEEPENS with the epoch, and ports expose it one BIT at a time:
# hentry sees h mod 2^bits.  Each saturation is a wall; each wall demands
# the next bit; fiber growth keeps higher bits informative — the format
# lattice as an unending developmental ladder.
def h_family(epoch):
    """Shears with entries up to 2^epoch: fiber depth outruns granted
    bits exponentially, so walls recur at every epoch forever."""
    K = 1 << epoch
    out = [((1, 0), (0, 1)), ((0, 1), (-1, 0)), ((1, 0), (0, -1))]
    for k in range(1, K + 1):
        out.append(((1, k), (0, 1)))
        out.append(((1, -k), (0, 1)))
        out.append(((1, 0), (k, 1)))
        out.append(((1, 0), (-k, 1)))
        if len(out) >= 3 + 8 * (1 + epoch):
            break
    return out

H_SET = h_family(0)  # rebound each epoch in live()


PORTED = [False]
PORT_BITS = [0]


def frontier(genome, value_pool, max_new=48, max_depth=4):
    """Terms the machine proposes to itself: compositions over its
    building material (earned genome plus raw coordinates it may yet
    earn), moduli from its own observed values.  Shallow terms first:
    parsimony is the proposal order."""
    have = {json.dumps(t) for t in genome}
    out = []

    def offer(t):
        key = json.dumps(t)
        if key not in have and depth(t) <= max_depth and len(out) < max_new:
            have.add(key)
            out.append(t)

    ported = HENTRIES if PORTED[0] else []
    blocks = [t for t in list(genome) + ENTRIES + ported
              if depth(t) <= max_depth - 1]
    for t in ENTRIES + ported:
        offer(t)  # coordinates are proposable, never given
    for t in blocks:
        for c in value_pool:
            offer(("mod", t, c))
        offer(("abs", t))
        offer(("sign", t))
    for i, t1 in enumerate(blocks):
        for t2 in blocks[i:]:
            offer(("gcd", t1, t2))
            offer(("valli", t1, t2))
    out.sort(key=depth)
    return out


# ---- persistence ---------------------------------------------------------

def load_state():
    if os.path.exists(STATE):
        with open(STATE) as fh:
            s = json.load(fh)
            if s.get("version") == 2:
                s["genome"] = [tuple_term(t) for t in s["genome"]]
                return s
    return {"version": 2, "shell": 1, "genome": list(SEED),
            "value_pool": [2, 3], "events": 0, "ported": False}


def tuple_term(t):
    return tuple(tuple_term(x) if isinstance(x, list) else x for x in t)


def save_state(state):
    os.makedirs(os.path.dirname(STATE), exist_ok=True)
    with open(STATE, "w") as fh:
        json.dump(state, fh)


def log(line):
    os.makedirs(os.path.dirname(LOG), exist_ok=True)
    with open(LOG, "a") as fh:
        fh.write(line + "\n")


# ---- the life ------------------------------------------------------------

def shell(bound):
    for entries in product(range(-bound, bound + 1), repeat=4):
        if max(abs(e) for e in entries) != bound:
            continue
        m = ((entries[0], entries[1]), (entries[2], entries[3]))
        if m == ((0, 0), (0, 0)):
            continue
        for h in H_SET:
            yield (m, h)


def live(max_shells=None):
    global H_SET
    state = load_state()
    state.setdefault("bits", 0)
    state.setdefault("epoch", 0)
    while max_shells is None or state["shell"] <= max_shells:
        step = state["shell"]
        bound = 1 + (step - 1) % 5          # breadth cycles 1..5
        state["epoch"] = (step - 1) // 5    # depth grows per cycle
        H_SET = h_family(state["epoch"])
        PORTED[0] = state["bits"] > 0
        PORT_BITS[0] = state["bits"]
        universe = list(shell(bound))
        machine = DescentMachine(universe)
        formed = absorbed = 0
        observed = set()

        def offer_term(t):
            nonlocal formed, absorbed
            event = machine.offer(show(t), lambda m, _t=t: ev(_t, m))
            state["events"] += 1
            for m in universe[:200]:
                v = ev(t, m)  # m is a full state (matrix, payload)
                if isinstance(v, int) and 2 <= abs(v) <= 13:
                    observed.add(abs(v))
            if event["kind"] == "forms":
                formed += 1
                return True
            absorbed += 1
            return False

        # genome first (accumulated selfhood), then its own proposals,
        # all under the attention budget
        offers = 0
        for t in list(state["genome"]):
            if offers >= BUDGET:
                break
            offer_term(t)
            offers += 1
        for t in frontier(state["genome"], state["value_pool"]):
            if offers >= BUDGET:
                break
            if offer_term(t):
                state["genome"].append(t)
                log(f"step={step} FORMS {show(t)} "
                    f"(genome={len(state['genome'])})")
            offers += 1

        # CERTIFY: if nothing formed beyond the genome, the machine
        # proves its own wall from inside. Grammar induction: every
        # available term factors through the endpoint projection unless
        # an hentry port is granted — so the carrier can never refine
        # past the m-partition, and the residual is exactly the fiber
        # family at every state. This is a proof the machine checks, not
        # an observation it despairs of.
        if formed == len(state["genome"]):
            # saturation has two distinct terminal readings, and the
            # machine distinguishes them exactly:
            fibs = machine.fibers()
            if len(fibs) == len(universe):
                # COMPLETE: carrier discrete — the world at this depth
                # is exhausted; growth (deeper epoch), never a port.
                log(f"step={step} COMPLETE at bits={state['bits']}: "
                    f"carrier discrete on {len(universe)} states; world "
                    f"exhausted at this depth; growing.")
            else:
                # WALL: stuck strictly below discreteness — provably,
                # by grammar induction, no term sees the fiber beyond
                # the granted bits.  Demand the next bit.
                log(f"step={step} WALL CERTIFICATE at bits="
                    f"{state['bits']}: carrier fixed at {len(fibs)} "
                    f"fibers over {len(universe)} states; grammar "
                    f"induction: no term sees the fiber beyond "
                    f"{state['bits']} bit(s). Demanding the next bit.")
                state["bits"] += 1
                log(f"step={step} PORT GRANTED: bit {state['bits']} "
                    f"of the fiber coordinate becomes visible.")
        new_values = sorted(observed - set(state["value_pool"]))[:3]
        state["value_pool"] = sorted(set(state["value_pool"])
                                     | set(new_values))
        log(f"step={step} (bound={bound} epoch={state['epoch']} "
            f"bits={state['bits']}) summary: universe={len(universe)} "
            f"formed={formed} absorbed={absorbed} "
            f"fibers={len(machine.fibers())} genome={len(state['genome'])} "
            f"pool={state['value_pool']}")
        state["shell"] += 1
        save_state(state)


if __name__ == "__main__":
    limit = int(sys.argv[1]) if len(sys.argv) > 1 else None
    live(limit)
