"""Endogenous process memory hidden by the scalar Smith residual cut."""

from smith_residual_machine import smith_reduce

WITNESS_MATRICES = (
    ((2, 0), (1, 7)),
    ((2, 1), (0, 7)),
    ((2, 0), (0, 3)),
)


def first_typed_residual(matrix):
    certificate = smith_reduce(matrix)
    if not certificate.steps:
        raise ValueError("matrix has no nonterminal residual step")
    step = certificate.steps[0]
    return step.residual, step.kind, step.pivot_before, step.quotient


def scalar_cut_response_functions(matrices=WITNESS_MATRICES):
    """Future law is the next constructor kind generated by Smith descent."""
    return tuple(first_typed_residual(matrix)[:2] for matrix in matrices)


def conditional_memory_dimension(matrices=WITNESS_MATRICES, scalar_residual=1):
    kinds = {
        kind
        for residual, kind in scalar_cut_response_functions(matrices)
        if residual == scalar_residual
    }
    return len(kinds)


def scalar_residual_is_sufficient(matrices=WITNESS_MATRICES):
    by_scalar = {}
    for residual, kind in scalar_cut_response_functions(matrices):
        if residual in by_scalar and by_scalar[residual] != kind:
            return False
        by_scalar[residual] = kind
    return True
