import unittest

from machinery.finite_holonomy_compiler import (
    compile_coinvariants,
    compile_predictive_holonomy,
)
from machinery.smith_holonomy_predictive_control import carrier, element_order
from machinery.smith_path_holonomy import act, witness


class FiniteHolonomyCompilerTests(unittest.TestCase):
    def setUp(self):
        *_, self.h, _, _, _ = witness()
        self.states = carrier()
        self.permutation = {state: act(self.h, state) for state in self.states}

    def test_smith_order_task_compiles_to_four_states(self):
        result = compile_predictive_holonomy(
            self.states, {"H": self.permutation}, (element_order,)
        )
        self.assertEqual(len(result.crystal.fibers), 4)
        self.assertTrue(all(word is None or word == ()
                            for word in result.shortest_witnesses.values()))

    def test_coordinate_task_has_one_step_witness(self):
        result = compile_predictive_holonomy(
            self.states, {"H": self.permutation}, (lambda value: value[1],)
        )
        self.assertEqual(len(result.crystal.fibers), 4)
        pair = ((0, 0, 0), (0, 0, 1))
        self.assertEqual(result.shortest_witnesses[pair], ("H",))

    def test_orbit_erasure_excludes_coordinate_but_not_order(self):
        # Theta is the orbit relation generated by H.
        orbit_label = {state: min(
            state, act(self.h, state), act(self.h, act(self.h, state))
        ) for state in self.states}
        result = compile_predictive_holonomy(
            self.states, {"H": self.permutation},
            (element_order, lambda value: value[1]), theta=orbit_label,
        )
        self.assertTrue(result.erasure.is_action_congruence)
        excluded_indices = {item[0] for item in result.erasure.excluded_observations}
        self.assertEqual(excluded_indices, {1})
        # Orbit erasure and predictive minimization are different quotients:
        # the former has six fibers here, while the order task has four.
        self.assertEqual(len(result.orbit_fibers), 6)
        self.assertEqual(len(result.crystal.fibers), 8)

    def test_rejects_nonpermutation_generator(self):
        constant = {state: self.states[0] for state in self.states}
        with self.assertRaisesRegex(ValueError, "not a permutation"):
            compile_predictive_holonomy(self.states, {"bad": constant}, (element_order,))

    def test_smith_coinvariants_are_zmod_three(self):
        result = compile_coinvariants((1, 2, 6), (self.h,))
        self.assertEqual(result.invariant_factors, (1, 1, 3))
        self.assertEqual(result.determinantal_divisors, (1, 1, 1, 3))
        self.assertEqual(result.nontrivial_factors, (3,))

    def test_trivial_action_returns_original_group(self):
        identity = ((1, 0), (0, 1))
        result = compile_coinvariants((2, 6), (identity,))
        self.assertEqual(result.invariant_factors, (2, 6))

    def test_rejects_non_lattice_preserving_action(self):
        bad = ((1, 0, 0), (1, 1, 0), (0, 0, 1))
        with self.assertRaisesRegex(ValueError, "does not preserve"):
            compile_coinvariants((1, 2, 6), (bad,))


if __name__ == "__main__":
    unittest.main()
