"""The 2-adic confinement index is determined by the filtration signature.

Companion to `notes/TWO_ADIC_CONFINEMENT.md`.

`MULTIPLICATIVE_CONFINEMENT.md` proved that multiplication alone confines a held
set to the subgroup it generates, and computed the index by Gauss's index
calculus -- which needs a **cyclic** group and so covers only odd prime moduli.
Its seed 3 predicted:

    p = 2 is non-cyclic, and Theorem GG's analogue there should reproduce the
    level l(U) of my very first note.  I would be surprised if it did not, and
    that is testable.

The displayed formula holds. With `l(U)` the level of
`FORMED_UNIT_FILTRATION_DEPTH.md` (3.1),

    confinement index  =  2^(l-2)   if U meets 3 mod 4,
                          2^(l-1)   otherwise.

Cross-review sharpened the statement: `l(U)` alone determines neither quantity
in the exceptional depth-one branch. The complete shared invariant is
`(l(U), sigma(U))`, with `sigma` recording whether `U` meets `3 mod 4`.
Gauss marked this boundary himself: *Disquisitiones* art. 57 gives
the index for cyclic moduli, art. 90 treats powers of two separately.

All arithmetic exact.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence

from formed_locus_depth import unit_level


def closure_mod_two_power(generators: Sequence[int], k: int) -> frozenset[int]:
    """The subgroup of `(Z/2^k)^*` generated by the held odd numbers."""
    if k < 3:
        raise ValueError("require k >= 3, where the group is non-cyclic")
    modulus = 2 ** k
    residues = []
    for g in generators:
        if g % 2 == 0:
            raise ValueError(f"{g} is not a unit mod 2^{k}")
        residues.append(g % modulus)
    reached = {1}
    frontier = [1]
    while frontier:
        x = frontier.pop()
        for g in residues:
            y = x * g % modulus
            if y not in reached:
                reached.add(y)
                frontier.append(y)
    return frozenset(reached)


def meets_three_mod_four(subgroup: frozenset[int]) -> bool:
    """Does the subgroup leave the `1 mod 4` part?"""
    return any(x % 4 == 3 for x in subgroup)


def predicted_index(level: int, meets_three: bool) -> int:
    """Theorem II: `2^(l-2)` when the subgroup meets `3 mod 4`, else `2^(l-1)`."""
    if level < 2:
        raise ValueError("the 2-adic level is at least 2")
    return 2 ** (level - 2) if meets_three else 2 ** (level - 1)


@dataclass(frozen=True)
class TwoAdicConfinement:
    """The 2-adic reach of a held set, and the level that determines it."""

    generators: tuple
    k: int
    subgroup_order: int
    group_order: int
    index: int
    level: int
    meets_three_mod_four: bool
    predicted: int


def confinement(generators: Sequence[int], k: int) -> TwoAdicConfinement:
    """The exact index, beside the level's prediction of it."""
    subgroup = closure_mod_two_power(generators, k)
    group_order = 2 ** (k - 1)
    index = group_order // len(subgroup)
    level = unit_level(2, k, list(generators))
    meets = meets_three_mod_four(subgroup)
    return TwoAdicConfinement(
        generators=tuple(generators),
        k=k,
        subgroup_order=len(subgroup),
        group_order=group_order,
        index=index,
        level=level,
        meets_three_mod_four=meets,
        predicted=predicted_index(level, meets),
    )


def unreachable_fraction(record: TwoAdicConfinement) -> float:
    """The share of `(Z/2^k)^*` multiplication can never reach."""
    return 1 - record.subgroup_order / record.group_order


if __name__ == "__main__":
    print("p = 2: confinement is a function of level plus the mod-4 sign bit")
    print(f"  {'gens':>10} {'k':>3} {'|U|':>6} {'group':>6} {'index':>6} "
          f"{'l(U)':>5} {'3 mod 4':>8} {'predicted':>10} {'unreachable':>12}")
    for gens in ((3,), (5,), (7,), (9,), (17,), (15,), (31,), (3, 5), (3, 7)):
        for k in (6, 8, 10):
            record = confinement(gens, k)
            assert record.index == record.predicted
            print(f"  {str(gens):>10} {k:>3} {record.subgroup_order:>6} "
                  f"{record.group_order:>6} {record.index:>6} "
                  f"{record.level:>5} {str(record.meets_three_mod_four):>8} "
                  f"{record.predicted:>10} "
                  f"{unreachable_fraction(record):>11.1%}")

    print()
    print("the arc closes: the two ends of the thread share one invariant")
    for gens in ((3,), (3, 5)):
        record = confinement(gens, 8)
        print(f"  gens {str(gens):>8}: l(U) = {record.level}; "
              f"FORMED_UNIT_FILTRATION_DEPTH used it for chart depth, "
              f"here it gives index {record.index}")

    print()
    print("the 2-adic exception is Gauss's own: art. 57 gives the index for")
    print("cyclic moduli, art. 90 treats powers of two separately.")
