"""One index formula for every prime power: the p=2 exception is a parameter.

Companion to `notes/UNIFIED_CONFINEMENT_INDEX.md`.

`MULTIPLICATIVE_CONFINEMENT.md` computed the confinement index for odd primes by
Gauss's index calculus; `TWO_ADIC_CONFINEMENT.md` needed a separate argument at
`p = 2` because `(Z/2^k)^*` is not cyclic.  Seed 1 of the latter predicted that
"one formula should cover both notes rather than two".  It does.

Split the unit group into its **tame** and **wild** parts,

    (Z/p^k)^*  =  (Z/T)^*  x  (1 + T Z)/p^k,

where `T` is the least modulus making the principal-unit factor **cyclic**:
`T = p` for odd `p`, and `T = 4` for `p = 2`.  Write `l_min = v_p(T)`, so
`l_min = 1` for odd `p` and `2` for `p = 2`.  Then for any subgroup `U` with
tame index `e` and level `l` (`U cap (1+TZ) = 1 + p^l`),

    index of U  =  e * p^(l - l_min).                                  (KK)

The whole `p = 2` exception is the value of `T`, and hence of `l_min`.  Nothing
else in the formula changes.

All arithmetic exact.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence


def valuation(n: int, p: int) -> int:
    """Exact p-adic valuation of a nonzero integer."""
    if n == 0:
        raise ValueError("valuation of zero is not finite")
    n = abs(n)
    k = 0
    while n % p == 0:
        n //= p
        k += 1
    return k


def tame_modulus(p: int) -> int:
    """The least `T` making `(1 + T Z)/p^k` cyclic: `p` if odd, else `4`."""
    if p < 2:
        raise ValueError("p must be a prime at least 2")
    return p if p > 2 else 4


def minimal_level(p: int) -> int:
    """`l_min = v_p(T)`: the level of the full unit group."""
    return valuation(tame_modulus(p), p)


def unit_closure(generators: Sequence[int], p: int, k: int) -> frozenset[int]:
    """The subgroup of `(Z/p^k)^*` generated by the held numbers."""
    if k < 1:
        raise ValueError("k must be positive")
    modulus = p ** k
    residues = []
    for g in generators:
        if g % p == 0:
            raise ValueError(f"{g} is not a unit at p={p}")
        residues.append(g % modulus)
    reached = {1}
    frontier = [1]
    while frontier:
        x = frontier.pop()
        for g in residues:
            y = x * g % modulus
            if y not in reached:
                reached.add(y)
                frontier.append(y)
    return frozenset(reached)


def tame_index(subgroup: frozenset[int], p: int) -> int:
    """`e`: the index of the subgroup's image in `(Z/T)^*`."""
    T = tame_modulus(p)
    order = T - T // p              # |(Z/T)^*| = p-1 for odd p, 2 for p = 2
    image = {x % T for x in subgroup}
    if order % len(image):
        raise AssertionError("the tame image is not a subgroup")
    return order // len(image)


def level(subgroup: frozenset[int], p: int, k: int) -> int:
    """`l`: the least `v_p(x-1)` over the principal part, or `k` if trivial."""
    T = tame_modulus(p)
    principal = [x for x in subgroup if x % T == 1 and x != 1]
    if not principal:
        return k
    return min(valuation(x - 1, p) for x in principal)


@dataclass(frozen=True)
class UnifiedIndex:
    """The confinement index, and the two parameters that determine it."""

    p: int
    k: int
    generators: tuple
    subgroup_order: int
    group_order: int
    index: int
    tame_index: int
    level: int
    minimal_level: int
    predicted: int


def unified_index(generators: Sequence[int], p: int, k: int) -> UnifiedIndex:
    """(KK) checked against the enumerated index."""
    subgroup = unit_closure(generators, p, k)
    group_order = (p - 1) * p ** (k - 1)
    e = tame_index(subgroup, p)
    l = level(subgroup, p, k)
    lmin = minimal_level(p)
    return UnifiedIndex(
        p=p, k=k, generators=tuple(generators),
        subgroup_order=len(subgroup),
        group_order=group_order,
        index=group_order // len(subgroup),
        tame_index=e,
        level=l,
        minimal_level=lmin,
        predicted=e * p ** (l - lmin),
    )


def principal_part_is_cyclic(p: int, k: int) -> bool:
    """`(1 + T Z)/p^k` is cyclic; `(1 + 2 Z)/2^k` is not, which is why T = 4."""
    T = tame_modulus(p)
    modulus = p ** k
    principal = [x for x in range(1, modulus) if x % T == 1]
    target = len(principal)
    for g in principal:
        order, x = 1, g
        while x != 1:
            x = x * g % modulus
            order += 1
        if order == target:
            return True
    return target <= 1


if __name__ == "__main__":
    print("(KK)  index = e * p^(l - l_min),  T = p for odd p and 4 for p = 2")
    print(f"  {'p':>3} {'k':>3} {'gens':>10} {'index':>6} {'e*p^(l-lmin)':>13} "
          f"{'e':>3} {'l':>3} {'lmin':>5}")
    cases = [(3, 4, (2,)), (3, 4, (4,)), (5, 3, (2,)), (5, 3, (4,)),
             (5, 4, (7,)), (7, 3, (2,)), (7, 4, (3,)), (11, 3, (3,)),
             (13, 3, (5,)), (2, 8, (3,)), (2, 8, (5,)), (2, 8, (7,)),
             (2, 8, (17,)), (2, 10, (31,)), (2, 8, (3, 5))]
    for p, k, gens in cases:
        record = unified_index(gens, p, k)
        assert record.index == record.predicted, (p, k, gens)
        print(f"  {record.p:>3} {record.k:>3} {str(record.generators):>10} "
              f"{record.index:>6} {record.predicted:>13} "
              f"{record.tame_index:>3} {record.level:>3} "
              f"{record.minimal_level:>5}")

    print()
    print("why T = 4 at p = 2: the principal part must be cyclic")
    for p, k in ((3, 4), (5, 3), (7, 3), (2, 6), (2, 8)):
        print(f"  p={p}, k={k}: T = {tame_modulus(p)}, "
              f"(1+T Z)/p^k cyclic = {principal_part_is_cyclic(p, k)}, "
              f"l_min = {minimal_level(p)}")
    print("  with T = 2 the p=2 principal part is the whole odd-residue group,")
    print("  which is NOT cyclic -- that is the entire content of the exception.")
